### ISSUE TITLE
Add Norfolk, VA

### ISSUE THREAD

**Issue by nfkctzn** [defund12/defund12.org#1004]
mayor@norfolk.gov; martin.thomas@norfolk.gov; courtney.doyle@norfolk.gov; mamie.johnson@norfolk.gov; paul.riddick@norfolk.gov; thomas.smigiel@norfolk.gov; andria.mcclellan@norfolk.gov; angelia.williams@norfolk.gov

Subject: Restrict Police Funding, Invest in Norfolk Social Services

Message (Don't forget to replace the [x]'s with your information!) 

My name is [YOUR NAME], and I am a resident of Norfolk. This past week, our nation has been gripped by protests calling for rapid and meaningful reevaluation of the role of policing in our communities and an end to institutionalized racism. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

Norfolk PD receives a disproportionate amount of our city's financial resources. In FY 2020, the Norfolk PD adopted $77,618,592 in total expenditures while the entire Norfolk Community Services Board's adopted expenditures totaled $25,078,661.  While we’ve been spending extraordinary amounts on policing, we have not seen significant improvements to safety, homelessness, mental health, or affordability in our city. 

I call on you to meaningfully restrict the Norfolk PD budget and instead use those extraordinary resources towards solving homelessness, which is felt most by our Black neighbors and veterans. Social programs and education generally have been shown to be much more effective at promoting safety and social equity than policing and incarceration.

We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by wendywx** [comment]
edits in bold:

----------------------------------------------------

mayor@norfolk.gov; martin.thomas@norfolk.gov; courtney.doyle@norfolk.gov; mamie.johnson@norfolk.gov; paul.riddick@norfolk.gov; thomas.smigiel@norfolk.gov; andria.mcclellan@norfolk.gov; angelia.williams@norfolk.gov

Subject: **[INSERT UNIQUE SUBJECT LINE]**

Message (Don't forget to replace the [x]'s with your information!)

My name is [YOUR NAME], and I am a resident of Norfolk. This past week, our nation has been gripped by protests calling for rapid and meaningful reevaluation of the role of policing in our communities and an end to institutionalized racism. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

Norfolk PD receives a disproportionate amount of our city's financial resources. In FY 2020, the Norfolk PD adopted $77,618,592 in total expenditures while the entire Norfolk Community Services Board's adopted expenditures totaled $25,078,661. While we’ve been spending extraordinary amounts on policing, we have not seen significant improvements to safety, homelessness, mental health, or affordability in our city.

I call on you to meaningfully restrict the Norfolk PD budget and instead use those extraordinary resources towards solving homelessness, which is felt most by our Black neighbors and veterans. Social programs and education generally have been shown to be much more effective at promoting safety and social equity than policing and incarceration.

We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

-------------------------------------------------

Confirmed statistics from https://www.norfolk.gov/DocumentCenter/View/50347/FY-2020-Adopted-Budget-Document?bidId=

This email looks good, just updated some minor format issues.

@skullface @mahrer could someone please update this to ready for PR?

**Comment by todd-m** [comment]
on it
