### ISSUE TITLE
please add New Haven, CT

### ISSUE THREAD

**Issue by chewpie** [defund12/defund12.org#1010]
MayorElicker@newhavenct.gov, Ward23@newhavenct.gov, alucas@newhavenct.gov, Ward1@newhavenct.gov, Ward2@newhavenct.gov, Ward3@newhavenct.gov, Ward4@newhavenct.gov, Ward5@newhavenct.gov, Ward6@newhavenct.gov, Ward7@newhavenct.gov, Ward8@newhavenct.gov, Ward9@newhavenct.gov, Ward10@newhavenct.gov, Ward11@newhavenct.gov, Ward12@newhavenct.gov, Ward13@newhavenct.gov, Ward14@newhavenct.gov, Ward15@newhavenct.gov, Ward16@newhavenct.gov, Ward17@newhavenct.gov, Ward18@newhavenct.gov, Ward19@newhavenct.gov, Ward20@newhavenct.gov, Ward21@newhavenct.gov, Ward22@newhavenct.gov, Ward24@newhavenct.gov, Ward25@newhavenct.gov, Ward26@newhavenct.gov, Ward27@newhavenct.gov, Ward28@newhavenct.gov, Ward29@newhavenct.gov, Ward30@newhavenct.gov

Subject: [Add Unique Subject Line Here!]

Dear Mayor Elicker and New Haven Board of Alders members, 

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD]. I am emailing to demand a more ethical plan for the New Haven expense budget beginning FY21 that shifts funds away from the NHPD and towards resources that address community well-being at the core, including social services, health services, and education. While the most recent budget did cut some police positions, it has become clear that those small changes are far from enough to bring the change we want to see in our communities. A disproportionate amount of funding is still going to a police department that has failed to protect and serve our residents and has unfairly targeted our Black and Brown communities.

It is your duty to represent the voices of your constituents. The numbers that have shown up to demonstrations in New Haven against police brutality are proof that we want to see a drastic shift in how community safety is handled. I join the call of those across the country, across the globe, for a reimagining of public safety that focuses on the health and prosperity of our community instead of relying on armed police officers. I am urging you to look at the next city budget as an opportunity to create long term, effective change in New Haven.

Thank you, 

[YOURNAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by skullface** [comment]
Hi @chewpie! Thanks for your interested adding New Haven to the site. Can you provide more detail about the city budget to make a more compelling argument, showing the disparities in numbers?

Please see our [email style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for some suggestions.

Thank you!

**Comment by chewpie** [comment]
MayorElicker@newhavenct.gov, Ward23@newhavenct.gov, alucas@newhavenct.gov, Ward1@newhavenct.gov, Ward2@newhavenct.gov, Ward3@newhavenct.gov, Ward4@newhavenct.gov, Ward5@newhavenct.gov, Ward6@newhavenct.gov, Ward7@newhavenct.gov, Ward8@newhavenct.gov, Ward9@newhavenct.gov, Ward10@newhavenct.gov, Ward11@newhavenct.gov, Ward12@newhavenct.gov, Ward13@newhavenct.gov, Ward14@newhavenct.gov, Ward15@newhavenct.gov, Ward16@newhavenct.gov, Ward17@newhavenct.gov, Ward18@newhavenct.gov, Ward19@newhavenct.gov, Ward20@newhavenct.gov, Ward21@newhavenct.gov, Ward22@newhavenct.gov, Ward24@newhavenct.gov, Ward25@newhavenct.gov, Ward26@newhavenct.gov, Ward27@newhavenct.gov, Ward28@newhavenct.gov, Ward29@newhavenct.gov, Ward30@newhavenct.gov

Subject: [Add Unique Subject Line Here!]

Dear Mayor Elicker and New Haven Board of Alders members,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD]. I am emailing to demand a more ethical plan for the next New Haven expense budget that shifts funds away from the NHPD and towards resources that address community well-being at the core, including public health services, youth programs, social services, and public works projects, and education. Currently, a disproportionate amount of funding is being given to a police department that has failed to protect and serve our residents and has unfairly targeted our Black and Brown communities. 

While the document for the budget approved on May 26, 2020 is not yet available online, it is my understanding that the Mayor's Proposed Budget for FY2020-21 is a close indicator. According to data available in the Proposed Budget, $43 million was allocated to Police Services. That figure is more than the combined total proposed for Public Health ($11.5 million), Youth & Recreation ($4.8 million), Community Services Administration ($4.5 million), and the Department of Public Works and Parks ($15.9 million). Furthermore, New Haven Public Schools requested a $10.8 million budget increase, were met with a much lower proposal from the Mayor's office of $3.5 million, and in the end, were approved only a $1 million increase in the final budget.

It is your duty to represent the voices of your constituents. The numbers that have shown up to demonstrations in New Haven against police brutality are proof that the people want to see a drastic shift in how community safety is handled. I join the call of those across the country, across the globe, for a reimagining of public safety that focuses on the health and prosperity of our community instead of relying on armed police officers. I am urging you to look at the next city budget as an opportunity to create long term, effective change in New Haven.

Thank you,

[YOURNAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by chewpie** [comment]
Thank you for the feedback, @skullface! I've commented with a revised version above. Please let me know if this meets the standards of the style guide. I am also going to reach out to more members of the New Haven community to see if anyone has additional ideas or further insight into budget specifics.

**Comment by skullface** [comment]
Thanks so much for following up @chewpie! This is now in the queue for in-depth review so we can get it live.

**Comment by rpalakkal** [comment]
on it
