### ISSUE TITLE
Defund

### ISSUE THREAD

**Issue by evelynn22** [defund12/defund12.org#1011]
Thanks for all your work! Can you add the city of Lansing as well as Brighton.

**Comment by skullface** [comment]
Hi @evelynn22, thanks for your interest in adding Brighton to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Messages should follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md). Remember that messages must be specific to your locale and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

There is an open request for Lansing at https://github.com/defund12/defund12.org/issues/979. If you have additional messaging you’d like to provide for Lansing, please do so at that issue.

Your request will be **closed** until you reply with the necessary content. Thank you!
