### ISSUE TITLE
Add Nevada County, California 

### ISSUE THREAD

**Issue by heidishimek** [defund12/defund12.org#1016]
comments@gvpd.net; public@cityofgrassvalley.com; info@cityofgrassvalley.com; ceo@co.nevada.ca.us; clifford.newell@co.nevada.ca.us; hhsa@co.nevada.ca.us; human.resources@co.nevada.ca.us; sheriff@co.nevada.ca.us; heidi.hall@co.nevada.ca.us; ed.scofield@co.nevada.ca.us; dan.miller@co.nevada.ca.us; sue.hoek@co.nevada.ca.us; richard.anderson@co.nevada.ca.us; catrina.olson@nevadacityca.gov; chad.ellis@nevadacityca.gov; paul.rohde@nevadacityca.gov; rleftwich@townoftruckee.com; truckee@townoftruckee.com; blee@townoftruckee.com;

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message (Don't forget to replace the [x]'s with your information!) 

To Whom It May Concern: 

My name is [YOUR NAME], and I am a resident of Nevada County. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-Blackness, and immediate reform in how Black people are treated in America. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

The three police departments in Nevada County have been a waste of our resources. For the Fiscal Year 2019-2020 in Grass Valley alone, the General Fund Expenditures was $13,093,905. The final budget for the GVPD was $4,141,770. This is a total of 31.6% of the General Fund. Nevada City PD budgeted 45.3% of the General Fund Expenditures ($2,096,760 out of the $4,632,239 Nevada City General Fund). The Truckee Police Department was allocated  $6,629,802 out of $23,177,108 in the General Fund.

While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police.

I call on you to slash the budgets of Nevada County Police Departments and instead use those extraordinary resources towards solving homelessness, which is felt most by our Black neighbors and veterans. We implore you to give every member of our community experiencing homelessness a place to call home and the treatment they need.

We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely,

[YOUR NAME]

[YOUR ADDRESS]

[YOUR EMAIL]

[YOUR PHONE NUMBER]

**Comment by heidishimek** [comment]
Sources for Review:

**Comment by heidishimek** [comment]
Sources for Reviewer: 

https://www.cityofgrassvalley.com/sites/main/files/file-attachments/fy_2019-20_budget.pdf?1579046635 (Page 23)

https://www.nevadacityca.gov/files/documents/FY1920AnnualAdoptedBudget1329053025071719PM.pdf (Page 1)

http://laserfiche.townoftruckee.com/WebLink/0/doc/59390639/Page1.aspx (Page 3)

Many thanks!

**Comment by heidishimek** [comment]
Hi! 
Anyway the sentence:
"Instead, we see wasteful and harmful actions of our police."
can be removed? 

Thanks!

**Comment by root2point0** [comment]
@mahrer what do you think? It's closed but I can reopen potentially

**Comment by mahrer** [comment]
Personally I think it's fine as is (I know some of our other templates use similar wording as well), but @heidishimek if you really want a change feel free to open a new issue with the label content-change-request
