### ISSUE TITLE
Add Toledo, OH

### ISSUE THREAD

**Issue by skullface** [defund12/defund12.org#1021]
```
- Wade.Kapszukiewicz@toledo.oh.gov
- Tyrone.Riley@toledo.oh.gov
- Yvonne.Harper@toledo.oh.gov
- Matt.Cherry@toledo.oh.gov
- Theresa.Gadus@toledo.oh.gov
- Sam.Melden@toledo.oh.gov
- Chris.Delaney@toledo.oh.gov
- Cecelia.Adams@toledo.oh.gov
- Gary.Johnson@toledo.oh.gov
- Nick.Komives@toledo.oh.gov
- Rob.Ludeman@toledo.oh.gov
- Katie.Moline@toledo.oh.gov
- Larry.Sykes@toledo.oh.gov
- Catherine.Crosby@toledo.oh.gov
- Karen.Poore@toledo.oh.gov
- Abby.Arnold@toledo.oh.gov
```

Hello, my name is [NAME] and I am a resident of [NEIGHBORHOOD].

The City of Toledo must do better by all of its residents. The current city budget affords the criminalization of Black communities while offering very little investment in them. In order for Toledo to be a more equitable city, I call on our leaders to reduce police spending for the 2021 fiscal year. 

In the 2020 budget for “basic services,” the police department receives $91,859,538 of $251,227,767 - more than a third of the budget. In the past three years alone, police spending has increased by $10 million. Consider what that $10 million could accomplish in three years if used to invest in communities instead of police them.

We all share the same goals for racial justice and equity. On June 5th, Mayor Kapszukiewicz said, “I believe that now is the time to bring change to police-community relations.” He’s right - now is definitely the time. Let’s take action and bring meaningful change by divesting from the police.

Toledo’s leaders and residents have the opportunity to create a more equitable city for all of us and correct what decades of neglect and destructive policing have done to underserved Black communities. I urge you to have the moral clarity to create a budget focused on building communities and creating positive change instead of investing in a racist and destructive institution.

Thank you, 
[NAME]

**Comment by skullface** [comment]
Budget stats confirmed, reads clearly!

**Comment by ahansrisuk** [comment]
on it
