### ISSUE TITLE
Add Poughkeepsie, New York - Dutchess County

### ISSUE THREAD

**Issue by DerilusP1** [defund12/defund12.org#1032]
**To:** 
sheriffbutch@gmail.com
CountyExec@DutchessNY.gov
CountyLegislature@DutchessNY.gov
BKendall@DutchessNY.gov
Comptroller@DutchessNY.gov
DistrictAttorney@dutchessny.gov
jbaisley@townofpoughkeepsie-ny.gov
jrenihan@townofpoughkeepsie-ny.gov
bill.carlos@aol.com
jlopez@townofpoughkeepsie-ny.gov
Michaelcifone@aol.com
mwoolever@townofpoughkeepsie-ny.gov
ashershin@yahoo.com
fsalvatore@townofpoughkeepsie-ny.gov
____________________________________________

**Subject: Defunding of the PK Police Department**

**Message**

To Poughkeepsie Town Officials:

My name is [Insert Name] and I am a resident of [Neighborhood/City]. 

Given the historic, social, and political origins of [police and policing](https://gen.medium.com/slavery-and-the-origins-of-the-american-police-state-ec318f5ff05b), in conjunction with the recent nationwide protests reflecting the antiBlack deaths of [George Floyd](https://www.refinery29.com/en-us/2020/05/9838535/george-floyd-killed-by-minneapolis-police-knee-video), [Breonna Taylor](https://zora.medium.com/where-is-the-outrage-for-breonna-taylor-f2f7ed762e79), and [Tony McDade](https://www.refinery29.com/en-us/2020/05/9844546/tony-mcdade-police-killed-tallahassee-black-transgender-man) I am contacting you because I am demanding you to redirect money away from the Poughkeepsie Police Department and prioritize collective services that will help improve the socio-economic conditions of Poughkeepsie's **_predominately Black_** communities. 

Subsequently, a majority of teachers are at serious risk of losing their positions as well the youth losing the essential human right to learn and receive a formal education. As such, the [Poughkeepsie City School District](https://www.poughkeepsiejournal.com/story/news/education/2020/04/30/poughkeepsie-district-proposes-48-positions-cut-amid-2-6-m-deficit/3058326001/) has stated the following:

> The Poughkeepsie City School District is proposing to eliminate 48 positions, including teachers, administrators and support staff, as it attempts to erase a $2.6 million deficit for its 2020-21 budget. The board voted Wednesday to eliminate positions for elementary assistant principals, the Poughkeepsie High School dean of students, the assistant to the superintendent and a position that had yet to be filled for the director of grants and advancement. 
> 
> Superintendent Eric Rosser said the cuts, most of which have yet to be voted on, are necessary to overcome financial challenges that include decreases in state aid, the loss of building aid, increases in operating costs, and other financial obligations. Some, but not all, of those losses are related to hardships created by the coronavirus pandemic.
> 
> He said as the administration continues to finalize its budget he may have to consider more eliminations. School budget votes, which were to take place May 19, were delayed until a date to be determined after June 1.
> 
> "Of course in this district we are not looking to take away valuable members of our organization that support student learning, but it is our hope that we would be able to retain our staff members, because each member is in the position to meet the varying needs of our children," Rosser said to the district board of education Wednesday. "Unfortunately, given our budgetary situation we are forced to move in this direction, it is not a good direction that I, as a superintendent, or even as an educator, would recommend. However, when you don't have the ability to meet people's payroll or salary you have to move in the direction of a budget that we will be able to meet the payroll." 
> 
> When contacted by the Journal, Board President Felicia Watson declined to answer questions regarding the moves, but said "The board awaits the presentation of the final budget that the superintendent will be holistically presenting soon."
> 
> The layoffs, if approved, would include 27 teacher positions, 11 administrator positions, and 10 support staff positions, as well as the restructuring of some central office positions. Rosser noted the eliminations do not necessarily mean 48 staff members will be laid off, given some positions are vacant due to retirements and other transitions. 
> 
> Administrative positions eliminated would include the P-Tech program principal, the PACE (Poughkeepsie Academic and Career Excellence) program principal, the PACE assistant principal, the high school dean of students, five elementary assistant principals, the assistant to the superintendent, and the director of grants and advancement. 
> 
> The proposed layoffs would result in around $3 million of savings. Rosser said the eliminations are likely to happen given the economic uncertainty amid the pandemic, and the district could see more eliminations as the budget is finalized. 
> He said more eliminations will be voted on by the board Wednesday, May 6. 
> 
> When asked by the board at the meeting how the schools will continue to provide services, Rosser did not have an answer. 
>  

In [addition to the lack of funding in schools](https://www.poughkeepsiejournal.com/story/news/local/2020/05/04/dutchess-county-reports-strong-fiscal-year-2019-amid-coronavirus/3077461001/?fbclid=IwAR2xMCqs8MPcPJ96YbvBj745yWSWh8BOuih0qclt6bvlipwiwYEkGFjFUuA), County Executive Marc Molinaro has reported that 2019 was a strong "fiscal" year, in particular response to the COVID-19 pandemic, stating:

> "Expenses totaled $471.2 million, while revenue added up to $472.6 million. Additionally, sales tax revenue increased by $9.1 million, a 4.6% increase over 2018. The county also ended the fiscal year with $56.9 million in its general fund balance."
> 
> Moreover, "...[r]evenues increased in 2019, even as expenditures also increased in several areas. That included a $7.6 million cost increase to the Dutchess County Sheriff's Employee Association for union contract settlements, positions, employee benefits and debt service.

Ultimately, the allocation of funds that have been attributed to the Poughkeepsie police department in contrast to the funding towards schools, is both erring and telling. I yearn to know what you will do to protect Black lives and prevent further instances of police-state-sanctioned violence, the emotional, social, and educational well-being of Black lives. I am calling to urge you to condemn police brutality, racial profiling, and the use of excessive force by police on oppressed communities. 

Sincerely,
[Insert Name]

**Comment by skullface** [comment]
Thanks so much for bearing with the requests @DerilusP1! This is in the review pipeline now.

**Comment by ctneal91** [comment]
on it now
