### ISSUE TITLE
Add Kennewick, WA

### ISSUE THREAD

**Issue by JDot104** [defund12/defund12.org#1038]

**Comment by JDot104** [comment]
let me know if i need to add anything else or if you need the sources, i have pdf's of everything required

**Comment by skullface** [comment]
Hi @JDot104, thanks for your interest in adding Kennewick to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Messages should follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md). Remember that messages must be specific to your locale and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!

**Comment by JDot104** [comment]
The emails at the top are the emails of the council members in my city.
I detailed the budget decisions of my city as well as the amount of funding (and percentage of total funding) of the police in the third paragraph.

**Comment by JDot104** [comment]
To:
Don.Britain@ci.kennewick.wa.us,steve.lee@ci.kennewick.wa.us, brad.beauchamp@ci.kennewick.wa.us,jim.millbauer@ci.kennewick.wa.us, Chuck.Torelli@ci.kennewick.wa.us,John.Trumbo@ci.kennewick.wa.us,Bill.McKay@ci.kennewick.wa.us
Subject: Public Safety Concern
Message
Dear Kennewick City Leadership,

My name is [YOUR NAME] and I am a resident of Kennewick. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community well being and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing. I will no longer accept empty gestures and suggestions of “reform.” I am demanding that my voice be heard now, and that real change be made to the way this city allocates its resources.
Rather than prioritize the quality of life for all of Kennewick with a proportional budget, Kennewick chooses to prioritize KPD. In the 2019-2020 budget flyer, the KPD was allocated a budget of $42,968,000 accounting for 39.4% of Kennewick’s total budget. This money can be spent in other ways that are proven to be more effective in improving community safety and wellness.

According to the Tri-City Herald, 223 Tri-Citians were homeless as of 2017, however the pandemic’s severe economic consequences has likely caused this number to increase. Support for communities in need is necessary now, more than ever. But instead, Kennewick has chosen to prioritize KPD over funding services for the homeless many of whom are facing mental health problems and drug addiction.

I demand the City Council defund KPD. Instead, I demand we redirect police funding to improving mental health response teams, homeless shelters, and funding drug addiction treatment centers. I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of at-risk Kennewick residents. I demand a budget that supports community well-being, rather than empowers the police forces that tear them apart.
I am urging you to completely revise the Kennewick budget for the 2020-2021 fiscal year. You need to adopt a People’s Budget. Public opinion is with me.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
