### ISSUE TITLE
Add Las Cruces, NM

### ISSUE THREAD

**Issue by runningpants** [defund12/defund12.org#1041]
Letter to Las Cruces Mayor Ken Miyagishima and City Council:
KMiyagishima@las-cruces.org; kgandara@las-cruces.org; tstuve@las-cruces.org; gvasquez@las-cruces.org; jbencomo@las-cruces.org; gsorg@las-cruces.org; yflores@las-cruces.org 

My name is [NAME]. I am a resident of [CITY/NEIGHBORHOOD], and I am emailing today to demand an overhaul to our Las Cruces Police Department budget in light of the Black Lives Matter protests across the US, but specifically in Las Cruces.
WE ARE JOINING TOGETHER TO DEMAND THAT YOU, MY LOCAL OFFICIALS, WILL:
Vote no on all increases to police budgets;
Vote yes to decrease police spending and budgets;
Vote yes to increase spending on healthcare, education, housing, and community programs that keep us safe.
The militarized tactics that police departments are using against citizens is unacceptable and unwarranted. We have seen mounting evidence that police departments are racist and ineffective institutions that put citizens at risk of injury and death. This is amply demonstrated by the recent killing of Antonio Valenzuela in Las Cruces Police custody using a banned “vascular neck restraint"--the same restraint used to kill George Floyd in Minneapolis. 
The approved 2020 FY budget allocated over 61% of our Public Safety fund to the Las Cruces Police Department. To ensure your dedication to our city and citizens, I demand that you defund the Las Cruces Police Department and start providing more support and funding towards our community efforts and organizations that serve our predominantly Black and Latinx communities. By doing so, I believe this will prevent further police brutality and violence in the future.
Black and Latinx communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors. According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections. In 2017, they spent $194 billion--a 220 percent increase. Despite continued police profiling, harassment, terror and killing in Black and Latinx communities, local and federal decision-makers continue to invest in the police, which leaves Black and Latinx people vulnerable and our communities no safer.
Where could that money go? It could go towards building healthy communities, to the health of our elders and children, to neighborhood infrastructure, to education, to childcare, to support a vibrant Black and Latinx future. The possibilities are endless.
We join in solidarity with the freedom fighters in Minneapolis, Louisville, and across the United States. And we call for the end to police terror.
Sincerely, [NAME] [PHONE_NUMBER] [EMAIL] [ADDRESS]

Some content borrowed from Albuquerque template.

**Comment by serifluous** [comment]
Budget info confirmed here, p47: https://las-cruces.org/DocumentCenter/View/3082/FY2020-Budget-Adopted-book-PDF?bidId=

Edits in bold below
--

Letter to Las Cruces Mayor Ken Miyagishima and City Council:
KMiyagishima@las-cruces.org; kgandara@las-cruces.org; tstuve@las-cruces.org; gvasquez@las-cruces.org; jbencomo@las-cruces.org; gsorg@las-cruces.org; yflores@las-cruces.org

**Dear Mayor Miyagishima and the Las Cruces City Council:**

My name is [NAME]. I am a resident of [CITY/NEIGHBORHOOD], and I am emailing today to demand an overhaul to our Las Cruces Police Department budget in light of the Black Lives Matter protests across the US, but specifically in Las Cruces.

**I AM DEMANDING** THAT YOU, MY LOCAL OFFICIALS, WILL:
- Vote no on all increases to police budgets.
- Vote yes to decrease police spending and budgets.
- Vote yes to increase spending on healthcare, education, housing, and community programs that keep us safe.

The militarized tactics that police departments are using against citizens is unacceptable and unwarranted. We have seen mounting evidence that police departments are racist and ineffective institutions that put citizens at risk of injury and death. This is amply demonstrated by the recent killing of Antonio Valenzuela in Las Cruces Police custody using a banned “vascular neck restraint"—the same restraint used to kill George Floyd in Minneapolis.

The approved 2020 FY budget allocated over 61% of our Public Safety fund to the Las Cruces Police Department. To ensure your dedication to our city and citizens, I demand that you defund the Las Cruces Police Department and start providing more support and funding towards our community efforts and organizations that serve our predominantly Black and Latinx communities. By doing so, I believe this will prevent further police brutality and violence in the future.
Black and Latinx communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors. 

According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections. In 2017, they spent $194 billion—a 220 percent increase. Despite continued police profiling, harassment, terror and killing in Black and Latinx communities, local and federal decision-makers continue to invest in the police, which leaves Black and Latinx people vulnerable and our communities no safer.

Where could that money go? It could go towards building healthy communities, to the health of our elders and children, to neighborhood infrastructure, to education, to childcare, to support a vibrant Black and Latinx future. The possibilities are endless.

We join in solidarity with the freedom fighters in Minneapolis, Louisville, and across the United States. And we call for the end to police terror.

Sincerely,
[NAME]
[PHONE_NUMBER]
[EMAIL]
[ADDRESS]

**Comment by root2point0** [comment]
on it
