### ISSUE TITLE
Add Richland, WA

### ISSUE THREAD

**Issue by JDot104** [defund12/defund12.org#1042]

**Comment by skullface** [comment]
Hi again @JDot104, thanks for your interest in adding Richland to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Messages should follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md). Remember that messages must be specific to your locale and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!

**Comment by JDot104** [comment]
im sorry I fixed it

**Comment by JDot104** [comment]
Letter To:
rlukson@ci.richland.wa.us, BThompson@CI.RICHLAND.WA.US, skent@CI.RICHLAND.WA.US, banderson@CI.RICHLAND.WA.US, plemley@ci.richland.wa.us, tchristensen@CI.RICHLAND.WA.US, malvarez@CI.RICHLAND.WA.US
Subject: Public Safety Concern
Message
Dear Richland City Leadership,

My name is [YOUR NAME] and I am a resident of Richland. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing. I will no longer accept empty gestures and suggestions of “reform.” I am demanding that my voice be heard now, and that real change be made to the way this city allocates its resources.

Rather than prioritize the quality of life for all of Richland with a proportional budget, Richland chooses to prioritize RPD. In the 2019-2020 budget, the RPD was allocated a budget of $14,651,400 accounting for 24% of Richland’s total budget. This money can be spent in other ways that are proven to be more effective in improving community safety and wellness.

According to the Tri-City Herald, 223 Tri-Citians were homeless as of 2017, however the pandemic’s severe economic consequences has likely caused this number to increase. Support for communities in need is necessary now, more than ever. But instead, Richland has chosen to prioritize RPD over funding services for the homeless many of whom are facing mental health problems and drug addiction.

I demand the City Council defund RPD. Instead, I demand we redirect police funding to improving mental health response teams, homeless shelters, and funding drug addiction treatment centers. I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of at-risk Richland residents. I demand a budget that supports community well-being, rather than empowers the police forces that tear them apart.

I am urging you to completely revise the Richland budget for the 2020-2021 fiscal year. You need to adopt a People’s Budget. Public opinion is with me.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
