### ISSUE TITLE
Add Pasco, WA

### ISSUE THREAD

**Issue by JDot104** [defund12/defund12.org#1044]
**To Pasco council members**
barajascouncil@pasco-wa.gov alvaradocouncil@pasco-wa.gov martinezcouncil@pasco-wa.gov serranocouncil@pasco-wa.gov milnecouncil@pasco-wa.gov maloneycouncil@pasco-wa.gov roachcouncil@pasco-wa.gov 
**Subject:** Public Safety Concern
**Message:**
Dear Pasco City Leadership, 

My name is [YOUR NAME] and I am a resident of Pasco. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police. 

We are in the midst of widespread upheaval over the systemic violence of policing. I will no longer accept empty gestures and suggestions of “reform.” I am demanding that my voice be heard now, and that real change be made to the way this city allocates its resources. 

Rather than prioritize the quality of life for all of Pasco with a proportional budget, Pasco chooses to prioritize PPD. In the 2019-2020 budget, the PPD was allocated a budget of $35,524,184 accounting for 35.5% of Pasco’s total budget. Meanwhile, the PPD is guilty of several cases of police brutality, including murder as recently as May 2020. This money can be spent in other ways that are proven to be more effective in improving community safety and wellness. 

According to the Tri-City Herald, 223 Tri-Citians were homeless as of 2017, however the pandemic’s severe economic consequences has likely caused this number to increase. Support for communities in need is necessary now, more than ever. But instead, Pasco has chosen to prioritize PPD over funding services for the homeless many of whom are facing mental health problems and drug addiction. 

I demand the City Council defund PPD. Instead, I demand we redirect police funding to improving mental health response teams, homeless shelters, and funding drug addiction treatment centers. I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of at-risk Pasco residents. I demand a budget that supports community well-being, rather than empowers the police forces that tear them apart. 

I am urging you to completely revise the Pasco budget for the 2020-2021 fiscal year. You need to adopt a People’s Budget. Public opinion is with me. 

Thank you for your time, 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by JDot104** [comment]
[PascoTotalExpenditure.pdf](https://github.com/defund12/defund12.org/files/4761944/PascoTotalExpenditure.pdf)

**Comment by serifluous** [comment]
Budget info confirmed on p45: https://www.pasco-wa.gov/DocumentCenter/View/60449/2019-2020-Adopted-Budget

**Comment by dalanmiller** [comment]
Grabbing this 🆗
