### ISSUE TITLE
Additional email address for OKC

### ISSUE THREAD

**Issue by caduckett** [defund12/defund12.org#1054]
craig.freeman@okc.gov must be added to Oklahoma City as he directly oversees the city budget

**Comment by ctneal91** [comment]
on it now

**Comment by ctneal91** [comment]
Upon further review, it looks like we are already sending Craig Freeman an email through the City Manager email address citymanager@okc.gov . https://www.okc.gov/government/city-manager/about-the-city-manager @mahrer I think we can close this issue

**Comment by todd-m** [comment]
thanks for checking @ctneal91, gonna close this

**Comment by caduckett** [comment]
I hear what you're saying, but I've received direct correspondence from
craig.freeman@okc.gov within the last week and I fear that the other email
is an older one from a former city manager.
