### ISSUE TITLE
North Charleston, SC - letter to Mayor and City Council Members

### ISSUE THREAD

**Issue by daliadalili** [defund12/defund12.org#1058]
mayor@northcharleston.org, mabrown@northcharleston.org, ncdist2@comcast.net, vjamison@northcharleston.org, rbrin@aol.com, jheyward@northcharleston.org, dwilliams0521@yahoo.com, shart@northcharleston.org, bob1408.king@comcast.net, kskipper@northcharleston.org, bmichaelchr@aol.com

Subject: Defunding the North Charleston Police Department

Message:Dear Mayor Summey and North Charleston City Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY].I am demanding you reallocate funds from the North Charleston City Police department and invest them into social services that would directly improve the well-being of North Charleston citizens.The budget for 2019 was $35,882,389, and the budget for 2020 is $37,834,665. This is almost a 6% increase from 2019 to 2020 and an almost 7% increase from 2018 to 2020. That money could be better spent on supporting affordable housing, educational opportunities, healthcare, and community outreach programs that are more successful at promoting safe and stable communities than law enforcement. I demand more aggressive financial support be directed to those areas.

I am demanding long term and sustainable change. I am demanding that the city of North Charleston’s budget be better spent on quality of life for all. In particular for those in our Black and Brown communities, who are more than likely to be directly affected by police brutality and violence. I also urge the North Charleston City Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity.

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents and take immediate action to address their concerns. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by brickaney** [comment]
I’m reviewing

**Comment by rpalakkal** [comment]
doing this one
