### ISSUE TITLE
ADD: DEFUND Durango PD 

### ISSUE THREAD

**Issue by adultman-cooley** [defund12/defund12.org#1060]
Mayor: DeanBrookie@durangogov.org
Council: ChrisBettin@durangogov.org
Council: barbaraNoseworthy@durangogov.org
Council: MelissaYoussef@durangogov.org

Hello,

My name is [YOUR NAME HERE], and I am a resident of Durango, Colorado. We are experiencing a revolution across this country. For too long black lives and BIPOC in general have lived in fear of police departments who act violently with little or no consequence. Attempts at reform and extra training has done little to alter this systemic problem.

As a result I call for immediate defunding of Durango PD. At well over 8 million dollars ($8,417,771), their budget accounts for 16% of the general fund for the city. In contrast, the funds allotted  for community services like aide for the homeless,  low income assistance, and youth services are less than 1 million ($921,102) That’s over 9 times the amount of funding for police versus community services. This is absurd, we need to invest in the wellbeing of the community NOT the police. 

Police are not trained to properly deal with most of the calls they answer and often make situations worse, especially when BIPOC are involved. What we need are more mental health professionals, more youth counselors, and more resources for homeless folks and those struggling to make ends meet. Investing so much money in the police shows a priority for maintaining a inequitable status quo, not a commitment toward community enhancement and racial justice. 

Americans are crying out for justice. And you all are in a position to make a lasting change in our city. This can not wait, I urge you to address this problem head on and reallocate police funds towards programs that will make a safer, healthier, and more thriving community. 

Please don’t wait, act now.

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by swallan** [comment]
Hi [USER]! Thanks for your interest in adding [CITY] to the site. Can you provide more detail about the city budget to make a more compelling argument, showing the disparities in numbers?

Please see our [email style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for some suggestions.

Thank you!

**Comment by adultman-cooley** [comment]
Updated

**Comment by mahrer** [comment]
Reviewing now

**Comment by mahrer** [comment]
Some minor edits:

---

Mayor: DeanBrookie@durangogov.org
Council: ChrisBettin@durangogov.org
Council: barbaraNoseworthy@durangogov.org
Council: MelissaYoussef@durangogov.org

Hello,

My name is [YOUR NAME HERE], and I am a resident of Durango, Colorado. We are experiencing a revolution across this country. For too long Black people, Indigenous people, and People of Color  have lived in fear of police departments who act violently with little or no consequence. Attempts at reform and extra training have done little to alter this systemic problem.

As a result, I call for immediate defunding of Durango PD. At well over 8 million dollars ($8,417,771), their budget accounts for 16% of the general fund for the city. In contrast, the funds allotted for community services like aide for the homeless, low income assistance, and youth services are less than 1 million ($921,102). Police have over 9 times the amount of funding of community services. This is absurd. We need to invest in the well-being of the community NOT the police.

Police are not trained to properly deal with most of the calls they answer and often make situations worse, especially when Black people, Indigenous people, and People of Color are involved. What we need are more mental health professionals, more youth counselors, and more resources for homeless folks and those struggling to make ends meet. Investing so much money in the police shows a priority for maintaining a inequitable status quo, not a commitment toward community enhancement and racial justice.

Americans are crying out for justice. And you all are in a position to make a lasting change in our city. This can not wait. I urge you to address this problem head on and reallocate police funds towards programs that will make a safer, healthier, and more thriving community.

Please don’t wait, act now.

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by adultman-cooley** [comment]
👍🏻👍🏻

**Comment by todd-m** [comment]
on it
