### ISSUE TITLE
Burbank, CA - Letter to Mayor and City Council 

### ISSUE THREAD

**Issue by accountability1** [defund12/defund12.org#1061]
To: CityCouncil@burbankca.gov  🔗

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!) 🔗

Dear Mayor Springer and Burbank City Council Members,

My name is [NAME HERE] and I am a Burbank resident. Burbank PD reserves an enormous share of the city’s general fund, taking away desperately needed resources from essential city programs and services. Over 31% of our city’s budget is directed to the police department, while only 23% is devoted to essential community development, library services, and parks, recreation, & community services combined. 

Burbank is faced with a projected loss of $11 million in revenue for this quarter and is set to continue to appropriate general funds at levels relatively consistent to FY 2019-20.  Burbank PD’s proposed $61 million budget will be used at the expense of vital public services, such as creating housing opportunities for homeless residents and safeguarding humane working conditions for temporary skilled workers. The investment in policing has not made us safer – Burbank PD continues to constitute a lethal threat to the city’s Black and Brown communities. With Burbank’s current finances in dire jeopardy, it is clear that we must defund the police.

As a Burbank resident, I demand that you take immediate action to ensure the following:

1. Significantly reduce Burbank PD’s allocation from the general fund.
2. Remove school resource officers from Burbank USD. 
3. Invest in housing, youth programs, restorative justice, and mental health workers to keep the community safe.

Burbank can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund Burbank PD.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by accountability1** [comment]
Sources: https://www.burbankca.gov/home/showdocument?id=51190
https://www.burbankca.gov/home/showdocument?id=53479

**Comment by todd-m** [comment]
on it
