### ISSUE TITLE
Eugene oregon

### ISSUE THREAD

**Issue by crcreug** [defund12/defund12.org#1067]
Would love a template to share. Thank you for your work!

**Comment by sophiagustafson** [comment]
Hi, thanks for your interest in adding your city to the website. Emails on defund12.org are all written by community members. To add your city, you must provide:

Email addresses (at least one) of the government officials you’d like to receive the message
Detailed message concerning the budgeting decisions at stake in your community
Until you provide this content, we cannot post your city.

Messages should follow our email style guidelines. Remember that messages must be specific to your locale and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be closed until you reply with the necessary content. Thank you!

**Comment by skullface** [comment]
Hi @crcreug! There’s a template going out for Eugene soon. Original request: https://github.com/defund12/defund12.org/issues/799

Thanks for your interest, look out for it!
