### ISSUE TITLE
Tompkins County

### ISSUE THREAD

**Issue by leighv55** [defund12/defund12.org#1068]
mayor@cityofithaca.org,
leslyn@twcny.rr.com,
klh7@cornell.edu,
carolchock@gmail.com,
nshinagawa@gmail.com,
jpd821@yahoo.com,
mike.sigler@yahoo.com,
dek22@cornell.edu,
dmckenna@tompkins-co.org,
brobinson@twcny.rr.com,
dsk11@cornell.edu,
dsk11@cornell.edu,
wburbank@tompkins-co.org,
mrobertson@tompkins-co.org,
mlane@tompkins-co.org

Dear Tompkins County Legislature,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am asking the County Legislature to begin meaningfully defunding the Tompkins County Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Tompkins County residents. Much scholarship shows that a living wage, access to health services and treatment, educational opportunity, and stable housing are far more successful at promoting community safety than policing and prisons. As such, I demand a meaningful reallocation of police department funds towards healthcare and social programs.

Sincerely, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by skullface** [comment]
Hi @leighv55! There is already an open request for Tompkins County at https://github.com/defund12/defund12.org/issues/869

If you’d like to combine messaging, please visit that open request.

Thank you!
