### ISSUE TITLE
Alamance County email (corrected)

### ISSUE THREAD

**Issue by mmarqu** [defund12/defund12.org#1071]
County commissioners:
Eddie Boswell: eddie.boswell@alamance-nc.com, Steve Carter: steve.carter@alamance-nc.com, Bill Lashley: bill.lashley@alamance-nc.com, Chair Amy Scott Galey: amy.galey@alamance-nc.com, Tim Sutton: tim.sutton@alamance-nc.com  

This email goes to them all: commissioners@alamance-nc.com and Tory Frink, Clerk to the Board: tory.frink@alamance-nc.com 

Dear County Commissioners:
My name is [YOUR NAME] and I am a resident of Alamance County. I urge you to advocate for a meaningful reallocation of the city's expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.

In 2019 Alamance County spent 7% of our County's budget on the Sheriff's office with another 7% going to the jail. In contrast, our schools have 26% of the budget, and we have one of the worst performing school districts in NC. The local community college receives only 2% of our budget, students have to take out loans in order to attend and adjunct faculty get paid $2,000 to teach a class. We are a rural community. Our investment should be in uplifting people through education. Not punishing people for poverty. 

In the proposed budget for 2020-2021 the "public safety" budget is 23%, almost doubling what it is now. Although we all want to live in a safe place, the best way to guarantee our safety is to provide people with the skills, healthcare, housing and food. Our local tax dollars should be going towards promoting community safety through investing in our children, education and health and wellbeing. 

Sincerely, 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
on it
