### ISSUE TITLE
Bounce back from one DC email address

### ISSUE THREAD

**Issue by freegonzo** [defund12/defund12.org#1076]
Fyi, but I got a bounce back from one of the email addresses in the DC email list (see below) correct address from the DC council website should be abonds@dccouncil.us.

=====================
"Delivery has failed to these recipients or groups:

abonds@dc.gov
The email address you entered couldn't be found. Please check the recipient's email address and try to resend the message. If the problem continues, please contact your helpdesk."

**Comment by ctneal91** [comment]
on it now
