### ISSUE TITLE
Shreveport, Louisiana

### ISSUE THREAD

**Issue by Boompoet** [defund12/defund12.org#1084]
Mayor Adrian Perkins - adrian.perkins@shreveportla.gov
Chief Administrative Officer Henry Whitehorn - HenryL.Whitehorn@shreveportla.gov
CFO Sherricka Fields Jones - finance@shreveportla.gov

City Council Members

Tabatha Taylor - Tabatha.taylor@shreveportla.gov
LeVette Fuller - LeVette.Fuller@shreveportla.gov
John Nickelson - John.Nickelson@shreveportla.gov
Grayson Boucher - Grayson.Boucher@shreveportla.gov
James Flurry - James.Flurry@shreveportla.gov 
James Green - James.Green@shreveportla.gov
Jerry Bowman - Jerry.Bowman@shreveportla.gov 

Dear Shreveport City Council, staff, and Executive departments

My name is [YOUR NAME]. I am a Shreveport resident writing to urge you to defund the City of Shreveport Police Department.

I am contacting you to demand a significant reduction to the $60,588,900 million that is currently allocated to funding the Shreveport Police department and for a formal review of the Shreveport Police Department Union Contract from an independent party that has no affiliation with SPD. The police funds make up roughly 28% of the budget, while other important public services such as Community development which should cover social programs and outreach receives only 10%, and property standards receive less than 2%. By reducing police funding and reducing incarceration rates, those funds can be reallocated to reducing blighted properties, housing, education, or improving our aging infrastructure, among other needs. That way we can focus on building our community efforts and local organizations, while preventing future police brutality and violence.

As Shreveport a resident, I therefore demand that you take immediate action towards the following ends:

1. Reduce SPD’s allocation from the General Fund by no less than 40%
2. Discontinue use of General Fund dollars to pay for settlements due to police murder, misconduct, and negligence
3. Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.

Shreveport can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to Defund SPD.

Sincerely, 

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by skullface** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review so we can publish.

**Comment by Boompoet** [comment]
FYI - If you need to see the city of Shreveport, Louisiana budget - https://www.shreveportla.gov/DocumentCenter/View/16851/2020-Annual-Operating-Budget?bidId=

**Comment by brickaney** [comment]
I am reviewing

**Comment by rpalakkal** [comment]
on it now
