### ISSUE TITLE
ADD -- St. Mary's County, Maryland

### ISSUE THREAD

**Issue by varunkataria** [defund12/defund12.org#1086]

**Comment by varunkataria** [comment]
**To: [STILL NEED COUNTY OFFICIALS HERE]**
Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Dear St. Mary’s County Officials,

My name is [YOUR NAME], and I am a St. Mary’s County resident. I am writing to ask that you reverse the recent increases to the budget of the St. Mary's County Sheriff's Office, but rather begin to defund it and shift money towards non-police resources that keep residents safe.

In the midst of this pandemic and public outcry against police brutality, it feels especially inappropriate to recently increase the St. Mary's County Sheriff's Office budget by $5,019,990 or 11.4%. Jeannett Cudmore, chief financial officer for the county, stated when recently approving the budget that she could go back and make adjustments to the county’s budget for FY2021 if any major changes take place. The rising movements around the world and even locally are a clear testament to major change being required. I urge you to ethically reallocate this increase, as well as a meaningful portion of the remaining Sheriff Office’s budget, towards social services and education. 

Investment in programs such as **[STILL NEED PROGRAMS HERE]** shows our commitment to communities and the vision that all St. Mary’s County residents deserve to thrive. Historically, the county government has spent far more on police than on public health, homeless services, youth services, and other vital agencies. 


It’s time to reallocate the funding of the Sheriff’s Office and begin the gradual process of strategically reallocating resources, funding, and responsibility away from an armed police force and towards community-based models of safety, support, and prevention. It’s time to protect investments in human services, the social safety net, and racial and economic justice. I am writing to insist that the St. Mary’s County budget for FY 2021 be adjusted and the upcoming FY 2022 budget development better reflects the voices and needs of our local citizens. I am asking that county officials give intense care, attention and effort towards sustainable, long-term change.

Sincerely, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by skullface** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review so we can publish.

**Comment by averymcguirt** [comment]
Please provide email addresses so we can proceed with this request

**Comment by varunkataria** [comment]
email addresses - 

csmc@stmarysmd.com, todd.morgan@stmarysmd.com, john.oconnor@stmarysmd.com, mike.hewitt@stmarysmd.com, eric.colvin@stmarysmd.com, randy.guy@stmarysmd.com, Jason.Babcock@stmarysmd.com, Julie.Yingling@stmarysmd.com, marvin.butler@stmarysmd.com, tim.cameron@stmarysmd.com, michael.merican@stmarysmd.com, Rebecca.Bridgett@stmarysmd.com, finance@stmarysmd.com, sheriff@stmarysmd.com

**Comment by mahrer** [comment]
Reviewing now

**Comment by mahrer** [comment]
Some minor edits below:

---

To: csmc@stmarysmd.com, todd.morgan@stmarysmd.com, john.oconnor@stmarysmd.com, mike.hewitt@stmarysmd.com, eric.colvin@stmarysmd.com, randy.guy@stmarysmd.com, Jason.Babcock@stmarysmd.com, Julie.Yingling@stmarysmd.com, marvin.butler@stmarysmd.com, tim.cameron@stmarysmd.com, michael.merican@stmarysmd.com, Rebecca.Bridgett@stmarysmd.com, finance@stmarysmd.com, sheriff@stmarysmd.com

Message:

Dear St. Mary’s County Officials,

My name is [YOUR NAME], and I am a St. Mary’s County resident. I am writing to ask that you reverse the recent increases to the budget of the St. Mary's County Sheriff's Office, but rather begin to defund it and shift money towards non-police resources that keep residents safe.

In the midst of this pandemic and public outcry against police brutality, it feels especially inappropriate to recently increase the St. Mary's County Sheriff's Office budget by $5,019,990 or 11.4%. Jeannett Cudmore, Chief Financial Officer for the county, stated when recently approving the budget that she could go back and make adjustments to the county’s budget for FY2021 if any major changes take place. The rising movements around the world and even locally are a clear testament to major change being required. I urge you to ethically reallocate this increase, as well as a meaningful portion of the remaining Sheriff Office’s budget, towards social services and education.

Investment in services such as affordable housing, education, health care, child care, public health, and youth services shows our commitment to communities and the vision that all St. Mary’s County residents deserve to thrive. Historically, the county government has spent far more on police than these vital community needs.

It’s time to reallocate the funding of the Sheriff’s Office and begin the gradual process of strategically reallocating resources, funding, and responsibility away from an armed police force and towards community-based models of safety, support, and prevention. It’s time to protect investments in human services, the social safety net, and racial and economic justice. I am writing to insist that the St. Mary’s County budget for FY 2021 be adjusted and the upcoming FY 2022 budget development better reflects the voices and needs of our local citizens. I am asking that county officials give intense care, attention and effort towards sustainable, long-term change.

Sincerely, 
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
on it
