### ISSUE TITLE
Add DC 

### ISSUE THREAD

**Issue by cd2129** [defund12/defund12.org#11]
DC Council is currently accepting testimony on the 2020-2021 budget. They are proposing $18.5 mil increase to the police budget and $5 mill for a new jail. 

Email testimony can be submitted to judiciary@dccouncil.us

More info here:
[Instructions for testimony](https://u1584542.ct.sendgrid.net/mps2/c/5wA/ni0YAA/t.32c/7KRu0pXsSJSZKIiOqhzpAQ/h24/cidj-2Bve7daPPm09dFhiTNfJweDUWjAoBSeD-2FGeVN75FH-2BSgPxS-2BPZV-2BNAcQIScnFxuNjaEQnCw1-2FbLaA-2B7dMkzVi2nedA-2FcSDZJSUqYhda5RMdOoSkmhmylmjxdDmwt8wc8nUrvo2boz0PLEoXZo4yI6AZNuhhuSJJOG9Qp3K6SQtUUVGmNpe3Ls3p2aC7ptTpdfy4DKseGWsPnmT9ECltHl4rklMs2MZRfhJIKh4-2BcJUj3hAIxPDAhtjzidiVLWGGdL5PCfDzurw3YXsdkVaPR-2Fg-2BkIOGz45INCCqrmC-2BCBPluasUxkVgws8Aog458-2B6NpEfMZjDgKOTElrQ-2FFbR8rbY0m1rggtDNl1QpSxlrcLot-2FeBfOIYm4o0TWAv1uo57Q5sPkN3fR679KrhQXt-2Bg-3D-3D/YYBP)

**Comment by teddywilson** [comment]
We are currently handling a lot of requests - please include the following information with your request: 
* A subject message for the email
* A list of emails (at least one) for the government officials you’d like to receive the message
* A detailed message concerning the budgeting decisions that are at stake in your community

**Comment by davisgrubin** [comment]
subject - Defund MPD and Commit to "Justice for All"

emails - judiciary@dccouncil.us, pmendelson@dccouncil.us, kmcduffie@dccouncil.us, abonds@dccouncil.us, dgrosso@dccouncil.us, esilverman@dccouncil.us, rwhite@dccouncil.us,
bnadeau@dccouncil.us, mcheh@dccouncil.us, btodd@dccouncil.us, callen@dccouncil.us, vgray@dccouncil.us, twhite@dccouncil.us

message - 
Hello,
My name is (your name) and I am a DC resident. I am emailing today to ask the Committee on the Judiciary and Public Safety to vote against the Mayor’s proposed budget increase for the Metropolitan Police Department (MPD). I am calling attention to the fact that this increase is occurring as the budgets for the Office of Neighborhood Safety and Engagement and the Office of Victim Services and Justice Grants are being reduced.

DC's incarcerated population is one of the most disproportionately Black in the US (at 89%), even though Black people only comprise 46% of the DC population.  Despite our liberal reputation and city motto of "Justice for All", if DC were a state, it would have the highest incarceration rate in the country. In 2019, the Washington Post reported that most stops by MPD were made of Black Washingtonians, and we are renowned across the country for the revenue we extract from these stops ($1 billion last year alone in traffic stops). In addition, the Washington Lawyers Committee for Civil Rights and Urban Affairs released a report on the disparities in fare evasion enforcement toward Black residents on public transportation. Findings demonstrated that the District disproportionately stops and incarcerates Black residents from the city's poorest wards. The systems flaws are wide open for all to see, and can only be solved with a recognition that the criminalization of poverty must end.

The MPD is at the center of this local crisis. While employing historically racist tactics to incite fear in Black communities, MPD has been in steady collaboration with ICE officials, standing against the city’s vows to be a sanctuary for immigrant communities. In addition to their continuation of the unconstitutional stop and frisk policies, often just by other names (protective pat-downs, and jump-outs), MPD often downplays this data in testimony to the DC Council. Additionally, the steady increase to the MPD budget despite the twenty percent uptick in from 2017-2018 in use of force cannot be ignored.

The COVID-19 pandemic has not only revealed stark disparities in housing, healthcare, COVID-19 testing, and access to food, but has exacerbated the underlying conditions that leave thousands of low-income residents more vulnerable to this deadly infectious disease. This is where we should be focusing our efforts and funding. It is unconscionable that in the midst of a health pandemic that is overwhelmingly killing Black people – as 76% of COVID deaths are of Black DC residents – that Mayor Bowser would propose increasing an already bloated police budget to almost $580 million, while at the same time divesting from critical public health resources like violence prevention and interruption, mental healthcare, trauma and victims services, and reentry services. The fact we have ample funds for riot shields and tear gas but at one point questioned the adequacy of our supply of hospital beds and PPE is more than poor leadership and mismanagement of resources - it is a glaring and total moral failure.

The $18.5 million increase to MPD, should be allocated elsewhere when considered within the context of this ongoing pandemic and the $700 million dollar city budget deficit. This funding would be better allocated towards supporting DC Public Schools and funding community health initiatives (such as the Dept. of Health, Dept. of Health Care Finance, and the Dept. of Behavioral Health).

We must ask ourselves as a city that claims "Justice for All" as our motto - what kind of justice are we referring to? Economic Justice? Racial Justice? Social Justice? Or is the grand sum of our capacity for justice to offload problems we are unwilling to deal with at their source onto an agency whose main tools will, at the end of the day, always be those of violence and coercion? 

The current status-quo cannot be maintained, and I urge you to listen to community leaders and members of the DC chapter of Black Lives Matter as well as Stop Police Terror Project DC and defund the Metropolitan Police Department. The resources are in desperate need elsewhere. Do not abandon the people you were elected to serve.

Thank you,
(Your name)

**Comment by serifluous** [comment]
Some of the info here could be added to the existing DC email.

**Comment by serifluous** [comment]
Title change: "Letter to Mayor and Council Members"

Additional email to add: abonds@dc.gov

Suggested email update (taking the first paragraph from the existing email and using the rest from what's proposed in this issue):

To the DC council in charge of the allocation of funds to the Metropolitan Police Department and its respective members,

My name is [YOUR NAME], and I am a resident of Washington, D.C. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-blackness, and immediate reform in how black people are treated in America. Our city has been at the forefront of much of this action. Accordingly, it has come to my attention that there will be a council meeting in June that will discuss the budget for the Metropolitan Police Department.

I am emailing today to ask the Committee on the Judiciary and Public Safety to vote against the Mayor’s proposed budget increase for the Metropolitan Police Department (MPD). I am calling attention to the fact that this increase is occurring as the budgets for the Office of Neighborhood Safety and Engagement and the Office of Victim Services and Justice Grants are being reduced.

DC's incarcerated population is one of the most disproportionately Black in the US (at 89%), even though Black people only comprise 46% of the DC population. Despite our liberal reputation and city motto of "Justice for All", if DC were a state, it would have the highest incarceration rate in the country. In 2019, the Washington Post reported that most stops by MPD were made of Black Washingtonians, and we are renowned across the country for the revenue we extract from these stops ($1 billion last year alone in traffic stops). In addition, the Washington Lawyers Committee for Civil Rights and Urban Affairs released a report on the disparities in fare evasion enforcement toward Black residents on public transportation. Findings demonstrated that the District disproportionately stops and incarcerates Black residents from the city's poorest wards. The systems flaws are wide open for all to see, and can only be solved with a recognition that the criminalization of poverty must end.

The MPD is at the center of this local crisis. While employing historically racist tactics to incite fear in Black communities, MPD has been in steady collaboration with ICE officials, standing against the city’s vows to be a sanctuary for immigrant communities. In addition to their continuation of the unconstitutional stop and frisk policies, often just by other names (protective pat-downs, and jump-outs), MPD often downplays this data in testimony to the DC Council. Additionally, the steady increase to the MPD budget despite the twenty percent uptick in from 2017-2018 in use of force cannot be ignored.

The COVID-19 pandemic has not only revealed stark disparities in housing, healthcare, COVID-19 testing, and access to food, but has exacerbated the underlying conditions that leave thousands of low-income residents more vulnerable to this deadly infectious disease. This is where we should be focusing our efforts and funding. It is unconscionable that in the midst of a health pandemic that is overwhelmingly killing Black people – as 76% of COVID deaths are of Black DC residents – that Mayor Bowser would propose increasing an already bloated police budget to almost $580 million, while at the same time divesting from critical public health resources like violence prevention and interruption, mental healthcare, trauma and victims services, and reentry services. The fact that we have ample funds for riot shields and tear gas but at one point questioned the adequacy of our supply of hospital beds and PPE is more than poor leadership and mismanagement of resources — it is a glaring and total moral failure.

The $18.5 million increase to MPD, should be allocated elsewhere when considered within the context of this ongoing pandemic and the $700 million dollar city budget deficit. This funding would be better allocated towards supporting DC Public Schools and funding community health initiatives (such as the Dept. of Health, Dept. of Health Care Finance, and the Dept. of Behavioral Health).

We must ask ourselves as a city that claims "Justice for All" as our motto — what kind of justice are we referring to? Economic Justice? Racial Justice? Social Justice? Or is the grand sum of our capacity for justice to offload problems we are unwilling to deal with at their source onto an agency whose main tools will, at the end of the day, always be those of violence and coercion?

The current status-quo cannot be maintained, and I urge you to listen to community leaders and members of the DC chapter of Black Lives Matter as well as Stop Police Terror Project DC and defund the Metropolitan Police Department. The resources are in desperate need elsewhere. Do not abandon the people you were elected to serve.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now
