### ISSUE TITLE
Clarksville, TN missing subject

### ISSUE THREAD

**Issue by ctneal91** [defund12/defund12.org#1108]
# Bug report

Found a problem with the site? Please provide the following information (if possible):

Clarksville, TN is missing a subject. Proposed subject: "Resident for Defunding the Clarksville Police Department"

**Comment by swallan** [comment]
I think subjects are all being propagated with the message to add your own unique one in the emails

**Comment by NickCrews** [comment]
I agree that unique subjects are good, but I would think a placeholder like `**[Add your subject here]**` would be better than nothing.

**Comment by swallan** [comment]
True!

**Comment by dionlarson** [comment]
⚠️  Note: `*` seems to make tests fai!
