### ISSUE TITLE
add Merced, CA

### ISSUE THREAD

**Issue by lehcarr** [defund12/defund12.org#1113]
See below for the list of contacts to send to, as well as a link on how to find your district. Also, see attached the email - edit and fill in sections as needed ! 
 
SEND TO: 
Mayor@Cityofmerced.org, MurphyM@Cityofmerced.org, District1@Cityofmerced.org, MartinezA@Cityofmerced.org, District2@Cityofmerced.org, EchevarriaF@Cityofmerced.org, District3@Cityofmerced.org, McLeodJ@Cityofmerced.org, District4@Cityofmerced.org, BlakeK@Cityofmerced.org, District5@Cityofmerced.org, SerrattoM@Cityofmerced.org, District6@Cityofmerced.org, SheltonD@Cityofmerced.org webmaster@cityofmerced.org CarriganS@cityofmerced.org DietzS@cityofmerced.org
 
See here to find your District: https://www.cityofmerced.org/departments/city-council
 
SUBJECT: [INSERT UNIQUE SUBJECT LINE]
 
To the Merced City Council,

I am a resident of Merced’s [YOUR DISTRICT]. I am writing to demand that the City Council adopt a budget strategy that prioritizes community well-being and redirects funding away from the police in the next budget evaluation period.

We have seen mounting evidence that police departments are ineffective institutions that marginalize minority communities and put citizens at risk of injury and death, yet the police budget accounts for 20.7 million of a 44.6 million dollar fund - this is 46% of the budget. This is wholly unacceptable.  I ask that you redirect a significant portion of the police budget toward community programs, notably in South Merced, that provide citizens with basic human needs, like affordable healthcare and housing and primarily access to food. We do not need a militarized police force. We need to create a space in which more mental health service providers, social workers, victim/survivor advocates, neighbors, and friends - all of the people who really make up our community - can look out for one another. Real, actionable change starts with reallocating funding in a manner consistent with these priorities.

The additional allocation of approximately $4M (or 2/3rds) of Measure C funds also being directed towards the Merced Police Department is unacceptable. As these funds are available for practically any use, it is a shame to see so much of it  (or any at all) go towards policing.  I would especially like to see these funds go to support education in schools across Merced county, particularly in underserved or underprivileged areas.
 
Further, I ask that the police in schools be removed. From 2018, there has been significant research into whether or not schools benefit from having a police presence. The overwhelming answer is that their presence creates unintended consequences like suspensions, expulsions and arrests — especially for students of color. The police presence is stated to be there in order for "safer schools", but as Marc Schindler, the head of the Justice Policy Institute, said in a 2018 interview with NPR: "In fact, the data really shows otherwise — that this is largely a failed approach in devoting a significant amount of resources but not getting the outcome in school safety that we are all looking for."[1][2] Black and other students of color deserve to have a school environment where THEY feel safe, and that implies without police presence. 
 
We also demand an apology for the way that District 2 Council Member Fernando Echevarria treated protestors at a recent candlelight vigil for Mr. George Floyd, along with demanding to be put in a chokehold. Frankly, he should be removed from the board for his mocking of the “I can’t breathe” cry Mr. Floyd let out as he died on camera. The Council Member did this as members of the public called for more questions to be answered. Although emotions are high and discussions are heated, we deserve to have open conversations - particularly with those leading our city. Merced is a growing place, with a large population of people of all races and economic backgrounds. This should be reflected in the city council, be that through conversations or eventually through massive change. This behavior did not show any intention of listening to the people, and was wholly unrepresentative of what a District representative should be. 
 
Personally, I hope that one day we can follow the lead of Minneapolis[3] and look for community alternatives to police forces. I am sure you are aware of the 8 Can't Wait campaign, but many of these alternatives and trainings are already in place and did not stop the murders of George Floyd, Freddie Gray, Breonna Taylor, and countless others across our country. I urge you to look further into the 8 to abolition movement: https://www.8toabolition.com/. 8 Can't Wait has been "debunked" publicly by abolition leaders and reformists alike. Instead of seeing the "72% decrease" in police shootings they promise, I hope to live in a world and a city where 0 police shootings occur. Reformist reforms will only continue the status quo, as we have seen following Ferguson and Baltimore. We are at a turning point, and abolitionist reforms hold the voice.  
 
As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year. We can be a beacon for other cities to follow if only we have the courage to change.
 
Thank you for your time,
 
[YOUR NAME] [YOUR ADDRESS] [YOUR PHONE NUMBER] [YOUR EMAIL ADDRESS]
 
[1] https://www.npr.org/2018/03/08/591753884/do-police-officers-in-schools-really-make-them-safer
[2] https://www.chalkbeat.org/2019/2/14/21121037/new-studies-point-to-a-big-downside-for-schools-bringing-in-more-police
[3] https://www.nytimes.com/2020/06/07/us/minneapolis-police-abolish.html

**Comment by mcooper5** [comment]
Thank you for adding this!!!!

**Comment by root2point0** [comment]
on it
