### ISSUE TITLE
Add an email for Lansing, MI

### ISSUE THREAD

**Issue by arcummings5** [defund12/defund12.org#1116]
sarahanthony@house.mi.gov
senchertel@senate.michigan.gov

Subject: Reallocate police budgets
Message (Don't forget to replace the [x]'s with your information!) 🔗 

Dear Lansing Representatives,

My name is [YOUR NAME] and I am a resident of Lansing. I am emailing today to demand that you vote to reallocate police budgets toward other social services like education and dismantling racial inequity. Furthermore, I urge you ONLY to vote for a budget that includes cuts to the LPD with equal reallocation towards social services and education programs, effective at the beginning of FY21, July 1, 2020.

Thank you, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by swallan** [comment]
#979 Hi @arcummings5, thanks for your request to add EL to the site! We have an open request at #979 . If you’d like to add to or edit the messaging, please visit that issue.
Thank you!
