### ISSUE TITLE
Add Winchester, VA

### ISSUE THREAD

**Issue by pnorthrup** [defund12/defund12.org#1120]
Mayor:
david.smith@winchesterva.gov

City Council members:
evan.clark@winchesterva.gov
john.hill@winchesterva.gov
les.veach@winchesterva.gov
bill.wiley@winchesterva.gov
kim.herbstritt@winchesterva.gov
corey.sullivan@winchesterva.gov
john.willingham@winchesterva.gov
judy.mckiernan@winchesterva.gov

Subject: Reallocate the WPD’s budget

Dear Mayor Smith and City Council members,

My name is [YOUR NAME], and I am a resident of Winchester. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police brutality, an end to racism and anti-Blackness, and immediate improvements in how Black people are treated in America.

While we’ve been spending extraordinary amounts on policing, we have not seen sufficient improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy). As such, I demand more aggressive financial support be directed to those areas. 

I urge you and the rest of the city council to amend the budget for 2021 and all future budgets. Money should be redirected away from the WPD and into social service programs that will benefit public health and our own communities, especially communities of color. 

Can I count on you to consider an alternative budget and review policing methods that puts a focus on social service programs and the wellbeing of the community?

Thank you,
[Your name]

**Comment by averymcguirt** [comment]
Minor edits for clarity:

Mayor:
david.smith@winchesterva.gov

City Council members:
evan.clark@winchesterva.gov
john.hill@winchesterva.gov
les.veach@winchesterva.gov
bill.wiley@winchesterva.gov
kim.herbstritt@winchesterva.gov
corey.sullivan@winchesterva.gov
john.willingham@winchesterva.gov
judy.mckiernan@winchesterva.gov

Subject: Reallocate the WPD’s budget

Dear Mayor Smith and City Council members,

My name is [YOUR NAME], and I am a resident of Winchester. This past week, our nation has been gripped by protests calling for rapid and meaningful reevaluation of the role of police in our communities, an end to police brutality, and an end to racism and anti-Blackness in America.

While we’ve been spending extraordinary amounts on policing, we have not seen sufficient improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police. Research shows that a living wage, access to health services and treatment, educational opportunity, and stable housing are far more successful at promoting safe communities than police or prisons. As such, I demand more aggressive financial support be directed to those areas.

I urge you and the rest of the city council to amend the budget for 2021 and all future budgets. Money should be redirected away from the WPD and into social service programs that will benefit public health and our own communities, especially communities of color.

Can I count on you to consider an alternative budget and review policing methods that puts a focus on social service programs and the wellbeing of the community?

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

**Comment by root2point0** [comment]
on it
