### ISSUE TITLE
Detroit Future Budget Request

### ISSUE THREAD

**Issue by emgarava** [defund12/defund12.org#1129]
email addresses 

Bjones_mb@detroitmi.gov,councilmembersheffield@detroitmi.gov,councilmemberayers@detroitmi.gov,councilmembertate@detroitmi.gov,councilmemberMcCalister@detroitmi.gov,BensonS@detroitmi.gov,councilmanSpivey@detroitmi.gov,councilmemberraquel@detroitmi.gov,LelandG@detroitmi.gov, williamsonk@detroitmi.gov,robertsonkya@detroitmi.gov,TandyK@detroitmi.gov,DavisSe@detroitmi.gov,JohnsonErn@detroitmi.gov,sessomsk@detroitmi.gov,azarl@detroitmi.gov,dperkins@detroitmi.gov,howardm@detroitmi.gov,fergusonz@detroitmi.gov,torrese@detroitmi.gov,millsa@detroitmi.gov,Alim@detroitmi.gov,fowlkese@detroitmi.gov,polkc@detroitmi.gov,naglickj@detroitmi.gov,david.massaron@detroitmi.gov,massarond@detroitmi.gov,hammerk@detroitmi.gov,stoudemiret@detroitmi.gov,

emails

Dear Honorable Detroit City Council Members,

Hi, my name is [NAME] and I am a resident of [DISTRICT]. I am emailing you today to ask that you redirect money away from the Detroit Police Department (DPD) in the city's FY2021-2024 budget. I am asking there to be an emergency city council meeting to reassess the budget and that you take immediate action to defund DPD. I urge you to pressure Mayor Duggan towards an ethical and equal reallocation of Detroit's General Fund away from DPD and towards efforts to improve equity through social programs and education, effective July 1, 2020.

COVID-19 has brought massive destruction to our amazing city. It is estimated that 48% of city residents are currently unemployed and that 43% of jobs lost will never return; 1 in 3 are about to run out of money. So far, 1,399 Detroiters have died from this virus, and, amid a global pandemic that has disproportionately affected blacks, the city has barely increased the Health Departments' total budget. In the FY2021-2024 General Fund, the Health Department only makes up 1.3%; by contrast, the police department makes up 30.7% of the General Fund. Of their respective departmental budgets, the General Fund accounts for 95.7% of DPD's total budget ($314 million) versus 32.1% for the Health Department ($13 million). The total budgets for these departments are $328 million and $41 million, respectively. How does this benefit our residents?

According to the current U.S. Census data, 36.4% of the city lives in poverty and 11.1% of the city does not have health insurance. Undoubtedly, given the effects of the pandemic, these numbers are likely much higher. And, given that the General Fund is comprised of five key tax revenues paid for by us, Detroit residents are paying a hefty price tag to be brutalized by our police. These funds could be more appropriately used to alleviate poverty and the systems that create crime in the first place. Continuing to fund these departments at this level can only be seen as a direct assault on the city's majority black and low-income populations. This budget is a war on poverty!

Despite policing America's blackest major city, DPD has never been exempt from racism, fatal encounters, excessive force, and gross police misconduct. It was only four years ago that DPD emerged from federal oversight from the U.S. Justice Department for committing such acts. Need I remind you of the 1943 and 1967 Rebellions? How about the deaths of Malice Green and Aiyana Stanely-Jones?

Action must be taken immediately. Can I count on you, Detroit City Council Members, to hold an emergency meeting to revise the budget and reallocate DPD funds to more appropriate services, like social service programming?

Thank you,
[YOUR NAME]

CC:
District Managers:
District 1: Karla Williams & Kya Robertson
District 2: Kim Tandy & Sean Davis
District 3: Ernest Johnson & Kayana Sessoms
District 4: Letty Azar & Dennis Perkins
District 5: Melia Howard & Zavia Ferguson
District 6: Eva Torres & Antonio Mora Mills
District 7: Mona Ali & Eric Fowlkes

Officer of the Budget Staff
David P. Massaron, Chief Financial Officer, City of Detroit
John Naglick, Chief Deputy CFO/Finance Director, City of Detroit
Katie Hammer, Chief Deputy CFO/Policy & Administration, City of Detroit
Tayna Stoudemire, Deputy CFO/Budget Director, City of Detroit
Cherie Polk, Executive Assistant to the CFO, City of Detroit

**Comment by averymcguirt** [comment]
Minor edits for clarity:

Bjones_mb@detroitmi.gov,councilmembersheffield@detroitmi.gov,councilmemberayers@detroitmi.gov,councilmembertate@detroitmi.gov,councilmemberMcCalister@detroitmi.gov,BensonS@detroitmi.gov,councilmanSpivey@detroitmi.gov,councilmemberraquel@detroitmi.gov,LelandG@detroitmi.gov, williamsonk@detroitmi.gov,robertsonkya@detroitmi.gov,TandyK@detroitmi.gov,DavisSe@detroitmi.gov,JohnsonErn@detroitmi.gov,sessomsk@detroitmi.gov,azarl@detroitmi.gov,dperkins@detroitmi.gov,howardm@detroitmi.gov,fergusonz@detroitmi.gov,torrese@detroitmi.gov,millsa@detroitmi.gov,Alim@detroitmi.gov,fowlkese@detroitmi.gov,polkc@detroitmi.gov,naglickj@detroitmi.gov,david.massaron@detroitmi.gov,massarond@detroitmi.gov,hammerk@detroitmi.gov,stoudemiret@detroitmi.gov,

emails

Dear Honorable Detroit City Council Members,

My name is [NAME] and I am a resident of [DISTRICT]. I am emailing you today to ask that you redirect money away from the Detroit Police Department (DPD) in the city's FY2021-2024 budget. I am asking there to be an emergency city council meeting to reassess the budget and that you take immediate action to defund DPD. I urge you to pressure Mayor Duggan towards an ethical and equal reallocation of Detroit's General Fund away from DPD and towards efforts to improve equity through social programs and education, effective July 1, 2020.

COVID-19 has brought massive destruction to our amazing city. It is estimated that 48% of city residents are currently unemployed and that 43% of jobs lost will never return; 1 in 3 are about to run out of money. So far, 1,399 Detroiters have died from this virus, and, amid a global pandemic that has disproportionately affected Black Americans, the city has barely increased the Health Departments' total budget. In the FY2021-2024 General Fund, the Health Department only makes up 1.3%; by contrast, the police department makes up 30.7% of the General Fund. Of their respective departmental budgets, the General Fund accounts for 95.7% of DPD's total budget ($314 million) versus 32.1% for the Health Department ($13 million). The total budgets for these departments are $328 million and $41 million, respectively. How does this benefit our residents?

According to the current U.S. Census data, 36.4% of the city lives in poverty and 11.1% of the city does not have health insurance. Undoubtedly, given the effects of the pandemic, these numbers are likely much higher. And, given that the General Fund is comprised of five key tax revenues paid for by us, Detroit residents are paying a hefty price tag to be brutalized by our police. These funds could be more appropriately used to alleviate poverty and the systems that create crime in the first place. Continuing to fund these departments at this level can only be seen as a direct assault on the city's majority black and low-income populations. This budget is a war on the poor!

Despite policing America's Blackest major city, DPD has never been exempt from racism, fatal encounters, excessive force, and gross police misconduct. It was only four years ago that DPD emerged from federal oversight from the U.S. Justice Department for committing such acts. Need I remind you of the 1943 and 1967 Rebellions? How about the deaths of Malice Green and Aiyana Stanely-Jones?

Action must be taken immediately. Can I count on you, Detroit City Council Members, to hold an emergency meeting to revise the budget and reallocate DPD funds to more appropriate social services?

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

**Comment by root2point0** [comment]
on it

**Comment by ctneal91** [comment]
on it now

**Comment by root2point0** [comment]
lmao you got it @ctneal91

**Comment by ctneal91** [comment]
no you

**Comment by ctneal91** [comment]
@root2point0 I will take the next one
