### ISSUE TITLE
Request for SF, Berkeley 

### ISSUE THREAD

**Issue by gasolinesunsets** [defund12/defund12.org#113]
San Francisco:  
MayorLondonBreed@sfgov.org 
Norman.Yee@sfgov.org 
Sandra.Fewer@sfgov.gov 
Catherine.Stefani@sfgov.org
Aaron.Peskin@sfgov.org 
Marstaff@sfgov.org 
prestonstaff@sfgov.org
Ronenstaff@sfgov.org
mandelmanstaff@sfgov.org
ahaha.safai@sfgov.org
waltonstaff@sfgov.org
haneystaff@sfgov.org
Carmen.Chu@sfgov.org 
cityattorney@sfcityatty.org
districtattorney@sfgov.org
sfso.complaints@sfgov.org 
jose.cisneros@sfgov.org 
manohar.raju@sfgov.org

Berkeley:
police@cityofberkeley.info 
mayor@cityofberkeley.info 
clerk@cityofberkeley.info
rkesarwani@cityofberkeley.info
cdavila@cityofberkeley.info
jchang@cityofberkeley.info 
kharrison@cityofberkeley.info
cnaso@cityofberkeley.info 
shahn@cityofberkeley.info 
swengraf@cityofberkeley.info
rrobinson@cityofberkeley.info
ldroste@cityofberkeley.info
auditor@cityofberkeley.info

**Comment by teddywilson** [comment]
Hey thanks for this list! 

We will still need a subject and email template to proceed.

**Comment by gasolinesunsets** [comment]
**San Francisco**
Subject: We demand a People's Budget 🔗
Message (Don't forget to replace the [x]'s with your information!) 🔗
I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing, embodied by the SFPD’s well documented history of discrimination and violence towards Black and brown people. We will no longer accept empty gestures and suggestions of “reform.” We are demanding that our voices be heard now, and that real change be made to the way this city allocates its resources.

We are in the midst of a pandemic with severe economic consequences. San Francisco County’s unemployment rate is 12.6%. Thousands of people were living in the street prior to COVID-19; the evictions and economic insecurity caused by COVID-19 will bring that number even higher. 

San Francisco’s 2019-20 operating budget is the largest in its history at $12 billion. With $3.5 billion left for discretionary spending, we demand that those funds are used for a People’s Budget. We demand that the City Council defund the SFPD. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk San Francisco citizens during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

It is your duty to represent your constituents. I am urging you to completely revise the SF Budget for 2020-2021 fiscal year, and to fund #CareNotCops. You need to adopt a People’s Budget. Public opinion is with me.

Thank you for your time,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by cstrouse** [comment]
Berkeley was added in #157.

**Comment by lleadbet** [comment]
SF was added in #134 as well.

**Comment by serifluous** [comment]
@gasolinesunsets 

Hi, thanks for your interest in adding **Berkeley** to the website. To add your city, you **must** provide:

- Subject line for the email
- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!
