### ISSUE TITLE
Add San Leandro, CA to the list!

### ISSUE THREAD

**Issue by jamiecatton** [defund12/defund12.org#1136]
Mayor & City Council Email Addresses: 
pcutter@sanleandro.org
dcox@sanleandro.org
ehernandez@sanleandro.org
vaguilar@sanleandro.org
blee@sanleandro.org
clopez@sanleandro.org
pballew@sanleandro.org

Subject: 
URGENT: Defund San Leandro Police Department

Body: 
Dear Mayor Pauline Russo Cutter and City Council Members,

My name is [YOUR NAME] and I am a San Leandro resident writing to urge you to defund San Leandro PD.

San Leandro PD takes too large of a share of the city’s general fund, taking away desperately needed resources from essential city programs and services. In the 2018-2019 Biennial Budget, the City of San Leandro allocated roughly $39 million dollars to our police system, an inordinate 34.7% of our total budget. This is compared to just $6.5 million allocated towards community development (5.7% of the budget) and recreation & human services (4.6% of the budget).

The projected budget for 2020-2021 for San Leandro PD still sits at 35% of the general budget, at $42,000,485, while community development is projected at 6% of the general fund, recreation & human services at 4% of the budget, and public works also at 6%. 

Within the community development budget, $307,662 was spent on the City Innovation Division for the 2018-2019 budget (8% of budget) and has been slashed to a projected $3,434 for 2019-2020 & 2020-2021 (0.0005% of community development budget for 2020-2021). Additionally within the community development budget for 2019-2020, $326,264 was spent for housing services (4%), and $429,568 for code compliance (6%). The projected budgets for 2020-2021 come to $341,211 for housing services (5% of budget) and $458,203 for code compliance (7% of the budget). 

With an estimated 200 homeless individuals in San Leandro, I demand you reallocate the budgets per the guidelines below to serve our residents in need.

As a San Leandro resident, I demand that you take immediate action to ensure the following:

1. Reduce San Leandro PD’s allocation from the General Fund by 50% ($21,000,242.5‬0)

2. Reallocate $20 million dollars from the San Leandro PD in the 2020-2021 budgets for Human Services, Community Development, and Public Works.

3. Invest the remaining $1,000,242.50 into bridge transitional housing programs like Marea Alta, on 1400 San Leandro Boulevard.

San Leandro cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to Defund San Leandro PD. 

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by swallan** [comment]
@jamiecatton, Hello,

#1124 already exists and is waiting to be merged. Would you like to add edits to that message?
