### ISSUE TITLE
Olympia, WA

### ISSUE THREAD

**Issue by noaner** [defund12/defund12.org#1140]
Emails: cselby@ci.olympia.wa.us, citycouncil@ci.olympia.wa.us

Dear Mayor Cheryl Selby and Olympia City Council Members, 

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY]. Given the history of policing and the most recent murders of Black people including the death of Olympia Resident Yvonne McDonald, I am asking you to redirect money away from the Olympia Police Department in the 2021 budget and instead prioritize services that help strengthen our communities. 

I want a budget that reflects our community’s priorities and needs. I urge you to advocate for a meaningful reallocation of the city’s expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. Beyond policing our community, these services are proven to be more effective in improving community safety and wellness. I demand a budget that supports community well-being, rather than gives power to police forces that tear them apart. 

Please consider your role in enriching and empowering our communities, especially during a time of racial injustice, wide-spread illness, and economic vulnerability. 

Thank you, 

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Hi @noaner , thanks for your request to add Olympia to the site! We have an open request at #986 . If you’d like to add to or edit the messaging, please visit that issue.
Thank you!
