### ISSUE TITLE
Paso Robles, CA

### ISSUE THREAD

**Issue by bmess4bml** [defund12/defund12.org#1174]
**To:**
 council@prcity.com, sgregory@prcity.com, jhamon@prcity.com, smartin@prcity.com, fstrong@prcity.com, mgarcia@prcity.com

**Subject:** +++Insert Uniquie Subject Line+++

**Message:**

Dear Mayor Steven Martin and City Council,

My name is [YOUR NAME] and I am a resident of Paso Robles. I am writing to demand that the Paso Robles City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police.

In 2019, the City of Paso Robles allocated $10,759,000  dollars to our police system, an inordinate 28% of our total budget. This is compared to just 18% of the budget, $6,598,900, allocated towards community development, with only no money towards affordable housing development. Next year, the city estimates that there will be deficits as a result of the pandemic. The city may recoup these funds by decreasing the police budget.

I demand that the City Council begin meaningfully defunding the Paso Robles Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, affordable housing programs, not police. I demand a budget that reflects the actual needs of Paso Roble residents.

History has shown that police “reform” is not enough. No more money, and more importantly, no more lives must be lost to police. We must take a hard look at the way the current system in place fails to serve-and in fact actively harms-our community, and come together to reimagine the role of police in our city.

I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to invest in the people, not the police.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by skullface** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.
