### ISSUE TITLE
Letter to Honolulu Mayor to defund HPD

### ISSUE THREAD

**Issue by rdeleon0612** [defund12/defund12.org#1177]
To mayor@honolulu.gov

Dear Honolulu City Council,

My name is (your name) and I am a resident of (city). I am writing to demand that the Honolulu City and County adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police.

In 2019, the City and County of Honolulu allocated $295,681,922 to our police. This is compared to just $112 million budgeted for ALL Community Services with only $68.7 million reserved for affordable housing, section 8, rental assistance, special projects and community development. Within the $68.7  million, only $10.2 million was projected to be spent on the Housing First Program, with only $2.5 million to community development rehabilitation centers.

According to lthawaii.gov there are 15,000 homeless in Hawai’i with the state paying an average of $8,327 per hospital visit and an annual average of $51,000 per arrestee at OCCC. By trading the HPD budget of $296 million with the Housing First Project’s $10.2 million, we could house all of them. Further studies show this could reduce the amount of visits to the ER and healthcare centers by 64% and the number of arrests by 61% within the first 2 years thus saving an average of $11,496 per year per person with a total average of $172,440,000 annually. Spending the resources to properly help the homeless community will not only increase their life span and quality of life, but decrease Honolulu crime rates and save our city money. 

I demand that the City Council begin meaningfully defunding the Honolulu Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Honolulu.

History has shown that police "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve--and in fact actively harms--our community, and come together to reimagine the role of police in our city.

Thank you for your time,
(Your name) 
(Your address)

**Comment by skullface** [comment]
List of City Councilors here: https://github.com/defund12/defund12.org/issues/89#issuecomment-639194545

**Comment by skullface** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by rdeleon0612** [comment]
Thank you! There’s nothing else I need to add?

**Comment by Rtrott** [comment]
Hiya! I'm just going to review this quickly to check all the numbers and grammar, could you link me to the sources you cited in your email, inc the budget?

**Comment by rdeleon0612** [comment]
Yes hi!

I got the 15,000 homeless count here:
https://ltgov.hawaii.gov/homeless-in-hawaii-facts-and-resources/

Money spent on homeless here:
https://www.honolulu.gov/rep/site/ohou/ohou_docs/HousingFirst-Societal-Impacts-Final.pdf

And city budget and spending plans here:

http://www.honolulu.gov/rep/site/bfs/bfs_docs/FINAL_web_corrected_bookmarks_Budget_Book_FY192018-03
07.pdf


Page A-20, Page B-20

Thank you!

**Comment by Rtrott** [comment]
Thanks so much! i'll get on this now

**Comment by Rtrott** [comment]
@rdeleon0612 did you get the figure $68.7 million by adding up the related funds at the bottom of B-20?

**Comment by rdeleon0612** [comment]
Yes, just the funds I listed

**Comment by Rtrott** [comment]
So if i'm reading the budget correctly, I don't think we can say with certainty that 68.7 million is ALL that was given to those projects, those number are listing different funds where the money to pay for the community services budget is coming from, so there could well be more money invested into those things within the $112 million Community services budget, if that makes sense?

**Comment by rdeleon0612** [comment]
Hmm makes sense, In the “budget highlights” it does say 10.2M being designated for the housing first program. 

And in this source, https://www.civilbeat.org/2020/03/honolulus-2-98-billion-budget-more-rail-funding-and-police-no-tax-increase/ the budgets mentioned just 8.1M for the housing first program

**Comment by Rtrott** [comment]
Yep the numbers for the Housing First program checks out!

**Comment by rdeleon0612** [comment]
Should I remove the 68.7 million?

**Comment by Rtrott** [comment]
I think so yep! I was going to go through and edit the stats if you'd be comfortable with that?

**Comment by rdeleon0612** [comment]
Oh please! Go ahead! I was struggling trying to make sense of all of it

**Comment by Rtrott** [comment]
to : mayor@honolulu.gov; ianderson@honolulu.gov; akobayashi@honolulu.gov; cafukunaga@honolulu.gov; jmanahan@honolulu.gov; belefante@honolulu.gov;  rmenor@honolulu.gov; tommy.waters@honolulu.gov; kmpine@honolulu.gov ; htsuneyoshi@honolulu.gov ;

Dear Mayor Caldwell and the Honolulu City and County Council,

My name is (your name) and I am a resident of Honolulu. I am writing to demand that Honolulu adopts a budget that prioritizes community wellbeing, and redirects funding away from the police.

In 2019, the City and County of Honolulu allocated $295,681,922 to our police. This is compared to just $112 million budgeted for ALL Community Services. Only $10.2 million was projected to be spent on the Housing First Program.

According to lthawaii.gov there are approximately 15,000 homeless people in Hawai’i. By diverting funds from the HPD budget of $296 million to the Housing First Project, we could drastically reduce this number. Further studies show this could reduce the amount of visits to the ER and healthcare centers from these individuals by 64% and the number of arrests by 61% (I have included the source of this data below) Spending the resources to properly help the homeless community will not only increase their life span and quality of life, but decrease Honolulu crime rates and save our city money. This is just one example of how divesting from the police could improve our city. 

I demand that the City Council begin meaningfully defunding the Honolulu Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Honolulu.

History has shown that police "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve--and in fact actively harms--our community, and come together to reimagine the role of police in our city.

Thank you for your time,
(Your name)
(Your address)
(your phone number)

Sources : https://www.honolulu.gov/rep/site/ohou/ohou_docs/HousingFirst-Societal-Impacts-Final.pdf

**Comment by rdeleon0612** [comment]
Looks good! What do I do now? Lol

**Comment by Rtrott** [comment]
I'll let the developers know it's ready to go up, and they'll change the tag for it and add it to the site as soon as they can! Thank you so much! :)

**Comment by rdeleon0612** [comment]
Thank you so much for your help!
