### ISSUE TITLE
Bergen County, NJ

### ISSUE THREAD

**Issue by martydefund12** [defund12/defund12.org#1180]
To: countyexecutive@co.bergen.nj.us, mamoroso@co.bergen.nj.us, jvoss@co.bergen.nj.us, DavidLGanz@co.bergen.nj.us, gortiz@co.bergen.nj.us, tsullivan@co.bergen.nj.us, Tracyzur@co.bergen.nj.us, Prosecutor@bcpo.net, dsands@bcsd.us

Subject: [CUSTOM SUBJECT]

To County Executive Tedesco, Board of Freeholders, County Prosecutor Musella, and County Sheriff Cureton,

My name is [YOUR NAME] and I am a resident of [YOUR TOWN/DISTRICT] in Bergen County. I am writing to demand that County Executive Tedesco and the Bergen County Board of Freeholders adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police. 

This week, the country has been gripped by protests demanding reconsideration of the role of police in America and an end to racism and anti-Blackness. Bergen County is not immune to the violence of racism in this country: Garfield resident Malik Williams was murdered by a police officer in 2011. His death is just one of many instances of police brutality in Bergen County, with several more instances of violence, abuse, and death at the hands of Bergen County officers. The County must do better. Moving funds away from the sheriff’s office and police department is a crucial way to combat these issues at the county level. 

The 2019 budget passed by County Exec. Tedesco and the Board of Freeholders appropriated almost 81 million dollars to the Sheriff’s Office, which is just about 15% of the county’s total budget. At the same time, an additional $658,000 was earmarked in revenues for spending on police body armor, among other costs (“BC 2019 Adopted State Budget”). While the budget for 2020 has not been made public, the appropriations in the 2019 budget highlight a severe imbalance in priorities. I demand that the County Board and County Executive begin to meaningfully defund the Sheriff’s Office and redirect funds to community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that supports community wellbeing, instead of one that empowers police forces to tear communities apart.

Sincerely,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by skullface** [comment]
Thank you for submitting your county to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment]
I’m reviewing
