### ISSUE TITLE
Arroyo Grande, CA

### ISSUE THREAD

**Issue by bmess4bml** [defund12/defund12.org#1187]
**To:**
lgeorge@arroyogrande.org 
kstorton@arroyogrande.org 
jpaulding@arroyogrande.org 
kbarneich@arroyogrande.org 
crayrussom@arroyogrande.org 

**Subject**: ++Insert Uniquie Subject Line++

**Message:**

Dear Mayor Caren Russom and Arroyo Grande City Council

My name is [YOUR NAME] and I am a resident of Arroyo Grande. I am writing to demand that the Arroyo Grande City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police.

In 2019, the City of Arroyo Grande allocated $6,950,000  dollars to our police system, an inordinate 39% of our total budget. This is compared much higher than the amount of money allocated towards community development, with only no money towards affordable housing development. Next year, the city estimates that there will be deficits as a result of the pandemic. The city may recoup these funds by decreasing the police budget.

I demand that the City Council begin meaningfully defunding the Arroyo Grande Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, affordable housing programs, not police. I demand a budget that reflects the actual needs of Arroyo Grande residents.

History has shown that police “reform” is not enough. No more money, and more importantly, no more lives must be lost to police. We must take a hard look at the way the current system in place fails to serve-and in fact actively harms-our community, and come together to reimagine the role of police in our city.

I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to invest in the people, not the police.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by skullface** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.
