### ISSUE TITLE
Oak Park, IL

### ISSUE THREAD

**Issue by Gracie-F** [defund12/defund12.org#1190]

**Comment by Gracie-F** [comment]
To: board@oak-park.us; mayoranan@oak-park.us; trusteeandrews@oak-park.us; trusteeboutet@oak-park.us; TrusteeBuchanan@oak-park.us; trusteemoroney@oak-park.us; trusteetaglia@oak-park.us; TrusteeWalker-Peddakotla@oak-park.us; clerkscaman@oak-park.us

Subject: [INSERT UNIQUE SUBJECT LINE]

Message:  [MAKE SURE YOU FILL IN BRACKETS]

Dear Mayor Anan Abu-Taleb and Oak Park Village Board,

My name is [YOUR NAME] and I am a resident of Oak Park. I am writing to demand that the Oak Park Village Board adopt a city budget that prioritizes community well-being, and redirects funding away from the police.

In FY2019, the Village of Oak Park allocated $24,877,758 dollars to our police system, an inordinate 39.6% of our total expense budget. This is compared much higher than the amount of money allocated towards public health services (0.01% of the budget), or any other department. Next year, there will likely be deficits as a result of the pandemic. The city may recoup these funds by decreasing the police budget.

I demand that the Village Board begin meaningfully defunding the Oak Park Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs. Police officers should not need to be the first resource for every crisis. I demand a budget that reflects the actual needs of Oak Park residents.

History has shown that police “reform” is not enough. Policing in America was developed to protect the institution of slavery. More money and training programs will not only not fix our current system, they will cause future lives to be lost to police brutality. We must take a hard look at the way the current system in place fails to serve-and in fact actively harms-our community, and come together to reimagine the role of police in our city.

I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to invest in the people, not the police.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by skullface** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by Rtrott** [comment]
Reviewing now!

**Comment by Rtrott** [comment]
To: board@oak-park.us; mayoranan@oak-park.us; trusteeandrews@oak-park.us; trusteeboutet@oak-park.us; TrusteeBuchanan@oak-park.us; trusteemoroney@oak-park.us; trusteetaglia@oak-park.us; TrusteeWalker-Peddakotla@oak-park.us; clerkscaman@oak-park.us

Dear Mayor Anan Abu-Taleb and the Oak Park Village Board,

My name is [YOUR NAME] and I am a resident of Oak Park. I am writing to demand that the Oak Park Village Board adopt a city budget that prioritizes community well-being, and redirects funding away from the police.

In 2019, the Village of Oak Park allocated $24,877,758 to our police system, an inordinate 33% of the Village general fund budget. This is compared much higher than the amount of money allocated towards public health services (less than 0.01% of the budget), or any other department. Next year, there will likely be deficits as a result of the pandemic. The city must recoup these funds by decreasing the police budget.

I demand that the Village Board begin meaningfully defunding the Oak Park Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs. Police officers should not need to be the first resource for every crisis. I demand a budget that reflects the actual needs of Oak Park residents.

History has shown that police “reform” is not enough. Policing in America was developed to protect the institution of slavery. More money and training programs for police will not fix our current system. It will instead cause future lives, especially Black lives, to be lost to police brutality. We must take a hard look at the way the current system in place fails to serve - and in fact actively harms - our community, and come together to reimagine the role of police in our city.

I am urging you to act on this as you develop the budget for the 2020-2021 fiscal year, and to invest in the people, not the police.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
