### ISSUE TITLE
Typo in Fullerton, CA email

### ISSUE THREAD

**Issue by DefundPoliceFullerton** [defund12/defund12.org#1192]
Hi! There is a typo in the Fullerton email. https://defund12.org/fullerton on the first line of the second paragraph. 

"....According to the Fullteron city website"

It should say "Fullerton" not "Fullteron"

Thank you so much!

**Comment by skullface** [comment]
Oops, thanks so much for flagging! We’ll get this fixed.

**Comment by swallan** [comment]
Thanks, @DefundPoliceFullerton, a correction has been made and will be going live soon.
