### ISSUE TITLE
Walla Walla, WA

### ISSUE THREAD

**Issue by solguad** [defund12/defund12.org#1195]
**TO:** tscribner@wallawallawa.gov, smoss@wallawallawa.gov, ybahena@wallawallawa.gov, rclubb@wallawallawa.gov, mhuie@wallawallawa.gov, tkoehler@wallawallawa.gov, snakonieczny@wallawallawa.gov

**SUBJECT:** [INSERT UNIQUE SUBJECT LINE]

**BODY:** (Don't forget to replace the [X]'s with your own information!!)

Dear Mayor Scribner and Walla Walla City Council Members,

My name is [NAME] and I am a resident of Walla Walla. 

I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

The past [NUMBER] weeks, our nation and community have been gripped by protests calling for an end to racism and anti-Blackness, and a complete overhaul in our approach to criminal justice. As a country, we are demanding that our voices be heard and that real change be implemented at all levels of community and government.

Walla Walla must follow the example set by cities like Minneapolis and respond to police violence by reevaluating our city’s budget priorities to better reflect the needs of our community. I urge you to advocate for a meaningful reallocation of the city’s expenditures: away from policing, and towards social programs and resources that support housing, education, physical healthcare, mental healthcare, childcare, and other critical community needs while responding to issues like domestic violence and sexual assault with trained crisis responders. Research shows that a living wage, access to health services and treatments, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (source: Popular Democracy).

The 2020 budget for policing in Walla Walla currently exceeds $9.98 million USD, accounting for 27.5% of the city’s general fund expenditure. Applied elsewhere, this money could effect real, positive change in our community. **I demand the immediate freezing of budget increases to the WWPD, demilitarization of the police force, and reallocation of funds from police to community-led health and safety strategies.** This must be a priority for not just the 2021-2022 biennial budget, but all subsequent city budgets.

If any complaints are filed against an officer for excessive use of force or an officer espouses white supremacist beliefs (such as through the display of Nazi/neo-Nazi iconography), they should be removed from the force. In addition, throughout the process of reallocating funds away from policing, no new officers should be hired to the WWPD, the number of SRO’s placed in public schools should not be increased, and no city or police funds should be used to purchase military surplus gear for the Walla Walla police force.

If we have the courage to change, we can set a positive example for all of Eastern Washington. 

Thank you for your time,
[YOUR FULL NAME]
[HOME ADDRESS]
[EMAIL ADDRESS]
[TELEPHONE]

**Comment by skullface** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment]
I’m reviewing

**Comment by solguad** [comment]
Edit: I wouldn't want to slow the review process at all, but it might be good to ensure self-consistency in the citations and add the missing 'return' before the last line of text. I changed that (and nothing else) here but ignore if it's not helpful.

“TO: tscribner@wallawallawa.gov, smoss@wallawallawa.gov, ybahena@wallawallawa.gov, rclubb@wallawallawa.gov, mhuie@wallawallawa.gov, tkoehler@wallawallawa.gov, snakonieczny@wallawallawa.gov

SUBJECT: [INSERT UNIQUE SUBJECT LINE]

BODY: (Don't forget to replace the [X]'s with your own information!!)

Dear Mayor Scribner and Walla Walla City Council Members,

My name is [NAME] and I am a resident of Walla Walla.

I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

The past [NUMBER] weeks, our nation and community have been gripped by protests calling for an end to racism and anti-Blackness, and a complete overhaul in our approach to criminal justice. As a country, we are demanding that our voices be heard and that real change be implemented at all levels of community and government.

Walla Walla must follow the example set by cities like Minneapolis and respond to police violence by reevaluating our city’s budget priorities to better reflect the needs of our community. I urge you to advocate for a meaningful reallocation of the city’s expenditures: away from policing, and towards social programs and resources that support housing, education, physical healthcare, mental healthcare, childcare, and other critical community needs while responding to issues like domestic violence and sexual assault with trained crisis responders. Research shows that a living wage, access to health services and treatments, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons [1].

The 2020 budget for policing in Walla Walla currently exceeds $9.98 million USD, accounting for 27.5% of the city’s general fund expenditure [2]. Applied elsewhere, this money could effect real, positive change in our community. I demand the immediate freezing of budget increases to the WWPD, demilitarization of the police force, and reallocation of funds from police to community-led health and safety strategies. This must be a priority for not just the 2021-2022 biennial budget, but all subsequent city budgets.

If we have the courage to change, we can set a positive example for all of Eastern Washington.

Thank you for your time,
[YOUR FULL NAME]
[HOME ADDRESS]
[EMAIL ADDRESS]
[TELEPHONE]

[1] https://populardemocracy.org/news/publications/freedom-thrive-reimagining-safety-security-our-communities
[2] https://www.wallawallawa.gov/home/showdocument?id=2903
