### ISSUE TITLE
San Luis Obispo County, CA

### ISSUE THREAD

**Issue by bmess4bml** [defund12/defund12.org#1202]
To:
District 1: jpeschong@co.slo.ca.us, vjanssen@co.slo.ca.us
District 2: bgibson@co.slo.ca.us, bfixler@co.slo.ca.us
District 3: ahill@co.slo.ca.us, nnix@co.slo.ca.us
District 4: lcompton@co.slo.ca.us, district4@co.slo.ca.us
District 5: darnold@co.slo.ca.us, molinger@co.slo.ca.us

Subject: ++Insert Uniquie Subject Line++

Message:

Dear [YOUR DISTRICT SUPERVISOR NAME]

My name is [YOUR NAME] and I am a resident of San Luis Obispo county. I am writing to demand that the county of San Luis Obispo adopt a budget that prioritizes community well-being, and redirects funding away from the police. It is unacceptable that Black, Indigenous, and People of Color communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors.

In the current proposed budget, the County of San Luis Obispo allocated 52.7 million dollars to our Sheriff-Coroner department, and inordinate 23% of our county budget (and this does not include an additional $5,775,892 for Law Enforcement health care). This number is particulary alarming when compared to the county services with evidence backed results in reducing crime. The Sheriffs budget is almost double the combined budget of the following programs which all together only make up $28.8 million, or 12.5% of the county's budget:
-Behavioral Health Services ($13,270, 246)
-Public Health Servies ($9,006,392)
-Child Support Services ($255,459)
-Community Parks ($3,977,039)
-Veteran Services ($680,039)
-Foster Care / Adoption Services ($1,400,604)
-CalWORKS ($261,080)

Additionally, community development is seeing one of the largest decreases in funding, with a recommended budget of $40,161, an unbelievable 92.3% decrease from the 19-20 budget. All of this at the same time Sheriff department requests $4.2 million additional funding for adding overtime hours in order to increase police presence by 75% during a pandemic stay at home order, while the Sheriff's department itself only sets a goal of 68% for violent crimes (admitedly better than the 55% it achieved in 18-19), the Sheriff's department regularly wastes county money with lawsuits like the $5 million settlement to the Holland family, and Ian Parkinson is paid $277,441 a year (more than the entire county spends on CalWORKS).

I demand that the County begin meaningfully defunding the San Luis Obispo Sheriff Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, affordable housing programs, not police. I demand a budget that reflects the actual needs of San Luis Obispo County residents.

History has shown that police “reform” is not enough. No more money, and more importantly, no more lives must be lost to police. We must take a hard look at the way the current system in place fails to serve-and in fact actively harms-our community, and come together to reimagine the role of police in our city.

I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to invest in the people, not the police.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by skullface** [comment]
Reviewer note: separate audience from existing SLO city email at https://github.com/defund12/defund12.org/issues/423

**Comment by swallan** [comment]
District 1: jpeschong@co.slo.ca.us, vjanssen@co.slo.ca.us
District 2: bgibson@co.slo.ca.us, bfixler@co.slo.ca.us
District 3: ahill@co.slo.ca.us, nnix@co.slo.ca.us
District 4: lcompton@co.slo.ca.us, district4@co.slo.ca.us
District 5: darnold@co.slo.ca.us, molinger@co.slo.ca.us

Subject: ++Insert Uniquie Subject Line++

Message:

Dear [YOUR DISTRICT SUPERVISOR NAME]

My name is [YOUR NAME] and I am a resident of San Luis Obispo county. I am writing to demand that the county of San Luis Obispo adopt a budget that prioritizes community well-being, and redirects funding away from the police. It is unacceptable that Black, Indigenous, and People of Color communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors.

In the current proposed budget, the County of San Luis Obispo allocated 52.7 million dollars to our Sheriff-Coroner department, and inordinate 23% of our county budget (and this does not include an additional $5,775,892 for Law Enforcement health care). This number is particulary alarming when compared to the county services with evidence backed results in reducing crime. The Sheriffs budget is almost double the combined budget of the following programs which all together only make up $28.8 million, or 12.5% of the county's budget:
-Behavioral Health Services ($13,270, 246)
-Public Health Servies ($9,006,392)
-Child Support Services ($255,459)
-Community Parks ($3,977,039)
-Veteran Services ($680,039)
-Foster Care / Adoption Services ($1,400,604)
-CalWORKS ($261,080)

I demand that the County begin meaningfully defunding the San Luis Obispo Sheriff Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, affordable housing programs, not police. I demand a budget that reflects the actual needs of San Luis Obispo County residents.

History has shown that police “reform” is not enough. No more money, and more importantly, no more lives must be lost to police. We must take a hard look at the way the current system in place fails to serve-and in fact actively harms-our community, and come together to reimagine the role of police in our city.

I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to invest in the people, not the police.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by bmess4bml** [comment]
Please post this asap. County budget meeting is on Tuesday.
