### ISSUE TITLE
Claremont, CA

### ISSUE THREAD

**Issue by Gracie-F** [defund12/defund12.org#1210]
To: ccalaycay@ci.claremont.ca.us; jleano@ci.claremont.ca.us; ereece@ci.claremont.ca.us; lschroeder@ci.claremont.ca.us; jstark@ci.claremont.ca.us 

Subject: [INSERT UNIQUE SUBJECT LINE]

Message: [MAKE SURE YOU FILL IN BRACKETS. ALSO ADD A LINE OR TWO SO THEY HAVE TO READ EACH MESSAGE]

Dear Mayor Larry Schroeder, Mayor Pro Tem Jennifer Stark, and Claremont City Council members,

My name is [YOUR NAME] and I am a resident of Claremont. I am writing to demand that the Claremont City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police.

In FY2019, the City of Claremont allocated an egregious $12,496,360 to our police department. Next year, there will likely be deficits as a result of the pandemic. The city may recoup these funds by decreasing the police budget.

I demand that the City Council begin meaningfully defunding the Claremont Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs. Police officers should not need to be the first resource for every crisis. I demand a budget that reflects the actual needs of Claremont residents.

History has shown that police “reform” is not enough. Policing in America was developed to protect the institution of slavery. More money and training programs will not only not fix our current system, they will cause future lives to be lost to police brutality. We must take a hard look at the way the current system in place fails to serve-and in fact actively harms-our community, and come together to reimagine the role of police in our city.

I am urging you to keep these things in mind for the budget for the 2020-2021 fiscal year and to invest in the people, not the police.

Thank you for your time,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by swallan** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by rpalakkal** [comment]
adding this one
