### ISSUE TITLE
Austin, TX email bounce 

### ISSUE THREAD

**Issue by sneakmeg** [defund12/defund12.org#1229]
Emails bouncing over a period of a few days to the addresses in the current Austin email. Someone cited that the below emails are correct: 

steve.adler@austintexas.gov
district2@austintexas.gov
district1@austintexas.gov
sabino.renteria@austintexas.gov
district4@austintexas.gov
district5@austintexas.gov
district8@austintexas.gov
district6@austintexas.gov
kathie.tovo@austintexas.gov  
district10@austintexas.gov 

The template claims that "over ⅓ of Austin’s budget should be allocated to the police." This is untrue. Over 1/3 of Austin's "General Funds" budget goes to the police. The "General Funds" is only about 1/3 of Austin's total budget. In reality about 1/10th (9.5%) of the budget goes to APD (still far too much).

I have found that opponents to the cause will jump at any inconsistencies to prove arguments are invalid. I thus believe it is important to get the facts straight, to make the case as effectively as possible. If there is anyway to change the template to reflect the true nature of the budget that would be much appreciated.

**Comment by swallan** [comment]
Thanks, @sneakmeg, a correction has been made and will be going live soon.

**Comment by avimoondra** [comment]
Closing as per https://github.com/defund12/defund12.org/pull/1235
