### ISSUE TITLE
Olympia, WA email 

### ISSUE THREAD

**Issue by sneakmeg** [defund12/defund12.org#1230]
jbateman@ci.olympia.wa.us
dmadrone@ci.olympia.wa.us
cgilman@ci.olympia.wa.us
lparshle@ci.olympia.wa.us
rrollins@ci.olympia.wa.us
jcooper@ci.olympia.wa.us
cselby@ci.olympia.wa.us

Dear Olympia City Leadership,

My name is [your name] and I am a resident of Thurston County. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing, embodied by the OPD's well documented history of murdering Black people. With our history of policing and violence directed at people of color including Andre Thompson and Bryson Chaplin in 2105 and the recent murders of black people including Olympia resident Yvonne McDonald, empty gestures and suggestions of “reform" are no longer acceptable. I am demanding that my voice and that of others be heard now, and that real change be made to the way this city allocates its resources.

Rather than prioritize the quality of life for all of Olympia with a proportional housing and development budget, Mayor Selby chooses to prioritize the OPD. In 2020 proposed budget, the funding for the Community Planning and development was $7,808,120. In comparison, the OPD was allocated a budget of $20,650,484. 

This pandemic has had severe economic consequences including high unemployment causing many people to be unable to pay rent. Prior to the pandemic,  800 people were unhoused according to the PIT homeless census counts in Thurston county; the evictions and economic insecurity caused by COVID-19 will bring that number even higher. Support for communities in need is necessary now, more than ever. But instead, out of all departments, the Mayor has proposed a budget that is allocating $12,842364 more to the OPD than to Community Planning and Development. This money can be spent in other ways that are proven to be more effective in improving community safety and wellness.

I demand that the City Council defund the OPD. I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of at-risk Olympians. I demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

Although City Council has avoided voting or revising Mayor Selby's budget proposal, the document is back in your hands. It is your duty to represent your constituents. I am urging you to completely revise the Olympia budget for 2020-2021 fiscal year. You need to adopt a People’s Budget. Public opinion is with me.

Thank you for your time,

[Name]

[Address]

[E-mail]

[Number]

Messages should follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md). Remember that messages must be specific to your locale and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!
-->

**Comment by mahrer** [comment]
Hi @sneakmeg, thanks for your request to add Olympia to the site! We have an open request at #986 . If you’d like to add to or edit the messaging, please visit that issue.
Thank you!
