### ISSUE TITLE
Pittsburgh, PA incorrect info 

### ISSUE THREAD

**Issue by sneakmeg** [defund12/defund12.org#1237]
I'm from just outside Pittsburgh and wanted to point out that Antwon Rose was not shot by Pittsburgh Police, but East Pittsburgh, which is a separate borough. Maybe the text could be updated to say he was shot in our region?  Thanks!

Please add: brosha.tkacheva@pittsburghpa.gov

**Comment by swallan** [comment]
thanks! on it
