### ISSUE TITLE
Pomona, CA - Letter to Mayor and City Council 

### ISSUE THREAD

**Issue by accountability1** [defund12/defund12.org#1240]
To: Tim_Sandoval@ci.pomona.ca.us,Rubio_Gonzalez@ci.pomona.ca.us,Victor_Preciado@ci.pomona.ca.us,Nora_Garcia@ci.pomona.ca.us,Elizabeth_Ontiveros-Cole@ci.pomona.ca.us,Steve_Lustro@ci.pomona.ca.us,Robert_Torres@ci.pomona.ca.us  🔗

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!) 🔗

Dear Mayor Sandoval and Pomona City Council Members,

My name is [NAME HERE] and I am a Pomona resident. Pomona PD reserves an enormous share of the city’s general fund, taking away desperately needed resources from essential city programs and services. Approximately 53% of our city’s budget is directed to the police department, while only 15.5% is devoted to essential neighborhood services, development services, library services, and public works combined. 

Though Pomona is faced with a projected loss of $7.7 million in revenue received by June 30, 2020, we are set to continue to appropriate general funds to Pomona PD at levels relatively consistent to FY 2019-20. Pomona PD’s proposed $62 million budget will be used at the expense of vital public services, such as creating housing opportunities for homeless residents and improving accessibility of the Pomona Valley Transportation Authority. The investment in policing has not made us safer – Pomona PD continues to constitute a lethal threat to the city’s Black and Brown communities. With Pomona’s current finances in dire jeopardy, it is clear that we must defund the police.

As a Pomona resident, I demand that you take immediate action to ensure the following:

1. Significantly reduce Pomona PD’s allocation from the general fund.
2. Remove school resource officers from Pomona USD. 
3. Invest in housing, youth programs, restorative justice, and mental health workers to keep the community safe.

Pomona can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund Pomona PD.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by accountability1** [comment]
Sources:https://www.ci.pomona.ca.us/mm/finance/budg/2020-2021/OPERATING/4.0%20Financial%20Summary%20final.pdf https://www.ci.pomona.ca.us/mm/finance/budg/2020-2021/OPERATING/2.0%20BudgetMessage.pdf

**Comment by swallan** [comment]
@accountability1 Thanks for the sources!

**Comment by wendywx** [comment]
edits in bold:

---------------------------------------

To: Tim_Sandoval@ci.pomona.ca.us,Rubio_Gonzalez@ci.pomona.ca.us,Victor_Preciado@ci.pomona.ca.us,Nora_Garcia@ci.pomona.ca.us,Elizabeth_Ontiveros-Cole@ci.pomona.ca.us,Steve_Lustro@ci.pomona.ca.us,Robert_Torres@ci.pomona.ca.us 🔗

Message (Don't forget to replace the [x]'s with your information!) 🔗

Dear Mayor Sandoval and Pomona City Council Members,

My name is **[YOUR NAME]** and I am a Pomona resident. Pomona PD reserves an enormous share of the city’s general fund, taking away desperately needed resources from essential city programs and services. Approximately 53% of our city’s **General Fund** budget is directed to the police department, while only **14.2**% is devoted to essential neighborhood services, development services, library services, and public works combined.

Though Pomona is faced with a projected loss of $7.7 million in revenue received by June 30, 2020, we are set to continue to appropriate general funds to Pomona PD at levels relatively consistent to FY 2019-20. Pomona PD’s proposed $62 million budget will be used at the expense of vital public services, such as creating housing opportunities for homeless residents and improving accessibility of the Pomona Valley Transportation Authority. The investment in policing has not made us safer – Pomona PD continues to constitute a lethal threat to the city’s Black, Brown, **and Indigenous** communities. With Pomona’s current finances in dire jeopardy, it is clear that we must defund the police.

As a Pomona resident, I demand that you take immediate action to ensure the following:

1. Significantly reduce Pomona PD’s allocation from the general fund.
2. Remove school resource officers from Pomona USD.
3. Invest in housing, youth programs, restorative justice, and mental health workers to keep the community safe.

Pomona can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund Pomona PD.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

-------------------------------------------------------------

Confirmed the statistics and added a few clarifying words, marking as ready for PR.

**Comment by ctneal91** [comment]
on it now

**Comment by rpalakkal** [comment]
@ctneal91 my bad
