### ISSUE TITLE
Support the Students of Randolph

### ISSUE THREAD

**Issue by maysawhyte** [defund12/defund12.org#1249]
Bhoward@randolph-ma.gov 
superintendent@randolph.k12.ma.us
nixona@randolph.k12.ma.us 
lisa.millwood@randolph.k12.ma.us 
pamela.davis@randolph.k12.ma.us 
frazierc@randolph.k12.ma.us 
gordoni@randolph.k12.ma.us 
duong.nguyen@randolph.k12.ma.us 
paul.mcdermott@randolph.k12.ma.us 
pmcdermott@randolph-ma.gov 
randolphtowncouncil@randolph-ma.gov 
jburgess@randolph-ma.gov 
regan@randolph-ma.gov 
WAlexopoulos@randolph-ma.gov 
RBrewer@randolph-ma.gov 
nclerger@randolph-ma.gov 
KClifton@randolph-ma.gov 
khuff-larmond@randolph-ma.gov 
calexopoulos@randolph-ma.gov 

Hello,

My name is [INSERT NAME]. I am a [RESIDENT/AFFILIATE/TEACHER, ETC] of Randolph and I am writing today to express my concerns about the divestment of the Arts, Music, and Physical Education departments, social workers, and counselors across all public schools and to demand that you allocate a portion of the Stabilization Fund to attain level-services as presented by the Town Manager’s budget for FY21.

What is the point of the Stabilization Fund if you’re not spending it for its intended purpose? How is laying off twenty-six members of our teaching staff, five social workers, and six K-8 counselors amid a pandemic providing a bright future for the Randolph community?

Cutting public education will cause severe negative externalities on students and families, which will have long-lasting effects on our community. After defunding the music program in 2003 and nearly losing accreditation in 2007 and, RHS graduation rates[1] dropped by 5.2 percent. It took over a decade to recover from those losses. Today, this situation is even more dire.

The senseless acts of police brutality against black people have shown the vast inequities they face for just being black. Studies have shown that previous killings of unarmed black people by police officers show a deterioration in the mental health of black Americans. With nearly half of Randolph students identifying either as African-American/black, these children need more support from their teachers, social workers, and counselors than ever before.

As part of the provisions of Massachusetts General Law, Part I, Title VII, Chapter 40, Section 6, “To provide for extraordinary or unforeseen expenditures, a town may at an annual or special town meeting appropriate or transfer a sum or sums not exceeding in the aggregate five percent of the levy of the fiscal year preceding the fiscal year for which the fund, to be known as the reserve fund, is established.” Under the law, any school district that accepts this section, by a majority vote of the school committee and the legislative body may transfer money to the reserve fund. This is exactly what the Stabilization Fund and reserves intended use is: to fill the gaps until revenue starts coming back.

I understand tough decisions need to be made; however, I strongly believe it is time to enact the “rainy day” fund to attain level-services for all public-school students. We cannot let our public schools revert to the systemic problems that have crippled this community for decades. Let us not make the same mistakes we made before by not investing in our long-term growth. Look back at the past, when Randolph nearly lost accreditation in 2007 from the severe cuts that rippled our public schools, to inform the present. The future of our students — and the trajectory of our community — rests in your hands.

We the residents of Randolph will hold you accountable for swift and just action.

Sincerely,

**Comment by swallan** [comment]
Hi @maysawhyte! Thanks for your interest in adding Randolph to the site. It looks like you have some unfinished content in your message. Please reply here when you make those changes. See our [email style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for suggestions:

**- We are amplifying calls to defund the police. The core message should be a direct statement to defund the police. Specific demands for reforms (e.g., policing tactics and training) will be removed.**

Thank you!

**Comment by maysawhyte** [comment]
> Hi @maysawhyte! Thanks for your interest in adding Randolph to the site. It looks like you have some unfinished content in your message. Please reply here when you make those changes. See our [email style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for suggestions:
> 
> **- We are amplifying calls to defund the police. The core message should be a direct statement to defund the police. Specific demands for reforms (e.g., policing tactics and training) will be removed.**
> 
> Thank you!

Thank you for your prompt response. Can you direct me to a similar matter that will let me do the same thing that you do possibly, if you know of something? We are trying to circulate a letter to our town leaders and I saw this platform used many times in regards to defunding the police and it definitely an oversight on my part because this is specifically for that reason. This is my first time on GitHub sorry!!

**Comment by maysawhyte** [comment]
@swallan ^^

**Comment by swallan** [comment]
@maysawhyte Can this help you? https://mailtolink.me/
