### ISSUE TITLE
Johns Creek - Letter to the Mayor and City Council

### ISSUE THREAD

**Issue by suprisama** [defund12/defund12.org#1250]
lenny.zaprowski@johnscreekga.gov
mike.bodker@johnscreekga.gov
brian.weaver@johnscreekga.gov 
john.bradberry@johnscreekga.gov
chris.coughlin@johnscreekga.gov
stephanie.endres@johnscreekga.gov
erin.elwood@johnscreekga.gov
ed.densmore@johnscreekga.gov

Dear Mayor Bodker and members of the Johns Creek City Council:

My name is [YOUR NAME]; I am a resident of [NEIGHBORHOOD/CITY/BOROUGH], and I am emailing to demand the resignation of JCPD Chief of Police Chris Byers as well as redistribution of city funds away from the police and towards community-oriented programs.

Recent events have indicated that the Johns Creek Police Chief Chris Byers shows no respect towards the Black community in Johns Creek and has no demonstrable knowledge of the Black Lives Matter movement. His position within the JCPD is one of power and influence, and the clearly racist and uninformed ideas that he has expressed are angering and concerning. His lack of empathy and understanding on behalf of the Black community is not only personal but also reflects on the JCPD as an institution. This is a call for the immediate resignation of Chris Byers and the temporary instatement of a police chief who has demonstrated empathy and humanity towards Black lives.

Furthermore, this is a request to redirect the 26% of the city’s budget allocated to the police towards underfunded departments such as Community Development and Parks and Recreation. JCPD was granted a budget of roughly $12 million in the 2020 Fiscal Year which surpasses the combined budget of Parks and Recreation, Community Development, and Public Works. Additionally, The JCPD currently has 88 full-time employees whereas Parks and Recreation, Community Development, and Public Works have a total of 17. This allocation of funding and personnel to a historically anti-Black institution negatively reflects the values of the City of Johns Creek as more concerned with the policing of Black bodies than investment in community-led initiatives that have been proven to reduce crime. I also urge the City Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity, but above all defunding is the most necessary and direct path to ensure the safety of Johns Creek’s residents.

The statement released regarding both the actions of Chris Byers and the “vital role” of the JCPD lead me to believe that you are not committed to Black lives in our community. The careful review that you have promised has fallen significantly short of the request that is being made and again demonstrates a lack of empathy and humanity. The words of Chris Byers are indeed far-reaching, and they have not fallen on deaf ears. I ask that you deeply consider the implications of allowing Chris Byers to retain his position and the impression made by your unwillingness to publicly condemn the man speaking these hateful words. Furthermore, defunding the police is a legitimate and necessary means to ensure the safety of all of Johns Creek’s residents. The JCPD has a history of disproportionately policing Black and Brown bodies and using excessive force in cases where crisis workers with mental health training would be far more effective, to which I am sure the family of Shukri Ali Said can attest. For these residents, the police do not ensure their safety but actively threaten it. Defunding the police necessarily means allocating money and resources towards crisis responders and medics and away from strangers with guns. It means creating jobs, investing in education, and promoting mental health resources, all of which are proven to promote community safety. These are the actions that will result in a healthier, more just community. I implore you to please listen to the needs of your constituents and take immediate action to address these concerns.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by brickaney** [comment]
I’m reviewing

**Comment by todd-m** [comment]
on it
