### ISSUE TITLE
Add one for Chattanooga, TN!

### ISSUE THREAD

**Issue by chatt-blm** [defund12/defund12.org#1263]
Subject line: Please Support the Chattanooga Community During This Time

To: cchenderson@chattanooga.gov, jmitchell@chattanooga.gov, kensmith@chattanooga.gov, dledford@chattanooga.gov, rgilbert@chattanooga.gov, cberz@chattanooga.gov, eoglesbyjr@chattanooga.gov, abyrd@chattanooga.gov, dcoonrod@chattanooga.gov, mayor@chattanooga.gov (city council members and city mayor) 

Hello,

My name is [NAME], and I am a resident of Chattanooga, Tennessee. I am writing to ask that money is allocated away from the Hamilton County Sheriff’s Office and instead towards the Chattanooga community, specifically in terms of COVID relief and community development.

On Sunday, May 31, deputies serving the Hamilton County Sheriff’s Office used tear gas on protesters, a substance banned in warfare as a result of the Chemical Weapons Convention and the 1925 Geneva Protocol. It is absolutely deplorable that these deputies felt the need to tear gas protesters, who are the very people they took an oath to protect and serve, and it is even more appalling that Hamilton County Sheriff Jim Hammond and Hamilton County Mayor Jim Coppinger defended a practice outlawed in war over ninety years ago. We should not, we cannot, excuse the heinous actions of these people and pretend that one of our own institutions didn’t hurt the members of its own community.

Over the past few months, COVID-19 has had a severe and negative impact on our city. From an increased demand in healthcare services to the financial losses many small and local businesses owners have faced, many Chattanooga residents have felt the effect of coronavirus deeply. That is why I implore that you help these members of our community by reallocating money to coronavirus relief and investing in the community with the funds taken away from the Hamilton County Sheriff’s Office if you so choose to reduce the amount of money the office receives.

Our city is at its worst when its people are afraid. In light of the death of George Floyd, many members of our Chattanooga community have been reminded of the unfortunate reality that is police brutality, and when deputies part of the Hamilton County Sheriff’s Office use tear gas on the same people they are meant to protect and serve, we don’t feel any safer. You are in a unique position of power to denounce the actions of the Hamilton County Sheriff’s Office and support the Chattanooga community. I urge you to use this power to the fullest extent of your ability and show us that you are here to help and serve the people of this city as you have promised.

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment]
I’m reviewing.
