### ISSUE TITLE
Concord CA

### ISSUE THREAD

**Issue by cliffbraun** [defund12/defund12.org#1266]
To:
citycouncil@cityofconcord.org
valerie.barone@cityofconcord.org
carlyn.obringer@cityofconcord.org
tim.mcgallian@cityofconcord.org
dominic.aliano@cityofconcord.org
laura.hoffmeister@cityofconcord.org
edi.birsan@cityofconcord.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message (Don't forget to replace the [x]'s with your information!) 
To whom it may concern,

My name is [INSERT NAME] and I am a resident of Concord. Our nation is in the midst of widespread upheaval over the systemic violence of policing, and the Bay Area has been at the forefront of much of this action. I’m writing to you today to demand that Concord adopts a People’s Budget that redirects funding away from the police and towards prioritizing other programs—affordable housing for our homeless and low-income neighbors, mental health programs (NOT by police), rent suspension and cancellation during this pandemic, and finally, more rehabilitative approaches to public health issues. By taking a preventative approach to stop violence in the community, Concord would reduce the need for a police force. Concord’s needs must be addressed by the provision of care, and not by conflict or by the threat of violence.

The Mayor and city council showed up at Todos Santos to listen to the voice of our community in early June. I would encourage you to take what you heard and apply It to your budget. the Concord Police Department is the single largest expenditure in the City’s General Fund and sees the smallest percentage reduction in your budget proposal. The city currently spends 57% of its general fund on police—$64.4m in the last fiscal year—more than $50 million more than was spent on community development, which is allocated the least amount of funding sans the library. Do not cut funding for Camp Concord, the local pool, and other public services while leaving this bloat.

We’re not asking for much, we just want human-centered services. Research shows that a living wage, access to health services and treatment, educational opportunities, and stable housing are far more successful at promoting safe communities compared to police or prisons. Support for communities in need—especially our communities of color and low-income communities—is necessary now, more than ever. As such, we need more aggressive financial support to be directed to those areas. Where should that money come from? The projected $50+ million to be allocated towards CPD this fiscal year.

We are demanding that this money be reallocated from the police department because it is an inherently harmful organization that has not responded to reform. More training or diversity among police officers won’t end police brutality, nor will firing and charging individual officers. Look at the Minneapolis Police Department. Their department offers trainings for implicit bias, mindfulness and de-escalation, embraces community policing and officer diversity, uses body cameras, implements an early intervention system to identify problematic officers, and receives training around mental health crisis intervention. George Floyd was still murdered. Historically, police forces were created to protect the property of white-owned businesses and the wealthy and enforce white supremacy. Today, despite the diversification of police services, the main activity of police remains street patrol. Police rarely focus on “white collar” crime; instead, they protect the living, working and commercial arrangements that keep capitalism running, and the white, upper-class citizens that benefit from them. Because the fundamental role of the police is to defend this unequal system, it is impossible for police to protect and serve everyone equally. Now more than ever is the time to demilitarize and divest from police resources. Imagine if the money used to pay the salaries of police officers, who endlessly patrol public housing buildings and harass residents, was used to fund alternative emergency response programs: trained first responders to help in mental health crises, city employees to check in on homeless citizens in our parks, and trauma-informed crisis intervention teams to disarm and de-escalate gun-related conflicts. Now is the time to drop the dated ideal that police force is the only way to keep us safe.

I join the calls of those across the country to defund the police and invest in the health and safety of our community. I demand a budget that adequately and effectively meets the needs of at-risk Concord residents during this trying and uncertain time, when livelihoods are on the line. I call on you to slash the CPD budget and instead, meaningfully reallocate funds towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart. I will oppose any additional sales tax ballot initiatives without significant reductions to the policing budget.

It is your duty to represent your constituents. I am urging you to completely revise the Concord city budget for 2020-2021 fiscal year. Public opinion is with me.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by cliffbraun** [comment]
some tweaks based on city council feedback to other letters tonight.

**Comment by brickaney** [comment]
@mahrer  Please close issue as duplicate/merge with existing. This city already has an email generated.

@cliffbraun If you’d like to add-to or edit content in the existing city email, submit a new issue.

**Comment by cliffbraun** [comment]
Bit confused by this comment, I don't see anything for Concord, CA in issues, PR, the website, or the emails folder. There is one for NH? There's also a closed issue where the person did not provide contact info.

**Comment by mahrer** [comment]
I think @brickaney may have gotten Concord NH and CA mixed up. I don't see anything in the works for Concord CA so I'm gonna leave this open.

**Comment by brickaney** [comment]
Oops, you’re right! I’ve actually lived in Concord, CA so I will review right now. Sorry about the mixup.

**Comment by cliffbraun** [comment]
Thanks for review!

http://www.cityofconcord.org/DocumentCenter/View/3167/Adopted-Biennial-Operating-Budget-Fiscal-Years-2019-21-PDF Page XXVII has char.
