### ISSUE TITLE
Repo access for devthered

### ISSUE THREAD

**Issue by devthered** [defund12/defund12.org#1269]
# Repo access

👋 I am a defund12.org collaborator requesting permissions to push branches and submit pull requests so I can assist on the dev team. I'd like to submit a pull request with a potential implementation of [Issue 1188](https://github.com/defund12/defund12.org/issues/1188).

**Comment by NickCrews** [comment]
Hey @devthered! FYI you shouldn't need permissions to submit pull requests, you just would need permissions to merge them. So feel free to implement something on your fork and the submit a PR.

I think the core team is being pretty frugal with giving out write permissions, so I doubt you will get it until you do some contributions to demonstrate that you're not likely to crash something.

**Comment by devthered** [comment]
> Hey @devthered! FYI you shouldn't need permissions to submit pull requests, you just would need permissions to merge them. So feel free to implement something on your fork and the submit a PR.
> 
> I think the core team is being pretty frugal with giving out write permissions, so I doubt you will get it until you do some contributions to demonstrate that you're not likely to crash something.

Oh, my bad - I tried to branch locally and push that instead of forking. I'll fork it instead and submit a PR :-)

**Comment by devthered** [comment]
See PR from forked branch at: #1270
