### ISSUE TITLE
Lakewood, WA

### ISSUE THREAD

**Issue by alfonsojgodinez** [defund12/defund12.org#1283]
**TO**: danderson@cityoflakewood.us; jwhalen@cityoflakewood.us; mmoss@cityoflakewood.us; mbrandsetter@cityoflakewood.us; lfarmer@cityoflakewood.us; pbocchi@cityoflakewood.us; jsimpson@cityoflakewood.us; jcaulfield@cityoflakewood.us 

**Subject**: [INSERT UNIQUE SUBJECT LINE]

**Message**: [MAKE SURE YOU FILL IN BRACKETS. ALSO ADD A LINE OR TWO SO THEY HAVE TO READ EACH MESSAGE]
Dear Mayor Anderson, Deputy Mayor Whalen, City Manager Caulfield, and Lakewood City Council members,

My name is [YOUR NAME] and I am a resident of [CITY, STATE]. I am writing to demand justice for Said Joquin, an innocent Black man who was murdered by a Lakewood police officer on May 1, and so many murdered Black people before him.

Said Joquin was pulled over for running a stop sign and was cooperating with police when he was shot. Putting the officer involved on administrative leave is not enough. Officer Mike Wiley is guilty of murder and should not have been allowed to serve after being linked to the murder of another unarmed Black man in 2013. This is unacceptable. Administrative leave is not enough. I demand that this officer be fired and arrested for his crimes.

I am also asking the City of Lakewood to show your commitment to racial justice moving forward by opposing any increase in the Lakewood Police Department’s budget, and that the Lakewood City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police.

In the 2020 Adopted Operating Expenditures, the City of Lakewood allocated an egregious $25,370,000 to our police department. Next year, there will likely be deficits as a result of the pandemic. The city may recoup these funds by decreasing the police budget.

I demand that the City Council begin meaningfully defunding the Lakewood Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs. Police officers should not need to be the first resource for every crisis. I demand a budget that reflects the actual needs of Lakewood residents.
History has shown that police “reform” is not enough. Policing in America was developed to protect the institution of slavery. More money and training programs will not only not fix our current system, they will cause future lives to be lost to police brutality. We must take a hard look at the way the current system in place fails to serve-and in fact actively harms-our community, and come together to reimagine the role of police in our city.

I am urging you to keep these things in mind for the development of the 2021-2022 Biennial Budget and to invest in the people, not the police.

Thank you for your time,
[YOUR NAME] 
[YOUR ADDRESS]
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by brickaney** [comment]
I’m reviewing

**Comment by aurendisson** [comment]
Editing notes: I corrected the Brandstetter email address.
Budget updated and confirmed via https://cityoflakewood.us/finance/biennial-budget/ https://cityoflakewood.us/wp-content/uploads/2019/08/20192020AdoptedBudgetFullDoc.pdf 
Note that if the officer is fired and/or arrested (one can hope), we should monitor and update this email content.

To: danderson@cityoflakewood.us; jwhalen@cityoflakewood.us; mmoss@cityoflakewood.us; mbrandstetter@cityoflakewood.us; lfarmer@cityoflakewood.us; pbocchi@cityoflakewood.us; jsimpson@cityoflakewood.us; jcaulfield@cityoflakewood.us

Subject: [INSERT UNIQUE SUBJECT LINE]

Message: [MAKE SURE YOU FILL IN BRACKETS. ALSO ADD A LINE OR TWO SO THEY HAVE TO READ EACH MESSAGE]

Dear Mayor Anderson, Deputy Mayor Whalen, City Manager Caulfield, and Lakewood City Council members,

My name is [YOUR NAME] and I am a resident of [CITY, STATE]. I am writing to demand justice for Said Joquin, an innocent Black man who was murdered by a Lakewood police officer on May 1, 2020, and justice for so many murdered Black people before him.

Said Joquin was pulled over for running a stop sign and was cooperating with police when he was shot. Putting the officer involved on administrative leave is not enough. Officer Mike Wiley is guilty of murder and should not have been allowed to serve after being linked to the murder of another unarmed Black man in 2013. This is unacceptable. Administrative leave is not enough. I demand that this officer be fired and arrested for his crimes.

I am also asking the City of Lakewood to show your commitment to racial justice moving forward by opposing any increase in the Lakewood Police Department’s budget, and that the Lakewood City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police.

In the 2020 Adopted Biennial Budget, the City of Lakewood allocated an egregious 25,369,550 to our police department. Next year, there will likely be deficits as a result of the pandemic. The city may recoup these funds by decreasing the police budget.

I demand that the City Council begin meaningfully defunding the Lakewood Police Department and reallocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs. Police officers should not need to be the first resource for every crisis. I demand a budget that reflects the actual needs of Lakewood residents.

History has shown that police “reform” is not enough. Policing in America was developed to protect the institution of slavery. More money and training programs will not only not fix our current system, but they will also cause future lives to be lost to police brutality. We must take a hard look at the way the current system in place fails to serve--and in fact actively harms--our community, and come together to reimagine the role of police in our city.

I am urging you to keep these things in mind for the development of the 2021-2022 biennial budget and to invest in the people, not the police.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by brickaney** [comment]
> @skullface PLEASE CHANGE LABEL, REVIEW COMPLETED.
> 
> Edits made: Added the email change and made reference to the budget and ensured the letter complies with the email guidelines (tried to make the language more generic).
> 
> “ To: [danderson@cityoflakewood.us](mailto:danderson@cityoflakewood.us); [jwhalen@cityoflakewood.us](mailto:jwhalen@cityoflakewood.us); [mmoss@cityoflakewood.us](mailto:mmoss@cityoflakewood.us); [mbrandstetter@cityoflakewood.us](mailto:mbrandstetter@cityoflakewood.us); [lfarmer@cityoflakewood.us](mailto:lfarmer@cityoflakewood.us); [pbocchi@cityoflakewood.us](mailto:pbocchi@cityoflakewood.us); [jsimpson@cityoflakewood.us](mailto:jsimpson@cityoflakewood.us); [jcaulfield@cityoflakewood.us](mailto:jcaulfield@cityoflakewood.us)
> 
> Subject: [INSERT UNIQUE SUBJECT LINE]
> 
> Message: [MAKE SURE YOU FILL IN BRACKETS. ALSO ADD A LINE OR TWO SO THEY HAVE TO READ EACH MESSAGE]
> Dear Mayor Anderson, Deputy Mayor Whalen, City Manager Caulfield, and Lakewood City Council members,
> 
> My name is [YOUR NAME] and I am a resident of [CITY, STATE]. This past week, our nation has been gripped by protests calling for rapid and meaningful reevaluation of the role of policing in our communities and an end to racism. I am writing to call upon this city council to restructure the 2021 city budget to adhere to your mission statement of: “Quality lifestyle fostered by a transparent government”.
> 
> I am asking this City Council to show your commitment to this community by making meaningful changes to the cities priorities as reflected in the budget. In 2019 the City of Lakewood allocated 27% of it’s 205 million dollars in expenses to the police department [1]. I demand that the City Council begin meaningfully defunding the Lakewood Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs. Police officers should not need to be the first resource for every crisis. I demand a budget that reflects the actual needs of Lakewood residents.
> 
> I am also writing to demand justice for Said Joquin, a Black man who was murdered by a Lakewood police officer on May 1, and so many murdered Black Americans before him. Said Joquin was pulled over for running a stop sign and was cooperating with police when he was shot. The city put the officer involved on administrative leave. I believe that Officer Mike Wiley is guilty of murder and should not be allowed to serve after being linked to the murder of another unarmed Black man in 2013 [2]. This is unacceptable. Administrative leave is not enough. I demand that this officer be fired and arrested for his crimes.
> 
> History has shown that police “reform” is not enough. More money spent on policy changes and training programs will not fix our current system. I ask that this committee take a hard look at the way the current system fails to serve this community and come together to reimagine the role of police in the city of Lakewood.
> 
> Thank you for your time,
> [YOUR NAME]
> [YOUR ADDRESS]
> [YOUR EMAIL]
> [YOUR PHONE NUMBER]
> 
> [1] https://cityoflakewood.us/finance/biennial-budget/ https://cityoflakewood.us/wp-content/uploads/2019/08/20192020AdoptedBudgetFullDoc.pdf
> [2] https://www.seattletimes.com/seattle-news/lakewood-officer-involved-in-recent-deadly-shooting-was-involved-in-2013-shooting-that-led-to-record-wrongful-death-verdict/
