### ISSUE TITLE
Malden MA

### ISSUE THREAD

**Issue by windy-summer-day** [defund12/defund12.org#1286]
Emails: mayor@cityofmalden.org; jsica@cityofmalden.org; citycouncil@cityofmalden.org

Content: 
Dear Mayor Christenson, City Council President Sica, and City Councillors,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD], and I am writing to demand that the Malden Police Department be defunded.

Over the past weeks, our nation has been gripped by protests in every single state, calling for the end to police brutality. Many Malden residents have joined in this movement. 

We know that “reform” of the police does not work – that has been tried in cities and states throughout the country for decades. We have been discussing reform for decades – and yet there continues to be violence and violation of basic rights by police. Eric Garner was killed by chokehold by the NYPD in 2014 – over 10 years after the department banned chokeholds. Tamir Rice was murdered by Cleveland PD despite a requirement to warn and de-escalate before shooting. It is very clear that banning certain practices or requiring police to adhere to a continuum of force or de-escalation does not work. And yet we devote a great deal of our budget to the police every year, while financially starving essential services that do help meet the basic needs of our community.

Defunding the police is not radical – it is an essential and logical step towards supporting community services that truly help promote community safety. In Fiscal Year 2020, Malden spent $11,592,266 on police. This is more than $1,000,000 more than the city spent on the Health Department, Public Works and Public Facilities combined in the same fiscal year. We desperately need to fund services that support the community and actually promote community safety – and cannot do so while supporting the truly excessive police budget in Malden.

We must de-fund the MPD and support our community. 

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by brickaney** [comment]
I’m reviewing.
