### ISSUE TITLE
Triage access for wendywx

### ISSUE THREAD

**Issue by wendywx** [defund12/defund12.org#1288]
# Triage access

👋 I am a defund12.org collaborator requesting triage permissions so I can assist in reviewing/editing and email dev, wherever efforts are needed most.

Contributions so far:
Email:
- https://github.com/defund12/defund12.org/pull/1143
Review:
- https://github.com/defund12/defund12.org/pull/1077
- https://github.com/defund12/defund12.org/issues/928
- https://github.com/defund12/defund12.org/issues/1004
- https://github.com/defund12/defund12.org/issues/773
- https://github.com/defund12/defund12.org/issues/914
- https://github.com/defund12/defund12.org/issues/554
- https://github.com/defund12/defund12.org/issues/898
- https://github.com/defund12/defund12.org/issues/863

**Comment by bingbongle** [comment]
Giving you triage access now!

**Comment by wendywx** [comment]
Thanks @bingbongle !
