### ISSUE TITLE
Letter to Lafayette, IN Mayor and Council 

### ISSUE THREAD

**Issue by wvencel** [defund12/defund12.org#1290]
Letter to Lafayette, IN City Council
kklinker@lafayette.in.gov
lahlersmeyer@lafayette.in.gov
pbrown@lafayette.in.gov
nnargi@lafayette.in.gov
rcampbell@lafayette.in.gov
JReynolds@lafayette.in.gov 
bdowning@lafayette.in.gov
mwilliamson@lafayette.in.gov
lheide@lafayette.in.gov 

Dear City Councilor Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY]. I am writing about the fiscal year 2021 budget for the City of Lafayette. 

Mayor Roswarski states that he wants the “to start a meaningful dialogue that will create tangible change and the opportunity for everyone to live a life of inclusion, free of racism and discrimination.” 

The 2019 budget allocated over $19 million, or 28.5% of the total budget, to the Lafayette Police Department, while the Human Relations Department received $1,300, or less than 0.001% of the total budget.

I am asking that the Lafayette City Council make a more overt and visible commitment to the city's Black and Brown communities to combat an over-investment in their criminalization and surveillance. I therefore demand that the Council find ways to redirect money away from the LPD's overinflated budget. Additionally, I demand that the 2020 City Budget be made public immediately as it is not currently viewable. I urge you to pressure the mayor for an ethical and equal reallocation of the city's expenditures, away from the LPD, and towards sectors that facilitate the dismantling of racial and class inequality.

Now especially, the City Council can take a supportive stand on racial and social justice by significantly defunding policing and investing in the community instead-starting with housing, transportation, education, community centers, and community-led organizations and projects.

Can I count on you to consider an alternative budget that puts a focus on human relations and social services programs?

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by Rtrott** [comment]
Editing now!

**Comment by Rtrott** [comment]
Letter to Lafayette, IN City Council
kklinker@lafayette.in.gov ; lahlersmeyer@lafayette.in.gov ; pbrown@lafayette.in.gov ;nnargi@lafayette.in.gov ;rcampbell@lafayette.in.gov ;JReynolds@lafayette.in.gov ;bdowning@lafayette.in.gov; mwilliamson@lafayette.in.gov;
lheide@lafayette.in.gov

Dear City Councilor Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY]. I am writing about the fiscal year 2021 budget for the City of Lafayette.

Mayor Roswarski stated that he wants the “to start a meaningful dialogue that will create tangible change and the opportunity for everyone to live a life of inclusion, free of racism and discrimination.” I suggest that meaningful change starts with defunding the Lafayette Police.

The 2019 budget allocated over $19 million to the Lafayette Police Department, 28.5% of the total General budget . I am asking that the Lafayette City Council make a more overt and visible commitment to the city's Black and Brown communities to combat an over-investment in their criminalization and surveillance. I therefore demand that the Council redirect money away from the LPD's overinflated budget. Additionally, I demand that the 2020 City Budget be made public immediately as it is not currently viewable.

 I urge you to pressure the mayor for an ethical and equal reallocation of the city's expenditures, away from the LPD, and towards sectors that facilitate the dismantling of racial and class inequality.
Now especially, the City Council can take a supportive stand on racial and social justice by significantly defunding policing and investing in the community instead-starting with housing, transportation, education, community centers, and community-led organizations and projects.

Can I count on you to consider an alternative budget that puts a focus on human relations and social services programs?

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now
