### ISSUE TITLE
Ithaca, NY

### ISSUE THREAD

**Issue by jquigley1993** [defund12/defund12.org#1296]
TO: council@cityofithaca.org

SUBJECT: [Unique subject line]

To the Ithaca Common Council and Mayor Svante Myrick,

My name is [YOUR NAME] and I am a resident of [CITY]. I am imploring you to meaningfully restrict the Ithaca Police Department’s $12.78 million budget immediately. These funds would be better allocated towards services proven to more effectively promote a safe and equitable community, such as community mental health services, substance abuse treatment services, education, affordable housing programs, and more. 

Last year's incident of police brutality towards Rose DeGroat and Cadji Ferguson on the Commons highlighted some of the issues with the IPD. In a recent statement to the Ithaca Voice (https://ithacavoice.com/2020/06/women-led-rally-for-racial-justice-draws-crowd-to-downtown-ithaca-as-protests-continue/), Mayor Myrick said he has "spent the last 9 years locked in a battle over the size and purpose of the Ithaca Police Department" and expressed a desire to divert funds towards services like those listed above. However, the final budgets for the city of Ithaca from 2012 to 2020 show that the Police Department budget has increased from $11.4 millon to $12.78 million, and moreover, the Mayor's proposed budgets have closely matched these figures. With recent public support for defunding the police, the time is right for Ithaca to reduce the budget of the IPD. 

Research shows that access to living wages, health services and treatment, educational opportunity, and stable housing are far more successful at promoting community safety than policing and prisons. Police “reform” is not enough. As such, I demand a meaningful reallocation of police department funds towards education, healthcare, and social programs.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Reviewing now

**Comment by mahrer** [comment]
Looks great! I simply put sources at the end of the email to favor readability:

---

TO: council@cityofithaca.org

Message:

To the Ithaca Common Council and Mayor Svante Myrick,

My name is [YOUR NAME] and I am a resident of [CITY]. I am imploring you to meaningfully restrict the Ithaca Police Department’s $12.78 million budget immediately. These funds would be better allocated towards services proven to more effectively promote a safe and equitable community, such as community mental health services, substance abuse treatment services, education, affordable housing programs, and more.

Last year's incident of police brutality towards Rose DeGroat and Cadji Ferguson on the Commons highlighted some of the issues with the IPD. In a recent statement to the Ithaca Voice (1), Mayor Myrick said he has "spent the last 9 years locked in a battle over the size and purpose of the Ithaca Police Department" and expressed a desire to divert funds towards services like those listed above. However, the final budgets for the city of Ithaca from 2012 to 2020 show that the Police Department budget has increased from $11.4 millon to $12.78 million (2), and moreover, the Mayor's proposed budgets have closely matched these figures. With recent public support for defunding the police, the time is right for Ithaca to reduce the budget of the IPD.

Research shows that access to living wages, health services and treatment, educational opportunity, and stable housing are far more successful at promoting community safety than policing and prisons. Police “reform” is not enough. As such, I demand a meaningful reallocation of police department funds towards education, healthcare, and social programs.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

(1): https://ithacavoice.com/2020/06/women-led-rally-for-racial-justice-draws-crowd-to-downtown-ithaca-as-protests-continue/ 
(2): https://www.cityofithaca.org/427/City-Budget

**Comment by todd-m** [comment]
on it let's gooooo
