### ISSUE TITLE
El Paso - Letter to Mayor Dee Margo & City Council 

### ISSUE THREAD

**Issue by jltol** [defund12/defund12.org#1309]
**To:**
mayor@elpasotexas.gov, district1@elpasotexas.gov, district2@elpasotexas.gov, district3@elpasotexas.gov, district4@elpasotexas.gov, district5@elpasotexas.gov, district6@elpasotexas.gov, district7@elpasotexas.gov, district8@elpasotexas.gov

**Subject:** [*** INSERT UNIQUE SUBJECT LINE ***]

**Message** _(Don't forget to replace the [x]'s with your information!)_

Dear City Council Members & Mayor Margo,

My name is [NAME]. I am a resident of [NEIGHBORHOOD] in El Paso, Texas. I write this letter today to demand a complete overhaul on our El Paso Police Department. In light of, and in solidarity with, the Black Lives Matter protests being demonstrated across the US and in our city, the El Paso community is calling for the complete and immediate defunding of the EPPD and reinvestment in our communities. 

WE ARE JOINING TOGETHER TO DEMAND THAT YOU, OUR LOCAL OFFICIALS, WILL: 

1. Vote NO on all increases to police budgets
2. Vote YES to decrease police spending and budgets
3. Vote YES to increase spending on health care, education, and community development initiatives and programs that keep up safe.

The El Paso Police Department is funded at a **drastically higher** amount than all other city programs. In 2019, EPPD received: **5** times as much than parks & recreation, **9** times as much as public health, **12** times as much as human and community development, **15** times as much as libraries, **29** times as much as museum and cultural affairs, and **363** times as much as support for the unhoused. (elpasotexas.gov/omb)

Rethink how you allocate funds, and in doing so what you could accomplish. Funding should go towards building healthy communities, especially those that are most vulnerable as Covid-19 has exposed. It should go towards the health of our elders and children, to social services, to neighborhood infrastructure, to education, to childcare, to homelessness, to dismantling racial inequality, to supporting a vibrant future for our city.

The possibilities are endless if you commit to investing in our communities, not in policing them. El Paso cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund EPPD.

Thank you,

The People of El Paso, TX

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by brickaney** [comment]
@mahrer  Please close issue as duplicate

@jltol El Paso has been added. If you’d like to add/edit information to the content, please submit a new issue.

**Comment by jltol** [comment]
@mahrer @brickaney I don't see El Paso on the list yet. Does it take awhile to appear? Thanks.

**Comment by mahrer** [comment]
@jltol After checking, I'm going to re-open as I don't see it anywhere either. @brickaney if you see that something is a duplicate can you link to the existing issue/template?

**Comment by brickaney** [comment]
Duplicate of #1079

**Comment by brickaney** [comment]
@mahrer Please change the label, I completed the review of this

Edits made: minor edits to content, added the reference to the budget website at the end.

“To:
mayor@elpasotexas.gov
district1@elpasotexas.gov
district2@elpasotexas.gov
district3@elpasotexas.gov
district4@elpasotexas.gov
district5@elpasotexas.gov
district6@elpasotexas.gov
district7@elpasotexas.gov
district8@elpasotexas.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message (Don't forget to replace the [x]'s with your information!)

Dear City Council Members & Mayor Margo,

My name is [NAME]. I am a resident of [NEIGHBORHOOD] in El Paso, Texas. I write this letter today to demand a complete overhaul on our El Paso Police Department. In light of, and in solidarity with, the Black Lives Matter protests being demonstrated across the US and in our city, the El Paso community is calling for the immediate defunding of the EPPD and reinvestment in our communities.

WE ARE JOINING TOGETHER TO DEMAND THAT YOU, OUR LOCAL OFFICIALS, WILL:

Vote NO on all increases to police budgets
Vote YES to decrease police spending and budgets
Vote YES to increase spending on health care, education, and community development initiatives and programs that keep up safe.

The El Paso Police Department is funded at a drastically higher amount than all other city programs. In 2019, EPPD received: 5 times as much than parks & recreation, 9 times as much as public health, 12 times as much as human and community development, 15 times as much as libraries, 29 times as much as museum and cultural affairs, and 363 times as much as support for the unhoused [1].

I demand that this council reallocate funds towards building healthy communities, especially those that are most vulnerable as Covid-19 has exposed. It should go towards the health of our elders and children, to social services, to neighborhood infrastructure, to education, to childcare, to homelessness, to dismantling racial inequality, to supporting a vibrant future for our city.

The possibilities are endless if you commit to investing in our communities, not in policing them. El Paso cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund EPPD.

Thank you,

The People of El Paso, TX

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

[1] elpasotexas.gov/omb
