### ISSUE TITLE
Alameda County, CA

### ISSUE THREAD

**Issue by h1016** [defund12/defund12.org#1316]
TO: district1@acgov.org, district2@acgov.or, district3@acgov.org, district4@acgov.org, district5@acgov.org, Scott.Haggerty@acgov.org, Richard.Valle@acgov.org, Wilma.Chan@acgov.org, nate.miley@acgov.org, keith.carson@acgov.org, nancy.omalley@acgov.org, info@alcoda.org 

SUBJECT: [Insert Unique Subject Line!]

MESSAGE: (Don’t forget to replace the [X’s] with your information!)

To District Attorney Nancy O’Malley and Alameda County Elected Board of Supervisors,

My name is [NAME] and I am an Alameda County resident from [YOUR CITY].

For the past week, our country has witnessed an outcry for and resulting demands for long overdue justice.

Police brutality - specifically the systemic racist charged brutality against Black people - is, and always has been, inherently tied to our policing system.

It is time to address the glaring issue of inequity in our own county. Predominantly White & Asian majority cities (such as Pleasanton and Piedmont) tend to allocate 25% of the city budget to police departments. This is still typically 3x the amount spent on public benefits. 

Cities with predominantly Black & Brown communities, however, spend around 50% of their budgets on policing, which perpetuates over-policing and the aggressive criminalization against People of Color.

I demand that police budgets (and therefore, police power) be reduced. Instead, it is time to invest that same money directly to underrepresented communities - specifically Black and Brown communities - through public services. 

Reform strategies have cost Alameda County cities millions of dollars and - despite the grotesque amounts of money spent on policing - we have not seen improvements to safety, homelessness, or the health of our county. Instead, Alameda County Police Departments remain a massive - sometimes lethal - threat to Black and Brown communities.

Moreover, police are the first responders to every issue in our community (i.e. Domestic violence, Mismanaged schools, Drug overdose, Neighborhood disputes) but police officers are **not** trained nor equipped to handle these issues, nor do they understand the root causes for these issues. The public institutions and grassroot organizations that are trained for these scenarios are painfully underfunded and undervalued. 

Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons. Crime is consistently correlated to inadequate social conditions; by defunding police and redirecting the money into communities, violent crime is reduced and communities are uplifted.

We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence. It is time to invest in our communities, promote well-being, safety, and prosperity through healthy alternatives to ACPDs.

I demand for a:
Reduction of the Alameda County Budget for each city department to under 25% of the total city budget.
Disallowment unauthorized overtime by OPD
Discontinued use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence.
Investment in housing, jobs, youth programs, education, health care, child care, restorative justice, mental health workers, and other critical community needs.

It is your duty to represent your constituents. Do not negate this duty by being complicit in this county's disproportionate targeting of people of color. I urge you to hear my demands and the righteous calls of those across the country; revise the Alameda County budget for the next fiscal year to defund the police as we cannot wait any longer for a budget that meets the needs of its residents.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by swallan** [comment]
@h1016 

Unfortunately, this letter is going to need some revision before we can publish it. The addressees are unlikely to have power over individual cities in their county, and it doesn't directly look like they fund these police departments. Consider writing about the county Sheriff, or or mention specifically how they fund police.

Until then, I'm going to close this issue, but it can be reopened with a more clear message.
