### ISSUE TITLE
Add Natick, MA

### ISSUE THREAD

**Issue by defundnatick** [defund12/defund12.org#1319]
- Email addresses (at least one) of the government officials you’d like to receive the message
mmalone@natickma.org,
ehenderson@natickma.org,
selectmen@natickma.org,
collector@natickma.org,
jfreas@natickma.org,
amehta@natickma.org,
jtownsend@natickma.org,
Jwhite@natickma.org,
rlefrancois@natickma.org,
anolin@natickps.org,
dpacker@natickma.org,
jfreedman@natickma.org,
ssalamoff@natickma.org,
mhickey@natickma.org,
amistrot@natickma.org

- Detailed message concerning the budgeting decisions at stake in your community
Subject: In Response to the Proposed Increase In Police Funding

Dear various Town Hall houses, departments, and their staff, 

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY]. On June 8th, Town Administrator Melissa Malone submitted a proposed budget for the 2021 fiscal year to the Selectboard. The cuts hit almost every department and job cuts include more than 12 full and part-time workers. In contrast, the police department would receive a budget increase of about $241,000. The town is also planning to fund a new police officer for half the year beginning in January at a cost of about $32,000. Natick does not need more police. According to FBI crime data, the chance of becoming a victim of crime in Natick is 1 in 76, which is a 1.3 percent chance. Natick must not increase the Natick Police Department budget and instead allocate those funds back into the community and educational programs. Now especially, the town of Natick can take a stand for racial justice by defunding policing and investing in Black and Brown communities. Racist police violence doesn’t just happen in other towns - it happens here in Natick too. The town must stop investing in a system of policing that we know to be unequal and discriminatory, and instead invest in what communities need to be safe and healthy such as COVID19 relief, youth programs, teachers, and school counselors. 

Thank you, 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**_Until you provide this content, we cannot post your city._**

Messages should follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md). Remember that messages must be specific to your locale and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!

**Comment by brickaney** [comment]
@skullface Please change label, I’ve completed my review.

Edits made: Updated the content to be more generalized and adhere to the email guidelines, trying to more-directly ask for defunding and reallocation to specific community services.

“To:
mmalone@natickma.org
ehenderson@natickma.org
selectmen@natickma.org
collector@natickma.org
jfreas@natickma.org
amehta@natickma.org
jtownsend@natickma.org
Jwhite@natickma.org
rlefrancois@natickma.org
anolin@natickps.org
dpacker@natickma.org
jfreedman@natickma.org
ssalamoff@natickma.org
mhickey@natickma.org
amistrot@natickma.org

Subject: [UNIQUE SUBJECT LINE]

Dear various Town Hall houses, departments, and their staff,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD]. On June 8th, Town Administrator Melissa Malone submitted a proposed budget for the 2021 fiscal year to the Selectboard. The cuts hit almost every department and job cuts include more than 12 full and part-time workers. In contrast, the police department would receive a budget increase of about $241,000 [1].

Natick must not increase the Natick Police Department budget and instead allocate those funds back into the community. With the rise of COVID-19, the rise of homelessness in our country and the ongoing problems of access to much needed resources around mental health, healthcare, housing and violence prevention, support for communities in need is necessary now, more than ever. 

I demand that the City Council defund the Natick Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, and affordable housing programs.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

[1] https://www.natickma.gov/DocumentCenter/View/9023/FY-2021-Town-Administrators-Preliminary-Budget
