### ISSUE TITLE
Oxnard, CA - Letter to the Mayor and City Council

### ISSUE THREAD

**Issue by jjjuarez** [defund12/defund12.org#1322]
To: tim.flynn@oxnard.org, carmen.ramirez@oxnard.org, perellobert@gmail.com, oscar.madrigal@oxnard.org, bryan.macdonald@oxnard.org, gabriela.basua@oxnard.org, vianeyforoxnard@gmail.com

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message (Don't forget to replace the [x]'s with your information!) 

Dear Mayor Flynn and City Council members,

My name is [YOUR NAME] and I am a resident of Oxnard. I am writing to demand that the Oxnard City Council adopt a budget prioritizing community well-being and redirecting funds away from the Oxnard Police Department.

For the past few weeks, hundreds of thousands of Americans across the country have taken to the streets to protest for change. They want to finally put an end to racism in this country, and win justice for those (especially Black Americans) who have been treated unfairly by law enforcement. Furthermore, they want their cities to dramatically reduce the role police play in our society.

In 2019, the City of Oxnard allocated $62,740,000 to our police system, an inordinate 44% of our total budget. This is a 17% ($10,240,00) increase from OPD’s 2016 budget. In the same time period, budget allocation towards community development, economic development, cultural and community services, and housing decreased from 14.7% to 14.15% of the city’s overall budget -- which is more than 3x less than the OPD budget. This budget prioritization punishes Oxnard’s most vulnerable communities while virtually leaving alone a department that eats up almost half of our general fund. 

We should be spending this money on resources that better serve the community, like affordable housing, mental health resources, and the library system just to name a few. Amidst a pandemic in which everyone has been affected monetarily, the police system should be the first to be defunded. There are other far more important initiatives that need our money.

I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of at-risk Oxnard residents during this trying and uncertain time, when livelihoods are on the line. I call on you to slash the Oxnard PD budget and instead meaningfully reallocate funds towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. We demand a budget that prioritizes community wellbeing, not police.

As the City Council, the budget proposal is in your hands. It is your duty to listen to and base your actions on the voices of your constituents. I am urging you to revise the budget for the 2020-2021 fiscal year, and to fund people, not police. Public opinion is with me.

Thank you for your time,

[YOUR NAME] 
[YOUR ADDRESS]
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by serifluous** [comment]
2019 Budget info confirmed here, p294: https://www.oxnard.org/wp-content/uploads/2019/05/FINANCE_draft_budget_book_19_20.pdf

2016 Budget info confirmed here, p12: https://www.oxnard.org/wp-content/uploads/2016/06/Att-F-FY-16-17-Proposed-Operating-Budget.pdf

**Edits in bold below**, one minor typo and a clarification on general fund budget

Email
--
To: tim.flynn@oxnard.org, carmen.ramirez@oxnard.org, perellobert@gmail.com, oscar.madrigal@oxnard.org, bryan.macdonald@oxnard.org, gabriela.basua@oxnard.org, vianeyforoxnard@gmail.com

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message (Don't forget to replace the [x]'s with your information!)

Dear Mayor Flynn and City Council members,

My name is [YOUR NAME] and I am a resident of Oxnard. I am writing to demand that the Oxnard City Council adopt a budget prioritizing community well-being and redirecting funds away from the Oxnard Police Department.

For the past few weeks, hundreds of thousands of Americans across the country have taken to the streets to protest for change. They want to finally put an end to racism in this country, and win justice for those (especially Black Americans) who have been treated unfairly by law enforcement. Furthermore, they want their cities to dramatically reduce the role police play in our society.

In 2019, the City of Oxnard allocated $62,740,000 to our police system, an inordinate 44% of our total **general fund** budget. This is a 17% ($10,240,00**0**) increase from OPD’s 2016 budget. In the same time period, budget allocation towards community development, economic development, cultural and community services, and housing decreased from 14.7% to 14.15% of the city’s **general fund** budget—which is more than 3x less than the OPD budget. This budget prioritization punishes Oxnard’s most vulnerable communities while virtually leaving alone a department that eats up almost half of our general fund.

We should be spending this money on resources that better serve the community, like affordable housing, mental health resources, and the library system just to name a few. Amidst a pandemic in which everyone has been affected monetarily, the police system should be the first to be defunded. There are other far more important initiatives that need our money.

I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of at-risk Oxnard residents during this trying and uncertain time, when livelihoods are on the line. I call on you to slash the Oxnard PD budget and instead meaningfully reallocate funds towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. We demand a budget that prioritizes community wellbeing, not police.

As the City Council, the budget proposal is in your hands. It is your duty to listen to and base your actions on the voices of your constituents. I am urging you to revise the budget for the 2020-2021 fiscal year, and to fund people, not police. Public opinion is with me.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now

**Comment by vanessa-flores21** [comment]
Thank you!!
