### ISSUE TITLE
Middlesex County, New Jersey

### ISSUE THREAD

**Issue by ssuryanar** [defund12/defund12.org#1340]
To: Representative Frank Pallone, Jr. <laura.cartwright@mail.house.gov>; Representative Bonnie Watson Coleman <NJ12BWIMA@mail.house.gov>; Senator Christopher Bateman <senbateman@njleg.org>; Assemblyman Roy Freiman <asmfreiman@njleg.org>; Assemblyman Andrew Zwicker <asmzwicker@njleg.org>; Senator Samuel D. Thompson <senthompson@njleg.org>; Assemblyman Robert D. Clifton <asmclifton@njleg.org>; Assemblyman Ronald S. Dancer <asmdancer@njleg.org>; Senator Linda R. Greenstein <sengreenstein@njleg.org>; Assemblyman Daniel R. Benson <asmbenson@njleg.org>; Assemblyman Wayne P. DeAngelo <asmdeangelo@njleg.org>; Senator Robert B. Smith <senbsmith@njleg.org>; Assemblyman Joseph Danielsen <asmdanielsen@njleg.org>; Assemblyman Joseph V. Egan <AsmEgan@njleg.org>; Senator Patrick J. Diegnan, Jr. <sendiegnan@njleg.org>; Assemblyman Robert Karabinchak <asmkarabinchak@njleg.org>; Assemblywoman Nancy J. Pinkin <aswpinkin@njleg.org>; Senator Joseph F. Vitale <senvitale@njleg.org>; Assembly Speaker Craig J. Coughlin <AsmCoughlin@njleg.org>; 
Assemblywoman Yvonne Lopez <aswlopez@njleg.org>; Senator Nicholas P. Scutari <senscutari@njleg.org>; Linda S. Carter <aswcarter@njleg.org>; Assemblyman James J. Kennedy <asmkennedy@njleg.org>

Subject: [WILL NEW JERSEY DEFEND ITS BLACK COMMUNITY?]

Message (Don't forget to replace the [x]'s with your information!) 🔗 
Dear Middlesex County Representatives,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the Middlesex County adopt a budget that prioritizes community wellbeing, and redirects funding away from the police system, as it disproportionately violates the rights and lives of Black community members - like Qwason Campbell who was assaulted by Woodbridge PD while protesting police brutality on July 6.

I demand that the Middlesex County Representatives begin meaningfully defunding all New Jersey Police Departments, especially those in Woodbridge Township and Middlesex County, and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Central New Jersey residents.

History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city.

Thank you for your time, 
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment]
I’m reviewing.
