### ISSUE TITLE
Email for Howard County, MD

### ISSUE THREAD

**Issue by DrewKaarakka** [defund12/defund12.org#1345]
**To:**
cball@howardcountymd.gov, ewalsh@howardcountymd.gov, ojones@howardcountymd.gov, crigby@howardcountymd.gov, djung@howardcountymd.gov, dyungmann@howardcountymd.gov

**Subject:** [INSERT UNIQUE SUBJECT LINE]
Dear Howard County Officials,

**Message** (Don't forget to replace the [x]'s with your information!) 

My name is [YOUR NAME], and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand the Howard County Council adopt a city budget that redirects funding away from the police to more community-oriented forms of public safety and wellbeing.

In 2019, Howard County allocated $118 million to the police, roughly 10% of the general budget. Though the county has succeeded in prioritizing community enrichment, with an astounding 57.51% of the general budget directed toward education, the current distribution of funds fails to adequately meet the needs of community members. In recent years, the county has witnessed a significant rise in opioid overdoses. Yet, departments intended to promote community wellness including Community Services and the Health Department only receive 6% and 1% of the budget, respectively.

I demand that the County Council move to defund the Howard County Police Department in favor of programs proven to more effectively promote a safe and equitable community: mental health services, drug rehabilitation services, affordable housing programs, and more. I demand a budget that prioritizes nonviolent, community-based approaches to public health and safety.
Howard County may designate proportionally fewer resources to the police than many cities and counties across the nation, but the need for change is urgent, nonetheless. To continue building a community that fosters health and wellness, we must reimagine a form of public safety that favors prevention and rehabilitation over punishment.

Thank you for your time, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment]
I’m reviewing
