### ISSUE TITLE
Email for High Point, NC 

### ISSUE THREAD

**Issue by kju0223** [defund12/defund12.org#1352]
**To:** 
Jay.Wagner@highpointnc.gov 
britt.moore@highpointnc.gov
tyrone.johnson@highpointnc.gov
cyril.jefferson@highpointnc.gov
Chris.williams@highpointnc.gov 
monica.peters@highpointnc.gov
wesley.hudson@highpointnc.gov
victor.jones@highpointnc.gov
michael.holmes@highpointnc.gov 

**Subject**: [INSERT UNIQUE SUBJECT LINE]

**Message:** 
Dear Mayor Wagner & City Council Members,

My name is [YOUR NAME]. I am a resident of High Point. I am writing to the Mayor and the City Council to object the allocation of over $30M to the City of High Point Police Department in the proposed 2020-2021 budget. 

I am asking that the High Point City Council take an overt and visible stance on racial justice by defunding the police. The current budget allocates a large amount of resources to police that could be better spent on community-led programs and initiatives. 

Research shows that stable housing, a living wage, access to holistic health services and treatment, and educational opportunities are far more successful at increasing community safety than police or prisons (Source: Popular Democracy). As such, I demand more aggressive financial support be directed to affordable housing and rent subsidies, food resources, and medical supplies to meet the immediate needs of High Point residents amid strain from the COVID-19 pandemic, as well as the long-term and longstanding needs of residents. Resources should also be allocated to EMTs, social workers, and other social service providers such that they are able to respond to health and wellness checks, domestic/sexual violence situations, and basic bureaucratic documentation around break-ins, vandalism, wrecks, etc. There is no reason to have armed officers responding to the majority of emergency needs in High Point when professionals with specific training in the de-escalation and counseling of these situations could better serve our residents and community. 

Reallocating funds away from the police and to the aforementioned avenues in High Point will provide much needed assistance and security to the most vulnerable people in our community. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Thank you, 
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment]
I’m reviewing
