### ISSUE TITLE
Henrico County, Virginia

### ISSUE THREAD

**Issue by khz7gy** [defund12/defund12.org#1355]
To: brookland@henrico.us, fairfield@henrico.us, tuckahoe@henrico.us, varina@henrico.us, threechopt@henrico.us, district12@senate.virginia.gov, district09@senate.virginia.gov, DelDAdams@house.virginia.gov, DelLBagby@house.virginia.gov, DelJMcGuire@house.virginia.gov, DelDMcQuinn@house.virginia.gov, DelSVanValkenburg@house.virginia.gov, DelRWillett@house.virginia.gov

Subject: [INSERT UNIQUE SUBJECT LINE: ex "My Personal Story with Henrico Police/ Racial Injustice in Henrico"]

Hello,

My name is [YOUR NAME], and I live in [YOUR NEIGHBORHOOD]. I am writing because I am disturbed by the similarities between the actions of our own police department and that of the Minneapolis police department which was responsible for murdering George Floyd. 

In 2015, Henrico County police officer Joel D Greenway was indicted with the malicious wounding and shooting of un-armed Black woman, Kimberly McNeil. Greenway shot at McNeil 7 times, striking her in the back of the head and in her arm. Greenway was acquitted. 

I do not believe the shooting of Kimberly McNeil and the murder of George Floyd are isolated incidents. I believe these tragedies can be traced back to racial bias and lack of accountability over our police. 
 
Thus, I call on you to meaningfully restrict the Henrico County Police Department's budget. The FY 20-21 proposed $3 million police budget increase to $84,173,103 is a misallocation of resources that would further endanger our Black community members. Those $3 million could instead go to increasing our residents' access to qualitiy healthcare, raising our teacher's salaries which would really help communities of color. 

Like our nation at large, Henrico County is rapidly becoming more diverse. However, our Black brothers and sisters are still threated by racial inequity as before. I believe it is your duty to address the issues of racial injustice head on and take swift action. 

Thank you for your time, 
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment]
I am reviewing
