### ISSUE TITLE
New York- Dutchess County Legislature

### ISSUE THREAD

**Issue by sodefeated** [defund12/defund12.org#1358]
CountyLegislature@DutchessNY.gov, gllaverias@dutchessny.gov, dsagliano@dutchessny.gov, mpolasek@dutchessny.gov, hblackdc4@gmail.com, tkeith@dutchessny.gov, redutchess6@gmail.com, wtruitt@dutchessny.gov, cbrendli@dutchessny.gov, rjohnson@dutchessny.gov, jeterb@hvc.rr.com, bkearney@dutchessny.gov, metzger4dc@gmail.com, dbolner@dutchessny.gov, lpaoloni@dutchessny.gov, jcavaccini@dutchessny.gov, fzernike@dutchessny.gov, dmchoul@dutchessny.gov, npage@dutchessny.gov, gpulver@dutchessny.gov, kmunn@dutchessny.gov, scaswell@dutchessny.gov, fgarito@dutchessny.gov, ehauser@dutchessny.gov, alansurman@optimum.net, dhouston@dutchessny.gov, CountyExec@DutchessNY.gov, cmorris@dutchessny.gov

Dear Dutchess County Legislature,

     Hi, my name is [NAME] and I am a resident of [TOWN]. I am asking you to reallocate money away from the Dutchess County Sheriff’s Department, which disproportionately targets Black residents. From traffic stops, to arrests, to the use of lethal force, Dutchess County Sheriff’s Department targets nonwhite residents at a rate far exceeding their share of the population. Much scholarship shows that a living wage, access to health services and treatment, educational opportunity, and stable housing are far more successful at promoting community safety than policing and prisons.  

     Dutchess County is currently allocating $54,665,818 of its budget to the Sheriff and Jail, $18,041,128 to Probation and $1,312,183 to Juvenile Detention, totaling $74,304,402 (14.5%) toward programs that have little benefit to the community.  All the while only allocating $49,520,574 (9.6%) toward public education from Pre-School through Community College, $46,379,552 (9%) to the Department of Behavioral & Community Health, and $11,668,951 (0.02%) to our already inadequate Public Transportation system.  Additionally, only $1,215,670 (0.002%) was allocated to the Agency Partner Grant Program which includes many of the programs that support the community in meaningful ways such as housing, restorative justice, food access, literacy, and much more.  This means that Dutchess County is allocating nearly the same amount of funding to policing and incarceration as it is to all of these other programs combined.  

     This is an unacceptable disparity in funding.  It stands to reason that a greater number of residents can benefit from access to healthcare, education, and transportation in their communities than they can from police presence and incarceration.  As such, I demand a meaningful reallocation of these funds towards healthcare and social programs that truly benefit the community.

Sincerely,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

*The 2020 Adopted Budget Appropriations document for Dutchess County is publicly available at https://www.dutchessny.gov/Departments/County-Legislature/Docs/2020-Adopted-Budget.pdf

**Comment by mahrer** [comment]
@sodefeated, thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

Note: There is already an open issue for Poughkeepsie at #1032, but since this email specifically targets the County Legislature I'll leave it open as a separate template.

**Comment by mahrer** [comment]
Copied and pasted here for ease of editing:

---

CountyLegislature@DutchessNY.gov, gllaverias@dutchessny.gov, dsagliano@dutchessny.gov, mpolasek@dutchessny.gov, hblackdc4@gmail.com, tkeith@dutchessny.gov, redutchess6@gmail.com, wtruitt@dutchessny.gov, cbrendli@dutchessny.gov, rjohnson@dutchessny.gov, jeterb@hvc.rr.com, bkearney@dutchessny.gov, metzger4dc@gmail.com, dbolner@dutchessny.gov, lpaoloni@dutchessny.gov, jcavaccini@dutchessny.gov, fzernike@dutchessny.gov, dmchoul@dutchessny.gov, npage@dutchessny.gov, gpulver@dutchessny.gov, kmunn@dutchessny.gov, scaswell@dutchessny.gov, fgarito@dutchessny.gov, ehauser@dutchessny.gov, alansurman@optimum.net, dhouston@dutchessny.gov, CountyExec@DutchessNY.gov, cmorris@dutchessny.gov

Dear Dutchess County Legislature,

 Hi, my name is [NAME] and I am a resident of [TOWN]. I am asking you to reallocate money away from the Dutchess County Sheriff’s Department, which disproportionately targets Black residents. From traffic stops, to arrests, to the use of lethal force, Dutchess County Sheriff’s Department targets nonwhite residents at a rate far exceeding their share of the population. Much scholarship shows that a living wage, access to health services and treatment, educational opportunity, and stable housing are far more successful at promoting community safety than policing and prisons.  

 Dutchess County is currently allocating $54,665,818 of its budget to the Sheriff and Jail, $18,041,128 to Probation and $1,312,183 to Juvenile Detention, totaling $74,304,402 (14.5%) toward programs that have little benefit to the community.  All the while only allocating $49,520,574 (9.6%) toward public education from Pre-School through Community College, $46,379,552 (9%) to the Department of Behavioral & Community Health, and $11,668,951 (0.02%) to our already inadequate Public Transportation system.  Additionally, only $1,215,670 (0.002%) was allocated to the Agency Partner Grant Program which includes many of the programs that support the community in meaningful ways such as housing, restorative justice, food access, literacy, and much more.  This means that Dutchess County is allocating nearly the same amount of funding to policing and incarceration as it is to all of these other programs combined.  

 This is an unacceptable disparity in funding.  It stands to reason that a greater number of residents can benefit from access to healthcare, education, and transportation in their communities than they can from police presence and incarceration.  As such, I demand a meaningful reallocation of these funds towards healthcare and social programs that truly benefit the community.

Sincerely,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

*The 2020 Adopted Budget Appropriations document for Dutchess County is publicly available at https://www.dutchessny.gov/Departments/County-Legislature/Docs/2020-Adopted-Budget.pdf
