### ISSUE TITLE
Virginia Beach, VA Gov. Ralph Northam

### ISSUE THREAD

**Issue by mvillania** [defund12/defund12.org#1361]
Please add Virginia Beach, VA to the website.

Mayor Robert “Bobby” Dyer
mailto: bdyer@vbgov.com

Re: Defunding 12

Requesting to reallocate egregious police budgets towards education, social services, and dismantling racial inequality via this crowd-sourced tool.

**Comment by mahrer** [comment]
Hi @mvillania, thanks for your interest in adding Virginia Beach to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Subject line for the email
- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!
