### ISSUE TITLE
Mill Valley, CA

### ISSUE THREAD

**Issue by KikiPlz** [defund12/defund12.org#1365]
finance@cityofmillvalley.org 
jmccauley@cityofmillvalley.org  
smcentee@cityofmillvalley.org
jwickham@cityofmillvalley.org
 ucarmel@cityofmillvalley.org
tossa@cityofmillvalley.org

Dear Mayor Sashi McEntee, Vice Mayor John McCauley, Councilmember Jim Wickham, Councilmember Urban Carmel, and Councilmember Tricia Ossa, 

My name is [YOUR NAME], and I am a resident of [YOUR NEIGHBORHOOD]. I am writing to demand that the Mill Valley City Council adopts a budget that prioritizes community wellbeing, and redirects funding away from the police.

Across all fifty states this past week, through protests, demonstrations, and vigils, the efficacy of our current form of policing and it’s systemic racism has been called into question. In Mill Valley, hundreds of people blocked Miller avenue two days in a row protesting in solidarity with the Black Lives Matter movement, demanding police accountability on a national and local level. In San Francisco, Mayor London Breed has already begun the process of budget reallocation, and now it is our turn, as a neighbor city, to do the same, and to lead the way for the rest of Marin County. 
The Mill Valley Police Department budget is not a reflection of the needs of our city. The millions of dollars we spend each year on police equipment and staff could be channeled into more productive resources, such as funding for mental health services, or on-call social workers. These adaptations are being made by other cities across the country. In a town with infrequent crime, a large and overly-equipped police force results in more arbitrary traffic stops, not less crime. This is a unique opportunity to re-imagine public safety from a community-based approach, an opportunity to prioritize youth programming, mental health, public education and more. 

Mill Valley can be a leader on this issue, if you and our other city officials have the courage to step up. I join the calls of those across the country to defund the police. 

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year.

We can be a beacon for other cities to follow, if only we have the courage to change.
Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Hi @KikiPlz! Thanks for your interest in adding San Bernardino to the site. Can you edit your email comment to provide more detail about the city budget to make a more compelling argument, showing the disparities in numbers? To get your submission published quicker, please provide source(s) for the data as well.

Please see our [email style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for some suggestions.

Thank you!

**Comment by serifluous** [comment]
@mahrer I think the second paragraph might be locale-specific enough without having to provide exact budget numbers. Thoughts?

**Comment by KikiPlz** [comment]
So all the info is taken from the actual budget, i could just include a
link to that 200-page budget? Oh, and it's for Mill Valley, CA not San
Bernadino

Thank you!

**Comment by KikiPlz** [comment]
We made the changes and cited with sources in the third paragraph, thanks
for the edits!

finance@cityofmillvalley.org

jmccauley@cityofmillvalley.org

smcentee@cityofmillvalley.org

jwickham@cityofmillvalley.org

  ucarmel@cityofmillvalley.org

tossa@cityofmillvalley.org

Dear Mayor Sashi McEntee, Vice Mayor John McCauley, Councilmember Jim
Wickham, Councilmember Urban Carmel, and Councilmember Tricia Ossa,

My name is [YOUR NAME], and I am a resident of [YOUR NEIGHBORHOOD]. I am
writing to demand that the Mill Valley City Council adopts a budget that
prioritizes community wellbeing, and redirects funding away from the police.

Across all fifty states this past week, through protests, demonstrations,
and vigils, the efficacy of our current form of policing and it’s systemic
racism has been called into question. In Mill Valley, hundreds of people
blocked Miller avenue two days in a row protesting in solidarity with the
Black Lives Matter movement, demanding police accountability on a national
and local level.  In San Francisco, Mayor London Breed has already begun
the process of budget reallocation, and now it is our turn, as a neighbor
city, to do the same, and to lead the way for the rest of Marin County.

Police Services in the number one expenditure by the city of Mill Valley1.
This budget is not a reflection of the needs of our city. While individuals
are expected to fundraise out-of-pocket for programs within public
education, such as dance, drama, and art2,  the police can be seen on a
daily basis giving tickets to drivers going one mile over the speed limit;
we need to re-prioritize our budget. The millions of dollars we spend each
year on police equipment and staff could be channeled into more productive
resources, such as funding for mental health services, or on-call social
workers. These adaptations are being made by other cities across the
country. In a town with infrequent crime, a large and overly-equipped
police force results in more arbitrary traffic stops, not less crime. This
is a unique opportunity to re-imagine public safety from a community-based
approach, an opportunity to prioritize youth programming, mental health,
public education and more.

Mill Valley can be a leader on this issue, if you and our other city
officials have the courage to step up. I join the calls of those across the
country to defund the police.

As the City Council, the budget proposal is in your hands. It is your duty
to represent your constituents. I am urging you to completely revise the
budget for the 2020-2021 fiscal year.

We can be a beacon for other cities to follow, if only we have the courage
to change.

Sincerely,

[YOUR NAME]

[YOUR ADDRESS]

[YOUR EMAIL]

[YOUR PHONE NUMBER]

   1.


   http://www.cityofmillvalley.org/civicax/filebank/blobdload.aspx?blobid=31428
   2.

   https://kiddo.org/

**Comment by mahrer** [comment]
Looks great! Some minor (mostly formatting) edits:

---

SEND TO:
finance@cityofmillvalley.org
jmccauley@cityofmillvalley.org
smcentee@cityofmillvalley.org
jwickham@cityofmillvalley.org
ucarmel@cityofmillvalley.org
tossa@cityofmillvalley.org

Dear Mayor Sashi McEntee, Vice Mayor John McCauley, Councilmember Jim Wickham, Councilmember Urban Carmel, and Councilmember Tricia Ossa,

My name is [YOUR NAME], and I am a resident of [YOUR NEIGHBORHOOD]. I am writing to demand that the Mill Valley City Council adopts a budget that prioritizes community wellbeing, and redirects funding away from the police.

Across all fifty states this past week, through protests, demonstrations, and vigils, the efficacy of our current form of policing and it’s systemic racism has been called into question. In Mill Valley, hundreds of people blocked Miller avenue two days in a row protesting in solidarity with the Black Lives Matter movement, demanding police accountability on a national and local level.  In San Francisco, Mayor London Breed has already begun the process of budget reallocation, and now it is our turn, as a neighbor city, to do the same, and to lead the way for the rest of Marin County.

Police Services in the number one expenditure by the city of Mill Valley (1). This budget is not a reflection of the needs of our city. While individuals are expected to fundraise out-of-pocket for programs within public education, such as dance, drama, and art (2), the police can be seen on a daily basis giving tickets to drivers going one mile over the speed limit; we need to re-prioritize our budget. The millions of dollars we spend each year on police equipment and staff could be channeled into more productive resources, such as funding for mental health services, or on-call social workers. These adaptations are being made by other cities across the country. This is a unique opportunity to re-imagine public safety from a community-based approach, an opportunity to prioritize youth programming, mental health, public education and more.

Mill Valley can be a leader on this issue, if you and our other city officials have the courage to step up. I join the calls of those across the country to defund the police.

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year.

We can be a beacon for other cities to follow, if only we have the courage to change.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

   1. http://www.cityofmillvalley.org/civicax/filebank/blobdload.aspx?blobid=31428
   2. https://kiddo.org/

**Comment by KikiPlz** [comment]
Coool, thanks so much! Is it ready to be posted?

Thank you all so much for providing this incredible community service

**Comment by mahrer** [comment]
@KikiPlz it is now in the hands of our dev team and should be posted shortly :) Thanks for your patience!

**Comment by KikiPlz** [comment]
yayyyyy wow you are so efficient, this is amazing!!!!!!!!!!

**Comment by todd-m** [comment]
on it
