### ISSUE TITLE
Re: Defund 12 Virginia Beach, VA

### ISSUE THREAD

**Issue by mvillania** [defund12/defund12.org#1368]
To Virginia Beach Mayor
Robert Dyer
bdyer@vbgov.com

Dear Mayor Dyer,

My name is [YOUR NAME]. I grew up in Virginia Beach, Virginia and currently residing in Norfolk. I am writing in hopes that the city’s expenditures and police budgets can be reallocated towards supporting community programs for social equality throughout Virginia Beach.

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by serifluous** [comment]
Hi @mvillania ! Thanks for your interest in adding Virginia Beach to the site. Can you edit your email comment to add a detailed message concerning the budgeting decisions at stake in your community? To get your submission published quicker, please provide source(s) for the data as well.

Please see our [email style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for some suggestions and examples.

Thank you!

**Comment by mahrer** [comment]
Hi @mvillania, a new issue #1788 was opened for Virginia Beach that contains some of the information you were missing. We will proceed with that one, but feel free to comment there if you'd like to contribute further.
