### ISSUE TITLE
Defund the Las Cruces Police Department

### ISSUE THREAD

**Issue by tazuzaz** [defund12/defund12.org#1372]
micaela.cadena@nmlegis.gov
angelica.rubio@nmlegis.gov
nathan.small@nmlegis.gov
joanne.ferrary@nmlegis.gov
https://www.heinrich.senate.gov/contact/write-martin
@MartinHeinrich
https://www.tomudall.senate.gov/?p=contact
@SenatorTomUdall
@XochforCongress

Every year 50% of our city budget goes to the LCPD. it goes to police hiring, police vehicles, police vehicle detailing. Those cool 'invisible' decals on police vehicles you see around town? The city and YOU pay for that. And what's the purpose? To sanction the killing of civilians, but invisibly? 

Our city is funding the execution of Las Cruces citizens at the hands of the LCPD at the highest rate in the nation for that last 5 years (Washington Post, June 2020). We are featured on Democracy Now! as a haven for police brutality. Is this our sleepy little Las Cruces or is this a border town with a pension for militarization? Defund the LCPD and invest in community. 

Email/call the people who represent Las Cruces. Tell them the same thing that Minneapolis organizers told the Mayor, the Governor, and local authorities: we are beyond tired of flagrant racism. We are sick to our stomachs over constant microaggressions, whether it be to the people in the streets or to our children in school. We are done. This will not stand any further.

**Comment by mahrer** [comment]
Hi @tazuzaz, thanks for your request to add Las Cruces to the site! We have an open request at #1041. If you’d like to add to or edit the messaging, please visit that issue.
Thank you!
