### ISSUE TITLE
Brookline, MA

### ISSUE THREAD

**Issue by claybl** [defund12/defund12.org#1373]
TO:
mkleckner@brooklinema.gov
bgreene@brooklinema.gov nheller@brooklinema.gov hhamilton@brooklinema.gov
rfernandez@brooklinema.gov jvanscoyoc0@gmail.com

SUBJECT: Defund Brookline PD

Dear Select Board, 
My name is [YOUR NAME], and I live in [YOUR PRECINCT] in Brookline. I am calling on you to use your power as a Select Board member to divest from police spending in the Town’s 2021 budget and use the money to fund Brookline schools and social services. We need a budget that prioritizes the well-being of all Brookline residents and invests in our community—not one that rewards a department that has had three claims of racial discrimination filed against it in the last four years. Next year, Brookline will spend $17.7 million on policing while leaving many essential services underfunded. The current budget allocates only $1.5 million toward Health, $940,000 toward the Council on Aging, and as little as $285,000 toward Diversity, Inclusion, and Community Relations. Our schools will also face a $500,000 deficit, which could result in as many as 30 teacher layoffs. These layoffs may disproportionately affect educators of color, many of whom were hired as part of a recent push for diversity. This is unacceptable. Given that Brookline has 1.5 times as many police officers per every 10,000 residents as Needham, Newton, and Lexington, it makes no sense that the Town continues to prioritize police spending. At a time when people across the country are demanding creative alternatives to policing, we should be looking for ways to invest overcriminalized BIPOC communities. I am asking that you use your power to defund the Brookline Police Department by at least 10 percent in the budget for FY21, specifically by freezing police recruitment; reducing police overtime; replacing police investigators in the police complaint review process with non-police civilian investigators; allowing civilians to direct traffic at construction and work sites or at public and private events; committing to a reduction in patrol force; and developing a plan to reallocate police community outreach programs (e.g., homeless person follow-ups) to social services departments. This issue matters to me because... [OPTIONAL - Talk about your own experience with the Brookline Police] In addition, I ask that you use funding divested from the police department to close the budget gap in Brookline schools. You can contact me to discuss why it is essential that Brookline redirect our police budget towards our schools and social services.
[YOUR NAME] 
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

LINK TO ORIGINAL SOURCE: https://docs.google.com/document/u/0/d/12XNOE0sp8M1BVW8zPtBn-eMoW8ZQNJ-eDHbUtFs9a6k

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment]
I’m reviewing
