### ISSUE TITLE
Takoma Park, Maryland

### ISSUE THREAD

**Issue by SethGrimes** [defund12/defund12.org#1403]
Add Takoma Park, Maryland, https://takomaparkmd.gov/

**Comment by rpalakkal** [comment]
Hi @SethGrimes , thanks for your interest in adding Takoma Park to the website. Emails on defund12.org are all written by community members. To add your city, you must provide:

Email addresses (at least one) of the government officials you’d like to receive the message
Detailed message concerning the budgeting decisions at stake in your community
Until you provide this content, we cannot post your city.

Follow our email style guidelines for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be closed until you reply with the necessary content. Thank you!
