### ISSUE TITLE
Fix typo in Wake County NC

### ISSUE THREAD

**Issue by mahrer** [defund12/defund12.org#1412]
There's a typo near the end of the email that says "Mayor Baldwin" but should instead say "Greg Ford and Commissioners." The submitter copied and pasted from a different template so this is important to fix as soon as possible. The fixed template is below:

---

To: commissioners@wakegov.com
CC: denise.hogan@wakegov.com
Subject: [*** INSERT UNIQUE SUBJECT LINE***]
Message (Don't forget to replace the [x]'s with your information!) 🔗
Dear Wake County Commissioners,

My name is [YOUR NAME] and I am a resident of Wake County. I urge you and the rest of the board to amend or deny the proposed budget for 2021. I would like to redirect money away from Wake Sheriff's Department and into social service programs that will benefit public health and our own communities, especially communities of color. The proposed budget for Fiscal Year 2021 (http://www.wakegov.com/budget/fy21/Documents/Recommended%20Budget%20Book.pdf) suggests cutting ambulances but not law enforcement. Fortunately it does not approve the $8 Million the Sheriff requested for even more officers, but that is less than 10% of the proposed total expenditures ($97,103,645) and it does little to invest in the community. Over 6,000 of my neighbors in Wake County are currently experiencing homelessness and in which nearly 100,000 of our neighbors in Wake County are impoverished and at risk of becoming homeless (www.raleighrescue.org) - these are the issues the board needs to address.

In order to really promote community safety, more law enforcement officers and more detention officers is not the answer - it is more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

I believe we don’t need a militarized police force. Wake County needs to create a space in which more mental health service providers, social workers, victim/survivor advocates, religious leaders, neighbors, and friends - all of the people who really make up our community - can look out for one another. Greg Ford and Commissioners, will you look out for me, and will you look out for us?

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now
