### ISSUE TITLE
Defund the Belleville, IL Police Department

### ISSUE THREAD

**Issue by ablsh** [defund12/defund12.org#1416]
To: 🔗 meckert@belleville.net, jmeyer@belleville.net, treasurer@belleville.net, Ward1kinsella@belleville.net, Ward1hazel@belleville.net, Ward2pusa@belleville.net, Ward2duco@belleville.net, Ward3randle@belleville.net, Ward3ferguson@belleville.net, Ward4anthony@belleville.net, Ward4ovian@belleville.net, Ward5dintelman@belleville.net, Ward5schaefer@belleville.net, Ward6stiehl@belleville.net, Ward6rothweiler@belleville.net, Ward7elmore@belleville.net, Ward7weygandt@belleville.net, Ward8wigginton@belleville.net, Ward8barfield@belleville.net

Subject: [*** INSERT UNIQUE SUBJECT LINE ***] 

Message: (Don't forget to replace the [x]'s with your information!) 🔗 
Dear Belleville City Council,
My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY]. Given the history of policing and the most recent murders of Black people, I am asking you to redirect money away from the Belleville PD in the 2021 budget, which currently receives more than one third of the city’s budget, or 35.73%, and instead to prioritize services that help strengthen our communities.
I want a budget that reflects our community’s priorities and needs. I demand you to advocate for a meaningful reallocation of the city’s expenditures: away from the Belleville Police Department, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. Beyond policing our community, these services are proven to be more effective in improving community safety and wellness. I demand a budget that supports community wellbeing, rather than gives power to police forces that tear them apart.
Please consider your role in enriching and empowering our communities, especially during a time of racial injustice, wide-spread illness, and economic vulnerability.
Thank you,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment]
@mahrer please change label, I’ve completed my review.

Edits made: minor structural edits. I updated some of the content to adhere to the email guidelines.

“To: 
meckert@belleville.net, 
jmeyer@belleville.net, 
treasurer@belleville.net, 
Ward1kinsella@belleville.net, 
Ward1hazel@belleville.net, 
Ward2pusa@belleville.net, 
Ward2duco@belleville.net, 
Ward3randle@belleville.net, 
Ward3ferguson@belleville.net, 
Ward4anthony@belleville.net, 
Ward4ovian@belleville.net, 
Ward5dintelman@belleville.net, 
Ward5schaefer@belleville.net, 
Ward6stiehl@belleville.net, 
Ward6rothweiler@belleville.net, 
Ward7elmore@belleville.net, 
Ward8wigginton@belleville.net, 
Ward8barfield@belleville.net

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message: (Don't forget to replace the [x]'s with your information!) 

Dear Belleville City Council,
My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY]. Given the history of policing and the most recent murders of Black people, I am asking you to redirect money away from the Belleville PD in the 2021 budget. The police department currently receives more than 35% of the city’s general budget and I believe that funding should be allocated differently [1].

Belleville should have a budget that reflects our community’s priorities and needs. I demand you to advocate for a meaningful reallocation of the city’s expenditures: away from the Belleville Police Department, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. Beyond policing our community, these services are proven to be more effective in improving community safety and wellness. 

I demand a budget that supports community wellbeing. Please consider your role in enriching and empowering our communities, especially during a time of racial injustice, wide-spread illness, and economic vulnerability.
Thank you,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

[1] https://www.belleville.net/ArchiveCenter/ViewFile/Item/2267

**Comment by todd-m** [comment]
on it
