### ISSUE TITLE
Add Whitpain Township, PA

### ISSUE THREAD

**Issue by mzj1312** [defund12/defund12.org#1418]
Notes: the following template was adapted from the Santa Barbara template. When sending your email, be sure to customize the brackets. If you can, alter parts of the email so that your email is unique and will not be filtered out by the office. 

[YOUR UNIQUE SUBJECT LINE]

SEND TO: supervisors@whitpaintownship.org
Dear Whitpain Township Board of Supervisors,

My name is [NAME], and I am a resident of [NEIGHBORHOOD/TOWN]. I am writing to demand that the Whitpain Township Board of Supervisors implement a new budget that prioritizes our community's well-being and redirects funding away from police. 

The 2020 Whitpain Township budget proposal presentation indicated that the General Fund allocated $7.49 million to police, making up 47% of the $15.9 million in total expenditures. This is an inordinate amount of funding, compared to the amount of funding that public works & facilities ($3.8 million) and parks & recreation ($800,000) received. 

I demand that the township reallocate this funding to more meaningful community projects, such as community-based mental health services, affordable housing programs, and substance abuse treatment. Our budget ought to reflect the needs of our community. 

We have witnessed the glaring inadequacy of police departments across our country to truly serve and protect. Simple reforms are not enough to reduce police violence. We have the ability to reshape our communities, and that starts with rethinking the role of police. 

Sincerely,
[NAME]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by Rtrott** [comment]
Reviewing now :)

**Comment by Rtrott** [comment]
Hi @mzj1312 , I've just checked the numbers you mentioned in the budget and I don't think the numbers that you've used are quite right, would you be comfortable with me checking and changing these numbers?

**Comment by mzj1312** [comment]
Hi @Rtrott, thanks for taking a look. I’m open to changes, and here is where I got my numbers: http://www.whitpaintownship.org/ArchiveCenter/ViewFile/Item/365

**Comment by Rtrott** [comment]
Oh wonderful! I was looking at a different document which had it all broken up. Those numbers do look right, although i'd mention that this was within General Fund Budget!

**Comment by mzj1312** [comment]
@Rtrott I've edited the email to make the source of the funds more explicit. Is there anything I need to do before this gets published? Thanks!

**Comment by mahrer** [comment]
Reviewing now

**Comment by mahrer** [comment]
Some minor edits below:

---

SEND TO: supervisors@whitpaintownship.org
Dear Whitpain Township Board of Supervisors,

My name is [NAME], and I am a resident of [NEIGHBORHOOD/TOWN]. I am writing to demand that the Whitpain Township Board of Supervisors implement a new budget that prioritizes our community's well-being and redirects funding away from police.

The 2020 Whitpain Township budget proposal presentation indicated that the General Fund allocated $7.49 million to Police, making up 47% of the $15.9 million in total expenditures. This is an inordinate amount of funding, compared to the amount of funding that Public Works & Facilities ($3.8 million) and Parks & Recreation ($800,000) received.

I demand that the township reallocate this funding to more meaningful community projects, such as community-based mental health services, affordable housing programs, and substance abuse treatment. Our budget ought to reflect the needs of our community.

We have witnessed the glaring inadequacy of police departments across our country to truly serve and protect. Simple reforms are not enough to reduce police violence. We have the ability to reshape our communities, and that starts with rethinking the role of police.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
on it
