### ISSUE TITLE
Letter to Montgomery County Virginia Board of Supervisors

### ISSUE THREAD

**Issue by womanatee** [defund12/defund12.org#1424]
To: bohnsr@montgomerycountyva.gov, blevinssm@montgomerycountyva.gov, fijalkowskisr@montgomerycountyva.gov, kingmt@montgomerycountyva.gov, shepparddo@montgomerycountyva.gov, biggsmw@montgomerycountyva.gov, demottsan@montgomerycountyva.gov

Dear Montgomery County Board of Supervisors,

My name is [YOUR NAME] and I am a resident of Montgomery County, VA. I am emailing in support of the nationwide initiative to defund police departments in favor of supporting community based public safety measures. The Approved Budget for FY 2020 states that $15,003,161 is allocated to the Sheriff, accounting for 81% of total public safety funds. Compared to the $9,416,204 allocated to all Health and Welfare services, this is enormously out of proportion with the needs and values of our community. The Montgomery County Board of Supervisors should adopt a budget that prioritizes community well-being, and redirects funding away from the Sheriff’s department. Additionally, given the likely budget shortfalls resulting from the pandemic, now is an urgent time to re-evaluate the priorities of our County.

The Montgomery County Board of Supervisors should begin meaningfully re-allocating Sheriff Department funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, affordable housing programs, schools and childcare, public health, sustainability, and infrastructure. Additionally, police officers should not be the first resource for every crisis. I demand a budget that reflects the needs and values of Montgomery County residents. We must take a hard look at the way the current system fails to serve-and in fact actively harms-our community, and come together to reimagine the role of law enforcement in our County.

I am urging you to keep these things in mind for the budget for the 2020-2021 fiscal year and to invest in the people, not the police.

Thank you, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by brickaney** [comment]
@serifluous Please change the label, I’ve completed my review.

Edits made: minor edits, added a reference to the budget page.

“To:
bohnsr@montgomerycountyva.gov
blevinssm@montgomerycountyva.gov
fijalkowskisr@montgomerycountyva.gov
kingmt@montgomerycountyva.gov
shepparddo@montgomerycountyva.gov
biggsmw@montgomerycountyva.gov
demottsan@montgomerycountyva.gov

Subject: [UNIQUE SUBJECT LINE]

Dear Montgomery County Board of Supervisors,

My name is [YOUR NAME] and I am a resident of Montgomery County, VA. 

I am emailing in support of the nationwide initiative to defund police departments in favor of supporting community based public safety measures. The Approved Budget for FY 2020 states that $15,003,161 is allocated to the Sheriff, accounting for 81% of total public safety funds [1]. Compared to the $9,416,204 allocated to all Health and Welfare services, this is enormously out of proportion with the needs and values of our community [1]. The Montgomery County Board of Supervisors should adopt a budget that prioritizes community well-being, and redirects funding away from the Sheriff’s department. Additionally, given the likely budget shortfalls resulting from the pandemic, now is an urgent time to re-evaluate the priorities of our County.

The Montgomery County Board of Supervisors should begin meaningfully re-allocating Sheriff Department funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, affordable housing programs, schools and childcare, public health, sustainability, and infrastructure. Additionally, police officers should not be the first resource for every crisis. I demand a budget that reflects the needs and values of Montgomery County residents. We must take a hard look at the way the current system fails to serve-and in fact actively harms-our community, and come together to reimagine the role of law enforcement in our County.

I am urging you to keep these things in mind for the budget for the 2020-2021 fiscal year and to invest in the people, not the police.

Thank you, 
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

[1] https://www.montgomerycountyva.gov/departments/finance-intro/budget

**Comment by todd-m** [comment]
on it
