### ISSUE TITLE
Boca Raton, FL - Letter to Mayor, City Council, and Financial Advisory Board

### ISSUE THREAD

**Issue by sofiass13** [defund12/defund12.org#1425]
To: BRCityClerk@myboca.us, mcc@myboca.us
CC: ssinger@ci.boca-raton.fl.us, athomson@myboca.us, MMayotte@ci.boca-raton.fl.us, AORourke@ci.boca-raton.fl.us, jrodgers@ci.boca-raton.fl.us

Dear Mayor Singer, Boca Raton City Council, and Boca Raton Financial Advisory Board, 

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/AREA].  I am writing to demand that the Boca Raton City Council adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police.

Our city's spending on Public Safety increased from 12.8% in 2018-2019 to 15.5% in 2019-2020, comprising approximately 50% of the General Fund. According to the Historical Summary Operating Expenditures, the city’s spending on police services has increased steadily from approx. $39.6 million in FY2014-15 to $56.5 million in FY 2019-20. I am writing today to ask that, when considering budget allocation for FY2020-2021, you work to actively decrease the percentage of our city’s budget that goes to Public Safety and reallocate it elsewhere.

I demand that the City Council begin meaningfully defunding the Boca Raton Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, adequate, ADA-accessible parks and library programming, and more. I demand a budget that reflects the actual needs of Boca Raton residents.

For example, [INSERT PERSONAL EXAMPLE IF AVAILABLE]. 

I urge you to reimagine the way the justice system works in our city. History has shown that police "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve--and in fact, actively harms--our community, and come together to reimagine the role of police in our city. This means investing in our community’s long-term health and prosperity and, in doing so, decreasing the demand for such an expensive police force in the first place. Until Boca Raton does this, we are failing to serve communities of color, our most marginalized, and actively upholding a structural system of white supremacy.

The city's mission statement is “to responsibly provide outstanding services to enhance our unique quality of life,” guided by principles that include "World-Class Municipal Services” and a "Vibrant and Sustainable City”. In order to achieve the title of “world-class,” let alone “outstanding", you should adopt a budget that prioritizes community well-being through education, enrichment, and social services while redirecting funding away from police and incarceration.

As one of your constituents, I’m asking you to take immediate, concrete action on this issue. I will be sure to tell my friends, family, and neighbors about your response.

I look forward to hearing from you all,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE]

**Comment by brickaney** [comment]
I’m reviewing

**Comment by todd-m** [comment]
on it
