### ISSUE TITLE
Email for San Bruno, CA

### ISSUE THREAD

**Issue by defundsbpd** [defund12/defund12.org#1453]
To: RMedina@sanbruno.ca.gov, MSalazar@sanbruno.ca.gov, LDavis@sanbruno.ca.gov, MMedina@sanbruno.ca.gov, lmason@sanbruno.ca.gov, councilsb@sanbruno.ca.gov, mthurman@sanbruno.ca.gov, 

To Mayor Medina, Vice Mayor Salazar, and our San Bruno elected and appointed officials,

My name is [YOUR NAME], and I am a San Bruno resident. Within the past week, we have seen a nationwide movement take to our streets in protest and outrage at the brutalization of Black people in our country at the hands of the police. The discussion has branched to whether the violent enforcement strategies of police actually keep us safe and are helpful to our community, and I believe we need to address that here in San Bruno. We must acknowledge and dismantle the waste and harm of our police budget.

The proposed budget for the San Bruno Police Department for the 2020-21 fiscal year currently utilizes forty percent of our city budget at $19,310,788. This proposed budget for a single police station will cost taxpayers more than twice as much as we spent on the total budget of all of our Community Services combined (including Recreation, Parks Maintenance, Libraries and Senior Services) and two-thirds the amount it costs to run the entirety of the San Bruno Park School District. The SBPD budget is excessive for a small town, and I am alarmed to see that San Bruno’s forecasted financial plan projects an increase to almost $23 million in spending on police despite historic unemployment, economic instability, and popular resistance to widespread police abuses.

We can be leaders on this issue, if you and our other city officials have the courage to step up. I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of at-risk San Bruno residents during this trying and uncertain time, when livelihoods are on the line. I call on you to meaningfully restrict the SBPD budget and instead intentionally reallocate funds towards social programs and resources that support affordable housing, education, health care, child care, and other critical community needs. We demand a budget that supports community wellbeing, rather than empowering the police forces that tear us apart.

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year.

We can be a beacon for other cities to follow, if only we have the courage to change.

Thank you,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by serifluous** [comment]
Hi @defundsbpd,thanks for your request to add San Bruno to the site! We have an open request at issue #1268. If you’d like to add to or edit the messaging, please visit that issue.

Thank you!
