### ISSUE TITLE
Mobile, Alabama - Letter to Mayor and City Councillors

### ISSUE THREAD

**Issue by jnco-unchained** [defund12/defund12.org#1454]
To: mayorstimpson@cityofmobile.org; council1@cityofmobile.org; council2@cityofmobile.org; council3@cityofmobile.org; council4@cityofmobile.org; council5@cityofmobile.org; council6@cityofmobile.org; council7@cityofmobile.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message: (Don't forget to replace the [x]'s with your information!) 

Dear Mayor Stimpson and City Council Members,

My name is [YOUR NAME] and I am a resident of Mobile. I am writing today to urge you to advocate for a meaningful reallocation of the city's expenditures: away from policing, and towards social programs and resources that our community desperately needs.

In 2019, just under $52 Million, 21.5% of the city's entire budget, went to the MPD. According to the proposed 2020 city budget, that amount is set to increase by nearly $6 Million. The Mayor's Neighborhood Development Program, by contrast, responsible for the city's homeless and low-to-moderate income housing, has a total budget of about $1.5 Million this year, less than 1% of the total city budget. 

With 22% of Mobilians living below the poverty line, according to the US Census Bureau, and surging unemployment due to COVID-19, the question, then, for the leaders of Mobile, is how do we want to address these issues? By devoting our time, energy, and resources to building a better community and addressing our actual societal needs, or by putting more cops with more weapons on the street, and letting them deal with it? The latter answer may have been more convenient in the past, but I believe we, as a city, must look to the future.

I demand that the Mayor and City Council begin meaningfully defunding the Mobile Police Department and re-allocate those funds to programs proven to more effectively promote a safe, healthy, and equitable community: affordable housing programs, substance abuse services, and mental health services, among others. I demand a budget that reflects the actual needs of our community.

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by rpalakkal** [comment]
on it
