### ISSUE TITLE
Defund Boca Raton Police Services (FL)

### ISSUE THREAD

**Issue by sagea123** [defund12/defund12.org#1456]
**Contacts**
ssinger@ci.boca-raton.fl.us
MMayotte@ci.boca-raton.fl.us
AORourke@ci.boca-raton.fl.us
jrodgers@ci.boca-raton.fl.us
athomson@myboca.us

**Email**
Dear Mayor Scott Singer and Boca Raton City Council Members,

My name is [X] and I am a resident of Boca Raton. I am writing to you as a constituent who is disturbed by the injustices and brutality carried out by police forces across the country against Black people. While I recognize that the Boca Raton Police Department practices the reforms from the “8 cant wait” campaign, and we are fortunate that the police have a good relationship and reputation within the community, I am demanding that real change be made to the way this city allocates funding for its resources. I demand that the City of Boca Raton adopt a budget that prioritizes community wellbeing and redirects funding away from the police and into more social services.

The Fiscal Year (FY) 2019-2020 Budget allocated $164,906,000 for Public Safety, of which $56,365,400 goes directly towards the operating budget of the police. This amounts to 20.8% of the total program expenditures for all City departments. Additionally there was a 45.25% increase in the budget since the FY 2018-2019 Budget. In comparison to the Public Safety budget, the Human Services budget is only allocated $2,348,500 and represents merely 0.3% of the City's total program budget. It is important to note that the budget allocated to Human services has actually decreased by approximately 10% since the FY 2018-2019 Budget. Another stark comparison to recognize is the amount of money budgeted to Golf Courses. The budget for Golf Courses, part of the Recreation Services Budget, allocates $2,959,100. This means we are prioritizing $610,600 more to playing golf than we are to providing Housing Assistance and other necessary resources for our community through the Human Services Budget.   

To really make community safety a priority, we do not need more policing. What we need instead are better jobs, better educational opportunities, more arts programs, more community centers, more affordable mental health resources, an emphasis on restorative justice, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

I am demanding that the City of Boca Raton’s elected officials cut partial funding to the Boca Raton Police Department. I am joining in the global outcries to actively and intentionally limit the funding of programs that inadvertently and systemically promote police brutality, violence, and discrimination which disproportionately effects the Black community. I am calling on the Boca Raton Town Council to take the following actions:

- Vote no on all increases to police budgets
- Vote yes to decrease/cut police spending and budgets
- Redirect funds to educational opportunities, youth development programs, and the arts, as well as removing police from schools
- Redirect funds to provide affordable and safe housing, agricultural and food-based inequality programs such as funding food banks, and free and more extensive public transport
- Redirect funds towards healthcare infrastructure including mental health resources, social work services, trauma centers, sexual assault services, non-coercive drug and alcohol treatment programming, and peer support networks
- Commit resources to support community-led alternatives to policing, such as social work programs, and practice restorative justice.
- Propose plans for ensuring the safety of Black and other marginalized people in our community from racial profiling by police and other security forces with input from members of the marginalized communities themselves by adding curriculum about race and diversity into trainings.  

I urge you to do the right thing and embrace the responsibility of your role at this moment in history. It is important to be proactive and take initiative, rather than waiting for our town to become another hashtag. Do not forget our poor communities and communities of color who are disproportionate targets of police violence. Justice will only be served when the police are reformed, and this will not fully be possible until we redistribute city funding.

Can I count on you to pass an alternative budget that puts a focus on social service programs for the betterment of our community? 

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Hi @sagea123, thanks for your request to add Boca Raton to the site! We have an open request at #1425. If you’d like to add to or edit the messaging, please visit that issue.
Thank you!
