### ISSUE TITLE
Laguna Beach, CA

### ISSUE THREAD

**Issue by devthered** [defund12/defund12.org#1457]
Bob Whalen (Mayor) (949) 497-0796
Steve Dicterow (Mayor Pro Tem) (949) 500-1132
Peter Blake (949) 584-1224
Toni Iseman (949) 494-7648
Sue Kempf (949) 439-3001

bwhalen@lagunabeachcity.net, sdicterow1121@yahoo.com, pblake@lagunabeachcity.net, 	tiseman@lagunabeachcity.net ,
skempf@lagunabeachcity.net

Dear Laguna Beach City Council,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the Laguna Beach City Council adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police.

For the FR 2020-2021 Budget, Laguna Beach has appropriated $19.8 million of the General Fund to the Police department. This is larger than any other portion of the General Fund - 27%. Compare this to just $3.8 million (5.2%) spent on Community Services - this includes City Parks, Community Assistance, and all Homeless Programs.

Around the country, we are witnessing shocking abuses of police power, manifested as violence and murder inflicted primarily on Black, Latinx, and Indigenous people. While these high-profile cases are taking place in other cities, Laguna Beach is not free from police violence and systemic racism within its criminal justice system. To truly rid ourselves of these problems we must imagine and build new systems to keep our community safe - systems that enable conflict de-escalation, substance abuse treatment, mental health and housing services.

I demand that the City Council begin defunding the Laguna Beach Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community, such as affordable housing programs, community-based mental health programs, and more investment in programs for the homeless such as the ASL.

Thank you for your time.

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by Rtrott** [comment]
Bob Whalen (Mayor) (949) 497-0796
Steve Dicterow (Mayor Pro Tem) (949) 500-1132
Peter Blake (949) 584-1224
Toni Iseman (949) 494-7648
Sue Kempf (949) 439-3001

bwhalen@lagunabeachcity.net, sdicterow1121@yahoo.com, pblake@lagunabeachcity.net, tiseman@lagunabeachcity.net ,
skempf@lagunabeachcity.net

Dear Laguna Beach City Council,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the Laguna Beach City Council adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police.

For the FR 2020-2021 Budget, Laguna Beach has appropriated $19.8 million of the General Fund to the Police department. This is larger than any other portion of the General Fund - 27%. Compare this to just $3.8 million (5.2%) spent on Community Services - this includes City Parks, Community Assistance, and all Homeless Programs.

Around the country, we are witnessing shocking abuses of police power, manifested as violence and murder inflicted primarily on Black, Latinx, and Indigenous people. While these high-profile cases are taking place in other cities, Laguna Beach is not free from police violence and systemic racism within its criminal justice system. To truly rid ourselves of these problems we must imagine and build new systems to keep our community safe - systems that enable conflict de-escalation, substance abuse treatment, mental health and housing services.

I demand that the City Council begin defunding the Laguna Beach Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community, such as affordable housing programs, community-based mental health programs, and more investment in programs for the homeless such as the ASL.

Thank you for your time.

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
