### ISSUE TITLE
UX - dropdown on mobile not styled properly

### ISSUE THREAD

**Issue by bingbongle** [defund12/defund12.org#1465]
The dropdown in desktop looks really nice and in line with our brand/design. On mobile - not sure if this is standard to use the native component or what - looks a little bit clunky. I definitely think we should use the default iOS selection view, but the clickable menu itself should probably be changed.

Running: iOS, chrome

![FullSizeRender](https://user-images.githubusercontent.com/10104111/84506200-fe4bc980-ac8c-11ea-8a81-b983289ffe31.jpeg)

**Comment by skullface** [comment]
👀 We could replace the jQuery library with a [React version](https://react-select.com/styles) that works on mobile!

**Comment by avimoondra** [comment]
Closed by use of react-select + https://github.com/defund12/defund12.org/pull/1575
