### ISSUE TITLE
Refactor frontend site structure

### ISSUE THREAD

**Issue by mcespo** [defund12/defund12.org#1468]
The site is b-e-a-u-tiful. However, we can always do more. One of the things I would like us to do is compartmentalize (or componentize some of the css styling) to better allow for some features (namely a sticky footer).

Alongside that, I want to lint through the CSS to filer out unused styles, use a normalize of some sort, use HTML header, article, main, footer, and aside tags, and generally refactor as much as we can while still keeping the look and feel of the site virtually unnoticeable to the untrained eye.

If the goal is to migrate this into a framework like Vue or React, it may not be the worst idea to get ahead of that by splitting up some of the css files in general. This project won't be trivial so any PR against this will be a work in progress.

**Comment by avimoondra** [comment]
cc: @Ceshion who is working on a port

**Comment by mcespo** [comment]
Resolved in this PR - https://github.com/defund12/defund12.org/pull/1487
