### ISSUE TITLE
Miami-Dade Email Needs Attention

### ISSUE THREAD

**Issue by d4nc3r5ky** [defund12/defund12.org#1470]
Hey! I'm sorry, I'm sure this is not the way to do this but... the email template for MIami-Dade County has been ready for review for a couple of days! The issue was closed awaiting the email content, but that was provided and it still hasn't been re-opened. I know you all might just be busy; I just didn't want it to be forgotten. Thanks!

**Comment by bingbongle** [comment]
Hey! I've reopened the issue here: https://github.com/defund12/defund12.org/issues/1036

We have quite a few requests right now, but sit tight and we'll get to it ASAP!
