### ISSUE TITLE
Novi, MI

### ISSUE THREAD

**Issue by Namanaseem** [defund12/defund12.org#1471]
Emails: bgatt@cityofnovi.org, dstaudt@cityofnovi.org, amutch@cityofnovi.org, lcasey@cityofnovi.org, kbreen@cityofnovi.org, hcrawford@cityofnovi.org, jfischer@cityofnovi.org 

Subject: [INSERT UNIQUE SUBJECT LINE HERE]

Dear Novi City Council:

My name is [INSERT NAME HERE] and I am a resident of [INSERT CITY/NEIGHBORHOOD]. Recently, the country has begun to understand how pervasive systemic racism is and the role police brutality plays in contributing to this culture. I believe it is important that we do our best within our own community to identify ways to end these injustices.  

I am writing to demand that the Novi City Council adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police. Although the FY 2020-21 budget has been approved, I am asking for a reconsideration before it goes into effect on July 1, 2020.

Considering that Novi’s City Council lacks racial diversity, it is not surprising that the current budget is set to best serve those with privilege. The budget reflects a lack of concern in regard to social services from the government, such as education, healthcare access, and financial assistance. Investing in these areas will only strengthen our community and help promote equality amongst Novi’s residents. 

As a former police detective, Mayor Bob Gatt has prided himself on reducing crime rates. By promoting this, he implies that there is excessive spending on police and he is creating a less than inviting home for Black Americans, who fear racial discrimination from the police. By reallocating funds, Novi can focus on having a culture that promotes diversity, by offering social services. 

By looking at the FY 2020-21 City Budget, the Novi Police Department (NPD) is overwhelmingly represented. For one, about 55% of the Property Tax is directed to Public Safety. Only 14% is dedicated to Parks, Recreation, & Cultural Services and Community Development. Secondly, the General Fund allocates about $14 million to NPD, which is significantly greater than community and economic development. 

I demand that you take immediate action to ensure the following:
•	Reduce NPD’s allocation from the General Fund by 50%
•	Hire trained social workers to manage services such as mental health, substance abuse, and domestic violence
 •	Disallow the use of the Gun Range Facility Fund to provide capital improvements to the city
 •	Invest in community development initiatives, such as affordable housing, education, and youth services

This effort will not increase crime rates. A 2016 report from the Obama White House’s Council of Economic Advisers found that “a 10 percent increase in wages for non-college educated men results in approximately a 10 to 20 percent reduction in crime rates.”

Please assemble a city budget that meets the needs of all residents. The time is now to demilitarize the NPD and invest in social services.

Thank you,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment]
@mahrer Please change label, I’ve completed my review.

Edits made: small structural edits, added reference to the budget, made the content more generic and adhere to the email guidelines.

“TO: 
bgatt@cityofnovi.org
dstaudt@cityofnovi.org
amutch@cityofnovi.org
lcasey@cityofnovi.org
kbreen@cityofnovi.org
hcrawford@cityofnovi.org
jfischer@cityofnovi.org

Subject: [INSERT UNIQUE SUBJECT LINE HERE]

Dear Novi City Council:

My name is [INSERT NAME HERE] and I am a resident of [INSERT CITY/NEIGHBORHOOD]. Recently, the country has begun to understand how pervasive systemic racism is and the role police brutality plays in contributing to this culture. I believe it is important that we do our best within our own community to identify ways to end these injustices.

I am writing to demand that the Novi City Council adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police. Although the FY 2020-21 budget has been approved, I am asking for a reconsideration. The budget reflects a lack of concern in regard to social services from the government, such as education, healthcare access, and financial assistance. Investing in these areas will only strengthen our community and help promote equality amongst Novi’s residents. By reallocating funds, Novi can focus on having a culture that promotes diversity, by offering social services. 

By looking at the FY 2020-21 City Budget, the Novi Police Department (NPD) is overwhelmingly represented. For one, about 55% of the Property Tax is directed to Public Safety [1]. Only 14% is dedicated to Parks, Recreation, & Cultural Services and Community Development [1]. Secondly, the General Fund allocates about $14 million to NPD, which is significantly greater than community and economic development [1]. 

I demand that you take immediate action to ensure the following:
• Reduce NPD’s allocation from the General Fund
• Hire trained social workers to manage services such as mental health, substance abuse, and domestic violence
• Invest in community development initiatives, such as affordable housing, education, and youth services

Please assemble a city budget that meets the needs of all residents. The time is now to demilitarize the NPD and invest in social services.

Thank you,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

[1] https://www.cityofnovi.org/Government/City-Services/City-Manager/Budget-and-Multi-Year-Financial-Plan-(Current-and/Budget2020-2021Recommended.aspx

**Comment by todd-m** [comment]
on it
