### ISSUE TITLE
Defund Fort Lauderdale, FL Police

### ISSUE THREAD

**Issue by hkdeven** [defund12/defund12.org#1479]
# EMAIL

Mayor of Fort Lauderdale: dtrantalis@fortlauderdale.gov

# LETTER:

Dear DEAN TRANTALIS, 

My name is [YOUR NAME] and I am a Fort Lauderdale resident and I live in [NEIGHBORHOOD]. I am writing to demand you consider diverting budget from police department activities for 2020-2021 fiscal year and revise the current budget accordingly. 

More than 36% of our cities budget has been allocated to the police this year.  I believe these funds could better be spent elsewhere.  Our city should prioritize universal needs (such as housing, childcare, healthy food, clear air and water), pandemic recovery, built environment, and reimagined public safety over the police department. You need to engage directly with communities, especially Black and Indigenous communities — the most at risk of police brutality and murder — to create a budget that serves ALL residents of Fort Lauderdale. 

Over the past two weeks, our city has shown its overwhelming support for defunding the FLPD. It has made clear — through both physical and digital actions— that Fort Lauderdale must not use its money to fund the murderous FLPD. 

Throughout this time of mass protest, the police have reacted with extreme violence and unwarranted escalation towards peaceful protestors and our unhoused neighbors. Police flash White Power signals openly in public and on television. Many police officers have hurt, abused and maimed citizens of our city.

This is unacceptable and FLPD must be defunded, now. 

Thank you for your time, 

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by wendywx** [comment]
Hi @hkdeven ! Thanks for your interest in adding Fort Lauderdale to the site. Could you please provide more detail about the city budget to make a more compelling argument, showing the disparities in numbers?

Please see our [email style guide](https://github.com/defund12/defund12.org/blob/master/EMAIL_TEMPLATE_STYLE_GUIDE.md) for some suggestions and general guidelines.

Thank you!

**Comment by mahrer** [comment]
I see that a new issue has been opened for Fort Lauderdale with the required information at #1589. @hkdeven if you would like to contribute to that template, feel free to hop over to that issue.
