### ISSUE TITLE
Please add Howard County, Maryland (to Howard County Council and County Executive)

### ISSUE THREAD

**Issue by egfrank** [defund12/defund12.org#1494]
To Howard County Council and County Executive 

TO: EWalsh@howardcountymd.gov, OJones@howardcountymd.gov, CRigby@howardcountymd.gov, DJung@howardcountymd.gov, DYungmann@howardcountymd.gov, mrharris@howardcountymd.gov, kknight@howardcountymd.gov, ccwilliams@howardcountymd.gov, ffacchine@howardcountymd.gov, ndvorak@howardcountymd.gov, cball@howardcountymd.gov, kpruim@howardcountymd.gov,  ssidh@howardcountymd.gov, jdjones@howardcountymd.gov, shernandez@howardcountymd.gov, 

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!)

Dear Howard County Elected Officials, 

My name is [YOUR NAME], and I am a resident of Howard County, Maryland. 

I write to you as people across the world take a public stand against policing and systemic racism. As demonstrated by the largest protest in Howard County history, the people of our community are also demanding change. It is critical that every elected official condemns police violence and affirms that Black Lives Matter. 

But speaking out is not enough, we also demand action. 

In Howard County’s proposed budget for Fiscal Year 2021, the police receive over $134 million, or more than $367,000 every day that could instead be used to fund vital community services. We should invest those millions in ending homelessness, supporting teachers and students, and in meeting all the needs of marginalized residents. We demand that the County Executive and County Council reapportion funds allocated to the HCPD to instead support community programs and services that, unlike increased police presence, promote the well-being of our residents and reduce crime. 

In addition, the presence of police in our schools leads to higher rates of suspensions, expulsions and arrests, especially for Black students. Police in schools do not increase safety, but do aid the school-to-prison pipeline that pushes children, especially Black children, into the criminal legal system. We demand that Student Resource Officers be removed from Howard County Schools and that those funds go to counselors and culturally specific services that actually create safer schools. 

As the rest of the country reckons with the inherent injustice of police, Howard County must do the same. Our demands are clear: fund the community, defund the police. 

Sincerely, 
[YOUR NAME]
[YOUR ADDRESS] 
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Hi @egfrank, thanks for your request to add a letter to the Howard County Council to the site! We have an open request at #1345. If you’d like to add to or edit the messaging, please visit that issue.
Thank you!
