### ISSUE TITLE
Letter to City Council - Springdale, Arkansas

### ISSUE THREAD

**Issue by hamaadwmehal** [defund12/defund12.org#1496]
*Borrows from a defund12.org template for Benton County*

mlawson@SpringdaleAR.gov; jwatson@SpringdaleAR.gov; awilliams@springdalear.gov; moverton@SpringdaleAR.gov; mlawson@SpringdaleAR.gov; kjaycox@SpringdaleAR.gov; 
bpowell@SpringdaleAR.gov; revans@SpringdaleAR.gov; cfulfer@SpringdaleAR.gov 

Dear Members of the Springdale City Council,

My name is [YOUR NAME], and I am a resident of Springdale, Arkansas. These past few weeks, our nation has been gripped by protests calling for rapid and meaningful change with regard to police brutality of black Americans, racism, and how law enforcement is perpetuating these issues. I believe that changes will begin by defunding law enforcement and investing in community programs and infrastructure.

Millions of dollars every year have been funneled toward law enforcement and mass incarceration systems that are harming our communities more than helping them. Benton County’s total budget for 2019 was roughly $18.7 million. 30 percent of that budget was spent on law enforcement activities, while less than 2 percent was allocated to sanitation, planning and community development, engineering, senior services, buildings, animal services, & cemetery services.

The funds that Springdale has budgeted for law enforcement and incarceration should be redirected into COVID-19 relief, affordable housing, education, healthcare, community centers, updating infrastructure, and community-led organizations. While Springdale has been spending extraordinary amounts on policing, I have not seen sufficient improvements to safety, community & diversity initiatives, infrastructure maintenance, or affordability in our towns. Springdale would be better served by dedicating resources to programs that are more effective at promoting safety and social equity than policing and incarceration.

The infrastructure of public spaces such as community gardens and parks has always been part of what makes Northwest Arkansas such a beautiful community, and that should not be restricted only to the wealthy areas of town.

We can be a beacon for other cities to follow if only we have the courage to change. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Sincerely,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by brickaney** [comment]
@swallan Please change to new label, I’ve completed my review.

Edits made: minor structural edits, added reference to the city budget.

“TO:
mlawson@SpringdaleAR.gov
jwatson@SpringdaleAR.gov
awilliams@springdalear.gov
moverton@SpringdaleAR.gov
mlawson@SpringdaleAR.gov
kjaycox@SpringdaleAR.gov
bpowell@SpringdaleAR.gov
revans@SpringdaleAR.gov
cfulfer@SpringdaleAR.gov

Subject: [UNIQUE SUBJECT LINE]

Dear Members of the Springdale City Council,

My name is [YOUR NAME], and I am a resident of Springdale, Arkansas. These past few weeks, our nation has been gripped by protests calling for rapid and meaningful change with regard to police brutality of black Americans, racism, and how law enforcement is perpetuating these issues. I believe that changes will begin by defunding law enforcement and investing in community programs and infrastructure.

Millions of dollars every year have been funneled toward law enforcement and mass incarceration systems that are harming our communities more than helping them. Springdale’s 2019 city budget breakdown shows that 30% of the general fund was spent on law enforcement activities, while less than 2% percent was allocated to sanitation, planning and community development, engineering, senior services, buildings, animal services, & cemetery services [1].

The funds that Springdale has budgeted for law enforcement and incarceration should be redirected into COVID-19 relief, affordable housing, education, healthcare, community centers, updating infrastructure, and community-led organizations. While Springdale has been spending extraordinary amounts on policing, I have not seen sufficient improvements to safety, community & diversity initiatives, infrastructure maintenance, or affordability in our towns. Springdale would be better served by dedicating resources to programs that are more effective at promoting safety and social equity than policing and incarceration.

The infrastructure of public spaces such as community gardens and parks has always been part of what makes Northwest Arkansas such a beautiful community, and that should not be restricted only to the wealthy areas of town.

We can be a beacon for other cities to follow if only we have the courage to change. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Sincerely,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

[1] http://www.springdalear.gov/DocumentCenter/View/4261/City-of-Springdale-2019-Budget

**Comment by todd-m** [comment]
on it
