### ISSUE TITLE
Lafayette, LA

### ISSUE THREAD

**Issue by brickaney** [defund12/defund12.org#1497]
TO:
MayorPresidentsOffice@LafayetteLA.gov
cwingerter@lafayettela.gov
nanettecook@lafayettela.gov
andynaquin@lafayettela.gov
patricklewis@lafayettela.gov
lizhebert@lafayettela.gov
glennlazard@lafayettela.gov
hconway@LafayetteLA.gov
bryantabor@lafayettela.gov
kevinnaquin@lafayettela.gov
joshcarlson@lafayettela.gov
johnguilbeau@lafayettela.gov
abrubin@lafayettela.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
(Don't forget to replace the [x]'s with your information!)  

To Mayor-President Josh Guillermo and the Lafayette City Council:

My name is [INSERT NAME] and I am a resident of [YOUR NEIGHBORHOOD]. I am writing to demand that the Lafayette City Council adopt a budget that prioritizes community wellbeing, and redirects funding away from the police.

Referencing the most recent city budget, a staggering 35 million dollars [1] was allocated to the Lafayette police department. Relatedly, Louisiana has the highest incarceration rate in the nation, which disproportionately affects Black residents (e.g., over 60% of incarcerated individuals in LA were black according to the 2010 U.S. census). 

Less than 6 million dollars are allocated for vital community programs including workforce innovations, job training, employment support programs, social services assistance, economic assistance, and housing assistance provided by the Office of Community Development for example [1]. The current city budget is communicating that law enforcement is almost 6 times more important that community development and I do not believe that this aligns with most residents values and the vision statement, particularly: “ Our People: A Vibrant Culture of Creativity, Innovation and Compassion” [2].

Lafayette is a city with high levels of poverty (15% [3])and I am demanding that we re-allocate funds from the police department to programs proven to more effectively promote a safe and equitable community and to address economic disparities. These programs include community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Lafayette residents.

History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city. I strongly urge you to remove funding from police departments and reallocate it to social services that make a meaningful difference for the citizens of Lafayette.

Sincerely, [YOUR NAME] 
[YOUR ADDRESS] 
[YOUR PHONE] 
[YOUR EMAIL]

[1] http://www.lafayettela.gov/Budget/SiteAssets/Files/Archive/2019-ADOPTED-BUDGET-Document.pdf
[2] http://www.lafayettela.gov/ComprehensivePlan/Pages/Vision-Statement
[3] https://www.census.gov/quickfacts/lafayetteparishlouisiana

**Comment by aurendisson** [comment]
Editing now!

**Comment by aurendisson** [comment]
Editing notes: Minimal edits made. Thank you for providing links/sources! 

To: MayorPresidentsOffice@LafayetteLA.gov, cwingerter@lafayettela.gov, nanettecook@lafayettela.gov, andynaquin@lafayettela.gov, patricklewis@lafayettela.gov, lizhebert@lafayettela.gov, glennlazard@lafayettela.gov, hconway@LafayetteLA.gov, bryantabor@lafayettela.gov, kevinnaquin@lafayettela.gov, joshcarlson@lafayettela.gov, johnguilbeau@lafayettela.gov, abrubin@lafayettela.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message: (Don't forget to replace the [x]'s with your information! Please add a couple of sentences in your own words to avoid filters. )

To Mayor-President Josh Guillermo and the Lafayette City Council,

My name is [INSERT NAME] and I am a resident of [YOUR NEIGHBORHOOD]. I am writing to demand that the Lafayette City Council adopt a budget that prioritizes community wellbeing, and redirects funding away from the police.

Referencing the most recent city budget, a staggering $34.7 million [1] was allocated to the Lafayette Police Department. Relatedly, Louisiana has the highest incarceration rate in the nation, which disproportionately affects Black residents (e.g., over 60% of incarcerated individuals in Louisiana were Black according to the 2010 U.S. Census).

Less than $6 million are allocated for vital community programs, including workforce innovations, job training, employment support programs, social services assistance, economic assistance, and housing assistance provided by the Office of Community Development [1]. The current city budget is communicating that law enforcement is almost 6 times more important that community development, and I do not believe that this aligns with most residents' values and the vision statement, particularly: “Our People: A Vibrant Culture of Creativity, Innovation and Compassion” [2].

Lafayette is a city with high levels of poverty (15%) [3], and I am demanding that we reallocate funds from the police department to programs proven to more effectively promote a safe and equitable community and to address economic disparities. These programs include community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Lafayette residents.

History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact, actively harms–our community, and come together to reimagine the role of police in our city. I strongly urge you to remove funding from police departments and reallocate it to social services that make a meaningful difference for the citizens of Lafayette.

Sincerely, 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

[1] http://www.lafayettela.gov/Budget/SiteAssets/Files/Archive/2019-ADOPTED-BUDGET-Document.pdf
[2] http://www.lafayettela.gov/ComprehensivePlan/Pages/Vision-Statement
[3] https://www.census.gov/quickfacts/lafayetteparishlouisiana

**Comment by todd-m** [comment]
on it
