### ISSUE TITLE
Cedar Rapids Iowa Police Reform 

### ISSUE THREAD

**Issue by SteveShriver** [defund12/defund12.org#1498]
City Council Members:

b.hart@cedar-rapids.org
t.olson@cedar-rapids.org
ann.poe@cedar-rapids.org
p.loeffler@cedar-rapids.org
s.overland@cedar-rapids.org
dalet@cedar-rapids.org
scott.olson@cedar-rapids.org
a.vanorny@cedar-rapids.org

Dear City Council Member,
My name is (Insert Name) and I am writing to ask you to consider introducing and supporting police reform in the City of Cedar Rapids.
There are 7 major items that would help our community become more fair and just:
1. Citizen’s Review Board:  An accountability measure should be put into place that helps ensure fairness and transparency during the unfortunate time when an investigation is needed for a police officer.
2. Significant investment in Diversity, Equity and Inclusion: Continual training is a must and will help the future of our City.
3. Strengthen Existing Use of Force Standards: Certain maneuvers such as “knee to neck” should not be allowed on handcuffed individuals.
4.  Decriminalize minor marijuana crimes and other lower-level offenses:  The ripple effect of incarceration for low level offenses is taking a toll on our community.
5. Impose Strict Body Camera Provisions:  A police officer should not be able to choose what gets recorded and what doesn’t.
6.  Make the negotiations between municipal authorities and the bargaining units that represent police officers public: Our community deserves to see where it’s tax dollars are being leveraged.
7.  Abolish Qualified Immunity:  Our community deserves a police force that is willing to take responsibility for its individual actions.

Thank you for your help in creating positive change for our community.
Sincerely,
(Your Name)

**Comment by SteveShriver** [comment]
City Council Members:

b.hart@cedar-rapids.org
t.olson@cedar-rapids.org
ann.poe@cedar-rapids.org
p.loeffler@cedar-rapids.org
s.overland@cedar-rapids.org  
dalet@cedar-rapids.org
scott.olson@cedar-rapids.org
a.vanorny@cedar-rapids.org

**Comment by rpalakkal** [comment]
Hey! We have a mail for cedar rapids in the works. You can check it out here #1401 and leave any suggestions/additions you want to make
