### ISSUE TITLE
Defund the Police in Thousand Oaks, California

### ISSUE THREAD

**Issue by rlswanson** [defund12/defund12.org#1500]
To: AAdam@toaks.org, claudia4slowgrowth@roadrunner.com, BEngler@toaks.org, EJones@toaks.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Dear Thousand Oaks City Council,

My name is [NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the Thousand Oaks City Council adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police. Although the national focus in the last few weeks has been on big cities with a higher level of race and class diversity, Thousand Oaks also has a responsibility to address these issues and build a more accessible and just community.

In 2019, the City of Thousand Oaks allocated $30.5 million to our police system, the second highest expenditure in the budget at 16% of the total. This is compared to just $10.6 million allocated towards community development (5% of the budget). Within the community development budget, just $196,000 was spent on the Community Development Block Grant program and all funds spent by the city on housing services were reimbursed.

I demand that the City Council begin meaningfully defunding the Thousand Oaks Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, public transit and more. The 2018 shooting at the Borderline Bar & Grill demonstrates the police force is not able to keep the residents of this city safe and programs such as the above are necessary to prevent tragedies like it in the future. These services will promote a more connected community and help our neighbors get the help they need, before anyone gets hurt. I demand a budget that reflects the actual needs of Thousand Oaks residents. 

We must take a hard look at the ways that the current system fails to serve–and in fact actively harms–our city, and come together to rethink the ways we address public safety. A more restorative, humane and preventative form of justice will improve the health of our community, and benefit us all.

Thank you,
[YOUR NAME]
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by root2point0** [comment]
on it
