### ISSUE TITLE
 Fairfax, CA 

### ISSUE THREAD

**Issue by rethinkpolice** [defund12/defund12.org#1511]
[Defund Fairfax CA.docx](https://github.com/defund12/defund12.org/files/4773999/Defund.Fairfax.CA.docx)

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by wendywx** [comment]
copy and pasting for ease of editing:

------------------------------------------------

rgoddard@townoffairfax.org 
backerman@townoffairfax.org 
bcoler@townoffairfax.org
shellman@townoffairfax.org 
jreed@townoffairfax.org 
mgardner@townoffairfax.org

Dear Town Council Members, 

My name is{     }. As a citizen of our town of Fairfax CA, I strongly reject the proposed ‘placeholder’ budget for 2020-2021 which calls for 38.6% of the town’s total budget to be allocated towards police. I call for a fundamental redirection of public resources away from policing via the Fairfax Police Department and toward a new, full-spectrum range of public safety practices, rooted in community care. I write to you today to advocate for an end to business-as-usual budget-making and police-centered services. 

As Black people across the United States are disproportionally mistreated by and dying at the hands of law enforcement, our nation has been gripped by protests in all 50 states calling for rapid and meaningful change with regard to police behavior, an end to systemic racism and anti-Blackness, and immediate reform in how Black people are treated in America. As a predominantly white, affluent, and safe community, we here in Fairfax and Marin County must take a hard look at our own public safety practices and expenditures to ensure that they adequately reflect our values as a community. As a corollary, we must endeavor to examine the various reasons for our glaring lack of diversity, and determine the ways in which policing contributes to this ongoing problem in Marin County.

Additionally, as we’ve seen in recent months, many of our townspeople are living in a public health and economic disaster that can only be addressed through a robust response. Our town’s small businesses have been hard hit by the shutdown and many will not recover. The town budget must recognize that a business-as-usual budget that ignores the extraordinary times we are living in does not support public safety or wellbeing for our community. 

Our budget should reflect our values. I feel that the current proposed budget does not reflect this town’s values with its 38.6% proposed allocation to police. Police logs clearly indicate that the vast majority of calls answered by Fairfax Police would be better suited to other kinds of community services—specifically those that do not arrive equipped for use of force. In our safe community, armed policing should be the exception, not the rule. 

Therefore, I call on the Town Council to begin a creative and visionary budget proposal process that allows members of the community to participate in meaningful discussion and decision-making about how our taxes are being spent. I propose the following: the creation of a Town Council commission on alternatives to policing. This should include investments in existing community-based organizations as well as additional funding to support the creation of alternative responses to community needs and emergencies, including unarmed mediation and intervention teams, mental health experts, and restorative justice programs. 
 I oppose the Town’s budget proposal. **I call on the Town Council to recognize that it is time to shift funds from the Police Department into other areas of the town budget that truly promote public health and safety while fostering community-building.** I ask you to join in leading the development of a new vision for public safety in Fairfax.

Sincerely,

**Comment by rethinkpolice** [comment]
Hello, Thank you. We would like to hold off on publishing because we were
alerted to some problematic language. We will be back in touch with an
update. Thank you!

**Comment by rethinkpolice** [comment]
Hello, Thank you. We would like to hold off on publishing because we were alerted to some problematic language. We will be back in touch with an update. Thank you!

**Comment by rethinkpolice** [comment]
rgoddard@townoffairfax.org 
backerman@townoffairfax.org 
bcoler@townoffairfax.org
shellman@townoffairfax.org 
jreed@townoffairfax.org 
mgardner@townoffairfax.org


Dear Town Council Members, 

My name is{     }. As a citizen of our town of Fairfax CA, I strongly reject the proposed ‘placeholder’ budget for 2020-2021 which calls for 38.6% of the town’s total budget to be allocated towards police. This is unacceptable. I call for a fundamental redirection of public resources away from policing via the Fairfax Police Department and toward a new, full-spectrum range of public safety practices, rooted in anti-racist community care. I write to you today to advocate for an end to business-as-usual budget-making and police-centered services. 

As Black people across the United States are disproportionately mistreated by and dying at the hands of law enforcement, our nation has been gripped by protests in all 50 states calling for rapid and meaningful change with regard to police behavior, an end to systemic racism and anti-Blackness, and immediate reform in how Black people are treated in America. Marin County ranks as THE most racially unequal county in California and ranks number two in crime and justice-related racial inequality. We here in Fairfax, and Marin County at large, must address our public safety practices and expenditures, and how they affect ALL of our community members. We must address the various reasons for our glaring lack of diversity, and determine the ways in which budget allocation and policing contribute to this ongoing problem in Marin County. 

Our budget should show integrity with our values. The current proposed budget does not reflect this town’s values with its 38.6% proposed allocation to police. Police logs clearly indicate that the vast majority of calls answered by Fairfax Police would be better suited to other kinds of community services—specifically those that do not arrive equipped for use of force. Armed policing should be the exception, not the rule. 

Therefore, I call on the Town Council to begin a creative and visionary budget proposal process that allows members of the community to participate in meaningful discussion and decision-making about how our taxes are being spent. I propose the following: the creation of a Town Council commission on alternatives to policing, centered around anti-racism. This should include investments in existing community-based organizations as well as additional funding to support the creation of alternative responses to community needs and emergencies, including unarmed mediation and intervention teams, mental health experts, and restorative and transformational justice programs. 

I strongly oppose the Town’s budget proposal. **I call on the Town Council to recognize that it is time to shift funds from the Police Department into other areas of the town budget that truly promote public health and safety for all races, fostering community-building.** I ask you to join in leading the development of a new vision for public safety in Fairfax.

Sincerely,

**Comment by rethinkpolice** [comment]
updated email above. We are ready to get back in publication line! Thanks so much!

**Comment by mahrer** [comment]
Some minor edits below:

---

rgoddard@townoffairfax.org
backerman@townoffairfax.org
bcoler@townoffairfax.org
shellman@townoffairfax.org
jreed@townoffairfax.org
mgardner@townoffairfax.org

Dear Town Council Members,

My name is [YOUR NAME] and I am a resident of [TOWN/CITY]. I strongly reject the proposed ‘placeholder’ budget for 2020-2021 which calls for 38.6% of the town’s total budget to be allocated towards police. This is unacceptable. I call for a fundamental redirection of public resources away from policing via the Fairfax Police Department and toward a new, full-spectrum range of public safety practices, rooted in anti-racist community care. I write to you today to advocate for an end to business-as-usual budget-making and police-centered services.

As Black people across the United States are disproportionately mistreated by and dying at the hands of law enforcement, our nation has been gripped by protests in all 50 states calling for rapid and meaningful change with regard to police behavior, an end to systemic racism and anti-Blackness, and immediate reform in how Black people are treated in America. Marin County ranks as the most racially unequal county in California and ranks number two in crime and justice-related racial inequality. We here in Fairfax, and Marin County at large, must address our public safety practices and expenditures, and how they affect all of our community members. We must address the various reasons for our glaring lack of diversity, and determine the ways in which budget allocation and policing contribute to this ongoing problem in Marin County.

Our budget should show integrity with our values. The current proposed budget does not reflect this town’s values with its 38.6% proposed allocation to police. Police logs clearly indicate that the vast majority of calls answered by Fairfax Police would be better suited to other kinds of community services—specifically those that do not arrive equipped for use of force, such as healthcare, housing support, education, social programs, and youth services. Armed policing should be the exception, not the rule.

Therefore, I call on the Town Council to begin a creative and visionary budget proposal process that allows members of the community to participate in meaningful discussion and decision-making about how our taxes are being spent. I propose the following: the creation of a Town Council commission on alternatives to policing, centered around anti-racism. This should include investments in existing community-based organizations as well as additional funding to support the creation of alternative responses to community needs and emergencies, including unarmed mediation and intervention teams, mental health experts, and restorative and transformational justice programs.

I strongly oppose the Town’s budget proposal. I call on the Town Council to recognize that it is time to shift funds from the Police Department into other areas of the town budget that truly promote public health and safety for all races, fostering community-building. I ask you to join in leading the development of a new vision for public safety in Fairfax.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by rethinkpolice** [comment]
This looks great. Thank you!

**Comment by rethinkpolice** [comment]
Thank you so much for all your hard work! Is there a next step needed to get it listed on your IG?
