### ISSUE TITLE
Defund Napa Police Department

### ISSUE THREAD

**Issue by napawakeup** [defund12/defund12.org#1512]
Email Addresses: jtechel@cityofnapa.org, dgentry@cityofnapa.org, ssedgley@cityofnapa.org, lalessio@cityofnapa.org, mluros@cityofnapa.org

Email Content:

Mayor Techel and City Council members,

My name is [YOUR NAME], and I am a resident of Napa, California. These past weeks, our nation has been gripped by protests calling for rapid and meaningful reevaluation of the role of policing in our communities and an end to racism and anti-Blackness. 

As Black people across the United States are dying at the hands of law enforcement, our communities are mourning the deaths of George Floyd, tortured to death by Minneapolis police, and Breonna Taylor, an EMT killed by officers while asleep in her bed in Louisville, and Sean Monterrosa shot while kneeling by a police officer at a protest in Vallejo. Their names are added to a devastatingly long list of people who have been killed at the hands of law enforcement - it is time for us to make different decisions. We demand change in the operation of the criminal legal system, we demand that we take care of our community instead of criminalizing those amongst us who need help, and we demand that police are not the front line responders to every emergency or call for help.

In Napa, fulfilling these demands requires making dramatic changes in our city’s budget. Our budget should reflect our values. The current budget does not. I am writing to you today to demand that the Napa City Council invest in alternative responses to law enforcement that actually keep our community safe and healthy.

After looking at the Napa city budget, I am appalled to see that 32% of Napa’s general fund goes to Napa’s Police Department. I am writing to demand that the City Council adopts a budget that prioritizes community well-being and redirects funding away from the police.

With the rise of COVID-19, the rise of homelessness in our city and the ongoing problems of access to much needed resources around mental health, healthcare, housing and violence prevention, support for communities in need is necessary now, more than ever. We demand that the City Council defund the Napa Police Department.

We demand a budget that adequately and effectively meets the needs of at-risk Napa residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police.

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year.

Thank you for your time,

[YOUR NAME]

[ADDRESS]

[EMAIL]

[PHONE NUMBER]

**Comment by serifluous** [comment]
Hi @napawakeup, thanks for your request to add Napa to the site! We have an open request at issue #1144. If you’d like to add to or edit the messaging, please visit that issue.

Thank you!
