### ISSUE TITLE
Adding Plano, Texas

### ISSUE THREAD

**Issue by ambylauren** [defund12/defund12.org#1533]
citycouncil@plano.gov
mayor@plano.gov
kayciprince@plano.gov
aricciardelli@plano.gov
mariatu@plano.gov
rickgrady@plano.gov
shelbywilliams@plano.gov
ricksmith@plano.gov
lilybao@plano.gov
 deedee@plano.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
(Don't forget to replace the [x]'s with your information!)
To Mayor Harry LaRosiliere and the city council,
My name is [INSERT NAME] and I am a resident of [YOUR NEIGHBORHOOD]. I am writing to demand that the Plano City Council adopt a budget that prioritizes community wellbeing, and redirects funding away from the police.
Referencing the most recent city budget, a staggering 78 million dollars [1] was allocated to the Plano police department. The fact that the expanding use of incarceration in Texas disproportionately affects the state’s non-White citizens remains undeniable. Additionally, prison related spending by the state has had a profound and damaging impact on state spending and on the economic vitality of Texas’s communities of color.
 [2]. The current city budget is communicating that law enforcement is almost 17 times[1] more important than community outreach and I do not believe that this aligns with most residents values.
I am demanding that we re-allocate funds from the police department to programs proven to more effectively promote a safe and equitable community and to address economic disparities. These programs include community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Plano residents.
History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city. I strongly urge you to remove funding from police departments and reallocate it to social services that make a meaningful difference for the citizens of Plano.
Sincerely, [YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]
[1] https://www.plano.gov/DocumentCenter/View/40521/2019-20-Program-of-Service
[2] http://www.justicepolicy.org/images/upload/05-02_rep_txraceimprisonment_ac-rd.pdf

**Comment by todd-m** [comment]
Thanks for submitting your city to defund12.org, @ambylauren! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment]
I’m reviewing
