### ISSUE TITLE
Defund Medford, OR Police and Jackson County Sheriff Dept

### ISSUE THREAD

**Issue by rewsauce16** [defund12/defund12.org#1534]
Fuck 12 defund all these bastards, Jackson is the most racist county in Oregon, stolen Klamath land.

**Comment by skullface** [comment]
Hi @rewsauce16, thanks for your interest in adding Medford and Jackson to the website. I appreciate your passion! But emails on defund12.org are all written by community members. To add your community, you **must** provide:

- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city/county._**

Follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!
