### ISSUE TITLE
Adding Scottsdale AZ

### ISSUE THREAD

**Issue by ambylauren** [defund12/defund12.org#1535]
citycouncil@scottsdaleaz.gov
jlane@scottsdaleaz.gov
sklapp@scottsdaleaz.gov
vkorte@scottsdaleaz.gov
klittlefield@scottsdaleaz.gov
lmilhaven@scottsdaleaz.gov
gphillips@scottsdaleaz.gov
SWhitehead@Scottsdaleaz.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
(Don't forget to replace the [x]'s with your information!)
To Mayor-President Jim Lane and the Scottsdale City Council:
My name is [INSERT NAME] and I am a resident of [YOUR NEIGHBORHOOD]. I am writing to demand that the Scottsdale City Council adopt a budget that prioritizes community wellbeing, and redirects funding away from the police.
Referencing the most recent city budget, a staggering 106 million dollars [1] was allocated to the Scottsdale police department. Hispanic people comprise 31 percent of Arizona’s resident population and 32 percent of arrests for marijuana possession, but almost 60 percent of the people admitted to prison for that crime
 [2]. The current city budget is communicating that law enforcement (1/3 of the budget) is almost 3 times[1] more important than community outreach and I do not believe that this aligns with most residents values. Scottsdale’s culture along with the city value of “listen, communicate, and take action” stresses open communication. [1]
I am demanding that we re-allocate funds from the police department to programs proven to more effectively promote a safe and equitable community and to address economic disparities. These programs include community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Scottsdale residents.
History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city. I strongly urge you to remove funding from police departments and reallocate it to social services that make a meaningful difference for the citizens of Scottsdale.
Sincerely, [YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

[1] https://www.scottsdaleaz.gov/Assets/ScottsdaleAZ/Finance/Archive/FY+2019-20/FY2019-20Volume1BudgetSummary.pdf
[2]
https://www.google.ca/amp/s/amp.azcentral.com/amp/2006408002

**Comment by todd-m** [comment]
Thanks for submitting your city to defund12.org, @ambylauren! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment]
I’m reviewing
