### ISSUE TITLE
Add Piscataway, NJ

### ISSUE THREAD

**Issue by meli1087** [defund12/defund12.org#1537]
# Feature request

⚠️ If you are looking to add a new city to the site, [use the email request template](https://github.com/defund12/defund12.org/issues/new?assignees=&labels=new-request&template=EMAIL_REQUEST.md&title=Add%20%5BCITY%2C%20STATE%5D). Thank you!

---

Hey, we’re so excited you have a way to improve defund12.org! 😍

### Before you file the request
Please search to see if your idea has been discussed before.

If you find your feature request already exists, use the Github’s “reactions” feature in place of a "+1" comment. Feel free to make relevant comments to further discussion in the issue. 👍 `upvote` 👎 `downvote`

### Feature request guidelines
Address the following in your issue.

* What is the use case for the suggested feature?
* Does the feature fit the scope and goals of defund12.org? We are focused on making it as easy as possible to contact local elected officials about police defunding.
* Provide as much detail and context as possible about how the feature will be used. Being specific helps us envision the feature and make it a reality.
* Can you lead the development of the feature?

**Comment by mahrer** [comment]
@meli1087 thanks for your interest in adding your city to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Subject line for the email
- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!
