### ISSUE TITLE
Add Jefferson County, Colorado

### ISSUE THREAD

**Issue by apiperwhite** [defund12/defund12.org#1539]
To 
County Commissioner Lesley Dahlkemper, ldahlkem@jeffco.us
County Commissioner Libby Szabo, commish1@jeffco.us
County Commissioner Casey Tighe, commish2@jeffco.us 

Dear Jefferson County Board of County Commissioners:

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY].
I am writing to demand a reallocation of funding from the Jefferson County Sheriff’s Department to social and public programming for our communities. With record unemployment and a seemingly intractable pattern of abuse and unequal treatment by police, our county needs a budget that adequately and effectively meets the needs of at-risk JeffCo residents.

In the 2020 Adopted Budget, $113,017,045 was allocated for policing (18.7% of the general fund budget). This is in addition to separate funding for city police departments, such as Golden (police budget of $10,734,451). Meanwhile, only $98,988,725 was allocated for public health and human services combined, an expansive category covering health, housing stability, economic development, and more. The disproportionate budget allocated to policing in our county is unacceptable, and I demand that the Board remedy this gross display of priorities. You must support a budget that supports social equity in our community. I urge you to advocate for a meaningful reallocation of the city's expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.

It is your duty to represent your constituents. I am urging you to advocate for revision of the Jefferson County budget for the upcoming fiscal year to reflect the decades of research showing that education and social programs better promote the safety of a city than policing.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by brickaney** [comment]
@mahrer Please move forward. I’ve completed my review.

Edits made: minor edits and added a reference to the budget.

“To:
ldahlkem@jeffco.us
commish1@jeffco.us
commish2@jeffco.us

Dear Jefferson County Board of County Commissioners:

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY].
I am writing to demand a reallocation of funding from the Jefferson County Sheriff’s Department to social and public programming for our communities. With record unemployment and a seemingly intractable pattern of abuse and unequal treatment by police, our county needs a budget that adequately and effectively meets the needs of at-risk JeffCo residents.

In the 2020 Adopted Budget, $113,017,045 was allocated for policing (18.7% of the general fund budget). This is in addition to separate funding for city police departments, such as Golden (police budget of $10,734,451) [1]. Meanwhile, only $98,988,725 was allocated for public health and human services combined, an expansive category covering health, housing stability, economic development, and more. The disproportionate budget allocated to policing in our county is unacceptable, and I demand that the Board remedy this gross display of priorities. I demand a budget that supports social equity in our community. I urge you to advocate for a meaningful reallocation of the city's expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.

I am urging you to advocate for revision of the Jefferson County budget for the upcoming fiscal year to reflect the decades of research showing that education and social programs better promote the safety of a city than policing.

Thank you for your time,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

[1] https://stories.opengov.com/jeffersoncountyco/published/P4I5YEi4x

**Comment by todd-m** [comment]
on it
