### ISSUE TITLE
Switching to Gatsby

### ISSUE THREAD

**Issue by Ceshion** [defund12/defund12.org#1549]
Hello everyone!

As you probably already know, we are in the process of reworking the site to run on Gatsby/React. The conversion is almost completed, but this ticket will track the remaining items and anything that comes up during deployment.

---

## Completed so far:
- Structural reworking of the HTML to fit into components (we could break these down further still, but the idea was to keep everything close to the Jekyll version for now)
- Querying against the email markdown files through GraphQL to generate pages for them
- Changes to _config.yml to change snake_case to camelCase, as well as a siteConfig schema for that file in GraphQL
- Moving style loading from main.css to gatsby-browser.js
- Additions to linting and test framework to support Typescript+JSX
- Cleaning up directories, files, and content related to Jekyll

## What's left to do:
- Review the 404 page design
- Add tests especially for cases that are missing data, or have invalid data.
- Adjust react-select's styling to be consistent with the rest of the site (including dark mode)

### PR: #1493

**Comment by bingbongle** [comment]
This is phenomenal. IMO, only the react-select styling should block us from merging and the other two are nice-to-haves.
