### ISSUE TITLE
Add Chattanooga TN

### ISSUE THREAD

**Issue by ambylauren** [defund12/defund12.org#1561]
cchenderson@chattanooga.gov
jmitchell@chattanooga.gov
kensmith@chattanooga.gov
dledford@chattanooga.gov
rgilbert@chattanooga.gov
cberz@chattanooga.gov
eoglesbyjr@chattanooga.gov
abyrd@chattanooga.gov
dcoonrod@chattanooga.gov
councilclerk@chattanooga.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
(Don't forget to replace the [x]'s with your information!)
To Mayor-President Andy Berke and the Chattanooga City Council:
My name is [INSERT NAME] and I am a resident of [YOUR NEIGHBORHOOD]. I am writing to demand that the Chatanooga City Council adopt a budget that prioritizes community wellbeing, and redirects funding away from the police.
Referencing the most recent city budget, a staggering 72 million dollars [1] was allocated to the Chatanooga police department. That is 27 percent of the yearly budget, whereas community based programs  take up less than one percent of the yearly budget.
 The current city budget is communicating that law enforcement is almost 27 times[1] more important than community outreach and I do not believe that this aligns with most residents values. Chattanooga’s  culture along with the city value of an "innovative form of government " [1] are being dismissed by funding the police department so heavily. African Americans make up 24.3 percent of Tennessee’s total population, but 45 percent of Tennessee’s felony inmate population. [2]
I am demanding that we re-allocate funds from the police department to programs proven to more effectively promote a safe and equitable community and to address economic disparities. Pledging to review the city’s use-of-force policies is not enough. These programs include community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Chattanooga residents.
History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city. I strongly urge you to remove funding from police departments and reallocate it to social services that make a meaningful difference for the citizens of Chatanooga.
Sincerely, [YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

[1] http://budget.chattanooga.gov/#!/year/2021/operating/0/service/Public+Safety/0/department/Police/0/program
[2] https://wdef.com/2018/02/07/forum-takes-look-mass-incarceration-locally-nationally/

**Comment by mahrer** [comment]
Hi @ambylauren, thanks for your request to add Chattanooga to the site! We have an open request at #1263. If you’d like to add to or edit the messaging, please visit that issue.
Thank you!
