### ISSUE TITLE
Add Oxford, OH

### ISSUE THREAD

**Issue by defundoxford** [defund12/defund12.org#1562]
To: mikesmith@cityofoxford.org, wsnavely@cityofoxford.org, jbracken@cityofoxford.org, gellerbe@cityofoxford.org, dprytherch@cityofoxford.org, craghu@cityofoxford.org, esouthard@cityofoxford.org

Subject: [***INSERT UNIQUE SUBJECT LINE***]

Message: (Don't forget to replace the [X]'s with your information!)

Dear Oxford City Council,

Hello, my name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY]. I am writing to demand that the Oxford City Council adopt a city budget that prioritizes community well-being and redirects funding away from the police.

In 2020, the City of Oxford is projected to allocate $5.7 million to Security of Persons and Property (32.4% of the budget), compared to just $145,000 allocated toward Public Health and Welfare (0.8% of the budget). Put another way, the City of Oxford is projected to spend nearly 40 times as much on policing as it does on public health and welfare. Excluding advances and transfers, the FY2020 budget allocates more money to policing than to all other expenses (i.e., general government, community environment, leisure activities, and public health and welfare) combined.

I demand that the City Council begin meaningfully defunding the Oxford Police Department and reallocating those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Oxford residents.

History has shown us that police “reform” is not enough. We must take a hard look at the ways in which the system currently in place fails to serve -- and, in fact, actively harms -- our community, and come together to reimagine the role of police in our city.

I know many of you feel strongly about racial justice and equity, as seen by Mayor Smith and others’ participation in Oxford’s vigil for George Floyd and endorsement of “transformative change” toward making Oxford “a community devoted to equity, diversity, and inclusion.” You must be prepared to put actions behind those words.

Individual solutions will not fix systemic problems. It is time for Oxford, its leaders, and its residents to create a more equitable city for all of us. Have the moral clarity to create a budget that invests in communities instead of investing in institutions rooted in racism, punishment, and oppression.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

-----
Sources:
- City of Oxford’s 2020 Online Budget document, page 91 (Note that the pie graph contains an incorrect percentage for security spending.)
[https://www.cityofoxford.org/sites/default/files/finance/2020%20Budget%20Final.pdf](url)
- [https://www.cityofoxford.org/news/2020/06/community-statement-against-hate-racism](url)

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment]
I’m reviewing

**Comment by todd-m** [comment]
on it
