### ISSUE TITLE
Add Murfreesboro TN

### ISSUE THREAD

**Issue by ambylauren** [defund12/defund12.org#1563]
smcfarland@murfreesborotn.gov
bshacklett@murfreesborotn.gov
esmotherman@murfreesborotn.gov
kwade@murfreesborotn.gov
mscalesharris@murfreesborotn.gov
rlalance@murfreesborotn.gov
rmartin@murfreesborotn.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
(Don't forget to replace the [x]'s with your information!)
To Mayor-President Shane McFarland and the Murfreesboro City Council:
My name is [INSERT NAME] and I am a resident of [YOUR NEIGHBORHOOD]. I am writing to demand that the Murfreesboro City Council adopt a budget that prioritizes community wellbeing, and redirects funding away from the police.
Referencing the most recent city budget, a staggering 30.9 million dollars [1] was allocated to the Murfreesboro police department. That is 18 percent of the yearly budget, whereas community based programs  take up less than one percent of the yearly budget.
 The current city budget is communicating that law enforcement is almost 30 times[1] more important than community outreach and I do not believe that this aligns with most residents values. The City of Murfreesboro strives to provide a safe, progressive, and healthy community for its citizens by employing dedicated individuals who work together to ensure the highest possible quality of life. [2] This statement cannot be true when African Americans make up 24.3 percent of Tennessee’s total population, but 45 percent of Tennessee’s felony inmate population. [3]
I am demanding that we re-allocate funds from the police department to programs proven to more effectively promote a safe and equitable community and to address economic disparities. Pledging to review the city’s use-of-force policies is not enough. These programs include community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Murfreesboro residents.
History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city. I strongly urge you to remove funding from police departments and reallocate it to social services that make a meaningful difference for the citizens of Murfreesboro.
Sincerely, [YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

[1] https://www.murfreesborotn.gov/DocumentCenter/View/8157/FY-2019-Operating-Budget?bidId=
[2] https://www.murfreesborotn.gov/496/City-Council
[3] https://wdef.com/2018/02/07/forum-takes-look-mass-incarceration-locally-nationally/

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment]
I’m reviewing

**Comment by todd-m** [comment]
on it
