### ISSUE TITLE
Collier County (Naples, Marco Island, Immokalee) has an extremely bloated funding proposal for the sheriffs department while neglecting community necessities. Please help. 

### ISSUE THREAD

**Issue by Arielraf** [defund12/defund12.org#1565]
Here are the county commissioners: 
Donna.Fiala@CollierCountyFL.Gov
Andy.Solis@CollierCountyFL.Gov
Burt.Saunders@CollierCountyFL.Gov
Penny.Taylor@CollierCountyFL.Gov
Bill.McDaniel@colliercountyfl.gov

Here is the budgeting decision at stake: 

42% of the collier county budget for 2021 is being spent on law enforcement and only 4% is going towards emergency services, 0.39% towards the health department and .08% towards veteran services. 

In Collier County we have an absurd amount of police officers. We are notorious for that. We are also known for having one of the highest economic disparities and one of the largest spikes in Covid 19 which disproportionately affects the Immokalee farmworkers who have little to no access to healthcare. 

Here is the email that I have created for example but I believe it needs some tuning up: 

I am a resident of Collier County and I am writing to demand that the county commissioners adopt a budget that prioritizes community wellbeing and redirects funding away from the police.

I DEMAND THAT YOU, MY LOCAL OFFICIALS, WILL:

- Vote no on all increases to police budgets.
- Vote yes to decrease police spending and budgets.
- Vote yes to increase spending on health care, education and community programs that keep us safe.

We need to defund the Collier County Police Department. We need a budget that adequately and effectively meets the needs of Collier County residents during the pandemic and well past it. We need a budget that supports our communities. 

42% of the collier county budget for 2021 is being spent on law enforcement and only 4% is going towards emergency services, 0.39% towards the health department and .08% towards veteran services. 

In the time of COVID-19, and specifically in Collier county where we have seen a huge spike in cases, there is no excuse for the amount of funds to go towards law enforcement proposed for the 2020-2021 fiscal year while neglecting the need to fund the health department, veteran services, mental health services and emergency services.

We demand that the County Commissioners meaningfully defund the CCPD. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk Collier County residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing.

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by Arielraf** [comment]
Oh that’s great news! Thanks y’all. I really look forward to spreading this
email throughout the community.

**Comment by mahrer** [comment]
Edits below:

---

Send to:
Donna.Fiala@CollierCountyFL.Gov
Andy.Solis@CollierCountyFL.Gov
Burt.Saunders@CollierCountyFL.Gov
Penny.Taylor@CollierCountyFL.Gov
Bill.McDaniel@colliercountyfl.gov

Message:

Dear County Commissioners,

I am a resident of Collier County and I am writing to demand that the County Commissioners adopt a budget that prioritizes community wellbeing and redirects funding away from the police.

42% of the proposed FY2020-2021 Collier budget is being spent on law enforcement, while only 4% is going towards emergency services, 0.39% towards the health department, and .08% towards veteran services. In Collier County, we are notorious for having both an absurd amount of police officers as well as one of the largest spikes in COVID-19, which disproportionately affects the Immokalee farmworkers who have little to no access to healthcare. There is no excuse for overfunding our law enforcement while neglecting the health department, veteran services, mental health services and emergency services.

I demand that you, my County officials, will:
- Vote no on all increases to police budgets.
- Vote yes to decrease police spending and budgets.
- Vote yes to increase spending on health care, education and community programs that keep us safe.
- Defund the Collier County Police Department. We need a budget that adequately and effectively meets the needs of Collier County residents during the pandemic and well past it. We need a budget that supports our communities.

I demand that the County Commissioners meaningfully defund the CCPD. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk Collier County residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by Arielraf** [comment]
This is great. What do I do next?
