### ISSUE TITLE
Add Springfield, MA

### ISSUE THREAD

**Issue by ariabracci** [defund12/defund12.org#1568]
skacoyannakis@springfieldcityhall.com
kmickiewicz@springfieldcityhall.com
LClick@springfieldcityhall.com
twhitfield@springfieldcityhall.com
jhurst@springfieldcityhall.com
Scurran@springfieldcityhall.com
kwalsh@springfieldcityhall.com
jlederman@springfieldcityhall.com
agomez@springfieldcityhall.com
mfenton@springfieldcityhall.com
melvinspeaks@msn.com
malomiajane@yahoo.com
Marcusjw88@gmail.com
Vdavila@springfieldcityhall.com
timallen1951@hotmail.com
oramos108@aol.com

***Fill in [BRACKETS] with your info***

Subject: [SUBJECT LINE]
To Mayor Sarno and the Springfield City Council:

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD]. I am writing to ask that the Springfield City Council redirect funding away from the police to support more proactive forms of wellness for the community.

First, we need greater transparency on spending. Within the expenses of the housing code department in the FY20 budget, "homeless services" receives $130,402 [1] and is described in only slightly more detail as "homeless outreach services". To whom are you reaching out? Whom benefits? Do any of the funds subsidize housing? If not, how much more would be needed to do so? In short, is any of this money being used to actively identify the causes of homelessness and mitigate them?

Similarly, in the section for the police department's "Uniform Divisions", which is bolstered by an exhaustive list of "highlights" (and which is slated to receive, in contrast to the budget for "homeless services", over $29 million in FY20) one such duty is to "perform preventive and high-visibility patrols around identified crime hot spots" [1]. Amidst the pages and pages of numbers and duties, I find neither success rates nor specific actions for such patrols.

Second, I ask you to consider what health truly looks like. According to the Vera Institute of Justice, almost 15% of the arrests made in the U.S. annually are for "drug abuse" [2]—where, in the dense yet unspecific lists of police department "highlights" is the duty to help those who abuse drugs by aiding them in recovery, so that they are less likely to continue such abuse (an act, I should add, that is not inherently dangerous to the public, unlike rape, which only constitutes 0.22% of arrests annually [2])?

So, lastly, imagine a transformed city. Imagine a city with more affordable housing, shelter availability, tailored addiction treatment, after-school programs, and job acquisition assistance. It could be Springfield, a city that, in your words, emphasizes "public education, public safety, healthy neighborhoods, and community services", at least as is outlined in your note upon releasing the city's FY20 budget [3].

It begins now.

Sincerely, [YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

[1] Fiscal Year 2020 Adopted Budget: https://www.springfield-ma.gov/finance/fileadmin/budget/2020/Springfield_FY20_Adopted_Budget-compressed.pdf
[2] "Vera: How many arrests are made annually, and for what?": https://arresttrends.vera.org/arrests
[3] "Fiscal Year 2020 Adopted Budget, A Message From Mayor Domenic Sarno": https://www.springfield-ma.gov/finance/index.php?id=omb#:~:text=Fiscal%20Year%202020%20Adopted%20Budget&text=To%20the%20beloved%20citizens%20of,over%20the%20FY19%20Adopted%20Budget.

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.
