### ISSUE TITLE
Add Bellingham, WA

### ISSUE THREAD

**Issue by danj1997** [defund12/defund12.org#1582]

**Comment by wpalchemist** [comment]
+1

**Comment by mahrer** [comment]
Hi @danj1997 and @wpalchemist, thanks for your interest in adding Bellingham to the website. As a Washingtonian I would also love to see it up there! However, emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Subject line for the email
- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!

**Comment by wpalchemist** [comment]
I will collect this information within the next day or two.

**Comment by mahrer** [comment]
@wpalchemist awesome! Would you mind opening a new issue when you have a template ready? 

I see the link above to our style guide is broken, so here's a new link for you:
https://github.com/defund12/defund12.org/blob/master/EMAIL_TEMPLATE_STYLE_GUIDE.md
