### ISSUE TITLE
Letter to the Board of Broward County Commissioners and County Administrator, FL

### ISSUE THREAD

**Issue by rakf713** [defund12/defund12.org#1588]
nrich@broward.org <nrich@broward.org>;mbogen@broward.org <mbogen@broward.org>; mudine@broward.org <mudine@broward.org>; lfisher@broward.org; bfurr@broward.org; tryan@broward.org; sgeller@broward.org <sgeller@broward.org>; bsharief@broward.org; dholness@broward.org; bhenry@broward.org 

To the Board of Broward County Commissioners and County Administrator Henry,

My name is [YOUR NAME] and I am a resident of [YOUR CITY], Florida. I request that the County Commission support our community and hear our call for:

-Efforts to defund and de-escalate the Broward County Sheriff’s Office and to reallocate money to programs and county-led initiatives that support education, rehabilitation, public health, and community-oriented activities.
-Rejection of expanded and militarized police budgets.
-Efforts to improve oversight and independent investigations to hold individual law enforcement officers and police departments accountable for misconduct.

Last May, Sheriff Tony asked for a 5.9% increase for the upcoming fiscal year, proposing an annual budget of $545.6 million, with more than 76% of that total or roughly $420 million being used to pay for personnel services. This year, he is again asking for a 5.2% increase, making the requested budget $571.3 million. 48% of that budget goes towards detention and law enforcement services, while only 4.3% goes towards community programs. Combined with federal and municipal-level funding, the full financial cost of policing in our area dramatically dwarfs support for resources that would enrich and protect Florida communities such as after-school youth programs, mental health and wellness, affordable housing, substance abuse prevention and treatment, and more.

I urge you to reimagine the way the justice system works in Broward County. This means investing in our community’s long-term health and prosperity and, in doing so, decreasing the demand for BSO. Until Broward County does this, we are failing to serve communities of color.

We urge you to adopt a budget that prioritizes community well-being through education, health care, and social services while redirecting funding away from police and incarceration.

As one of your constituents, I’m asking you to take immediate, concrete action on this issue. I will be sure to tell my friends, family, and neighbors about your response.

Sincerely, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE ]

**Comment by mahrer** [comment]
Thank you for submitting to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by mahrer** [comment]
Some minor edits below:

---

nrich@broward.org nrich@broward.org;mbogen@broward.org mbogen@broward.org; mudine@broward.org mudine@broward.org; lfisher@broward.org; bfurr@broward.org; tryan@broward.org; sgeller@broward.org sgeller@broward.org; bsharief@broward.org; dholness@broward.org; bhenry@broward.org

To the Board of Broward County Commissioners and County Administrator Henry,

My name is [YOUR NAME] and I am a resident of [YOUR CITY], Florida. I request that the County Commission support our community by:

-Defunding and de-escalating the police and sheriff department, and reallocating money to programs and county-led initiatives that support education, rehabilitation, public health, and community-oriented activities.
-Rejecting expanded and militarized police budgets.
-Improving oversight and independent investigations to hold individual law enforcement officers and police departments accountable for misconduct.

Last May, Sheriff Tony asked for a 5.9% increase for the upcoming fiscal year, proposing an annual budget of $545.6 million, with more than 76% of that total or roughly $420 million being used to pay for personnel services. Combined with federal and municipal-level funding, the full financial cost of policing in our area dramatically dwarfs support for resources that would enrich and protect Florida communities, such as after-school youth programs, mental health and wellness, affordable housing, substance abuse prevention and treatment, and more.

I urge you to reimagine the way the justice system works in Broward County. This means investing in our community’s long-term health and prosperity and, in doing so, decreasing the demand for such an expensive police force. Until Broward County does this, we are failing to serve communities of color.

I urge you to adopt a budget that prioritizes community well-being through education, health care, and social services while redirecting funding away from police and incarceration. As one of your constituents, I’m asking you to take immediate, concrete action on this issue. I will be sure to tell my friends, family, and neighbors about your response.

Sincerely, 
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE ]

**Comment by rakf713** [comment]
I just added a few more details! (re: the budget)

**Comment by mahrer** [comment]
No prob @rakf713! Final edits below:

---

nrich@broward.org nrich@broward.org;mbogen@broward.org mbogen@broward.org; mudine@broward.org mudine@broward.org; lfisher@broward.org; bfurr@broward.org; tryan@broward.org; sgeller@broward.org sgeller@broward.org; bsharief@broward.org; dholness@broward.org; bhenry@broward.org

To the Board of Broward County Commissioners and County Administrator Henry,

My name is [YOUR NAME] and I am a resident of [YOUR CITY], Florida. I request that the County Commission support our community by:

-Defunding and de-escalating the police and sheriff department, and reallocating money to programs and county-led initiatives that support education, rehabilitation, public health, and community-oriented activities.
-Rejecting expanded and militarized police budgets.
-Improving oversight and independent investigations to hold individual law enforcement officers and police departments accountable for misconduct.

Last May, Sheriff Tony asked for a 5.9% increase for the upcoming fiscal year, proposing an annual budget of $545.6 million, with more than 76% of that total or roughly $420 million being used to pay for personnel services. This year, he is again asking for a 5.2% increase, making the requested budget $571.3 million. 48% of that budget goes towards detention and law enforcement services, while only 4.3% goes towards community programs. Combined with federal and municipal-level funding, the full financial cost of policing in our area dramatically dwarfs support for resources that would enrich and protect Florida communities such as after-school youth programs, mental health and wellness, affordable housing, substance abuse prevention and treatment, and more.

I urge you to reimagine the way the justice system works in Broward County. This means investing in our community’s long-term health and prosperity and, in doing so, decreasing the demand for such an expensive police force. Until Broward County does this, we are failing to serve communities of color.

I urge you to adopt a budget that prioritizes community well-being through education, health care, and social services while redirecting funding away from police and incarceration. As one of your constituents, I’m asking you to take immediate, concrete action on this issue. I will be sure to tell my friends, family, and neighbors about your response.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE ]

**Comment by rakf713** [comment]
Great! In the beginning, I also changed it to say : "-Efforts to defund and de-escalate the Broward County Sheriff’s Office" since this letter is specifically for the County Commissioners.

**Comment by mahrer** [comment]
Okay. Here's the final version then:

---

nrich@broward.org nrich@broward.org;mbogen@broward.org mbogen@broward.org; mudine@broward.org mudine@broward.org; lfisher@broward.org; bfurr@broward.org; tryan@broward.org; sgeller@broward.org sgeller@broward.org; bsharief@broward.org; dholness@broward.org; bhenry@broward.org

To the Board of Broward County Commissioners and County Administrator Henry,

My name is [YOUR NAME] and I am a resident of [YOUR CITY], Florida. I request that the County Commission support our community by:

-Defunding and de-escalating the Broward County Sheriff’s Office, and reallocating money to programs and county-led initiatives that support education, rehabilitation, public health, and community-oriented activities.
-Rejecting expanded and militarized police budgets.
-Improving oversight and independent investigations to hold individual law enforcement officers and police departments accountable for misconduct.

Last May, Sheriff Tony asked for a 5.9% increase for the upcoming fiscal year, proposing an annual budget of $545.6 million, with more than 76% of that total or roughly $420 million being used to pay for personnel services. This year, he is again asking for a 5.2% increase, making the requested budget $571.3 million. 48% of that budget goes towards detention and law enforcement services, while only 4.3% goes towards community programs. Combined with federal and municipal-level funding, the full financial cost of policing in our area dramatically dwarfs support for resources that would enrich and protect Florida communities such as after-school youth programs, mental health and wellness, affordable housing, substance abuse prevention and treatment, and more.

I urge you to reimagine the way the justice system works in Broward County. This means investing in our community’s long-term health and prosperity and, in doing so, decreasing the demand for such an expensive police force. Until Broward County does this, we are failing to serve communities of color.

I urge you to adopt a budget that prioritizes community well-being through education, health care, and social services while redirecting funding away from police and incarceration. As one of your constituents, I’m asking you to take immediate, concrete action on this issue. I will be sure to tell my friends, family, and neighbors about your response.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE ]

**Comment by rakf713** [comment]
Great! Thanks!
