### ISSUE TITLE
Corona, CA

### ISSUE THREAD

**Issue by concernedsebster** [defund12/defund12.org#1590]
To: Jim.Steiner@CoronaCA.gov, Jacque.Casillas@CoronaCA.gov, Yolanda.Carrillo@CoronaCA.gov, Jason.Scott@CoronaCA.gov, Wes.Speake@CoronaCA.gov, Chad.Willardson@CoronaCA.gov, CityClerk@CoronaCA.gov

Subject: [Commit to Vote No on Proposed FY21 Budget / Defund the CPD]

Dear Corona City Council Members, 

My name is [YOUR NAME] and I am a resident of [CITY, STATE]. The city’s proposed budget for Fiscal Year 2021 increases the CPD budget by over $2M, reinforcing a historically-disproportionate allocation of funds towards this department (i.e. _32.86%_ of the general fund went towards the CPD in FY2020). Also, the proposed budgets for Community Development, Public Works, and Library & Recreation are either cut or marginally increased. 

I am emailing you today to demand that you vote **no** on the FY21 proposed budget. Furthermore, I urge you to pressure the office of the mayor towards an ethical and equal reallocation of the Corona general expenditure budgets away from the CPD and towards educational programs, social services, and community development programs effective at the beginning of FY21.

The proposed CPD budget for FY21 is larger than community development, library & recreation, and public works _combined_. I am asking that city officials strategically reallocate funds and responsibility away from police and towards community-based models of safety, support, and prevention. 

Thank you, 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by erinb223** [comment]
### **Edited Email Copy**
Swapped paragraphs 1 and 2 for a more logical argument flow. Made a few minor grammatical edits.

------

To: Jim.Steiner@CoronaCA.gov, Jacque.Casillas@CoronaCA.gov, Yolanda.Carrillo@CoronaCA.gov, Jason.Scott@CoronaCA.gov, Wes.Speake@CoronaCA.gov, Chad.Willardson@CoronaCA.gov, CityClerk@CoronaCA.gov

Subject: [Commit to Vote No on Proposed FY21 Budget / Defund the CPD]

Dear Corona City Council Members,

My name is [YOUR NAME] and I am a resident of Corona. I am emailing you today to demand that you vote no on the FY21 proposed budget. Furthermore, I urge you to pressure the office of the mayor towards an ethical and equal reallocation of the Corona general expenditure budgets away from the CPD and towards educational programs, social services, and community development programs effective at the beginning of FY21.

The city’s proposed budget for Fiscal Year 2021 increases the CPD budget by over $2M, reinforcing a historically-disproportionate allocation of funds towards this department (i.e. 32.86% of the general fund went towards the CPD in FY2020). Also, the proposed budgets for Community Development, Public Works, and Library & Recreation are either cut or marginally increased.

The proposed CPD budget for FY21 is larger than Community Development, Library & Recreation, and Public Works combined. I am asking that city officials strategically reallocate funds and responsibility away from police and towards community-based models of safety, support, and prevention.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by erinb223** [comment]
This is ready for pr
