### ISSUE TITLE
Add Brentwood, Ca- 94513 

### ISSUE THREAD

**Issue by Citlali1305** [defund12/defund12.org#1591]
To: 
City Attorney: CityAttorney@brentwoodca.gov
City Clerk: CityClerk@brentwoodca.gov
Current Mayor: btaylor@brentwoodca.gov
Vice Mayor: jbryant@brentwoodca.gov
City Council: jrodriguez@brentwoodca.gov krarey@brentwoodca.gov cstaton@brentwoodca.gov CityCouncil@brentwoodca.gov

[UNIQUE SUBJECT LINE]

Dear Brentwood City Council,

My name is [first and last name] and I am a resident of Brentwood. I am writing to demand that the Brentwood City Council adopt a budget that redirects funding away from the police and prioritizes our community's wellbeing.

In the 2019-2020 budget, the City of Brentwood allocated $ 27,878,876 dollars to our police system, in comparison $ 5,708,738 dollars directed towards community development. This disparity is unacceptable. I join the calls of those across the country and demand that City Council defund the Brentwood Police Department and re-allocate those funds towards programs that promote a safer and more equitable community, such as mental health services, affordable housing, youth programs, and education.

As members of the City Council, it is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year, in favor of a budget that reflects the actual needs of Brentwood residents. As history has shown us, "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve, and in fact actively harms our community, and come together to reimagine the role of police in our city.

Thank you for your time, 
[Your Name here]
[Email Address] 

Sources (removed once City is accepted): 

I used the defund12 Antioch email as a template for this email here is the link: https://defund12.org/antioch 
I got permission from the writer 
![Antioch permission 2](https://user-images.githubusercontent.com/66972038/84725247-06329480-af3f-11ea-994d-ca0078638a3d.png)
![Antioch permission](https://user-images.githubusercontent.com/66972038/84725249-06cb2b00-af3f-11ea-8e3c-a29333f899eb.png)

I got the budget information from Brentwood's website: https://www.brentwoodca.gov/gov/finance/docs/opbudgets.asp 
Clicked on "FY 2020/21 - 2021/22 DRAFT" 

where I got the budget information: 
Page 127: Community Development budget for 2019/2020 
Page 152: Police Budget 2019/2020
[20-21 Full Budget FINAL 6-23-20.pdf](https://github.com/defund12/defund12.org/files/4784038/20-21.Full.Budget.FINAL.6-23-20.pdf)

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

Also - thank you so much for including your sources and permissions :) We appreciate it!

**Comment by Citlali1305** [comment]
Hi mahrer! It's been  a week and I was just wondering if there were any updates? About how long does it take a request to be accepted?

**Comment by mahrer** [comment]
Reviewing now!

**Comment by mahrer** [comment]
Some minor edits below. I'll flag this ready for a pr. Thanks again for your patience, and for including your sources!

---

To:
City Attorney: CityAttorney@brentwoodca.gov
City Clerk: CityClerk@brentwoodca.gov
Current Mayor: btaylor@brentwoodca.gov
Vice Mayor: jbryant@brentwoodca.gov
City Council: jrodriguez@brentwoodca.gov krarey@brentwoodca.gov cstaton@brentwoodca.gov CityCouncil@brentwoodca.gov

[UNIQUE SUBJECT LINE]

Dear Brentwood City Council,

My name is [YOUR NAME] and I am a resident of Brentwood. I am writing to demand that the Brentwood City Council adopt a budget that redirects funding away from the police and prioritizes our community's wellbeing.

In the 2019-2020 budget, the City of Brentwood allocated $ 27,878,876 dollars to our police system, while only $5,708,738 dollars were directed towards community development. This disparity is unacceptable. I join the calls of those across the country and demand that City Council defund the Brentwood Police Department and re-allocate those funds towards programs that promote a safer and more equitable community, such as mental health services, affordable housing, youth programs, and education.

As members of the City Council, it is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year, in favor of a budget that reflects the actual needs of Brentwood residents. As history has shown us, "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve, and in fact actively harms our community, and come together to reimagine the role of police in our city.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by root2point0** [comment]
on it @mahrer
