### ISSUE TITLE
Update to South San Francisco, CA email template

### ISSUE THREAD

**Issue by ssf4change** [defund12/defund12.org#1610]
Hello, the budget for South San Francisco has recently changed. Can we change the value and percentage $31,935,228—28% out of $112,262,261.08 to $31,128,044.93--29.8% of the FY 2020-2021 budget out of $104,298,600.62? This change was made on June 9th.

**Comment by todd-m** [comment]
on it. I can't find a proposed budget doc per se, but this [article](https://www.smdailyjournal.com/news/local/calls-made-to-defund-south-san-francisco-police/article_5dd4bb5c-ac5e-11ea-8642-277ab76737e8.html) seems to corroborate the overall change in the proposal.
