### ISSUE TITLE
Please Add Email for Truth or Consequences, NM

### ISSUE THREAD

**Issue by leeshantel** [defund12/defund12.org#1617]
Emails: 
sandra.whitehead@torcnm.org
brendan.tolley@torcnm.org
randall.aragon@torcnm.org
paul.baca@torcnm.org
amanda.forrister@torcnm.org
fluna@sierraco.org
tday@sierraco.org
jpaxon@sierraco.org

Dear Mayor Whitehead and the Truth or Consequences City Commission and the Sierra County Commission,

My name is [YOUR NAME] I am a resident of Truth or Consequences, and I am emailing today to demand an overhaul to our Truth or Consequences Police Department budget in light of the Black Lives Matter protests across the US, but specifically in Truth or Consequences.

I AM DEMANDING THAT YOU, MY LOCAL OFFICIALS, WILL:
-Vote no on all increases to police budgets.
-Vote yes to decrease police spending and budgets.
-Vote yes to increase spending on healthcare, education, housing, and community programs that keep us safe.

The militarized tactics that police departments are using against citizens is unacceptable and unwarranted. We have seen mounting evidence that police departments are racist and ineffective institutions that put citizens at risk of injury and death. This is amply demonstrated by the recent killing of Antonio Valenzuela in Las Cruces Police custody using a banned “vascular neck restraint"—the same restraint used to kill George Floyd in Minneapolis.

To ensure your dedication to our city and citizens, I demand that you defund the Truth or Consequences Police Department and start providing more support and funding towards community-based safety and social programs. This reprioritization will be necessary to prevent further police brutality and violence in the future, and finally mark a turn from overpolicing and incarceration.

Black, Latinx, and Indigenous communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors. According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections. In 2017, they spent $194 billion—a 220 percent increase. Despite continued police profiling, harassment, terror and killing in Black, Latinx, and Indigenous communities, local and federal decision-makers continue to invest in the police, which leaves these communities vulnerable and our communities no safer.

Where could reallocated money go? It could go towards building healthy communities, to the health of our elders and children, to neighborhood infrastructure, to education, to childcare, to support vibrant Black, Latinx, and Indigenous futures. The possibilities are incredibly exciting.

We join in solidarity with the freedom fighters in Albuquerque, Las Cruces, Santa Fe, Minneapolis, Louisville, and across the United States. And we call for the end to police terror.

Sincerely,
[YOUR NAME] 
[YOUR NUMBER]
[YOUR EMAIL]

**Comment by erinb223** [comment]
### **Edited Email Copy**
This message has been edited for grammar, clarity, and flow. No changes have been made to impact the meaning of the message.

-----

Emails:
sandra.whitehead@torcnm.org
brendan.tolley@torcnm.org
randall.aragon@torcnm.org
paul.baca@torcnm.org
amanda.forrister@torcnm.org
fluna@sierraco.org
tday@sierraco.org
jpaxon@sierraco.org

Dear Mayor Whitehead, the Truth or Consequences City Commission, and the Sierra County Commission,

My name is [YOUR NAME] I am a resident of Truth or Consequences. I am emailing today to demand an overhaul to our Truth or Consequences Police Department budget in light of the Black Lives Matter protests across the US, but specifically in Truth or Consequences.

I AM DEMANDING THAT YOU, MY LOCAL OFFICIALS:
-Vote "no" on all increases to police budgets.
-Vote "yes" to decrease police spending and budgets.
-Vote "yes" to increase spending on healthcare, education, housing, and community programs that keep us safe.

The militarized tactics that police departments are using against citizens is unacceptable and unwarranted. We have seen mounting evidence that police departments are racist and ineffective institutions that put citizens at risk of injury and death. This is amply demonstrated by the recent killing of Antonio Valenzuela in Las Cruces Police custody using a banned “vascular neck restraint"—the same restraint used to kill George Floyd in Minneapolis.

To ensure your dedication to our city and citizens, I demand that you defund the Truth or Consequences Police Department and start providing more support and funding towards community-based safety and social programs. This reprioritization will be necessary to prevent further police brutality and violence in the future, and finally mark a turn from overpolicing and incarceration.

Black, Latinx, and Indigenous communities are living in persistent fear of being killed by state authorities like police, immigration agents, and even white vigilantes who are emboldened by state actors. According to the Urban Institute, in 1977 state and local governments spent $60 billion on police and corrections. In 2017, they spent $194 billion—a 220 percent increase. Despite continued police profiling, harassment, terror, and killing in Black, Latinx, and Indigenous communities, local and federal decision-makers continue to invest in the police, which leaves these communities vulnerable and our communities no safer.

Where could reallocated money go? It could go towards building healthy communities, to the health of our elders and children, to neighborhood infrastructure, to education, to childcare, to support vibrant Black, Latinx, and Indigenous futures. The possibilities are incredibly exciting.

We join in solidarity with the freedom fighters in Albuquerque, Las Cruces, Santa Fe, Minneapolis, Louisville, and across the United States. And we call for the end to police terror.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR NUMBER]
[YOUR EMAIL]

**Comment by erinb223** [comment]
This is ready for pr
