### ISSUE TITLE
Please add: Trenton, NJ

### ISSUE THREAD

**Issue by mathilderoux** [defund12/defund12.org#1619]
SUBJECT: [*** INSERT UNIQUE SUBJECT LINE ***]

EMAILS: mayorsoffice@trentonnj.org; kmcbride@trentonnj.org; mcaldwell-wilson@trentonnj.org; jblakeley@trentonnj.org; jharrison@trentonnj.org; georgemuschal@aol.org; srodriguez@trentonnj.org; rvaughn@trentonnj.org 

EMAIL TEXT:

Dear Mayor Gusciora and City Council Members,

My name is [YOUR NAME] and I am a resident of [YOUR WARD/NEIGHBORHOOD]. In light of recent protests in support of the Black Lives Matter Movement sparked by the murders of Black individuals at the hands of police, I am writing to urge you to advocate for a meaningful reallocation of the City's expenditures away from policing and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. 

One of the largest appropriations in Trenton’s proposed FY 2020 budget of $221.4 million is for police. At over $35 million, the appropriation for police dwarfs appropriations for social programs such as Environmental Health, Community Relations and Social Services, Emergency Shelter, Housing and Economic Development, and Recreation, and the departments that provide them such as the Health and Human Services Director and the Office of Adult and Family Services, all of which receive less than $1 million in appropriations and in many cases much less than that. This is unacceptable in a city with a poverty rate of 28.4%, significantly higher than the New Jersey overall rate of 9.5% and the nationwide rate of 11.8%. 

Economic security must be a central consideration in any strategy aimed at increasing community safety. This is particularly relevant now during a pandemic which has disproportionately affected communities of color and low-income people both with in terms of public health impacts of the virus and economic impacts of the resulting recession. In the coming months and years, investments in social programs will be critical in helping communities recover.

I urge you to revise the FY 2020 budget to redistribute funding away from police and toward the needs of Trenton residents, ideally with participation of those residents in the creation of the budget, and show that the City of Trenton is committed to a vision of true public safety, one that reduces and eliminates harm for everyone.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

SOURCES:
https://nj-trenton.civicplus.com/DocumentCenter/View/4182/2020-Introduced-Budget
https://nj-trenton.civicplus.com/CivicAlerts.aspx?AID=309
https://www.census.gov/quickfacts/fact/table/NJ,trentoncitynewjersey,US/PST045219

**Comment by erinb223** [comment]
### **Edited Email Copy**
I linked the source documents into the email body for a smoother reading experience. I also broke up a long sentence in the middle of the message for ease of readability without altering its meaning.

-----

SUBJECT: [*** INSERT UNIQUE SUBJECT LINE ***]

EMAILS: mayorsoffice@trentonnj.org; kmcbride@trentonnj.org; mcaldwell-wilson@trentonnj.org; jblakeley@trentonnj.org; jharrison@trentonnj.org; georgemuschal@aol.org; srodriguez@trentonnj.org; rvaughn@trentonnj.org

EMAIL TEXT:

Dear Mayor Gusciora and City Council Members,

My name is [YOUR NAME] and I am a resident of [YOUR WARD/NEIGHBORHOOD]. In light of recent protests in support of the Black Lives Matter Movement sparked by the murders of Black individuals at the hands of police, I am writing to urge you to advocate for a meaningful reallocation of the City's expenditures away from policing and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.

One of the largest appropriations in [Trenton’s proposed FY 2020 budget](https://nj-trenton.civicplus.com/DocumentCenter/View/4182/2020-Introduced-Budget) of [$221.4 million](https://nj-trenton.civicplus.com/CivicAlerts.aspx?AID=309) is for police. At over $35 million, the appropriation for police dwarfs appropriations for social programs such as Environmental Health, Community Relations and Social Services, Emergency Shelter, Housing and Economic Development, and Recreation. It's also more than the funding for departments that provide these services, such as the Health and Human Services Director and the Office of Adult and Family Services, both of which receive less than $1 million in appropriations, and in many cases much less than that. This is unacceptable in [a city with a poverty rate of 28.4%](https://www.census.gov/quickfacts/fact/table/NJ,trentoncitynewjersey,US/PST045219), significantly higher than the New Jersey overall rate of 9.5% and the nationwide rate of 11.8%.

Economic security must be a central consideration in any strategy aimed at increasing community safety. This is particularly relevant now, during a pandemic which has disproportionately affected communities of color and low-income people both in its public health impacts and in the economic impacts of the resulting recession. In the coming months and years, investments in social programs will be critical in helping communities recover.

I urge you to revise the FY 2020 budget to redistribute funding away from police and toward the needs of Trenton residents, ideally with participation of those residents in the creation of the budget, and show that the City of Trenton is committed to a vision of true public safety, one that reduces and eliminates harm for everyone.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE]
[YOUR EMAIL]

**Comment by erinb223** [comment]
This request is ready for PR.
