### ISSUE TITLE
Please Add Schenectady New York

### ISSUE THREAD

**Issue by roseanneluvr** [defund12/defund12.org#1636]
To: smykoo@schenectadyny.gov , kZalewskiWildzunas@schenectadyny.gov , jpolimeni@schenectadyny.gov , ekosiur@schenectadyny.gov , jmootooveren@schenectadyny.gov , lperazzo@schenectadyny.gov . mporterfield@schenectadyny.gov , cpatrick@schenectadyny.gov

Subject: [INSERT UNIQUE SUBJECT LINE]

My name is [YOUR NAME] and I am a resident of Schenectady. I am writing to demand that the Schenectady City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police and towards housing, jobs, youth programs, restorative justice and mental health workers to help the community.

In the 2020 budget, the City of Schenectady allocated an egregious $34,368,057 to our police department. I demand that the City Council begin meaningfully defunding the Schenectady Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs. Police officers are not equipped to – and should not – be the first resource for every crisis. I demand a budget that reflects the actual needs of Schenectady residents.

History has shown that police “reform” is not enough. Policing in America was developed to protect the institution of slavery. More money and training programs will not only _**not**_ fix our current system, they will cause future lives to be lost to police brutality. We must take a hard look at the way the current system in place fails to serve – and in fact actively harms – our community, and come together to reimagine the role of police in our city.

I am urging you to keep these things in mind for the budget for the upcoming fiscal year and to invest in the people, not the police.

Thank you for your time,
[YOUR NAME][YOUR ADDRESS]
[YOUR EMAIL][YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by erinb223** [comment]
### **Edited Email Copy*

--------

To: smykoo@schenectadyny.gov , kZalewskiWildzunas@schenectadyny.gov , jpolimeni@schenectadyny.gov , ekosiur@schenectadyny.gov , jmootooveren@schenectadyny.gov , lperazzo@schenectadyny.gov . mporterfield@schenectadyny.gov , cpatrick@schenectadyny.gov

Subject: [INSERT UNIQUE SUBJECT LINE]

My name is [YOUR NAME] and I am a resident of Schenectady. I am writing to demand that the Schenectady City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police and towards housing, jobs, youth programs, restorative justice and mental health workers to help the community.

In the 2020 budget, the City of Schenectady allocated an egregious $34,368,057 to our police department. I demand that the City Council begin meaningfully defunding the Schenectady Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs. Police officers are not equipped to—and should not—be the first resource for every crisis. I demand a budget that reflects the actual needs of Schenectady residents.

History has shown that police “reform” is not enough. Policing in America was developed to protect the institution of slavery. More money and training programs will not only not fix our current system, they will cause future lives to be lost to police brutality. We must take a hard look at the way the current system in place fails to serve—and in fact actively harms—our community, and come together to reimagine the role of police in our city.

I am urging you to keep these things in mind for the budget for the upcoming fiscal year and to invest in the people, not the police.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by erinb223** [comment]
This is ready for pr

**Comment by root2point0** [comment]
on it

**Comment by roseanneluvr** [comment]
Will I be notified when this is published? Would like to share....

Jacob Brancasi | 518 698 9013 | jacobbrancasi.com
<http://www.jacobbrancasi.com/>
