### ISSUE TITLE
Please add Puyallup, WA

### ISSUE THREAD

**Issue by Woolery** [defund12/defund12.org#1644]
To: 
Mayor _Julie Door_ - jdoor@ci.puyallup.wa.us
Deputy Mayor _John Palmer_ - jpalmer@ci.puyallup.wa.us
District 1 Councilmember _Robin Farris_ - rfarris@ci.puyallup.wa.us
District 1 Councilmember _Jim Kastama_ - jkastama@ci.puyallup.wa.us
District 2 Councilmember _Cyndy Jacobsen_ - cjacobsen@ci.puyallup.wa.us
District 3 Councilmember _Ned Witting_ - nwitting@ci.puyallup.wa.us
At-Large Council Member _Dean Johnson_ - djohnson@ci.puyallup.wa.us
City Clerk _Mary Winter_ - mwinter@ci.puyallup.wa.us
City Manager _Steve Kirkelie_ - skirkelie@ci.puyallup.wa.us
City Manager Executive Assistant _Jessica Johnson_ -  jmjohnson@ci.puyallup.wa.us
Economic Development Manager _Meredith Neal_ - mneal@ci.puyallup.wa.us
Public Affairs Officer _Brenda Fritsvold_ - brenda@ci.puyallup.wa.us
Community Relations Coordinator _Erica Unruh_ - eunruh@ci.puyallup.wa.us

[ENTER SUBJECT LINE]

Dear Puyallup Mayor, City Councilmembers, City Clerk, and City Manager,

My name is [FIRST NAME AND LAST NAME] and I am a resident of Puyallup. I am writing to you all in regards to the current budget that has been allocated to the Police Department. As a community we need to redistribute these funds to other services that are more appropriate in addressing the issues the Police Department faces.

In the adopted 2020 budget, 42% of the general fund is being allocated to the Police Department to assure a high level of public safety. However, by utilizing funding in this way, the needs of the residents of Puyallup are failing to be met. Failing to meet these needs influence public safety. These needs can be met through increased funding to libraries, parks and recreation, the programs in our community such as the Puyallup Food Bank, Rebuilding Hope!, and Helping Hand House as examples. Utilizing this route would align with Puyallup's City Council Priorities - "Effectively manage expenditures, while seeking to increase traditional revenue sources and _pursue alternative sources_", **"Evaluate programs, regulations, and practices to provide a high level of service to the community"**, and "Actively promote Puyallup's economic development and _redevelopment opportunities_ while maintaining the essence and character of our community." Funding could also be redistributed to the capital funds.

As representatives of your community, I am encouraging you to revise your budget for the 2020 fiscal year to better serve the needs of Puyallup. Consider the trends in our own U.S history and what research has shown to work best in comparison to the police in some of the problems our community faces.

Thank you for reading this,
[NAME]
[EMAIL]

**Comment by Woolery** [comment]
Here is the Puyallup Budget:
https://www.cityofpuyallup.org/DocumentCenter/View/11816/2020-Adopted-Budget

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by erinb223** [comment]
### **Edited Email Copy**
Removed names before emails for efficiency in filling email fields, added officials' names to make the email more personal, made a few grammatical edits, added address and phone prompts at the end.

To:
jdoor@ci.puyallup.wa.us
jpalmer@ci.puyallup.wa.us
rfarris@ci.puyallup.wa.us
jkastama@ci.puyallup.wa.us
cjacobsen@ci.puyallup.wa.us
nwitting@ci.puyallup.wa.us
djohnson@ci.puyallup.wa.us
mwinter@ci.puyallup.wa.us
skirkelie@ci.puyallup.wa.us
jmjohnson@ci.puyallup.wa.us
mneal@ci.puyallup.wa.us
brenda@ci.puyallup.wa.us
eunruh@ci.puyallup.wa.us

[ENTER SUBJECT LINE]

Dear Mayor Door, City Councilmembers, City Clerk Winter, and City Manager Kirkelie,

My name is [FIRST NAME AND LAST NAME] and I am a resident of Puyallup. I am writing to you all in regards to the current budget that has been allocated to the Police Department. As a community we need to redistribute these funds to other services that are more appropriate in addressing the issues the Police Department faces.

In the adopted 2020 budget, 42% of the general fund is being allocated to the Police Department to assure a high level of public safety. However, by utilizing funding in this way, the needs of the residents of Puyallup are failing to be met. Failing to meet these needs influence public safety. These needs can be met through increased funding to libraries, parks and recreation, the programs in our community such as the Puyallup Food Bank, Rebuilding Hope!, and Helping Hand House as examples. Utilizing this route would align with Puyallup's City Council Priorities: "Effectively manage expenditures, while seeking to increase traditional revenue sources and pursue alternative sources," "Evaluate programs, regulations, and practices to provide a high level of service to the community," and "Actively promote Puyallup's economic development and redevelopment opportunities while maintaining the essence and character of our community." Funding could also be redistributed to the capital funds.

As representatives of your community, I am encouraging you to revise your budget for the 2020 fiscal year to better serve the needs of Puyallup. Consider the trends in our own U.S. history and what research has shown to work best in comparison to the police in some of the problems our community faces.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE NUMBER]
[YOUR EMAIL]

**Comment by erinb223** [comment]
This is ready for pr

**Comment by root2point0** [comment]
on it
