### ISSUE TITLE
Kirkland, WA

### ISSUE THREAD

**Issue by xentac** [defund12/defund12.org#1646]
psweet@kirklandwa.gov,jarnold@kirklandwa.gov,nblack@kirklandwa.gov,kcurtis@kirklandwa.gov,afalcone@kirklandwa.gov,tnixon@kirklandwa.gov,jpascal@kirklandwa.gov

- Detailed message concerning the budgeting decisions at stake in your community

Dear City of Kirkland Mayor, Deputy Mayor, and Councilmembers,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the City Council adopt a 2021-2022 Budget for the people that satisfies the council's public safety goal of "[Providing] for public safety through a community-based approach that focuses on prevention of problems..." [1] and redirects funding away from the police.

I am asking this City Council to show your commitment to this community by making meaningful changes to the cities priorities as reflected in the budget. In the 2019-2020 Budget the City of Kirkland allocated 21% of its 245 million dollars in expenses to the Kirkland Police Department [2]. I urge you to advocate for a meaningful reallocation of the city's expenditures: away from policing and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.

History has shown that police "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve--and in fact actively harms--our community, and come together to reimagine the role of police in our city.

Thank you for your time,
[YOUR NAME][YOUR ADDRESS]
[YOUR EMAIL][YOUR PHONE NUMBER]

[1] https://www.kirklandwa.gov/Assets/City+Council/Council+PDFs/Council+Goals+2019.pdf
[2] https://www.kirklandwa.gov/Assets/Finance+Admin/2019-2020+Budget/2019-2020+Final+Budget+Document.pdf

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by puddlebug** [comment]
Hello!  Another Kirkland resident here.  I also wrote a letter but noticed a few hours after submitting it that this letter was also written.  This letter looks awesome!

If you'd like to grab anything from the letter I wrote, it is posted by mahrer above.

**Comment by xentac** [comment]
Mayor: Penny Sweet psweet@kirklandwa.gov
Deputy Mayor: Jay Arnold jarnold@kirklandwa.gov
Councilmember: Neal Black nblack@kirklandwa.gov
Councilmember: Kelli Curtis kcurtis@kirklandwa.gov
Councilmember: Amy Falcone afalcone@kirklandwa.gov
Councilmember: Toby Nixon tnixon@kirklandwa.gov
Councilmember: Jon Pascal jpascal@kirklandwa.gov

Dear City of Kirkland Mayor, Deputy Mayor, and Councilmembers,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the City Council adopt a 2021-2022 Budget for the people that satisfies the council's public safety goal of "[Providing] for public safety through a community-based approach that focuses on prevention of problems..." [1] and redirects funding away from the police.

I am asking this City Council to show your commitment to this community by making meaningful changes to the cities priorities as reflected in the budget. In the 2019-2020 Budget the City of Kirkland allocated 21% of its 245 million dollars in expenses to the Kirkland Police Department [2]. I urge you to advocate for a meaningful reallocation of the city's expenditures: away from policing and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.

Our nation confronts a fact which rings so clear: police brutality is not a problem we can solve with reform alone. Police brutality is evidence of police power gone too far. Ironically, we have seen police response to peaceful protests across our country be incredibly aggressive. We have seen police terrorize journalists, civilian medics, and peaceful protesters just across the lake in Seattle. Tear gas, mace, and rubber bullets have been used to qualm dissent.

History has shown that police "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve--and in fact actively harms--our community, and come together to reimagine the role of police in our city.

Thank you for your time,
[YOUR NAME][YOUR ADDRESS]
[YOUR EMAIL][YOUR PHONE NUMBER]

[1] https://www.kirklandwa.gov/Assets/City+Council/Council+PDFs/Council+Goals+2019.pdf
[2] https://www.kirklandwa.gov/Assets/Finance+Admin/2019-2020+Budget/2019-2020+Final+Budget+Document.pdf

**Comment by xentac** [comment]
I took your middle paragraph because it helped to strengthen the last one and because it mentioned examples in Seattle.

**Comment by mahrer** [comment]
This looks great! Thanks for your collaboration on this. Some very minor edits below:

---

Mayor: Penny Sweet psweet@kirklandwa.gov
Deputy Mayor: Jay Arnold jarnold@kirklandwa.gov
Councilmember: Neal Black nblack@kirklandwa.gov
Councilmember: Kelli Curtis kcurtis@kirklandwa.gov
Councilmember: Amy Falcone afalcone@kirklandwa.gov
Councilmember: Toby Nixon tnixon@kirklandwa.gov
Councilmember: Jon Pascal jpascal@kirklandwa.gov

Dear City of Kirkland Mayor, Deputy Mayor, and Councilmembers,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the City Council adopt a 2021-2022 Budget for the people that satisfies the council's public safety goal of "[Providing] for public safety through a community-based approach that focuses on prevention of problems..." [1] and redirects funding away from the police.

I am asking this City Council to show your commitment to this community by making meaningful changes to the city's priorities as reflected in the budget. In the 2019-2020 Budget, the City of Kirkland allocated 21% of its 245 million dollars in expenses to the Kirkland Police Department [2]. I urge you to advocate for a meaningful reallocation of the city's expenditures: away from policing and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.

Our nation confronts a fact which rings so clear: police brutality is not a problem we can solve with reform alone. Police brutality is evidence of police power gone too far. Ironically, we have seen police response to peaceful protests across our country be incredibly aggressive. We have seen police terrorize journalists, civilian medics, and peaceful protesters just across the lake in Seattle. Tear gas, mace, and rubber bullets have been used to qualm dissent.

History has shown that police "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve--and in fact actively harms--our community, and come together to reimagine the role of police in our city.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

[1] https://www.kirklandwa.gov/Assets/City+Council/Council+PDFs/Council+Goals+2019.pdf
[2] https://www.kirklandwa.gov/Assets/Finance+Admin/2019-2020+Budget/2019-2020+Final+Budget+Document.pdf

**Comment by root2point0** [comment]
on it

**Comment by xentac** [comment]
Seems like the links were forgotten at the bottom of the email. I created https://github.com/defund12/defund12.org/pull/1773 to fix it. Thanks!
