### ISSUE TITLE
Please add Bonney Lake, WA

### ISSUE THREAD

**Issue by Woolery** [defund12/defund12.org#1648]
Mayor _Neil Johnson_ - Mayor@cobl.us
City Administrator _John Vodopich_ - vodopichj@cobl.us
Executive Assistant _Leslie Harris_ - harrisl@cobl.us
Councilmember 1 _Todd Dole_ - dolet@cobl.us
Councilmember 2 _Justin Evans_ - evansj@cobl.us
Councilmember 3 _Dan Swatman_ - swatmand@cobl.us
Councilmember 4 _James (Kelly) McClimans Sr._ - mcclimansj@cobl.us
Councilmember 5 _Tom Watson_ - watsont@cobl.us
Councilmember 6 _Terry Carter_ - cartert@cobl.us
Councilmember 7 _Michelle Keith_ - keithm@cobl.us

Subject: [UNIQUE SUBJECT LINE]
Dear Mayor, City Administrator, Executive Assistant, and Councilmembers:

My name is [FIRST NAME AND LAST NAME] and I am a resident of Bonney Lake. As there has been increased light on police department and citizen interactions across the nation, I am concerned about our community's budget allocation for our police department in the current biennium. I demand there be an adjustment to the current budget and that future bienniums reflect the needs of our community through redistributing the funds given to the police department.

Looking at the proposed budget for the 2020 year, our police department has received $8,240,428 in funding while our community events and community services allocation was collectively given a measley $85,032. This is concerning as it has been shown time and time again that other avenues such as social service organizations are more effective in addressing many of the issues police officers face in the field like homelessness, domestic violence, and substance use as examples.

Police historically stem from slave patrols. We cannot keep supporting an institution, a structure, to maintain white supremacy in our country and communities. I urge you to reflect the interests of your constituents. If we are going to be "a center for diverse cultural and social opportunities", we need to take action like one. 

Thank you for your time,
[FIRST AND LAST NAME]
[EMAIL ADDRESS]

**Comment by Woolery** [comment]
Bonney Lake Budget https://www.ci.bonney-lake.wa.us/UserFiles/Servers/Server_15292413/File/Finance/2019-2020%20Budget%20Report%20-%20ADA.pdf

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by erinb223** [comment]
### **Edited Email Copy**
Removed official names before emails for easier addition to email fields, added officials' names to make the email more personal, made minor grammatical adjustments, added additional constituent info to the end

----------------

Mayor@cobl.us
vodopichj@cobl.us
harrisl@cobl.us
dolet@cobl.us
evansj@cobl.us
swatmand@cobl.us
mcclimansj@cobl.us
watsont@cobl.us
cartert@cobl.us
keithm@cobl.us

Subject: [UNIQUE SUBJECT LINE]
Dear Mayor Johnson, City Administrator Vodopich, Executive Assistant Harris, and Councilmembers:

My name is [FIRST NAME AND LAST NAME] and I am a resident of Bonney Lake. As there has been increased light on police department and citizen interactions across the nation, I am concerned about our community's budget allocation for our police department in the current biennium. I demand there be an adjustment to the current budget and that future bienniums reflect the needs of our community through redistributing the funds given to the police department.

Looking at the proposed budget for the 2020 year, our police department has received $8,240,428 in funding while our community events and community services allocation was collectively given a measly $85,032. This is concerning as it has been shown time and time again that other avenues such as social service organizations are more effective in addressing many of the issues police officers face in the field like homelessness, domestic violence, and substance use as examples.

Police historically stem from slave patrols. We cannot keep supporting an institution, a structure, to maintain white supremacy in our country and communities. I urge you to reflect the interests of your constituents. If we are going to be "a center for diverse cultural and social opportunities," we need to act like one.

Thank you for your time,
[FIRST AND LAST NAME]
[YOUR ADDRESS]
[YOUR PHONE NUMBER]
[YOUR EMAIL]

**Comment by erinb223** [comment]
This is ready for pr

**Comment by root2point0** [comment]
on it
