### ISSUE TITLE
Please add Ridgefield, CT

### ISSUE THREAD

**Issue by ryjo1026** [defund12/defund12.org#1661]
Board of Selectmen: selectman@ridgefieldct.org
Board of Finance: controller@ridgefieldct.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

To the Rudy Marconi, the Ridgefield Board of Selectmen, and the Ridgefield Board of Finance:

My name is [YOUR NAME] and I am a Ridgefield resident currently living in [YOUR NEIGHBORHOOD]. I am writing to demand that the Ridgefield Board of Selectmen adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police.
In 2019, Ridgefield recorded a $5,495,911 expenditure on Police compared to a $232,140 expenditure on social services.

I ask that the town begins to meaningfully defund the Ridgefield Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more.

History has shown that police "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve--and in fact, actively harms--our community, and come together to reimagine the role of police in our town.

Thank you for your time, [YOUR NAME][YOUR ADDRESS] [YOUR EMAIL][YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by erinb223** [comment]
### **Edited Email Copy**
Added the individual email of one of the Selectmen, minor formatting changes.
-------

selectman@ridgefieldct.org, Bob@HebertPartners.com, controller@ridgefieldct.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

To Rudy Marconi, the Ridgefield Board of Selectmen, and the Ridgefield Board of Finance:

My name is [YOUR NAME] and I am a Ridgefield resident currently living in [YOUR NEIGHBORHOOD]. I am writing to demand that the Ridgefield Board of Selectmen adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police.

In 2019, Ridgefield recorded a $5,495,911 expenditure on Police compared to a $232,140 expenditure on social services.

I ask that the town begins to meaningfully defund the Ridgefield Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more.

History has shown that police "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve--and in fact, actively harms--our community, and come together to reimagine the role of police in our town.

Thank you, 
[YOUR NAME]
[YOUR ADDRESS] 
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by erinb223** [comment]
How wild that the city council is in Ridgefield called the "Board of Selectmen" lol. This is ready for pr

**Comment by root2point0** [comment]
on it
