### ISSUE TITLE
Please add Elmhurst, IL

### ISSUE THREAD

**Issue by kmccracken12** [defund12/defund12.org#1663]
jackie.haddad-tamer@elmhurst.org
econdev@elmhurst.org
tom.trosien@elmhurst.org
cityadmin@elmhurst.org
steven.morley@elmhurst.org
elaine.libovicz@elmhurst.org
marti.deuter@elmhurst.org
norman.leader@elmhurst.org
bob.dunn@elmhurst.org
michael.bram@elmhurst.org
dannee.polomsky@elmhurst.org
noel.talluto@elmhurst.org
tina.park@elmhurst.org
scott.levin@elmhurst.org
jim.kennedy@elmhurst.org
michael.honquest@elmhurst.org
mike.brennan@elmhurst.org
mark.mulliner@elmhurst.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message: (Don't forget to replace the [x]'s with your information!)🔗
Hello,
My name is [NAME] and I am a resident of [NEIGHBORHOOD/CITY]. I am extremely concerned with the City of Elmhurst’s inordinate investment in the Elmhurst Police Department (EPD) at the expense of critical youth, education, and health services. As demonstrated by ongoing peaceful protests and a 2019 Gallup poll, a majority of individuals living in Illinois view the police negatively.
I am therefore writing to demand that the City Council vote to reapportion funds allocated to the EPD to support evidence-based programs and services that, unlike increased police presence, promote the well-being of citizens and reduce crime. It is morally reprehensible to dedicate 30% of the City’s operating budget towards policing while too many citizens are homeless and many more lack access to essential services, including clean running water and necessary mental health resources.
I also urge the City Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity.
People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents and take immediate action to address their concerns.
Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by mahrer** [comment]
Hi @kmccracken12, I'm having trouble finding a source for the claim that 30% of the city budget goes towards policing. Would you mind sharing where you got that number from?

**Comment by kmccracken12** [comment]
Hello, 
I got the budget info from www.elmhurst.org:

https://www.elmhurst.org/DocumentCenter/View/16061/Governmental-FundsPDF?bidId=

**Comment by root2point0** [comment]
on it
