### ISSUE TITLE
Please add Covington, WA

### ISSUE THREAD

**Issue by Woolery** [defund12/defund12.org#1664]
Mayor _Jeff Wagner_ - jwagner@covingtonwa.gov
Councilmember _Fran Hollums_ - fhollums@covingtonwa.gov
Mayor Pro Tem _Sean Smith_ - ssmith@covingtonwa.gov
Councilmember _Joseph Cimaomo, Jr_ - jcimaomojr@covingtonwa.gov
Councilmember _Jared Koukal_ - jkoukal@covingtonwa.gov
Councilmember _Jennifer Harjehausen_ - jharjehausen@covingtonwa.gov
Councilmember _Kristina Soltys_ - ksoltys@covingtonwa.gov

Subject: [UNIQUE SUBJECT LINE HERE]

Hello Mayors and Councilmembers,

My name is [FIRST NAME AND LAST NAME] and I am a resident of Covington. I am writing to you all to address the funding of our police department here in our community. As a community we are a responsible for addressing the needs of our citizens in an effective manner. 

In our annual budget for the 2020 year, 37.02% of the general budget has been distributed to the police. We need to be using these funds to better serve the needs of our community. According to the budget, we are allocating over $4 million to the police while only $444,539  to the Personnel and Human Services department. Social and human services can better address the issues of domestic violence, homelesssness, substance use, and other problems that the police address.

I hope as councilmembers you will represent your constituents. The police stems from the maintenance of white supremacy in history. If we are to foster "community cohesiveness"  and "a strong sense of unity", we need to be doing better. I demand there be a change to defund the police and serve our community now and that it continues in the future.

Sincerely,
[FIRST NAME AND LAST NAME]
[EMAIL ADDRESS]

**Comment by Woolery** [comment]
https://www.covingtonwa.gov/2020%20Budget-S.pdf

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by mahrer** [comment]
Some minor edits below:

---

Mayor Jeff Wagner - jwagner@covingtonwa.gov
Councilmember Fran Hollums - fhollums@covingtonwa.gov
Mayor Pro Tem Sean Smith - ssmith@covingtonwa.gov
Councilmember Joseph Cimaomo, Jr - jcimaomojr@covingtonwa.gov
Councilmember Jared Koukal - jkoukal@covingtonwa.gov
Councilmember Jennifer Harjehausen - jharjehausen@covingtonwa.gov
Councilmember Kristina Soltys - ksoltys@covingtonwa.gov

Message:

Hello Mayors and Councilmembers,

My name is [YOUR NAME] and I am a resident of Covington. I am writing to you all to address the funding of our police department here in our city. As elected officials, you are a responsible for addressing the needs of our community in an effective manner.

In our annual budget for the 2020 year, 37.02% of the general budget has been distributed to the police. According to the budget, we are allocating over $4 million to the police while only $444,539 go to the Personnel and Human Services Department. Social and human services can better address the issues of domestic violence, homelessness, substance use, and other problems that the police address. We need to be using these funds to better serve the needs of our community.

I hope as councilmembers you will represent your constituents. The system of policing stems from the maintenance of white supremacy in history. If we are to foster community cohesiveness and a strong sense of unity, we need to be doing better. I demand you vote to defund the police and fund services that help our community now, and in the future.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by root2point0** [comment]
on it
