### ISSUE TITLE
Bellingham, WA

### ISSUE THREAD

**Issue by wpalchemist** [defund12/defund12.org#1676]
To: hestone@cob.org, dchammill@cob.org​, laanderson@cob.org, hahuthman@cob.org, gknutson@cob.org, ptmvargas@cob.org​, mlilliquist@cob.org​, mayorsoffice@cob.org
Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message: (Don't forget to replace the [x]'s with your information!)

Dear Bellingham City Council,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the Bellingham City Council adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police.

The Bellingham city budget for 2019-2020 allocates over $30 million to the police department, about a third of the total budget.  I demand that the City Council begin meaningfully defunding the Bellingham Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Bellingham residents.

History has shown that police "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve--and in fact actively harms--our community, and come together to reimagine the role of police in our city.  Our town is small, close-knit, and empathetic, and defunding the police and reallocating that funding towards social services would make this an even more amazing place to live. 

I understand that this is a massive change and we can't make it overnight, and that Bellingham also faces huge challenges dealing with coronavirus, but please do not spend too much time with forums and community tours.  I demand an immediate commitment to action on defunding the police.

Thank you for your time,
[YOUR NAME][YOUR ADDRESS]
[YOUR EMAIL][YOUR PHONE NUMBER]

**Comment by wpalchemist** [comment]
This is largely copied from https://defund12.org/santabarbara?browse with some adjustments for Bellingham.

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by mahrer** [comment]
Hey @wpalchemist - 

In the second paragraph you say that the budget "allocates about many times more funding towards public safety than to human services." Can we be more specific here? It'd be very effective if you compare numbers or percentages of funding between departments, as well as citing your source (ex: "according to the FY2020 proposed budget...").

**Comment by wpalchemist** [comment]
@mahrer I have updated the text to include more accurate information about the budget.

**Comment by mahrer** [comment]
Some very minor edits:

--

To: hestone@cob.org, dchammill@cob.org​, laanderson@cob.org, hahuthman@cob.org, gknutson@cob.org, ptmvargas@cob.org​, mlilliquist@cob.org​, mayorsoffice@cob.org
Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message: (Don't forget to replace the [x]'s with your information!)

Dear Bellingham City Council,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the Bellingham City Council adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police.

The Bellingham city budget for 2019-2020 allocates over $30 million to the police department, about a third of the total budget. I demand that the City Council begin meaningfully defunding the Bellingham Police Department and re-allocating those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Bellingham residents.

History has shown that police "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve--and in fact actively harms--our community, and come together to reimagine the role of police in our city. Our town is small, close-knit, and empathetic, and defunding the police and reallocating that funding towards social services would make this an even more amazing place to live.

I understand that this is a massive change and we can't make it overnight, and that Bellingham also faces huge challenges dealing with coronavirus, but please do not spend too much time with forums and community tours. I demand an immediate commitment to action on defunding the police.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by root2point0** [comment]
on it
