### ISSUE TITLE
Edgewood Borough, PA

### ISSUE THREAD

**Issue by cod33** [defund12/defund12.org#1677]
Emails: jwilson@edgewoodboro.com (mayor) , jwainright1@edgewoodboro.com (council president), ryan@edgewoodboro.com (council VP), ben.love@edgewoodboro.com (pres pro tem), jpetrolla@edgewoodboro.com, jfbright1@edgewoodboro.com, tyaney@edgewoodboro.com, gfuller1@edgewoodboro.com

Hello,
My name is [YOUR NAME] and I am a resident of Edgewood Borough. I am writing to demand the borough dismantle the Edgewood Police Budget and redirect funding into supporting community operations.
The proposed 2020 budget for the Police Department is $1,242,916 This is ~35.6% - over one third - of the overall Borough General Fund Budget.
The combined budgets of Public Works, Community Affairs, Library Donations, Parks & Playgrounds, and Recreation is $333,359, reflecting only 10% of the Borough's budget. The mission statement, found on the Police Department's website, is " We are committed to work as a team with other departments, government agencies and our community, to provide innovative, effective and efficient service which will improve the quality of life in the Borough of Edgewood."  However, our current budget does not reflect this mission statement at all. The community would be much better served by people like social workers, mental health professionals, and traffic controllers than the police.
I urge you to advocate for a meaningful reallocation of the city's expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. 
Sincerely,
[YOUR NAME][YOUR ADDRESS]
[YOUR EMAIL][YOUR PHONE NUMBER]

Letter for the mods: thank you for organizing this!!!!!

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by mahrer** [comment]
Some minor edits below:

---

Emails: jwilson@edgewoodboro.com (mayor) , jwainright1@edgewoodboro.com (council president), ryan@edgewoodboro.com (council VP), ben.love@edgewoodboro.com (pres pro tem), jpetrolla@edgewoodboro.com, jfbright1@edgewoodboro.com, tyaney@edgewoodboro.com, gfuller1@edgewoodboro.com

Hello,

My name is [YOUR NAME] and I am a resident of Edgewood Borough. I am writing to demand the borough defund the Edgewood Police Budget and redirect funding into supporting community operations.

The proposed 2020 budget for the Police Department is $1,242,916. This is about 35.6% - over one third - of the overall Borough General Fund Budget. In contrast, the combined budgets of Public Works, Community Affairs, Library Donations, Parks & Playgrounds, and Recreation is $333,359, reflecting only 10% of the Borough's budget. 

The mission statement found on the Police Department's website claims, "We are committed to work as a team with other departments, government agencies and our community, to provide innovative, effective and efficient service which will improve the quality of life in the Borough of Edgewood."  However, our current budget does not reflect this mission statement at all. The community would be much better served by people like social workers, mental health professionals, and traffic controllers than the police.

I urge you to advocate for a meaningful reallocation of the city's expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. 

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
