### ISSUE TITLE
Please add Elgin, IL

### ISSUE THREAD

**Issue by knicows** [defund12/defund12.org#1683]
Email to: mayor@cityofelgin.org, steffen_j@cityofelgin.org, gavin_t@cityofelgin.org, dixon_c@cityofelgin.org, martinez_r@cityofelgin.org, powell_t@cityofelgin.org, rauschenberger_c@cityofelgin.org, shaw_t@cityofelgin.org, citymanager@cityofelgin.org, cogley_w@cityofelgin.org, lalley_a@cityofelgin.org 

Subject: [**INSERT UNIQUE SUBJECT LINE**]

Mr. Mayor and Councilpersons: 
 
I, [YOUR NAME], a tax-paying citizen of Elgin, am writing to demand urgent change to the policies and procedures governing the Elgin Police Department, and adoption of a city budget that prioritizes community well-being, helps build an all-inclusive, anti-racist community, and redirects funding away from the police.

In 2020, the city of Elgin allocated $47,558,740 to our police system, an inordinate 37% of the city’s general fund budget. This is comparatively much higher than the amount of money allocated towards community development and social services ($1,408,330- less than 0.01% of the budget), or any other department. Next year, there will likely be deficits as a result of the pandemic. The city must recoup these funds by decreasing the police budget.

I demand that the city council begin meaningfully defunding the Elgin Police Department and reallocating those funds to evidence-based programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs. Police officers should not need to be the first resource for every crisis. I demand a budget that reflects the actual needs of Elgin residents.
 
Therefore, I propose the following demands: 
 
1. Reallocate taxpayer dollars from the police to community-based mental health services, substance abuse treatment services, affordable housing programs, and education. 

2. The formation of a Citizens Advisory Council to provide oversight for police discipline, internal investigation, hiring, and police union contracts. This authority will hold law enforcement accountable for misconduct and abuse and will have the authority to review any and all information relevant to related cases. This authority will be held by elected citizens who are not former law enforcement nor have relatives in law enforcement.
 
3. The forced retirement/resignation of Lieutenant Chris Jensen, to help the community move forward and heal after DeCynthia Clement’s murder. Any settlement or retirement paid to Jenson must come from the Elgin Police Department budget. In addition, all future settlements will come from the Elgin Police department budget, and officer names will not be redacted from settlements. I urge the City Council to enact legislation that holds police accountable and ensures they can no longer use lethal force against the residents of Elgin without consequence. 

4. Remove all police from U-46 schools.
 
5. Addition of clear and precise procedures concerning body cameras, and enforcement of their usage.

6. Elgin Police dispatch feeds should become publicly accessible. 

History has shown that police “reform” is not enough. Policing in America was developed to protect the institution of slavery. More money and training programs for police will not fix our current system. We must take a hard look at the way the current system in place fails to serve - and in fact actively harms - our community, and come together to reimagine the role of police in our city.

I am urging you to act on this as you develop the budget for the 2020-2021 fiscal year, and to invest in the people, not the police.

Thank you for your time,

[YOUR NAME][YOUR ADDRESS]
[YOUR EMAIL][YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by aurendisson** [comment]
Editing notes: I made some updates to align with the style, added Baldemar Lopez's email address, and updated the percentage stat. 
Budget numbers confirmed here: https://elgin.app.box.com/s/5i9e1mww48xvagph8rbd2wv4s33b926u/file/553078926285?sb=/details

To: mayor@cityofelgin.org, steffen_j@cityofelgin.org, gavin_t@cityofelgin.org, dixon_c@cityofelgin.org, martinez_r@cityofelgin.org, powell_t@cityofelgin.org, rauschenberger_c@cityofelgin.org, shaw_t@cityofelgin.org, citymanager@cityofelgin.org, cogley_w@cityofelgin.org, lalley_a@cityofelgin.org, blopez@cityofelgin.org

Subject: [INSERT UNIQUE SUBJECT LINE]

Message: (Don't forget to replace the [x]'s with your information! And consider adding a couple of sentences in your own words to avoid filters and get your message read.)

Dear Mr. Mayor and Councilpersons:

I, [YOUR NAME], a resident of Elgin, am writing to demand urgent change to the policies and procedures governing the Elgin Police Department and adoption of a city budget that prioritizes community well-being, helps build an all-inclusive, anti-racist community, and redirects funding away from the police.

In 2020, the city of Elgin allocated $47,558,740 to our police system, an inordinate 37% of the city’s general fund budget. This is comparatively much higher than the amount of money allocated towards community development and social services ($1,408,330—just 1% of the budget), or any other department. Next year, there will likely be deficits as a result of the pandemic. The city must recoup these funds by decreasing the police budget.

I demand that the city council begin meaningfully defunding the Elgin Police Department and reallocating those funds to evidence-based programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs. Police officers should not need to be the first resource for every crisis. I demand a budget that reflects the actual needs of Elgin residents.

Therefore, I propose the following demands:
1. Reallocate taxpayer dollars from the police to community-based mental health services, substance abuse treatment services, affordable housing programs, and education.
2. The formation of a Citizens Advisory Council to provide oversight for police discipline, internal investigation, hiring, and police union contracts. This authority will hold law enforcement accountable for misconduct and abuse and will have the authority to review any and all information relevant to related cases. This authority will be held by elected citizens who are not former law enforcement nor have relatives in law enforcement.
3. The forced retirement/resignation of Lieutenant Chris Jensen, to help the community move forward and heal after the murder of DeCynthia Clements. Any settlement or retirement paid to Jenson must come from the Elgin Police Department budget. In addition, all future settlements will come from the Elgin Police Department budget, and officer names will not be redacted from settlements. I urge the City Council to enact legislation that holds police accountable and ensures they can no longer use lethal force against the residents of Elgin without consequence.
4. Remove all police from U-46 schools.
5. Addition of clear and precise procedures concerning body cameras and enforcement of their usage.
6. Elgin Police dispatch feeds should become publicly accessible.

History has shown that police “reform” is not enough. Policing in America was developed to protect the institution of slavery. More money and training programs for police will not fix our current system. We must take a hard look at the way the current system in place fails to serve—and, in fact, actively harms—our community, and come together to reimagine the role of police in our city.

I am urging you to act on this as you develop the budget for the 2020-2021 fiscal year, and to invest in the people, not the police.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by root2point0** [comment]
on it
