### ISSUE TITLE
Defund Kirkland, WA PD: Letter to Mayor Penny Sweet & City Council

### ISSUE THREAD

**Issue by puddlebug** [defund12/defund12.org#1684]
Mayor: Penny Sweet psweet@kirklandwa.gov
Deputy Mayor: Jay Arnold jarnold@kirklandwa.gov
Councilmember: Neal Black nblack@kirklandwa.gov
Councilmember: Kelli Curtis kcurtis@kirklandwa.gov
Councilmember: Amy Falcone afalcone@kirklandwa.gov
Councilmember: Toby Nixon tnixon@kirklandwa.gov
Councilmember: Jon Pascal jpascal@kirklandwa.gov

SUBJECT: [INSERT UNIQUE SUBJECT LINE]

Dear Mayor Penny Sweet and Kirkland City Council members,

My name is [YOUR NAME], I am a resident of [NEIGHBORHOOD] and am addressing you all in regard to the excessive funding of the Kirkland Police Department.

The heinous murder of George Floyd by Derek Chauvin of the Minneapolis Police Department, and the three officers who aided Chauvin and/or stood by and watched passively, sparked anger which has reverberated across our nation.  Many have taken to the streets to show our leaders we have had it; police violence has gone on for too long.  Some have argued that cases of police brutality are the misfortune rooted in a few ‘bad apples’ who have found their way into the division which claims to ‘protect and serve’.  However, I believe we are now forced to reckon with the racist structure which allow crimes against humanity be committed by those wearing a badge our police departments claim stands for justice and peace.

Our nation confronts a fact which rings so clear: police brutality is not a problem we can solve with reform alone.  Police brutality is evidence of police power gone too far.  Ironically, we have seen police response to peaceful protests across our country be incredibly aggressive.  We have seen police terrorize journalists, civilian medics, and peaceful protesters just across the lake in Seattle.  Tear gas, mace, and rubber bullets have been used to qualm dissent.  

Though Kirkland PD’s response to peaceful protests has not been blatantly hostile like the response of other departments, I am concerned that the heavy funding Kirkland PD is provided with is counterproductive and even dangerous.  Kirkland, a city with a small population of 87,240 has an inflated police budget of $57,740,340, a budget which is growing each year.  Additionally, they have access to military equipment including at least one armored vehicle.
   
We invest in police who carry guns and handcuffs and then turn around and intimidate and terrorize our communities.  These individuals are expected to take on the role of mental health professional, marriage counselor, sexual assault specialists; perhaps we burdening armed police officers with too great a responsibility.   Reform alone will not solve this problem; police departments receive egregious funding and it is about time we think critically about where we are investing our city's dollars.  Rather than having people with arms enforce laws and respond to crisis, we should have a variety of unarmed professionals trained to respond to situations without violence. 

I want to see the Kirkland Police department defunded and have funds which once belonged to them invested into our community.  I demand that the funds available to them be reduced be 50% and those funds be invested into community care.  I would like to see mental health professionals and social workers supported and funded.  I would like to see the removal of police officers from Kirkland schools.  Policing as we know it is an antiquated order which depends on the threat of violence and has seen a tremendous growth in power.  We must reduce funding and personnel in our police department and reconsider how we address public safety.  

Respectfully,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by puddlebug** [comment]
Here is a link to the Kirkland City Budget (2019-2020): https://www.kirklandwa.gov/Assets/Finance+Admin/2019-2020+Budget/2019-2020+Final+Budget+Document.pdf

**Comment by mahrer** [comment]
Hi @puddlebug, thanks for your request to add Kirkland to the site! We have an open request at #1646 that's waiting for review. If you’d like to add to or edit the messaging, please visit that issue.
Thank you!
