### ISSUE TITLE
Public Comment for Modesto City Council Budget Meeting June 23

### ISSUE THREAD

**Issue by ingatpo** [defund12/defund12.org#1685]
To: ccmeetings@modestogov.com, mayor@modestogov.com, mgrewal@modestogov.com, tmadrigal@modestogov.com, kahyou@modestogov.com, bzoslocki@modestogov.com, jkenoyer@modestogov.com, dridenour@modestogov.com
Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message: (Don't forget to replace the [x]'s with your information!)

Mayor Brandvold and City Council members,

My name is [YOUR NAME], and I am a resident of Modesto, California. This past few weeks, our nation has been gripped by protests calling for rapid and meaningful reevaluation of the role of policing in our communities and an end to racism and anti-Blackness. Based on the population of Modesto, a Black person was 3.1 times as likely to have deadly force used on them than a White person from 2016 - 2018.
At a time when people are calling for an end to racially motivated murders by armed police, in order to reduce police brutality with weapons, there should be a defunding and demilitarization of police. After looking at the city’s budget, I am appalled to learn that 52% of Modesto’s general fund expenses is dedicated to funding the police department with only up to 28% of the budget explicitly dedicated to projects, departments, and programs that invest in community well-being.
We demand that the City Council defund the Modesto Police Department, which receives at least $71 Million, and redirect that money to much needed services and resources for our community. 
As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Hi @ingatpo! Thanks so much for your submission.
The Modesto letter is already on the site from a previous submission:
https://defund12.org/modesto 
 
You can always personalize that template to highlight the upcoming council budget meeting when you send it. If you would like to make changes to the template, please open a new issue so we can follow-up.
Thank you!
