### ISSUE TITLE
Wilmington, NC

### ISSUE THREAD

**Issue by AustinB12** [defund12/defund12.org#1697]
**To:** council@wilmingtonnc.gov, bill.saffo@wilmingtonnc.gov

**Subject:** 2021 Proposed City Budget

**Message:**
Dear Mayor Bill Saffo and Wilmington City Council Member,

My name is [YOUR NAME HERE] and I am a Wilmington resident. I am writing to urge you to significantly reduce the Wilmington Police Department’s budget and to reinvest those funds to social service programs in order to better support and protect our community. It has become clear that a radical shift in our concept of policing and community health must take place at the local level. It is unacceptable that Black, Indigenous, and People of Color communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors.

We have all seen images and videos of horrific police brutality in our country. Despite this, our local officials continue to invest heavily in the police. This decision has not and will not make our communities safer. It is immoral to continue investing money in a police force that has clearly failed us, while schools and public health resources are routinely underfunded. 

Videos of police shooting tear gas at peaceful protesters on Front street deeply, worry, and sadden me. When public safety institutions terrorize its own people, as we have seen at home and across the country, it creates a severe lack of trust not only in our police, but also in our governing bodies that support them. 

In the proposed fiscal 2021 budget, we have more money allocated to the police department than we do Engineering, Public Services, Planning Development & Transportation, Community Services, and Information Technology Services COMBINED. I know that our schools have old, broken-down textbooks. I know that our teachers' pay is far too low. I know that there are many people experiencing homelessness in Wilmington. I know our roads and bridges need repairs. Yet I've never seen a police officer here without a shiny new car.

I call for the defunding of  the police department and a reinvestment into the community.

Sincerely,

[YOUR NAME HERE]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by AustinB12** [comment]
I tried to follow the email style guide closely, and I drew a lot of inspiration from other people's new email requests. 

I would definitely appreciate any criticism. Thanks!

**Comment by mahrer** [comment]
Hi @AustinB12! Thanks so much for your submission.
The Wilmington, NC letter is already published from a previous submission:
 https://defund12.org/wilmington-nc 

If you would like to make specific changes to the existing content, please open a new issue so we can follow-up.
Thank you!

**Comment by AustinB12** [comment]
Hey @mahrer 

Sorry about the duplicate! When I initially checked Wilmington had not been added yet.

**Comment by mahrer** [comment]
No worries @AustinB12! Thanks for your interest :)
