### ISSUE TITLE
Letter and emails for Yolo County, CA

### ISSUE THREAD

**Issue by benevolentfoibles** [defund12/defund12.org#1730]
To:🔗 gary.sandy@yolocounty.org (Chair)
oscar.villegas@yolocounty.org
don.saylor@yolocounty.org
jim.provenza@yolocounty.org
duane.chamberlain@yolocounty.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message: (Don't forget to replace the [x]'s with your information!)🔗
Dear Yolo County Supervisors,
My name is [YOUR NAME] and I am a resident of Yolo County. I am writing to demand that the Yolo County Board of Supervisors adopt a budget that prioritizes community well-being, and redirects funding away from the police and jails.
In the 2020-21 budget, Yolo County allocates 107 million dollars to our police system, an inordinate 20% of the county’s total budget of $539,088,239. This is compared to the 10% allocated to housing programs suggests how highly the county has valued punishing its citizens even while many of them are without secure housing. The picture becomes even clearer when one considers the county’s allocations for the expansions of the Leinberger Jail $33 million ($66 million over three years) and Monroe Jail $13 million ($41 million over three years) making up 100% of the proposed Capital Improvement budget for this year and 93% of last year's Capital Improvement Budget. The expansion of our carceral systems represents 28% of our budget during a year that is absolutely certain to see a downturn in revenue
The county may recoup these funds by decreasing the police and jail expansion budget.
I demand that the board of supervisors begin meaningfully defunding the Yolo County Sheriff’s Office and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, affordable housing programs, not police. I demand a budget that reflects the actual needs of Yolo County residents.
History has shown that police "reform" is not enough. No more money, and more importantly, no more lives must be lost to police. We must take a hard look at the way the current system in place fails to serve-and in fact actively harms-our community, and come together to reimagine the role of police in our city.
I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to invest in the people, not the police.
Thank you for your time,
[YOUR NAME][YOUR ADDRESS]
[YOUR EMAIL][YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by benevolentfoibles** [comment]
Thank you! Please let me know if there is anything I can add or clarify.

**Comment by mahrer** [comment]
Minor edits below:

---

To:
gary.sandy@yolocounty.org
oscar.villegas@yolocounty.org
don.saylor@yolocounty.org
jim.provenza@yolocounty.org
duane.chamberlain@yolocounty.org

Message:

Dear Yolo County Supervisors,

My name is [YOUR NAME] and I am a resident of Yolo County. I am writing to demand that the Yolo County Board of Supervisors adopt a budget that prioritizes community well-being, and redirects funding away from the police and jails.
In the 2020-21 budget, Yolo County allocates $107 million to our police system, an inordinate 20% of the county’s total budget of $539,088,239. When compared to the 10% allocated to housing programs, this suggests how highly the county has valued punishing its citizens even while many of them are without secure housing. The picture becomes even clearer when one considers the county’s $33 million ($66 million over three years) allocated to the Leinberger Jail, and $13 million ($41 million over three years) allocated to the Monroe Jail, making up 100% of the proposed Capital Improvement budget for this year and 93% of last year's Capital Improvement Budget. The expansion of our carceral systems represents 28% of our budget during a year that is absolutely certain to see a downturn in revenue. The county may recoup these funds by decreasing the police and jail expansion budget.

I demand that the board of supervisors begin meaningfully defunding the Yolo County Sheriff’s Office and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, affordable housing programs, not police. I demand a budget that reflects the actual needs of Yolo County residents.

History has shown that police "reform" is not enough. No more money, and more importantly, no more lives must be lost to police. We must take a hard look at the way the current system in place fails to serve-and in fact actively harms-our community, and come together to reimagine the role of police in our city.

I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to invest in the people, not the police.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
