### ISSUE TITLE
Letter and Email addresses for Davis, CA

### ISSUE THREAD

**Issue by benevolentfoibles** [defund12/defund12.org#1731]
To:🔗  blee@cityofdavis.org, gpartida@cityofdavis.org, warnold@cityofdavis.org, dcarson@cityofdavis.org, lucasf@cityofdavis.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]
Message: (Don't forget to replace the [x]'s with your information!)🔗

Dear Mayor Lee and Davis City Council,

My name is [YOUR NAME] and I am a resident of Davis. I am writing to demand that the Davis City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police.

In the 2020-21 budget, the City of Davis allocates 22.4 million dollars to our police system, an inordinate 12% of our total budget. We also want it considered the way Davis police department spends their funds and the goodwill of the counsel out if the interest of our citizen’s safety, spending last year with counsel approval $138,000 to purchase an armored vehicle and moving ahead with the purchase of $200,000 to purchase surveillance cameras – technologies designed to dominate and spy on our residents endangering lives in the interest of protecting property. 

In this moment of unprecedented vulnerability for so many of our residents and budget shortfalls, funds can be recouped by decreasing the police budget.

I demand that the City Council begin meaningfully defunding the Davis Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs, not police. I demand a budget that reflects the actual needs of Davis residents.

History has shown that police "reform" is not enough. No more money, and more importantly, no more lives must be lost to police. We must take a hard look at the way the current system in place fails to serve-and in fact actively harms-our community, and come together to reimagine the role of police in our city.

I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to invest in the people, not the police.

Thank you for your time,
[YOUR NAME][YOUR ADDRESS]
[YOUR EMAIL][YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by mahrer** [comment]
Minor edits below:

--

To:
blee@cityofdavis.org, gpartida@cityofdavis.org, warnold@cityofdavis.org, dcarson@cityofdavis.org, lucasf@cityofdavis.org

Message: (Don't forget to replace the [x]'s with your information!)

Dear Mayor Lee and Davis City Council,

My name is [YOUR NAME] and I am a resident of Davis. I am writing to demand that the Davis City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police.

In the 2020-21 budget, the City of Davis allocates 22.4 million dollars to our police system, an inordinate 12% of our total budget. Furthermore, the Davis Police Department does not spend their funds in the interest of our residents' safety. Last year, counsel approved $138,000 to purchase an armored vehicle and $200,000 to purchase surveillance cameras  – technologies designed to dominate and spy on our residents, endangering lives in the interest of protecting property. In this moment of unprecedented financial vulnerability and budget shortfalls, funds can be recouped by decreasing the police budget.

I demand that the City Council begin meaningfully defunding the Davis Police Department and re-allocating those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs, not police. I demand a budget that reflects the actual needs of Davis residents.

History has shown that police "reform" is not enough. No more money, and more importantly, no more lives must be lost to police. We must take a hard look at the way the current system in place fails to serve - and in fact actively harms - our community, and come together to reimagine the role of police in our city.

I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to invest in the people, not the police.

Thank you for your time,
[YOUR NAME][YOUR ADDRESS]
[YOUR EMAIL][YOUR PHONE NUMBER]

**Comment by root2point0** [comment]
on it

**Comment by benevolentfoibles** [comment]
Thank you all!
