### ISSUE TITLE
Please add Union City, CA

### ISSUE THREAD

**Issue by jb9000** [defund12/defund12.org#1747]
CarolD@UnionCity.org
EmilyD@unioncity.org
jaimep@unioncity.org
PatG@UnionCity.org
GaryS@UnionCity.org

Dear Union City Councilmembers,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the Union City City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police.

According to the 2019-2020 proposed budget, the City of Union City allocated $24.9 million to our police system, an inordinate 41% of our total budget. This is compared to just $3.4 million allocated towards economic & community development (5.6% of the budget).

I demand that the City Council begin to meaningfully defund the Union City Police Department and to reallocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. We need a budget that reflects the actual needs of Union City residents.

History has shown that police “reform” is not enough. Policing in America was developed to protect the institution of slavery. More money and training programs for police will not fix our current system. We must take a hard look at the way the current system in place fails to serve - and in fact actively harms - our community, and come together to reimagine the role of police in our city.

I am urging you to act on this as you develop the budget for the 2020-2021 fiscal year, and to invest in the people, not the police.

Thank you for your time,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by jb9000** [comment]
Source for Budget and contact info:

https://www.unioncity.org/DocumentCenter/View/3021/BB?bidId=
https://www.unioncity.org/202/Mayor-City-Council

**Comment by mahrer** [comment]
Hi @jb9000! Thanks so much for your submission.
The Union City letter is already on the site from a previous submission:
https://defund12.org/unioncity 

If you would like to make specific changes to the existing content, please open a new issue so we can follow-up.
Thank you!
