### ISSUE TITLE
Melbourne, FL

### ISSUE THREAD

**Issue by rawtilapia** [defund12/defund12.org#1765]
Kathy.Meehan@mlbfl.org, Paul.Alfrey@mlbfl.org, Tim.Thomas@mlbfl.org, mark.larusso@mlbfl.org, Yvonne.Minus@mlbfl.org, Debbie.Thomas@mlbfl.org, julie.sanders@mlbfl.org

Melbourne City Hall
900 E. Strawbridge Ave.
Melbourne, FL 32901

Dear Mayor, Vice Mayor, and Council Members,

My name is [YOUR NAME], resident of Melbourne, Florida . In light of the Black Lives Matter movement, I am writing to request that your budget for next year prioritizes community well-being and redirects funding away from law enforcement and corrections facilities to continue to disproportionately target Black Americans and other minorities.

This year’s budget allotted almost $24 million towards police services and merely $589,567 towards Melbourne’s Housing and Urban Development program, which is meant to “improve the quality of life of low income residents by providing housing assistance, improving public facilities, and providing opportunities for personal and economic growth, as well as grants management, solicitation, and compliance.” 

Budgeting more towards these types of programs would bolster communities and allow residents to move away from the types of behaviors that can cause criminality to begin with. Time and time again, it is found that policing disproportionately targets poorer people of color and addressing issues of poverty at the root will allow the community to spend less on its police force. 

I, as your constituent, urge you to take a closer look at what Melbourne can do to mitigate the harm that has been caused by the over policing of minorities throughout the years and become a leader in creating a community where residents have resources available to them to break the systemic cycle of criminality that has been the norm in the United States for so many years.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

Source: https://www.melbourneflorida.org/home/showdocument?id=5719

**Comment by mahrer** [comment]
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by root2point0** [comment]
on it
