### ISSUE TITLE
Tacoma, WA Justice for the Manslaughter of Manuel Ellis

### ISSUE THREAD

**Issue by pcnap** [defund12/defund12.org#182]
******* Justice for the Manslaughter of Manuel Ellis
******* Chris.beale@cityoftacoma.org Victoria.woodwards@cityoftacoma.org nicole.nowman@cityoftacoma.org
******* 
Hello Tacoma Officials, 

As a concerned citizen I am writing to you on behalf of the family of Manuel Ellis. I am demanding justice for the murder, by Tacoma law enforcement, of Manuel in Tacoma on March 3rd, 2020. Justice includes the release of compliant history of his murder, disciplinary record, toxicology reports of Manuel and the officers involved, release of autopsy and footage to the family of Manuel Ellis. 

Additionally, please use the power appointed by the people to you to fire and prosecute to officers Matthew Collins, Christopher Burbank, Masyih Ford, and Timothy Rankine involved in the manslaughter of Manuel Ellis. To further prosecute the injustice unpunished by police chief Donald Ramsdell, please terminate him immediately and replace him with an anti-racist and justice leader. 

Thank you

**Comment by mantism** [comment]
@pcnap do you have any information about the police budget that we can include?

**Comment by serifluous** [comment]
No info yet on 2021–2022 budget https://www.cityoftacoma.org/government/city_departments/office_of_management_and_budget

[2019–2020 budget](https://cms.cityoftacoma.org/finance/budget/2019-2020/2019-2020%20Adopted%20Budget%20Book.pdf) shows:
- $182,701,652 total Police funding (p206)
- $175,483,381 (96%) of that funding comes from the general fund (property, sales, utility, and business taxes). This makes up 34% of general fund expenditures (p21), and was a 13% increase from 2018 (p206).
- 2018 community survey showed significant disparities by race in satisfaction of city services, especially with Police Patrol, Police Investigations, among others (p75)

**Comment by serifluous** [comment]
Email is up on https://defund12.org/tacoma
