### ISSUE TITLE
Please add Memphis, TN

### ISSUE THREAD

**Issue by milkis2** [defund12/defund12.org#192]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

******* We Demand Divestment from Police and an Investment in Our Communities
******* JFord.Canale@memphistn.gov,Jeff.Warren@memphistn.gov,Chase.Carlisle@memphistn.gov,Martavius.Jones@memphistn.gov,Cheyenne.Johnson@memphistn.gov,JB.Smileyjr@memphistn.gov,Michalyn.Easter-Thomas@memphistn.gov,Edmund.FordSr@memphistn.gov,Worth.Morgan@memphistn.gov,Jamita.Swearengen@memphistn.gov,frank.colvettjr@memphistn.gov,Rhonda.Logan@memphistn.gov,Patrice.Robinson@memphistn.gov 
******* Dear City Council Members,
My name is [NAME] and I am a resident of [NEIGHBORHOOD]. I am asking to redirect money away from the Memphis PD and into the following social services: [LIST - Community Development, COVID Relief, Education, Parks & Recreation]. I request that an emergency meeting be called before the fiscal year goes into effect in order to deny the mayor’s proposed budget and reallocate these funds to resources the citizens can benefit from.
Thank you for your time,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by serifluous** [comment]
Memphis template added here: https://defund12.org/memphis
