### ISSUE TITLE
Please add Long Beach, CA

### ISSUE THREAD

**Issue by hunnyyy** [defund12/defund12.org#198]
To:
Mayor@longbeach.gov, District1@longbeach.gov, District2@longbeach.gov, District3@longbeach.gov, District4@longbeach.gov, District5@longbeach.gov, District6@longbeach.gov, District7@longbeach.gov, District8@longbeach.gov, District9@longbeach.gov

Subject: Defund the Police Department

Message:
My name is [YOUR NAME], I am a resident of district [YOUR DISTRICT NUMBER]. We demand reallocation of funding from LBPD to social and public programming that takes place in our communities. It is an outrage that 48.3% of the city funding for 2021 is planned towards the Police Department and that Chief Luna’s salary is equivalent to that of the president of the United States. 

We demand that the City Council defund the LBPD. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk Long Beach residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

It is your duty to represent your constituents. I am urging you to completely revise the Long Beach city budget for 2020-2021 fiscal year, and to fund #CareNotCops. Public opinion is with me.

Thank you for your time,

[YOUR NAME]

**Comment by hunnyyy** [comment]
To: mayor.helpdesk@lacity.org,councilmember.cedillo@lacity.org,councilmember.Krekorian@lacity.org,councilmember.blumenfield@lacity.org,david.ryu@lacity.org,paul.koretz@lacity.org,councilmember.martinez@lacity.org,councilmember.rodriguez@lacity.org,councilmember.harris-dawson@lacity.org,councilmember.price@lacity.org,councilmember.wesson@lacity.org,councilmember.bonin@lacity.org,councilmember.englander@lacity.org,councilmember.ofarrell@lacity.org,councilmember.huizar@lacity.org,councilmember.buscaino@lacity.org 🔗
CC: email@address.com 🔗
Subject: We demand a People's Budget 🔗
Message (Don't forget to replace the [x]'s with your information!) 🔗 
I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing, embodied by the LAPD’s well documented history of murdering Black people. We will no longer accept empty gestures and suggestions of “reform.” This includes Mayor Garcetti’s paltry 5% proposed cut with no clarity as to where these funds will be redirected, if at all. We are demanding that our voices be heard now, and that real change be made to the way this city allocates its resources.

We are in the midst of a pandemic with severe economic consequences. Over 50% of Angelenos are unemployed, and we can expect 42% lasting unemployment. Over 50% of those in this city are renters. When people are unemployed, they cannot pay rent. Prior to the pandemic, 60k people were unhoused; the evictions and economic insecurity caused by COVID-19 will bring that number even higher.

We demand that the City Council meaningfully defund the LAPD. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk Angelenos during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

Although City Council has avoided voting or revising Mayor Garcetti’s draconian budget proposal, the document is back in your hands. It is your duty to represent your constituents. I am urging you to completely revise the LA budget for 2020-2021 fiscal year, and to fund #CareNotCops. You need to adopt a People’s Budget. Public opinion is with me.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by hunnyyy** [comment]
Please do not post on the website yet I am waiting for confirmation from community leaders that this is in alignment with all of the demands

**Comment by hunnyyy** [comment]
Good to post thank you

**Comment by averymcguirt** [comment]
Adding directly via siteleaf now. @hunnyyy I will make minor tweaks to conform to our style guide (i.e. remove hashtags) https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md

Closing the issue but reopen and comment if any questions. Thank you for your contribution!
