### ISSUE TITLE
Fairfax County VA

### ISSUE THREAD

**Issue by charpark1355** [defund12/defund12.org#214]
chairman@fairfaxcounty.gov
mason@fairfaxcounty.gov

A subject message for the email : Fairfax County Resident for Defunding FCPD

To Chairman Jeffrey McKay, the Fairfax County Board of Supervisors, and Fairfax County Elected Officers

My name is [YOUR NAME], and I am a resident of Fairfax County. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-blackness, and immediate reform in how black people are treated in America. Our city has been at the forefront of much of this action. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

FCPD has been a waste of our resources. Last year, the Police Department cost the county $176,424,490. While we've been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police.

I call on you to slash the FCPS budget and instead use those extraordinary resources towards funding what Black and Brown communities need to be safe and healthy: COVID19 relief, housing, healthcare, treatment, healing, cooperative businesses, community centers, community-led organizations and projects.

We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely,

[YOUR NAME]

[YOUR ADDRESS]

[YOUR EMAIL]

[YOUR PHONE NUMBER]

**Comment by mantism** [comment]
Raised a PR, I included emails for the other members of the board.

**Comment by teddywilson** [comment]
What is the status of this PR. Can you update here?

**Comment by teddywilson** [comment]
@mantism

**Comment by mantism** [comment]
@teddywilson it has been merged
