### ISSUE TITLE
Please add San Antonio, TX

### ISSUE THREAD

**Issue by urmildivecha** [defund12/defund12.org#226]
DUE TO HIGH VOLUME EMPTY ISSUES WILL BE IMMEDIATELY CLOSED. PLEASE PROVIDE ALL INFORMATION. THANK YOU!!!! :^)

******* A subject message for the email
******* A list of emails (at least one) for the government officials you’d like to receive the message
******* A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by lytxmom** [comment]
SUBJECT: Decrease funding for SAPD in the 2021 budget

EMAIL: ron.nirenberg@sanantonio.gov (Mayor of San Antonio)

MESSAGE: Hello,

My name is [YOUR NAME ]. I am a resident of San Antonio, Texas and I am emailing today to demand a complete overhaul on our San Antonio Police Department in light of the Black Lives Matter protests being demonstrated across the US, but specifically our city.

Currently, more than a third of the city’s $1.3 billion operating budget is spent on the police department. At the same time, studies of the San Antonio PD have proven SAPD officers use force at [higher rates against minorities.](http://projects.expressnews.com/analysis-sapd-officers-use-force-at-higher-rates-against-minorities) I am asking you, Mayor Nirenberg, to make a more overt and visible commitment to the city’s Black and Brown communities to combat an over-investment in their criminalization and surveillance. I therefore demand that you find ways to redirect money away from the SAPD’s overinflated budget. I urge you to pressure the city council for an ethical and equal reallocation of the city’s expenditures, away from the SAPD, and towards sectors that facilitate the dismantling of racial and class inequality.

Now especially, you can take a supportive stand on racial and social justice by significantly defunding policing and investing in the community instead—starting with housing, transportation, education, community centers, and community-led organizations and projects.

Can I count on you to consider an alternative budget that puts a focus on social services programs?

Sincerely,
[NAME]
[ADDRESS]
[PHONE]
[EMAIL]

**Comment by caldric** [comment]
On it.
