### ISSUE TITLE
Erie, Pa 

### ISSUE THREAD

**Issue by supbri96** [defund12/defund12.org#233]
Head Of Finances 
PLichtenwalter@erie.pa.us
Economic Community Development
CGroner@erie.pa.us
Community Liason 
MOutlaw@erie.pa.us
Citizen Relations 
MSala@erie.pa.us
Executive asst. to the Mayor 
MBruce@erie.pa.us
Chief of Police 
DSpizarny@erie.pa.us

Erie City Council 
President James Winarski
Jwinarski@erie.pa.us

Lallen@erie.pa.us
Dbrennan@erie.pa.us
Ebrzezinski@erie.pa.us
Mkeys@erie.pa.us
Kschaaf@erie.pa.us
Mwitherspoon@erie.pa.us

Dear Erie Mayor's Office and City Council Members, 
My name is ______ from _______. Nearly a quarter of Erie's overall budget goes into funding for the Erie Beureau of Police, this is unacceptable. I urge you towards an ethical and equal reallocation of the ERIE expense budget, away from ERIE PD and towards social services and educational services.

**Comment by ctneal91** [comment]
On it

**Comment by ctneal91** [comment]
@supbri96 can we get some more detailed budget information or police information? I think that will make the letter more impactful. Check out some other letters for ideas! Otherwise, I am ready to add the letter

**Comment by supbri96** [comment]
Erie's 2020 police budget is allocated 31 million out of an overall 90 million budget. Erie also received 2 grants, 1st one for 958,434 dollars allocated to strategic crime reduction in lower East side Erie neighborhoods, primarily Black communities. 6th-26th and Wayne + German. 2nd is 247,000 dollar grant for body cameras. Both granted in 2019 but to be implemented summer of 2020.
