### ISSUE TITLE
Please Add Providence / Rhode Island (updated) 

### ISSUE THREAD

**Issue by Deadwitchcraft** [defund12/defund12.org#24]
Governer: Gina Raimondo
governor@governor.ri.gov

Mayor: Jorge Elorza
Mayor@mayor.ri.gov

Ward2@providenceri.gov
Ward3@providenceri.gov
Ward4@providenceri.gov
Ward5@providenceri.gov
Ward6@providenceri.gov
Ward7@providenceri.gov
Ward8@providenceri.gov
Ward9@providenceri.gov
Ward10@providenceri.gov
Ward11@providenceri.gov
Ward12@providenceri.gov
Ward13@providenceri.gov
Ward14@providenceri.gov
Ward15@providenceri.gov 

The current City Council consists of:
Ward 1: Vacant
Ward 2: Councilwoman Helen Anthony
Ward 3: Councilwoman Nirva LaFortune
Ward 4: Councilman Nicholas J. Narducci, Jr., Senior Deputy Majority Leader
Ward 5: Councilwoman Jo-Ann Ryan, Majority Leader
Ward 6: Councilman Michael Correia, Council President Pro Tempore
Ward 7: Councilman John Igliozzi, Majority Whip
Ward 8: Councilman Jim Taylor
Ward 9: Councilwoman Carmen Castillo
Ward 10: Councilman Pedro Espinal
Ward 11: Councilwoman Mary Kay Harris, Deputy Majority Leader
Ward 12: Councilwoman Katherine Kerwin
Ward 13: Councilwoman, Rachel Miller
Ward 14: Councilman David Salvatore
Ward 15: Councilwoman Sabina Matos, Council President

**Comment by teddywilson** [comment]
We are currently handling a lot of requests - please include the following information with your request:

A subject message for the email
A list of emails (at least one) for the government officials you’d like to receive the message
A detailed message concerning the budgeting decisions that are at stake in your community
See our current links for examples at https://defund12.org.

Thank you!!

**Comment by Deadwitchcraft** [comment]
governor@governor.ri.gov
Mayor@mayor.ri.gov
Ward2@providenceri.gov
Ward3@providenceri.gov
Ward4@providenceri.gov
Ward5@providenceri.gov
Ward6@providenceri.gov
Ward7@providenceri.gov
Ward8@providenceri.gov
Ward9@providenceri.gov
Ward10@providenceri.gov
Ward11@providenceri.gov
Ward12@providenceri.gov
Ward13@providenceri.gov
Ward14@providenceri.gov
Ward15@providenceri.gov

Subject: Defund the Police Department


Hello,  
my name is [NAME] and I am a resident of Providence. I am writing to demand that Governer Raimondo, Mayor Elorza and the members of the City Council do everything in their power to adopt a budget that redirects all funds from the Police Department and prioritizes community well being, mental health and the needs of its residents.  It has become clear that Police Departments are ineffective at keeping local communities safe, while being incubators for racism and the protection of racists. While Providence has recieved a $700,000 grant to formulate a Behavioral Health Response Team, that amount is a mere drop in the bucket of the nearly $90 million budgeted for Police in 2021.  The current budget proposal has allocated $961,000 on guns and ammunition, $1,461,620 for 50 new police recruits, not to mention $14.9 million for uniforms and "wearing apparel", presumably including more of the riot gear that is currently being used to attack peaceful protesters.  
I also strongly urge the city to enact legislation instituting a community elected Civilian Police Accountability Council with the ability to review all violent interactions and institute disciplinary actions, including firing.  
Providence may be a small city, but we have shown that we can make a huge impact on America at large.  We desperately need to change our financial priorities and let our tax dollars go to communities, not cops.

Thank you for your time,

[name]
[email address]

**Comment by serifluous** [comment]
- Confirmed $700k grant: https://www.providenceri.gov/ppd-smart-policing-innovation-grant/
- Confirmed overall police budget: page 1 https://www.providenceri.gov/wp-content/uploads/2020/05/FY21-Proposed-Budget-Book-for-web.pdf
- Detailed police budget (guns and ammunition, new recruits, uniforms): @Deadwitchcraft Can you share where you're getting the budget numbers for these? I'm seeing something different on page 36 of the above link.

**Comment by Deadwitchcraft** [comment]
https://data.providenceri.gov/view/qhq3-hviv

I got my numbers from that nightmare of a website. I recommend opening it on a computer. Thank you for doing this!

**Comment by hexelgon** [comment]
Thank you so much for this!! While they work on adding this to defund12.org, people can use this document (https://docs.google.com/document/d/1YgusLVk2ehTB7dMHDrAQHAW3ACqmuW8OHausF-n1hSc/edit?usp=sharing) to send a (slightly modified) version of that message.

**Comment by Deadwitchcraft** [comment]
Thank you thank you!

**Comment by teddywilson** [comment]
Awesome, thanks so much everyone.

Can you provide a new template that adheres to our newly created style guide?

https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md

**Comment by hexelgon** [comment]
Hi Teddy, does this work?

Hello,

My name is [name] and I am a resident of Providence. I am writing to demand that Governor Raimondo, Mayor Elorza and the members of the City Council do everything in their power to adopt a budget that redirects all funds from the Police Department and towards community wellbeing, mental health and the needs of its residents. It has become clear that police forces are ineffective at keeping local communities safe, and that they perpetuate the oppression of residents who are people of color, undocumented, mentally ill, disabled, and LGBTQ. While Providence has received a $700,000 grant to formulate a Behavioral Health Response Team, that amount is a mere drop in the bucket of the nearly $90 million budgeted for Police in 2021. The current budget proposal has allocated $961,000 on guns and ammunition, $1,461,620 for 50 new police recruits, not to mention $14.9 million for uniforms and "wearing apparel,” presumably including more of the riot gear that is currently being used to suppress peaceful protests. Imagine how much those dollars could accomplish when used to fund low-income and public housing, education, resources for formerly incarcerated individuals, and public transportation, as Direct Action for Rights and Equality has demanded.

Providence may be a small city, but we have shown that we can make a huge impact on America at large. We desperately need to change our financial priorities and let our tax dollars go to communities, not cops.

Thank you for your time,

[name]
[address]
[email address]
[phone number]

**Comment by serifluous** [comment]
I still can't find the original budget numbers. I grabbed this info from the link posted above and am suggesting the edits below. For anyone from Providence, please let me know if this isn't ok!:

![Screenshot of Providence police funding](https://i.imgur.com/tarRyag.png)

**Edits in bold:**

Hello,

My name is **[NAME]** and I am a resident of Providence. I am writing to demand that Governor Raimondo, Mayor Elorza**,** and the members of the City Council do everything in their power to adopt a budget that redirects all funds from the Police Department and towards community wellbeing, mental health and the needs of its residents. It has become clear that police forces are ineffective at keeping local communities safe, and that they perpetuate the oppression of residents who are people of color, undocumented, mentally ill, disabled, and LGBTQ.

While Providence has received a $700,000 grant to formulate a Behavioral Health Response Team, that amount is a mere drop in the bucket of the nearly $90 million budgeted for Police in 2021. The current budget proposal has allocated **$154,450 on guns and ammunition, a 19% increase from 2020, which itself was a 44% increase from previous year. Not to mention the $963,626 that is** allocated for uniforms and "wearing apparel,” presumably including more of the riot gear that is currently being used to suppress peaceful protests. Imagine how much those dollars could accomplish when used to fund low-income and public housing, education, resources for formerly incarcerated individuals, and public transportation, as Direct Action for Rights and Equality has demanded.

Providence may be a small city, but we have shown that we can make a huge impact on America at large. We desperately need to change our financial priorities and let our tax dollars go to communities, not cops.

Thank you for your time,
**[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]**

**Comment by todd-m** [comment]
on it

**Comment by Deadwitchcraft** [comment]
I got the number from this article. Feel free to change it tho

FY21: $1,461,620 (salaries, uniforms and testing costs for 50 recruits anticipated class start winter
2021)
FY20: $2,760,516 (48 officers hired 6/24/19)

https://www.abc6.com/mayor-elorza-unveils-506-million-budget-for-fy-2021/#:~:text=PROVIDENCE%2C%20R.I.%20(WLNE)%20%E2%80%93,from%20the%20FY%202020%20budget.

**Comment by serifluous** [comment]
@Deadwitchcraft  perfect, thank you! Sorry for all the back and forth

**Comment by hexelgon** [comment]
Thank you so much for your work on this!
