### ISSUE TITLE
Please add Durham, NC 

### ISSUE THREAD

**Issue by hahaNC** [defund12/defund12.org#256]
******* A subject message for the email: Defund the Police & Reallocate Funds
******* A list of emails: Steve.Schewel@durhamnc.gov, council@durhamnc.gov
******* A detailed message concerning the budgeting decisions that are at stake in your community

Dear Mayor Schewel & City Council Members: 

My name is ________. I am a resident of Durham.
I am writing to object to the allocation of over $70M to the Durham Police Department in the 2020-2021 city budget. It is indefensible to increase the police budget when city workers face layoffs and denial of wage increases, and thousands of our community members face unemployment, and housing and food insecurity in the midst of the COVID-19 pandemic.
 The police cannot protect us from these challenges. In fact, more often than not, when police are dispensed, rather than more qualified medical, psychiatric, and social work professionals, the effect is to bring violence where none previously existed, despite the best efforts of all involved. Moreover, to paraphrase an existing council member, it is not cities with the most police, but the most resources, that are the safest.  To that end, I make a two-fold request to the council: 
1. Reallocate all proposed increases in police budget to Durham Public Schools, affordable housing and rent subsidies, eviction diversions, food resources, and medical supplies, which have both immediate and longstanding consequences that will more positively affect our current residents. 
2. Implement a 5-year plan to reallocate---at a minimum—50% of existing police resources to institutions and experts better equipped to deal with many of the issues DPD have been conscripted, without adequate training, to do. Resources should be allocated to EMTs, social workers, and other social service providers to respond to the majority of current police business, including health and wellness checks, domestic/sexual violence situations, and basic bureaucratic documentation around break-ins, vandalism, wrecks, etc. Additional money should go to community education around de-escalation and community support for drug, SV/DV, and property-related incidents.  I recommend that you follow the lead of progressive cities such as Austin, TX and Camden, NJ in this regard. There is no reason to have armed officers responding the majority of emergency needs in Durham. Finally, I request that you divest over half the force of offensive weapons. Offensive weapons are known to escalate violence, especially when deployed in situations where none existed before. Almost all the current litany of Black men and women dead from police violence were non-violent, unarmed people, for whom armed police became the site of death and violence. We, as a community, need to commit to non-violent policing and pro-people programs.  Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by teddywilson** [comment]
Durham is live! closing this one out.
