### ISSUE TITLE
Please add Las Vegas, NV

### ISSUE THREAD

**Issue by phelanj** [defund12/defund12.org#266]
To: officeofthemayor@lasvegasnevada.gov

Subject: Decrease Police Brutality NOW

My name is [First Name, Last Name]. I am a resident of Las Vegas, NV and I am emailing today to demand that you utilize your position in office to enforce the implementation of the following policies on LVMPD immediately to decrease police brutality in Las Vegas:

• Ban the use of chokeholds and strangleholds by law enforcement
• Require exhausting all other means before shooting
• Ban shooting at moving vehicles
• Require comprehensive reporting by law enforcement
• Ban the use of tear gas on peaceful protesters
• Ban the use of rubber bullets on peaceful protesters

Law enforcement should be there to protect its civilians, not use militarized weapons against them, especially when our tax payer dollars fund these weapons. The abuse of power that I’ve witnessed documented on video shared across social media these past couple of days documenting the police brutality used by the LVMPD is atrocious. Citizens of Las Vegas are watching what you do next in these crucial moments of history. You have the power to make real change today.

Sincerely,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by serifluous** [comment]
Las Vegas being added in PR #360
