### ISSUE TITLE
baltimore email template

### ISSUE THREAD

**Issue by poochiepee** [defund12/defund12.org#273]
email: eric.costello@baltimorecity.gov

template: 

[Dear Eric T. Costello, 

My name is (NAME) and I am a Baltimore resident. In the midst of this pandemic and public outcry against police brutality, it feels more inappropriate than ever to propose increases to the BPD budget from $530 Million to $545 million. I urge you to ethically reallocate the Baltimore City Expense Budget, divesting interest in the BPD, and investing social services and education programs, effective at the beginning of FY 2021. Investment in programs such as the Affordable Housing Trust Fund, Baltimore Children and Youth Fund, Safe Streets Baltimore, the Office of Employment and Development, or the Department of Health, shows our commitment to communities and the vision that all Baltimore residents deserve to thrive. Historically, the city government has spent far more on police than on public health, homeless services, youth services, and other vital agencies. It’s time to defund the BPD’s harmful expansion into homeless services, schools, youth services, mental health, and other social services where police don’t belong. It’s time to protect investments in human services, the social safety net, and racial and economic justice. I am writing to insist that the upcoming BBMR budget hearings for FY 2021 reflect the voices and needs of Baltimore’s citizens. I am asking that city officials lobby intense care, attention and effort towards finding sustainable, longterm change. 

Thank you, (Name) June 4, 2020]

**Comment by emilyhuntsman** [comment]
on it! Do you mind if we also add in the city council as recipients?

**Comment by poochiepee** [comment]
no not at all here is a page with all their contact.

http://www.baltimorecitycouncil.com/council-members

also important to not i did not make this template, anna krooks (@annay2k)
made it.

Thank you for all the work you are doing.

Patrick

**Comment by emilyhuntsman** [comment]
I will submit this for approval

**Comment by rianciela** [comment]
This is written for State Senators and Delegates of the MD State Legislature -- so people could use the link I gave above to figure out who their state senator and delegates are for their particular district -- or could just do all of them together. Here is the list of them all together, thanks!

antonio.hayes@senate.state.md.us,  jill.carter@senate.state.md.us, mary.washington@senate.state.md.us, cory.mccray@senate.state.md.us, bill.ferguson@senate.state.md.us, charles.sydnor@senate.state.md.us, frank.conaway@house.state.md.us, nick.mosby@house.state.md.us, melissa.wells@house.state.md.us, dalya.attar@house.state.md.us, tony.bridges@house.state.md.us, samuel.rosenberg@house.state.md.us, curt.anderson@house.state.md.us, regina.boyce@house.state.md.us, maggie.mcintosh@house.state.md.us, keith.haynes@house.state.md.us, chanel.branch@house.state.md.us, talmadge.branch@house.state.md.us, stephanie.smith@house.state.md.us, luke.clippinger@house.state.md.us, robbyn.lewis@house.state.md.us, brooke.lierman@house.state.md.us,
