### ISSUE TITLE
Raleigh - https://tinyurl.com/yal8sfsz

### ISSUE THREAD

**Issue by chatcher101** [defund12/defund12.org#29]
^^^ link above is the mailto but i'm not sure if that's what's easiest so I'm copying all the other stuff here:

TO: mary-ann.baldwin@raleighnc.gov
CC: jonathan.melton@raleighnc.gov, nicole.stewart@raleighnc.gov, patrick.buffkin@raleighnc.gov, david.cox@raleighnc.gov, corey.branch@raleighnc.gov, saige.martin@raleighnc.gov, david.knight@raleighnc.gov

SUBJECT: Decrease funding for police in the proposed budget

Dear Mayor Baldwin,

My name is [NAME] and I am a resident of Raleigh. I urge you and the rest of the city council to amend or deny the proposed budget for 2021. I would like to redirect money away from RPD and into social service programs that will benefit public health and our own communities, especially communities of color. The proposed budget for 2021 suggests that the largest fraction of the city’s budget should go to policing ($110,650,573), which is over 60% larger than even the second largest allocation of funds, fire ($67,687,901). If this is truly representative of the council’s thoughts on how funds should be allocated in a city in which over 6,000 of my neighbors (Raleigh + Wake County) are currently experiencing homelessness and in which nearly 100,000 of my neighbors (Raleigh + Wake County) are impoverished and at risk of becoming homeless (www.raleighrescue.org), I am ashamed to call Raleigh my home and I am ashamed to call you my elected officials. 

Crime is not random. Crime usually happens when someone has been unable to meet their basic needs through other means. So, to really "fight crime," we don't need more police officers - we need more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding! 

We don't need a militarized police force. We need to create a space in which more mental health service providers, social workers, victim/survivor advocates, religious leaders, neighbors, and friends - all of the people who really make up our community - can look out for one another. Mayor Baldwin, will you look out for me, and will you look out for us?

Thank you,
[NAME]

**Comment by minicreative** [comment]
Add this now, thank you!

**Comment by minicreative** [comment]
Added with 309d965f69dd39572e00e6e9e37a5c821a633dc6, thank you!!

**Comment by dschwentker** [comment]
The City Council ccs are not being populated for the Raleigh email.

**Comment by minicreative** [comment]
They come up in the email client for me but are not being displayed on the site - I'll fix this. Do they not come up in the email for you?

**Comment by teddywilson** [comment]
This is working fine for me. Verified coming up on site and in mail client. Please reopen if the issue persists.
