### ISSUE TITLE
Add Arlington, VA

### ISSUE THREAD

**Issue by ackoch3** [defund12/defund12.org#325]

**Comment by ritikabhasker** [comment]
To the Arlington County Board
CountyBoard@arlingtonva.us

Libby Garvey: lgarvey@arlingtonva.us
Matt de Ferranti: mdeferranti@arlingtonva.us
Katie Cristol: kcristol@arlingtonva.us
Christian Dorsey: cdorsey@arlingtonva.us

My name is [YOUR NAME], and I am a resident of Arlington, VA. This past week, our nation has been gripped by protests calling for rapid and meaningful reevaluation of the role of policing in our communities and an end to racism and anti-Blackness. Our county recently withdrew police presence from DC, and is re-evaluating our mutual aid obligations to the city, but that is not enough. 

Arlington's public would be better served by dedicating resources to addressing homelessness, strengthening mental health resources, increasing affordable housing, and other community services. I call on you to meaningfully restrict the Arlington PD budget and instead use those extraordinary resources for programs that are much more effective at promoting safety and social equity than policing and incarceration.

We can be a beacon for other counties to follow if only we have the courage to change. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by serifluous** [comment]
Duplicate request in issue #453

**Comment by teddywilson** [comment]
Closing this duplicate out.
