### ISSUE TITLE
please add Santa Rosa, CA

### ISSUE THREAD

**Issue by ariririririri** [defund12/defund12.org#337]
SUBJECT: Santa Rosa Resident for Defunding the SRPD

EMAILS: tschwedhelm@srcity.org, vfleming@srcity.org, jsawyer@srcity.org, crogers@srcity.org, eolivares@srcity.org, hjtibbetts@srcity.org, rdowd@srcity.org, dguhin@srcity.org, cmcbride@srcity.org, jnutt@srcity.org, sgallagher@srcity.org, cMcBride@srcity.org, swilliams@srcity.org

MESSAGE:

Dear Santa Rosa City Leaders: 

I am writing you today out of great concern for our community and our future. I am [INSERT IDENTIFYING INFO BUT ONLY AS MUCH AS YOU FEEL COMFORTABLE WITH INCLUDING THE AMOUNT OF TIME YOU'VE BEEN A RESIDENT OF SR, WHERE YOU WORK, IF YOU'RE A LOCAL BUSINESS OWNER, ANY OTHER COMMUNITY TIES LIKE FAITH COMMUNITY OR OTHER COMMUNITY-BASED ORGS] 

As black people across the United States are dying at the hands of law enforcement, our communities are mourning the deaths of George Floyd, tortured to death by Minneapolis police, and Breonna Taylor an EMT killed by officers while asleep in her bed in Louisville. Their names are added to a devastatingly long list of Black people who have been killed at the hands of law enforcement - it is time for us to make different decisions. We demand change in the operation of the criminal legal system, we demand that we take care of our community instead of criminalizing those amongst us who need help, and we demand that police are not the front line responders to every emergency or call for help. 

In Santa Rosa, fulfilling these demands requires making dramatic changes in our city’s budget. Our budget should reflect our values. The current budget does not. While I understand that due to Measure O, the City Council is not able to reduce the allocated budget expenditures to police, I am writing to you today to demand that the Santa Rosa City Council invest in alternative responses to law enforcement that actually keep our community safe and healthy. I also call on our collective community to reconsider Measure O’s policy, and work to change it. Law Enforcement should be the Exception, not the rule. 

Increasingly, The United States has responded to every emergency or call for help with law enforcement. Meanwhile, our communities desperately lack meaningful access to healthcare, employment, and housing. Instead, we have the largest military budget in the world, and some of the most well-funded and militarized police departments. Policing and militarization overwhelmingly dominate the bulk of national and local budgets. In fact, police and military funding has increased every single year since 1973, and at the same time, while funding for public health has decreased every year. According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections.[1] In 2017, they spent $194 billion. A 220 percent increase. In Santa Rosa, funding for local police makes up 32% of the city budget.[2] Housing and community services accounts for only 1%. That is a staggering and illuminating statistic. What does it say about our community? It says that rather than responding to the needs in our community with meaningful support and resources, we respond with law enforcement. This is unacceptable. Where could that money go? It could go towards building healthy communities, to housing development, to neighborhood infrastructure, to education, to childcare. The possibilities are endless. 

Therefore we demand the following: 
The creation of a local police commission and a city council subcommittee on alternatives to policing. A commitment to changing Measure O, so we may act to reduce funding for police in the Santa Rosa City budget, and instead invest more in housing and community services. Investment in local alternatives to policing. This should include investments in existing community based organizations as well as additional funding to support the creation of alternative responses to community needs and emergencies, including: Unarmed mediation and intervention teams, Social worker teams and mental health experts, as well as Restorative Justice programs. We further request that an emergency meeting of the full city council be immediately scheduled to address these concerns. You are welcome to contact me with any questions or concerns regarding these requests. 

Regards, [FULL NAME EMAIL PHONE NUMBER CITY COUNCIL DISTRICT  https://srcity.org/2864/Find-My-Council-District]

[1] https://www.urban.org/policy-centers/cross-center-initiatives/state-and-local-finance-initiative/state-and-local-backgrounders/police-and-corrections-expenditures 
[2] https://srcity.org/ArchiveCenter/ViewFile/Item/4172

**Comment by emilyhuntsman** [comment]
on it!
