### ISSUE TITLE
add Westchester County, NY

### ISSUE THREAD

**Issue by lauren** [defund12/defund12.org#347]
emails: CE@westchestergov.com, kjenkins@westchestergov.com, lcs5@westchestergov.com, dept-of-finance@westchestergov.com, Covill@westchesterlegislators.com, boykin@westchesterlegislators.com, awilliams@westchesterlegislators.com, barr@westchesterlegislators.com, borgia@westchesterlegislators.com, burrows@westchesterlegislators.com, clements@westchesterlegislators.com, cunzio@westchesterlegislators.com, johnson@westchesterlegislators.com, kaplowitz@westchesterlegislators.com, maher@westchesterlegislators.com, parker@westchesterlegislators.com, perez@westchesterlegislators.com, shimsky@westchesterlegislators.com, testa@westchesterlegislators.com, tubiolo@westchesterlegislators.com, williams@westchesterlegislators.com

Subject: Commit to Reallocation for Social Equity 
Message:
Dear Westchester County Legislature,

Hi, my name is [NAME] and I am a resident of [TOWN]. I am asking you to reallocate money away from the Westchester County Police Department. According to a 2018 report, black people are the subjects of 42% of all arrests in Westchester despite making up only 14% of our population: https://www.criminaljustice.ny.gov/crimnet/ojsa/comparison-population-arrests-prison-demographics/2018%20Population%20Arrests%20Prison%20by%20Race.pdf. Furthermore, black people convicted of a crime in Westchester are sentenced to jail time at a higher rate than any those of any other race, across all types of crimes: https://www.criminaljustice.ny.gov/crimnet/ojsa/dispositions-adult-arrest-demographics/2018/Westchester.pdf

County police is the third-highest line-item in the 2020 county budget, but research shows that a living wage, access to health services and treatment, educational opportunity, and stable housing are far more successful at promoting community safety than policing and prisons. As such, I demand a meaningful reallocation of PD funds towards healthcare and social programs.

Sincerely, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by unitof** [comment]
I got this!

**Comment by lauren** [comment]
@unitof I decided to open a PR for it

**Comment by unitof** [comment]
Sorry, got pulled away midway through. No prob.

**Comment by volckeep** [comment]
These addresses were undeliverable. 
gab6@westchestergov.com
vxp1@westchestergov.com
jxt2@westchestergov.com
mkk8@westchestergov.com

**Comment by unitof** [comment]
Their own website has only contact forms, no listed emails: https://westchesterlegislators.com/district-legislators

This may be outdated but has very different emails at a different domain: http://www.childcarewestchester.org/pdf/Contact_Your_Representatives_brochure_2018.pdf

And this campaign confirms the syntax should be `[lastname]@westchesterlegislators.com`., with first initial prepended for a duplicate last name: http://www.dontkillwestchestercoops.org/wp-content/uploads/2018/02/Legislator-numbers-1.pdf

**Comment by unitof** [comment]
Would love if anyone from Westchester could chime in if they know something, but looking like maybe these should switch to the @westchesterlegislators.org domain.

**Comment by lauren** [comment]
@unitof I live in westchester and got the emails from the brochure you pointed to. 

I did do a test send of the email locally and got the same bounce message. However none of the addresses that bounced are in my to list, so one of them must alias to those. I decided to submit the PR anyway believing that emailers getting a bounce for a handful of emails on an alias is not really a big problem. As you can see from the screenshot of the reply I received, the individual emails are correct. 

![D4FAE940-D527-42C8-B828-C62F80C75ACB](https://user-images.githubusercontent.com/28343/83949972-2a7eca80-a7f5-11ea-9685-c2343fc2e554.png)

**Comment by lauren** [comment]
dept-of-finance@westchestergov.com Is most likely to be the alias so maybe we should just remove that one.

**Comment by lauren** [comment]
@unitof I removed the dept-of-finance email from my PR :)
