### ISSUE TITLE
Please add Las Vegas Nevada!!! (There is another request already but the body asks for reform, not defunding!)

### ISSUE THREAD

**Issue by bernardsanders** [defund12/defund12.org#353]
SUBJECT- Demand for Redistribution of Funds Allocated To LVMPD
RECIPIENTS- Mayor Carolyn Goodman: cgoodman@lasvegasnevada.gov, Office of the Mayor: officeofthemayor@lasvegasnevada.gov, Chief Financial Officer for City of Las Vegas Gary Ameling: gameling@lasvegasnevada.gov 

BODY-
I am a resident of Las Vegas. I am writing to demand that Mayor Carolyn Goodman and City Council do everything in their power to adopt a budget that prioritizes our community well being and redirects funding away from the police in the next budget evaluation period.

We have seen mounting evidence that police departments are racist and ineffective institutions that put citizens at risk of injury and death, yet the police budget accounts for 13% of our general fund.

I ask that you redirect the majority of the $174M allotted for crime prevention towards community programs that provide citizens with basic human needs like affordable healthcare and housing. With nearly 35% of our residents currently unemployed, we need funding to address the needs of people hurting from the effects of COVID 19, people experiencing homelessness, and the marginalized communities in our city.

I also STRONGLY URGE the City Council to enact legislation instituting a community elected Civilian Police Accountability Council with the following powers; ability to review and change disciplinary actions, review all violent interactions, and impose discipline including firing.

Our community is in pain along with the nation. We desperately need to change what our community prioritizes.

Thank you for your time,

[YOUR NAME]

[YOUR ADDRESS]

[YOUR EMAIL]

[YOUR PHONE NUMBER]

**Comment by emilyhuntsman** [comment]
On it, Senator!
