### ISSUE TITLE
Wilmington, DE

### ISSUE THREAD

**Issue by haleyyum** [defund12/defund12.org#371]
**To:** mspurzycki@WilmingtonDE.gov, jcarney@state.de.us, MMeyer@nccde.org, jtogden@WilmingtonDE.gov, dsophrin@WilmingtonDE.gov, mgjopson@WilmingtonDE.gov , alance@WilmingtonDE.gov, karen.hartley-nagle@newcastlede.gov, kenneth.woods@newcastlede.gov, dee.durham@newcastlede.gov, janet.kilpatrick@newcastlede.gov, penrose.hollins@newcastlede.gov, elisa.diller@newcastlede.gov, david.carter@newcastlede.gov, george.smiley@newcastlede.gov, john.cartier@newcastlede.gov, timothy.sheldon@newcastlede.gov, jea.street@newcastlede.gov, david.tackett@newcastlede.gov, james.bell@newcastlede.gov

**Subject** Wilmington (DE) demands a People's Budget

**Message** (Don't forget to replace the [x]'s with your information!) 

“To whom it may concern,

I am a resident of [YOUR DISTRICT]. I am writing to demand that the City Council adopts a People’s Budget that prioritizes community well-being and redirects funding away from the police.

We are in the midst of widespread upheaval over the systemic violence of policing. We will no longer accept empty gestures and suggestions of “reform.” We are demanding that our voices be heard now, and that real change be made to the way this city allocates its resources.

Support for communities in need is necessary now, more than ever. We demand that the City Council defund the NCCPD. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk Wilmington residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to fund #CareNotCops. You need to adopt a People’s Budget. Public opinion is with me.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now

**Comment by haleyyum** [comment]
thank you!

**Comment by ctneal91** [comment]
PR #372
