### ISSUE TITLE
Ripon Resident for Defunding RPD

### ISSUE THREAD

**Issue by kylaris3** [defund12/defund12.org#390]
To: jparks@cityofripon.org, ddegraaf@cityofripon.org, uecker105@yahoo.com, mrestuccia@cityofripon.org, leo.zuber@yahoo.com, kwerner@cityofripon.org

Subject: Ripon Resident for Defunding RPD

Message: 

"To the City Administrator and the Ripon City Council

My name is [YOUR NAME], and I am a resident of Ripon. 

This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police brutality, an end to racism and anti-Blackness, and immediate reform in how Black people are treated in America. Accordingly, it has come to my attention that the budget for 2019-2020 is poorly allocated. I am emailing you to demand an ethical and equal reallocation of the Ripon expense budget away from Ripon Police Department and towards the community center, parks, and the library.

Redirect money away from the police department and into these programs that will benefit public health and the community. The budget for 2019-2020 suggests that the largest fraction of the city's budget should go to policing ($6,557,258) whereas the budget for the community center is a mere $98,971.

If this is truly representative of the council's thoughts on how funds should be allocated, I am ashamed to call Ripon my home and I am ashamed to call you my elected officials.

Crime is not random. Crime usually happens when someone has been unable to meet their basic needs through other means. So, to really “fight crime,” we don’t need more police officers - we need more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely,

[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]"

**Comment by emilyhuntsman** [comment]
I will post the PR # shortly!
