### ISSUE TITLE
Please add Bakersfield,CA

### ISSUE THREAD

**Issue by GustavoEsparza** [defund12/defund12.org#394]
To: Mayor@bakersfieldcity.us , City_Council@bakersfieldcity.us

Subject: Defund the Bakersfield Police Department

Message:
My name is [YOUR NAME], I am a resident of [YOUR WARD/NEIGHBORHOOD]. We demand reallocation of funding from BPD to social and public programming that takes place in our communities. It is an outrage that nearly a quarter of the city funding for 2021 is planned towards the Police Department and that Chief Terry’s salary is nearly $300,000.

We demand that the City Council defund the BPD. We join the calls of those across the country to #DefundThePolice. We demand a budget that adequately and effectively meets the needs of at-risk Bakersfield residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

It is your duty to represent your constituents. I am urging you to completely revise the Bakersfield city budget for 2020-2021 fiscal year, and to fund #CareNotCops. Public opinion is with me.

Thank you for your time,

[YOUR NAME]

**Comment by ctneal91** [comment]
on it
