### ISSUE TITLE
Please add Boise, Idaho

### ISSUE THREAD

**Issue by jranck2** [defund12/defund12.org#399]

**Comment by emilyhuntsman** [comment]
#257

**Comment by mahrer** [comment]
Mayor's email: mayormclean@cityofboise.org

**Comment by mahrer** [comment]
Mayor Lauren McLean – mayormclean@cityofboise.org
Councilwoman Elaine Clegg – eclegg@cityofboise.org
Councilman TJ Thomson – tjthomson@cityofboise.org
Councilwoman Holli Woodings – hwoodings@cityofboise.org
Councilwoman Lisa Sanchez – lsanchez@cityofboise.org
Councilman Patrick Bageant – pbageant@cityofboise.org
Councilman Jimmy Hallyburton – jhallyburton@cityofboise.org

**Comment by skullface** [comment]
Hi @mahrer and @jranck2! Thanks for your interest in adding Boise to the website. Letters on defund12.org are all written by community members. To add your city, you **must** provide:

- Subject line for the email
- Email addresses (at least one) of the government officials you’d like to receive the message ✅
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide that content, we cannot post your city._**

Read more about our [email style guidelines here](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. If your letter is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!
