### ISSUE TITLE
Hayward, CA Request

### ISSUE THREAD

**Issue by milkteabelle** [defund12/defund12.org#410]
To: Barbara.Halliday@hayward-ca.gov; Francisco.Zermeno@hayward-ca.gov; Al.Mendall@hayward-ca.gov; Sara.Lamnin@hayward-ca.gov; Elisa.Marquez@hayward-ca.gov; Mark.Salinas@hayward-ca.gov; aisha.wahab@hayward-ca.gov; askrcd-da@acgov.org

Subject: Hayward Resident for Defunding the HPD

To Mayor Halliday, the Hayward City Council and Alameda County Elected Officials,

My name is [YOUR NAME], and I am a resident of Hayward. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-Blackness, and immediate reform in how Black people are treated in America. Our city has been at the forefront of much of this action. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

Hayward Police Department (HPD) has been a waste of our resources. Last year, the HPD comprised approximately a quarter of available discretionary funds. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police. In addition, the proposed budget changes introduced during the City Council meeting held on June 2 will slash funding for essential public programs that will disproportionately affect the Black residents of Hayward. Meanwhile, the HPD received no proposed cuts to staffing and a minimal impact to its budget.

I call on you to slash the HPD budget and instead use those extraordinary resources towards solving homelessness, which is felt most by our Black neighbors and veterans. We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]”

**Comment by ctneal91** [comment]
on it now

**Comment by ceug** [comment]
Add Toney.Chaplin@hayward-ca.cov
Maria.Hurtado@hayward-ca.cov
Dustin.Claussen@hayward-ca.cov

**Comment by bingbongle** [comment]
@shortcircuit3 I'd like to have the content team take another look at this one.

**Comment by averymcguirt** [comment]
@milkteabelle  et al. Sorry this request stalled! Minor edits made below,  definitely ready for a PR. Thanks all.

To: Barbara.Halliday@hayward-ca.gov; Francisco.Zermeno@hayward-ca.gov; Al.Mendall@hayward-ca.gov; Sara.Lamnin@hayward-ca.gov; Elisa.Marquez@hayward-ca.gov; Mark.Salinas@hayward-ca.gov; aisha.wahab@hayward-ca.gov; askrcd-da@acgov.org; Toney.Chaplin@hayward-ca.cov; Maria.Hurtado@hayward-ca.cov; Dustin.Claussen@hayward-ca.cov

Subject: Hayward Resident for Defunding the HPD

To Mayor Halliday, the Hayward City Council and Alameda County Elected Officials,

My name is [YOUR NAME], and I am a resident of Hayward. This past week, our nation has been gripped by protests calling for a rapid and meaningful reevaluation of the role of police in our communities, given the racism and anti-blackness that they have come to represent and perpetuate. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

Hayward Police Department (HPD) has been a waste of our resources. Last year, the HPD consumed approximately a quarter of available discretionary funds. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police. In addition, the proposed budget changes introduced during the City Council meeting held on June 2 will slash funding for essential public programs that will disproportionately affect the Black residents of Hayward. Meanwhile, the HPD received no proposed cuts to staffing and a minimal impact to its budget.

I call on you to meaningfully restrict the HPD budget and instead use those extraordinary resources towards solving homelessness, which is felt most by our Black neighbors and veterans. We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by dionlarson** [comment]
I'll reopen and update!
