### ISSUE TITLE
San Luis Obispo, CA - Letter to Mayor and City Council

### ISSUE THREAD

**Issue by bmess4bml** [defund12/defund12.org#423]
**To:**
emailcouncil@slocity.org
hharmon@slocity.org
agomez@slocity.org
cchristianson@slocity.org
apease@slocity.org
estewart@slocity.org

**Subject:**
A budget for the well-being of San Luis Obispo

**Message:** _(Dont' forget to replace the [x]'s with your information)_

Dear San Luis Obispo City Council,

My name is [YOUR NAME] and I am a resident of San Luis Obispo. I am writing to demand that the San Luis Obispo City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police. 

In 2019, the City of San Luis Obispo allocated 36.3 million dollars to our police system, an inordinate 27.5% of our total budget. This is compared to just $9.7 million allocated towards community development (7.3% of the budget). with only $1.4 million towards housing development. 

I demand that the City Council begin meaningfully defunding the San Luis Obispo Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse
treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of San Luis Obispo residents. 

History has shown that police "reform" is not enough. We must take a hard look at the way the current system in place fails to serve-and in fact actively harms-our community, and come together to reimagine the role of police in our city.

I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to fund care not cops. 

Thank you for your time,
[YOUR NAME] 
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by emilyhuntsman** [comment]
I'm on it!
