### ISSUE TITLE
Chapel Hill, NC Update to Mayor and Town council -- Actively Defund Police

### ISSUE THREAD

**Issue by defundpoliceCH** [defund12/defund12.org#425]
* SUBJECT
Please Redistribute Away From and Defund Chapel Hill Police

* LIST OF EMAILS
mayorandcouncil@townofchapelhill.org; phemminger@townofchapelhill.org; mparker@townofchapelhill.org; janderson@townofchapelhill.org; abuansi@townofchapelhill.org; hgu@townofchapelhill.org; thuynh@townofchapelhill.org; aryan@townofchapelhill.org; kstegman@townofchapelhill.org

* DETAILED MESSAGE OF WHAT IS AT STAKE

Dear Mayor Pam and Chapel Hill Town Council,

I am asking you all to actively defund the police, to clarify how much Town Council plans to defund the police in advance of the Public Hearing on June 10, and provide evidence of how the initiatives discussed by Mayor Pam "yielded positive results," with statistical or testimonial breakdowns by race or ethnicity. 

As a resident of Chapel Hill, I am calling you to actively defund the police and limit its reach into our communities, especially those of Black and ethnic minorities. The "slight" cuts mentioned by Mayor Pam, that were already anticipated due to Covid-19, undermines global outcries to actively and intentionally limit the funding of programs that inadvertently promote police brutality, violence, and discrimination. Many of the policies Mayor Pam listed actually work to extend the reach of police violence and discrimination under the guise of progress. I am worried about these initiatives given what I am seeing everyday. Who exactly is benefiting and who is being harmed? For example, the Good Neighbor Initiative in Northside, a historically Black community, deserves close scrutiny since it can enable the internal bias and target Black residents, when a noise complaint can lead to a court fee, criminal charge, arrest, or murder. 

Council must act and be proactive to redistribute funds away from the police. Although cities and towns across the country have implemented many of the 8cantwait policies mentioned by Mayor Pam, these same cities and towns regularly see the murder and discrimination of Black and minority ethnics. The 8cantwait policies are **_not_** what I am calling for. Rather, the most direct way to avoid police brutality and discrimination is to significantly shift the budget away from the Chapel Hill Police Department.

I call on Chapel Hill Town Council to take the following actions:

1. Redirect funds divested from policing to provide educational opportunities, youth programs, environmental justice initiatives, mental health resources, agricultural and food-based inequality programs, sexual assault services, and social work services to our communities.
2. Ensure that Covid-19 budget cuts do not affect important community programs but the budget rather be drawn from the Chapel Hill Police Department
3. Commit resources to support community-led alternatives to policing, such as social work programs.
4. Propose plans for ensuring the safety of Black and other marginalized people in our community from racial profiling by police and other security forces with input from members of the marginalized communities themselves.

If Council members in larger cities, such as Minneapolis, Saint Paul, New York, and Los Angeles, are actively working to limit community ties with the police and implement defunding strategies, I am optimistic that the town of Chapel Hill can do the same. I am urging you, Chapel Hill Town Council, to adopt a budget that defunds the police and funds non-violent, community-led, health and safety strategies. This is a time that will be stamped in public memory, where residents can say whether our Town Council members did or did not actively engage to significantly defund the police.

Sincerely, 
[YOUR NAME]

**Comment by defundpoliceCH** [comment]
Sorry!! The first "We" should be an "I" according to guidelines.

**Comment by mantism** [comment]
on it
