### ISSUE TITLE
please include richmond, va! 

### ISSUE THREAD

**Issue by ywnsn** [defund12/defund12.org#428]
To Mayor Levar Stoney 
RVAmayor@richmondgov.com 

the Richmond City Council 
andreas.addison@richmondgov.com 
kimberly.gray@richmondgov.com
chris.hilbert@richmondgov.com
kristen.larson@richmondgov.com
stephanie.lynch@richmondgov.com
ellen.robertson@richmondgov.com
cynthia.newbille@richmondgov.com
reva.trammell@richmondgov.com
michael.jones@richmondgov.com 

My name is [YOUR NAME], and I am a resident of Richmond. This past week, our nation has been gripped by protests calling for rapid and meaningful reevaluation of the role of policing in our communities and an end to racism and anti-Blackness. Our city has been at the forefront of much of this action. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

RPD has been a waste of our resources. Last year, the RPD’s total general fund was $95,403,743 while Housing and Community Development’s was $3,296,705.  While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. For example, the Housing & Community Development budget for 2019 was   Instead, we see wasteful and harmful actions of our police.

I call on you to meaningfully restrict the RPD budget and instead use those extraordinary resources towards solving homelessness, which is felt most by our Black neighbors and veterans. Social programs and education generally have been shown to be much more effective at promoting safety and social equity than policing and incarceration.

We can be a beacon for other cities to follow if only we have the courage to change. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by emilyhuntsman** [comment]
Will post the PR # when submitted

**Comment by ywnsn** [comment]
wait i’m really really sorry but i made a typo. 
the corrected version is below i’m really sorry again. 

My name is [YOUR NAME], and I am a resident of Richmond. This past week, our nation has been gripped by protests calling for rapid and meaningful reevaluation of the role of policing in our communities and an end to racism and anti-Blackness. Our city has been at the forefront of much of this action. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

RPD has been a waste of our resources. Last year, the RPD’s total general fund was $95,403,743 while Housing and Community Development’s was $3,296,705. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police where there could have been investment back into community initiatives. 

I call on you to meaningfully restrict the RPD budget and instead use those extraordinary resources towards solving homelessness, which is felt most by our Black neighbors and veterans. Social programs and education generally have been shown to be much more effective at promoting safety and social equity than policing and incarceration.

We can be a beacon for other cities to follow if only we have the courage to change. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Sincerely,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]
