### ISSUE TITLE
Holly Springs, NC - https://tinyurl.com/ycvd832r (requested by friend)

### ISSUE THREAD

**Issue by chatcher101** [defund12/defund12.org#433]
TO: dick.sears@hollyspringsnc.us, dan.berry@hollyspringsnc.us, christine.kelly@hollyspringsnc.us, shaun.mcgrath@hollyspringsnc.us, peter.villadsen@Hollyspringsnc.us, aaron.wolff@hollyspringsnc.us

SUBJECT: Decrease funding for the police department

BODY: Dear Mayor Sears and Town Council,

My name is [NAME] and I am a resident of Holly Springs. I urge you to amend the proposed budget for 2021. I would like to redirect money away from Holly Springs Police Department and into social service programs that will benefit public health and our own community directly, especially our community of color. The proposed budget for 2021 suggests that the largest fraction of the town's budget should go to policing ($7,861,585), which is nearly 30% larger than even the second largest allocation of funds, parks and recreation ($6,082,691). The recommended budget for FY20-21 suggests that 25% of the general fund changes should go to a "Safe and Friendly" priority area while only 2% should go to "Economic Prosperity and Diversity" and an "Engaged, Healthy, and Active Community," respectively. You must consider that economic prosperity and diversity, as well as public health in general, have so much more to do with the safety of a community than does a police force, especially as we see our nation reel and ache over the unjust murder of George Floyd and countless other black Americans at the hands of police forces, not to mention the police brutality that has ensued as a direct result of protests against police brutality. Holly Springs already applauds itself for being the "#1 Safest City in North Carolina." We do not need to spend so much on policing. 

Crime is not random. Crime usually happens when someone has been unable to meet their basic needs through other means. So, to really “fight crime,” we don’t need more police officers - we need more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

We don’t need a more-funded police force. We need to create a space in which more mental health service providers, social workers, victim/survivor advocates, religious leaders, neighbors, and friends - all of the people who really make up our community - can look out for one another. Mayor Sears, will you look out for me, and will you look out for us?

Thank you,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by lhmzhou** [comment]
On it!
