### ISSUE TITLE
Please add Tacoma, WA

### ISSUE THREAD

**Issue by mahrer** [defund12/defund12.org#437]
Here are the Mayor and City Councilmembers emails:

Mayor Victoria Woodards: victoria.woodards@cityoftacoma.org 

City council: john.hines@cityoftacoma.org, robert.thoms@cityoftacoma.org, catherine.ushka@cityoftacoma.org, chris.beale@cityoftacoma.org, lillian.hunter@cityoftacoma.org, conor.mccarthy@cityoftacoma.org, kristina.walker@cityoftacoma.org 

Here is a sample script:

Dear Mayor Woodards and Tacoma City Council, 

My name is [NAME] and I am a resident of [CITY/STATE]. I am writing to demand justice for Manuel Ellis, an innocent Black man who was murdered by Tacoma police officers on March 3, and so many murdered Black people before him. 

Despite autopsy evidence ruling Ellis’ death a homicide, the officers involved in this murder have not been charged and are still employed at the Tacoma Police Department. This is unacceptable. Administrative leave is not enough. I demand that these officers be fired and arrested for their crimes.

I am also asking the City of Tacoma to show your commitment to racial justice moving forward by opposing any increase in the Tacoma Police Department’s budget, and re-allocating city resources from policing to services that keep Black people safe, such as healthcare, education, and community programs.

Thank you,
[YOUR NAME]

Thank you for your good work!

**Comment by emilyhuntsman** [comment]
will submit a PR # when done
