### ISSUE TITLE
Please add Fort Collins, CO !!!

### ISSUE THREAD

**Issue by duster1312** [defund12/defund12.org#447]
wtroxell@fcgov.com; kstephens@fcgov.com; sgutowsky@fcgov.com; jpignataro@fcgov.com; ksummers@fcgov.com; rcunniff@fcgov.com; egorgol@fcgov.com; dkennedy@fcgov.com; gsawyer@fcgov.com; datteberry@fcgov.com; business@fcgov.com

Subject: Fort Collins Resident for Defunding of FCPD

To Mayor Troxell, the Fort Collins City Council, City Manager, and other city officials

My name is [YOUR NAME], and I am a resident of Fort Collins. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-Blackness, and immediate reform in how Black people are treated in America. Although Fort Collins is not at the forefront of these protests, it is not exempt from the racism and violence of the police system.

Fort Collins, Colorado also has a history of police violence against community members in addition to gentrification that has pushed communities farther away from central Fort Collins to floodplains and railroad tracks. Natasha Patnode was beaten by Fort Collins Police Officer Todd Hopkins in 2018. This ended up in an excessive-use-of-force settlement. In 2017, Michaella Surat, a former CSU student, was subjected to excessive force by officer Randall Klamser, as well as having her constitutional rights violated by unreasonable search and seizure. 

Fort Collins Police Department (FCPD) has not only been violent towards our community, they have been a waste of our resources. Last year, the FCPD cost the City of Fort Collins $87.7 million. While only a mere $12.8 million was spent on affordable housing and social health. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police.

It is your duty to represent your constituents. I am demanding that you not reform, but defund the FCPD. Please advocate for revision of the Fort Collins city budget for the upcoming fiscal year, to reflect the decades of research showing that education and social programs much better promote the safety of a city than policing.

Sincerely,
[YOUR NAME] 
[YOUR ADDRESS]
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by emilyhuntsman** [comment]
will add PR when posted!
