### ISSUE TITLE
Wrong Contact for Denver CO

### ISSUE THREAD

**Issue by ale2x** [defund12/defund12.org#452]
I received this after submitting an email through the Denver CO link. She suggests we reach out to Mayor Hancock directly, thanks! 

“Hello,

Thanks for reaching out to my office with your concerns. However, I do not represent Denver in the Colorado Senate–you can find your representative and senator at leg.co.gov/findmylegislator. Additionally, the Colorado state legislature does not control this budget.

I would recommend contacting the Denver mayor's office to fight for change with regard to DPD's funding if you have not already. You can contact Mayor Hancock here: https://www.denvergov.org/content/denvergov/en/mayors-office/contact-the-mayor.html

Take care,

Jessie Danielson
State Senator
Colorado Senate District 20
303-866-4856
www.jessiedanielson.com”

**Comment by serifluous** [comment]
Fixed in PR #546
