### ISSUE TITLE
Please add Spokane, WA

### ISSUE THREAD

**Issue by calliv** [defund12/defund12.org#455]
Dear Mayor Nadine Woodward and Spokane City Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY]. Given the history of policing and the most recent murders of Black people, I am asking you to redirect money away from the Spokane PD in the 2021 budget and instead to prioritize services that help strengthen our communities.

I want a budget that reflects our community's priorities and needs. I urge you to advocate for a meaningful reallocation of the city's expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. Beyond policing our community, these services are proven to be more effective in improving community safety and wellness. I demand a budget that supports community wellbeing, rather than gives power to police forces that tear them apart.

Please consider your role in enriching and empowering our communities, especially during a time of racial injustice, wide-spread illness, and economic vulnerability.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

Emails for Mayor and City Council Members: 
mayor@spokanecity.org
bbeggs@spokanecity.org
kateburke@spokanecity.org
mcathcart@spokanecity.org
bwilkerson@spokanecity.org
lkinnear@spokanecity.org
cmumm@spokanecity.org
kstratton@spokanecity.org

**Comment by emilyhuntsman** [comment]
will post PR!
