### ISSUE TITLE
please add Portland Maine

### ISSUE THREAD

**Issue by rasperry89** [defund12/defund12.org#456]
# Found a problem with the site?
 please add Portland Maine

Please provide the following information (if possible):
* How to reproduce to the issue
* Browser/Mail Client/OS (if relavent) Chrome
* [Optiona] Proposed solution/idea Add Portland Maine

**Comment by serifluous** [comment]
Email template proposed in #463

**Comment by rasperry89** [comment]
THANK YOU!
