### ISSUE TITLE
Defund Portland Maine Police 

### ISSUE THREAD

**Issue by hmh122127** [defund12/defund12.org#463]
Draft of an email below, found at the link http://tinyurl.com/defundthepoliceME

Send to: nmm@portlandmaine.gov, fclark@portlandmaine.org, Richard.Farnsworth@legislature.maine.gov, kcook@portlandmaine.org, jduson@portlandmaine.gov, pali@portlandmaine.org

Civil Servants, 

My name is (INSERT NAME) and I am a citizen of (INSERT CITY), Maine. I am a taxpayer and a voter. 

I am writing to ask that you provide NO NEW FUNDING for the Maine Association of Police (MAP). I am also asking that you halt all funding that has already been approved. 

According to documents on the city website, MAP received an overall increase of 5.3% in the budget plan for 2020. I ask you to REFUSE to increase the budget for MAP in the year 2021 and DEFUSE all unspent funds into organizations throughout the state that are for ESSENTIAL HUMAN SERVICES, which MAP has proven not to be. 

With the economic impact that COVID-19 has had on Maine’s economy, difficult and thoughtful decisions will be required when it comes to the budget for Maine in 2021. Mainers are experiencing HOMELESSNESS, ILLNESS, UNEMPLOYMENT, LOSS OF INCOME AND POLICE BRUTALITY in record numbers. The people that have burdened the brunt of this are People of Color, Indigenous peoples, the poor, and the working class.  

Data shows that Black people are THREE TIMES MORE LIKELY TO BE ARRESTED THAN WHITES IN PORTLAND. In addition to that Black, Indigenous, and other People of Color in Maine are disproportionately subject to policing, arrests, and incarcerations. This PROVE THAT SYSTEMATIC RACISM IS PRESENT HERE IN MAINE AND IS PERPETUATED BY THE MAINE ASSOCIATION OF POLICE. Defunding the police will be the first step towards improving the quality of living for People of Color that are Mainers. It will divert funds from going to an institutionally racist association and allow those funds to be diverted to human services that need them badly. 

PLEASE DO THE RIGHT THING. PRIORITIZE THE HEALTH AND SAFETY OF MAINE RESIDENTS.

REFUSE TO FUND THE MAINE ASSOCIATION OF POLICE. 

A concerned citizen, 
(INSERT NAME)

**Comment by emilyhuntsman** [comment]
on it
