### ISSUE TITLE
Letter to Redwood City, CA Mayor, Vice Mayor, and City Council members

### ISSUE THREAD

**Issue by nmasharani** [defund12/defund12.org#468]
Subject: Redwood City Resident for Defunding the RCPD

emails:

council@redwoodcity.org

dhoward@redwoodcity.org

smasur@redwoodcity.org

aaguirre@redwoodcity.org

ibain@redwoodcity.org

jborgens@redwoodcity.org

ghale@redwoodcity.org

dreddy@redwoodcity.org

 
To Mayor Howard, Vice Mayor Masur, and Redwood City City Council Members,

My name is [YOUR NAME], and I am a resident of Redwood City. This past week, our nation and community have been gripped by protests calling for an end to racism and anti-blackness and a complete overhaul in our approach to criminal justice in America. We are demanding that our voices be heard, and that real change be made to the way this city allocates its resources.

The Redwood City Police Department encompasses $46.5M (33.9%) of the city’s FY 2019-20 operating budget and is $48.9M (34.3%) of its recommended FY 2020-21 operating budget. It is shameful and unproductive that, in comparison, in the recommended FY 2020-21 operating budget only $6.8M of is allocated to affordable housing and $2.5M is allocated to the Community Benefits Fund. Research shows that a living wage, access to holistic health services and treatment including mental health services, educational opportunity, and stable housing are far more successful at reducing crime than punitive systems like police or prisons (Source: [Popular Democracy](https://populardemocracy.org/sites/default/files/Freedom%20To%20Thrive%2C%20Higher%20Res%20Version.pdf)). 

There is not just a need for police reform, but police defunding and abolition, because the entire structure of the police force is inherently corrupt and ineffective. The average police recruit spends 58 hours learning how to shoot and only 8 hours learning how to de-escalate (Source: [Campaign Zero](https://www.joincampaignzero.org/train)). They are not trained or equipped to react to the vast majority of crises. In the journal of Sociology of Race and Ethnicity, Phillip McHarris (PhD candidate at Yale focusing on race) [argues](https://journals.sagepub.com/doi/10.1177/2332649216650692) that we must work towards a reality in which healthcare workers and emergency response teams handle substance abuse, domestic violence, homelessness, or mental health cases. Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing ([The Nation](https://www.thenation.com/article/activism/defund-police-protest/), [The Atlantic](https://www.theatlantic.com/ideas/archive/2020/06/defund-police/612682/)). We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence.

We demand the immediate freezing of budget increases to the police force, cancelling of cadet classes, demilitarization of our forces, and reallocation of funds from police to community-led health and safety strategies.

Please do not vote for more SRO’s in schools, militarized police, and officers patrolling our streets. Redirect police funding to efforts that are actually proven to reduce crime, such as affordable housing, shelters, and mental health services. Do not be complicit in the disproportionate targeting and continuous oppression of people of color. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

It is your duty to represent your constituents. I am urging you to revise the Redwood City recommended operating budget for FY 2020-21, and to fund #CareNotCops. We can be a beacon for other cities to follow if only we have the courage to change.

Thank you for your time,

[YOUR NAME]

[YOUR ADDRESS]

[YOUR EMAIL]

[YOUR PHONE NUMBER]

**Comment by nmasharani** [comment]
PR https://github.com/teddywilson/defund12.org/pull/474

**Comment by nmasharani** [comment]
#474

**Comment by averymcguirt** [comment]
closed by #474
