### ISSUE TITLE
Greenbelt, MD Request

### ISSUE THREAD

**Issue by am-thomas** [defund12/defund12.org#471]
To:  colinabyrd@greenbeltmd.gov, ejordan@greenbeltmd.gov, jdavis@greenbeltmd.gov, lmach@greenbeltmd.gov, spope@greenbeltmd.gov, eputens@greenbeltmd.gov, rroberts@greenbeltmd.gov

Subject: Equitably Defunding the Police

Message:

Dear Greenbelt City Council, 

My name is [YOUR NAME] and I am a resident of Greenbelt. Given the history of police brutality and the systematic oppression of minorities in thus country, I am writing to demand that the city council reevaluate our city budget to prioritize community well-being. To do this, we must redirect funds, disproportionately given to the police, to more effective services for public safety such as educational, mental health, housing, and employment programs. I trust you to ensure that a gradual and equitable defunding transition will occur so that members negatively impacted will have the resources to secure financial stability.

As Dallas police chief David Brown eloquently states, "We're asking cops to do too much in this country. We are. Every societal failure, we put it off on the cops to solve. Not enough mental health funding, let the cops handle it... Here in Dallas, we got a loose dog problems; let's have the cops chase loose dogs. Schools fail, let's give it to the cops... That's too much to ask. Policing was never meant to solve all of those problems." 

I hope you keep this in mind and do everything that you can to ensure justice and safety for our community.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mantism** [comment]
on it

**Comment by serifluous** [comment]
Greenbelt, MD added here: https://defund12.org/greenbelt
