### ISSUE TITLE
Please add Tempe, AZ

### ISSUE THREAD

**Issue by ebrillhart** [defund12/defund12.org#477]
https://docs.google.com/spreadsheets/d/1E89ObpV5-nONI9T1-XuGWtx0a2rqZeakXZYD9r_UkWk/edit#gid=416857666

Emails: mark_mitchell@tempe.gov, lauren_kuby@tempe.gov, jennifer_adams@tempe.gov, robin_arredondo-savage@tempe.gov, arlene_chin@tempe.gov, randy_keating@tempe.gov, joel_navarro@tempe.gov

Subject: Commit to reallocate for social equity - Defund the TPD

Dear Mayor Mitchell and Tempe City Council,

My name is [NAME] and I am a resident of Tempe, AZ. I am writing today to urge you to reduce funding for and limit the reach of the police in Tempe.

I implore you to take action on the following:
- Prioritize spending on community health, education, and affordable housing
- Reduce the size of the police force
- Suspend the use of paid administrative leave for police officers under investigation
- Withhold pensions and don’t rehire police officers involved in excessive force
- Require police officers to be liable for misconduct settlements
- Withdraw participation in police militarization programs

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents and take immediate action to address their concerns.

Thank you for your time,
[NAME]

**Comment by todd-m** [comment]
on it
