### ISSUE TITLE
Please add Santa Cruz, CA.

### ISSUE THREAD

**Issue by clara-github** [defund12/defund12.org#491]
**Subject:** Defund the SCPD
**Contact:** jcummings@cityofsantacruz.com, dmeyers@cityofsantacruz.com, kbeiers@cityofsantacruz.com, sbrown@cityofsantacruz.com, rgolder@cityofsantacruz.com, cmathews@cityofsantacruz.com, mwatkins@cityofsantacruz.com
**Message:** 
To Mayor Cummings and the Santa Cruz City Council:

My name is <NAME>, and I am a resident of Santa Cruz. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-blackness, and immediate reform in how black people are treated in America. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

SCPD has been a waste of our resources. Last year, the SCPD budget totaled over $30,000,000, most coming from the general fund -- more than any other single department, including firefighters. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police, while these critical issues largely go ignored.

I call on you to slash the SCPD budget and instead use those extraordinary resources to help our homeless community members and solve the affordability crisis. I implore you to give every member of our community experiencing homelessness a place to call home and the treatment they need before needlessly spending money on a police force that seeks order through force.

Santa Cruz has long been a leader on progressive issues. We can be a leader here, as well, if our you and our other city officials have the courage to step up.

Sincerely,
<NAME>
<ADDRESS>
<EMAIL>
<PHONE>

**Comment by swallan** [comment]
Dear Mayor Cummings and the Santa Cruz City Council:

My name is [NAME HERE], and I am a resident of Santa Cruz. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-blackness, and an immediate change in how black people are treated in America. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

SCPD has been a waste of our resources. Last year, the SCPD budget totaled over $30,000,000, most coming from the general fund -- more than any other single department, including firefighters. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police, while these critical issues largely go ignored.

I call on you to greatly reduce the SCPD budget and instead use those extraordinary resources to better serve our community by investing in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe. Additionally, I implore you to give every member of our community experiencing homelessness during this pandemic a place to call home and the treatment they may need before needlessly spending money on a police force that seeks order through force.

Santa Cruz has long been a leader on progressive issues. We can be a leader here, as well, if our you and our other city officials have the courage to step up.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by swallan** [comment]
@milesalex should be ready for a PR

**Comment by emilyhuntsman** [comment]
on it!
