### ISSUE TITLE
Add Overland Park, Kansas

### ISSUE THREAD

**Issue by lct45** [defund12/defund12.org#492]
* subject: "Defund Overland Park Police Department"
* list of emails: "pdprofessionalstandards@opkansas.org , carl.gerlach@opkansas.org, logan.heley@opkansas.org , holly.grummert@opkansas.org , curt.skoog@opkansas.org , paul.lyons@opkansas.org , jim.kite@opkansas.org , tom.carignan@opkansas.org , fred.spears@opkansas.org , stacie.gram@opkansas.org , john.thompson@opkansas.org , faris.farassati@opkansas.org , chris.newlin@opkansas.org , scott.hamblin@opkansas.org, frank.donchez@opkansas.org   "
* detailed message: 
"Dear Mayor Gerlach, City Counselpeople, and Police Chief Donchez,

Hi, my name is [NAME] and I am a resident of Overland Park [YOUR COUNCIL WARD]. I am asking you to redirect money away from the Overland Park PD and into the public services such as housing, education, and healthcare access, and to consider direct financial relief to citizens (not just businesses) impacted by COVID-19.

As it stands, our city is facing massive revenue shortfalls due to conditions created by the Covid-19 Pandemic. Rather than see a further reduction to public services and layoffs of essential public workers, I request that the mayor and city council first and foremost consider significantly defunding the police department. Since 2018, the Police Department has seen a budget increase of just under 5 million dollars, as listed in the 2020 budget information. This money can be spent in other ways that are proven to be more effective in improving community safety and wellness.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]"

SOURCE: https://dw.opkansas.org/public/FileCabinets/2fa13812-70a3-4126-848b-3a20df7175c3/Documents/10427/FileDownload?targetFileType=Auto&keepAnnotations=false

**Comment by ctneal91** [comment]
on it now
