### ISSUE TITLE
Berkeley, CA: Email to Mayor and City Council

### ISSUE THREAD

**Issue by swallan** [defund12/defund12.org#505]
mayor@cityofberkeley.info rkesarwani@cityofberkeley.info cdavila@cityofberkeley.info jchang@cityofberkeley.info KHarrison@cityofberkeley.info SHahn@cityofberkeley.info swengraf@cityofberkeley.info RRobinson@cityofberkeley.info ldroste@cityofberkeley.info auditor@cityofberkeley.info

Dear Mayor Arreguin and Berkeley City Council Members,

My name is [NAME HERE] and I am a Berkeley resident from district [YOUR DISTRICT]. BPD takes an enormous share of the city’s general fund, and that percentage has risen exponentially for the last two decades, taking away desperately needed resources from essential city programs and services. 38% of our city’s budget goes towards the police department, while only 10% goes towards health, housing, and community service. 

Berkeley may be faced with up to a 28 million dollar budget deficit in the FY2020-2021 and is set to invest 43% of the general fund in policing. That 74 million dollars is being used at the expense of vital public services such as housing and healthcare. The investment in policing has not made us safer -- BPD remains an embarrassment to the city and a lethal threat to Berkeley’s Black and Brown communities, while increased police spending shows no correlation to decreasing crime levels over the past 20 years. With Berkeley’s current finances in dire jeopardy, it is clear that we must defund the police.

As a Berkeley resident, I demand that you take immediate action to ensure the following:

1.Reduce BPD’s allocation from the general fund by 50%.
2.Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence.
3.Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.

Berkeley can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund BPD.

Thank you,

\[YOUR NAME\]

**Comment by swallan** [comment]
@milesalex I wrote this one so I'm not totally objective, but I think it's ready for PR

**Comment by emilyhuntsman** [comment]
working on it!

**Comment by swallan** [comment]
@emilyhuntsman Thanks for including that! I forgot to add it.
