### ISSUE TITLE
Clarksville, TN should be added!

### ISSUE THREAD

**Issue by catherinehowardd** [defund12/defund12.org#508]
to: joe.pitts@cityofclarksville.com, ward1@cityofclarksville.com, ward2@cityofclarksville.com, ward3@cityofclarksville.com, ward4@cityofclarksville.com, ward5@cityofclarksville.com, ward6@cityofclarksville.com, ward7@cityofclarksville.com, ward8@cityofclarksville.com, ward9@cityofclarksville.com, ward10@cityofclarksville.com, ward11@cityofclarksville.com, ward12@cityofclarksville.com

subject: We Demand Justice

Hello,
My name is [NAME] and I am a resident of [NEIGHBORHOOD/WARD]. The unjust deaths of George Floyd, Breonna Taylor, and others undeniably call for reform. I am emailing today to demand action.

If you stand and, as Leaf Chronicle Photo captions, “listen to protesters in the middle of Wilma Rudolph Boulevard on Saturday,” we demand that you recognize and condemn the murder of George Floyd, who did not simply “die in police custody.” Failing to acknowledge his death as a murder only serves to minimize the responsibility that should be assumed by the police. 

In response to national protests and unrest relating to police brutality and racial biases, the Clarksville Police Department has decided to conduct a review of its practices, which articles report you “praised.” I demand that such a review be performed externally rather than internally so as to improve the reliability of the findings of the review. The police killed 1,098 people in 2019. The existing policies do not work. The praise reported in the article is directed towards the CALEA accreditation website. Further research reveals no statistically significant difference between CALEA-accredited departments and non-accredited ones in the total number of complaints received and the number of sustained citizen complaints. That being said, the cities with the highest average number of police killings per 1M in the US (St. Louis and Oklahoma City) also have this accreditation. What significance does CALEA really play in reducing police brutality other than providing a certificate of completion when it is shown not to work?

Further, adopting new policies like 8Can’tWait that better address racist, biased, and generally dangerous practices is requisite to building a safer community and have been proven to reduce killings by police by up to 72%.

Finally, I demand that the budget for the Clarksville Police Department be made available immediately and I urge you to consider redistributing funds from the CPD to initiatives relating to community development, COVID-19 relief, Parks and Recreation, and the Clarksville Montgomery County School System. Better investment of resources in these sectors can be used to ameliorate Clarksville’s sense of community and even to address racism explicitly.

This is a human rights issue. I am heartbroken to see yet another black life lost at the hands of racist officers. They must be held accountable. Your immediate action is necessary. I urge you to do the right thing.

Sincerely,
[Your Name]

**Comment by ctneal91** [comment]
on it now

**Comment by swallan** [comment]
@catherinehowardd Thank you for the submission, but we are only able to allow emails that push for police defunding rather than reforming the police. [If you'd like to learn more, this graphic may be helpful.
](https://static1.squarespace.com/static/59ead8f9692ebee25b72f17f/t/5b65cd58758d46d34254f22c/1533398363539/CR_NoCops_reform_vs_abolition_CRside.pdf)

@ctneal91 Hold off for a little bit

**Comment by milesalex** [comment]
@ctneal91 Are you in the discord? Please wait for the `ready-for-pr` tag to implement. read community guidelines in [team doc](https://github.com/defund12/defund12.org/blob/gh-pages/TEAMS.md)

**Comment by catherinehowardd** [comment]
Hi! Thank you guys for the quick review. I definitley agree that defunding (and abotlition) is the best. Can I resubmit taking away the paragraph about 8cantwait and just push for defunding? Would that fit the guidelines?

**Comment by catherinehowardd** [comment]
Amending to this:

to: joe.pitts@cityofclarksville.com, ward1@cityofclarksville.com, ward2@cityofclarksville.com, ward3@cityofclarksville.com, ward4@cityofclarksville.com, ward5@cityofclarksville.com, ward6@cityofclarksville.com, ward7@cityofclarksville.com, ward8@cityofclarksville.com, ward9@cityofclarksville.com, ward10@cityofclarksville.com, ward11@cityofclarksville.com, ward12@cityofclarksville.com

subject: We Demand Justice

Hello,
My name is [NAME] and I am a resident of [NEIGHBORHOOD/WARD]. The unjust deaths of George Floyd, Breonna Taylor, and others undeniably call for justice. I am emailing today to demand action.

If you stand and, as Leaf Chronicle Photo captions, “listen to protesters in the middle of Wilma Rudolph Boulevard on Saturday,” we demand that you recognize and condemn the murder of George Floyd, who did not simply “die in police custody.” Failing to acknowledge his death as a murder only serves to minimize the responsibility that should be assumed by the police. 

In response to national protests and unrest relating to police brutality and racial biases, the Clarksville Police Department has decided to conduct a review of its practices, which articles report you “praised.” I demand that such a review be performed externally rather than internally so as to improve the reliability of the findings of the review. The police killed 1,098 people in 2019. The existing policies do not work. The praise reported in the article is directed towards the CALEA accreditation website. Further research reveals no statistically significant difference between CALEA-accredited departments and non-accredited ones in the total number of complaints received and the number of sustained citizen complaints. That being said, the cities with the highest average number of police killings per 1M in the US (St. Louis and Oklahoma City) also have this accreditation. What significance does CALEA really play in reducing police brutality other than providing a certificate of completion when it is shown not to work?

I demand that the budget for the Clarksville Police Department be made available immediately and I urge you to consider redistributing funds from the CPD to initiatives relating to community development, COVID-19 relief, Parks and Recreation, and the Clarksville Montgomery County School System. Better investment of resources in these sectors can be used to ameliorate Clarksville’s sense of community and even to address racism explicitly.

This is a human rights issue. I am heartbroken to see yet another black life lost at the hands of racist officers. They must be held accountable. Your immediate action is necessary. I urge you to do the right thing.

Sincerely,
[Your Name]

**Comment by serifluous** [comment]
The last line just needs to be replaced with:

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

Otherwise, looks good to me.

**Comment by caldric** [comment]
Taking this one.
