### ISSUE TITLE
Charlottesville VA request

### ISSUE THREAD

**Issue by rachelsg6** [defund12/defund12.org#509]
![image](https://user-images.githubusercontent.com/66535821/83955130-b9074200-a81d-11ea-85b3-f264bd6c3f5c.png)

[Defund CPD email.docx]

**Comment by milesalex** [comment]
Please copy the text here

**Comment by rachelsg6** [comment]
To: council@charlottesville.org; budget@charlottesville.gov 

Subject: Charlottesville City Resident for Defunding CPD

Message: 
Dear Members of the City Council and Budget Department,

My name is [YOUR NAME], and I am a resident of Charlottesville City. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police brutality, an end to racism and anti-Blackness, and immediate improvements in how Black people are treated in America. 

Accordingly, it has come to my attention that the budget for FY 2021 was recently revised, and that city officials will soon begin the FY 2022 budget process. The Charlottesville Police Department has been a waste of our resources. For FY 2021, $18M has been allocated to CPD. While we’ve been spending extraordinary amounts on policing, we have not seen sufficient improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police.

While the new Community Review Board might be a step in the direction, this effort doesn’t go nearly far enough in protecting Black community members from CPD. I call on you to slash the CPD budget and instead use those extraordinary resources to fund what Black and other marginalized communities need to be safe and healthy: COVID-19 relief, affordable housing, education, healthcare (including mental healthcare), jobs with livable wages, community centers, treatment, and community-led organizations.

The nation looked to Charlottesville in 2017, as our activists stood up to white supremacists. Our community can again be a beacon for other cities to follow if only we have the courage to change.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by swallan** [comment]
@milesalex ready for pr

**Comment by emilyhuntsman** [comment]
got it!
