### ISSUE TITLE
Please add virginia, fairfax county

### ISSUE THREAD

**Issue by Melwells07** [defund12/defund12.org#51]

**Comment by averymcguirt** [comment]
We are currently handling a lot of requests - please include the following information with your request:

    A subject message for the email
    A list of emails (at least one) for the government officials you’d like to receive the message
    A detailed message concerning the budgeting decisions that are at stake in your community

See our current links for examples at https://defund12.org.

Thank you!!

**Comment by serifluous** [comment]
Budget info: https://www.fairfaxcounty.gov/budget/sites/budget/files/assets/documents/fy2021/fy-2021-adopted-package.pdf (page 26, line 90–91 has Police Department and Office of the Sheriff expenditures for 2020 budget and 2021 adopted budget)

Board of Supervisors emails:
chairman@fairfaxcounty.gov
mason@fairfaxcounty.gov
braddock@fairfaxcounty.gov
mtvernon@fairfaxcounty.gov
dranesville@fairfaxcounty.gov
provdist@fairfaxcounty.gov
huntermill@fairfaxcounty.gov
springfield@fairfaxcounty.gov
leedist@fairfaxcounty.gov
sully@fairfaxcounty.gov

https://www.fairfaxcounty.gov/boardofsupervisors/members-and-districts
