### ISSUE TITLE
Please Add Palo Alto, CA

### ISSUE THREAD

**Issue by Isha-Goyal** [defund12/defund12.org#510]
To: Adrian.Fine@cityofpaloalto.org Alison.Cormack@cityofpaloalto.org Tom.Dubois@cityofpaloalto.org eric.filseth@cityofpaloalto.org liz.kniss@cityofpaloalto.org Lydia.Kou@cityofpaloalto.org greg.tanaka@cityofpaloalto.org citymgr@cityofpaloalto.org pd@cityofpaloalto.org 

Subject: Palo Alto Resident for Defunding the PAPD 

Message: 

Hi all, 

My name is [YOUR NAME], and I am a resident of Palo Alto. I am writing to demand that the City Council adopts a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

This past week, our nation has been gripped by protests calling for a rapid and meaningful reconsideration of the role of policing in communities as well as an end to racism and anti-Blackness in America. The Bay Area has been at the forefront of much of this action. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.
PAPD is a poor use of our resources. Last year, the Palo Alto general fund spent 43.8 million dollars on the PAPD. This means PAPD cost us taxpayers more than was spent on libraries, parks, arts, sciences, and recreation programs combined.

We could be spending this money on resources that better serve the community, like affordable housing, mental health resources, and the library system just to name a few. Amidst a pandemic in which everyone has been affected monetarily, the police system should be the first to be defunded. There are other far more important initiatives that need our money.

I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of at-risk Palo Alto residents during this trying and uncertain time, when livelihoods are on the line. I call on you to slash the PAPD budget and instead meaningfully reallocate funds towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year.

We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely,
[YOUR NAME]
 [YOUR ADDRESS]
 [YOUR EMAIL]
 [YOUR PHONE NUMBER]

**Comment by swallan** [comment]
@milesalex ready for pr

**Comment by ctneal91** [comment]
on it now
