### ISSUE TITLE
Please add Bennington VT

### ISSUE THREAD

**Issue by chinworth** [defund12/defund12.org#515]
Please add Bennington, VT

**Comment by skullface** [comment]
Hi @chinworth! Thanks for your interest in adding Bennington, VT to the website. Letters on defund12.org are all written by  community members. To add your city, you **must** provide:

- Subject line for the email
- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Read more about our [email style guidelines here](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. If your letter is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!
