### ISSUE TITLE
OC, CA issue with Letter to the Board of Supervisors template. Edit needed.

### ISSUE THREAD

**Issue by blaizec** [defund12/defund12.org#521]
In the 5th full paragraph of the template, the 6th sentence is incomplete. It begins and ends "Defunding the police and finding greater". I believe deleting this sentence would suffice because the next paragraph addresses increasing funding to community services.

**Comment by swallan** [comment]
@milesalex content change not bug

**Comment by blaizec** [comment]
thank you sorry I am new to this site! will look for content change rn

**Comment by swallan** [comment]
@blaizec no problem, I don't think it is easily set up for submitters yet

**Comment by emilyhuntsman** [comment]
if we have the ok on here I'll edit and do a PR @swallan

**Comment by milesalex** [comment]
@swallan I'll create one

**Comment by blaizec** [comment]
thank you so much

**Comment by nguyenthee** [comment]
Content change suggestions/additions are bolded -- current text addresses "police force" that is not under jurisdiction of OC Board of Supervisors

- Subject: Defund Orange County **Sheriff's Department** 
- Message: To the **Orange County Board of Supervisors**
- Sentence edit: The time has come to **defund the sheriff's department.** 

- Additional paragraph suggestion after the above sentence: **Last year, the Board of Supervisors approved of a $65 million increase to the sheriff's department largely for the force's salary and benefits, while curbing the spending of health and social services. This is unacceptable, especially when residents have called on the board to fund issues like homeless housing. I also want to express my concern towards the types of policing happening in the cities of Orange County.**
