### ISSUE TITLE
Please add Letter for Fairfield, CA

### ISSUE THREAD

**Issue by melena707** [defund12/defund12.org#524]
Position | Name | District | Contact Info
Mayor | Harry T. Price |   | Phone: 707-428-7395 | E-mail: hprice@fairfield.ca.gov
Vice-Mayor | Pam Bertani | District 6 | Phone: 707-628-6974 | E-mail: pbertani@fairfield.ca.gov
City Council Member | Chuck Tim | District 1 | Phone: 707-428-7401 | E-mail: cct707@aol.com
City Council Member | Chaterine Moy | District 3 | Phone: 707-639-0500 | E-mail: cmoy@fairfield.ca.gov
City Council Member | Rick Vaccaro | District 4 | Phone: 707-24-3533 | E-mail: rvaccaro@fairfield.ca.gov

Letter to Mayor and City Council 
Subject: Divest from Police and Invest in Community 

My name is [YOUR NAME], and I am a resident of Fairfield, California. This past week, our nation has been gripped by protests calling for rapid and meaningful reevaluation of the role of policing in our communities and an end to racism and anti-Blackness. After looking at the city budget, I am appalled to see that 40% of Fairfield's city budget is dedicated to funding the police department with only 23% of the budget explicitly dedicated to projects, departments and programs that invest in community well-being.  I am writing to demand that the City Council adopts a budget that prioritizes community well-being and redirects funding away from the police. 

With the rise of COVID-19, the rise of homelessness in our city and the ongoing problems of access to much needed resources around mental health, healthcare, housing and violence prevention, support for communities in need is necessary now, more than ever. We demand that the City Council defund the Fairfield Police Department, which receives at least 40% of the city budget, much more than that dedicated to much needed services and resources for our community.

We demand a budget that adequately and effectively meets the needs of at-risk Fairfield residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers the police.

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year. 

Thank you for your time, 

[YOUR NAME] [ADDRESS] [EMAIL] [PHONE NUMBER

**Comment by dorazhao99** [comment]
On it!

**Comment by milesalex** [comment]
@dorazhao99 Please wait to implement until it has the tag `ready-for-pr]`

**Comment by dorazhao99** [comment]
yes sorry just saw the new guidelines for contributing!
