### ISSUE TITLE
Louisiana - Letter to State Congresspeople

### ISSUE THREAD

**Issue by lunaluna1** [defund12/defund12.org#527]
Hello,
My name is [YOUR NAME], and I am a resident of [CITY/STATE]. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-Blackness, and immediate reform in how Black people are treated in America. Our state has a shameful history of police abuses and excessively high levels of incarceration. We have the highest incarceration rate in the entire country, and one of the highest in the world, and more than half of the incarcerated people in Louisiana are Black. Police forces in many Louisiana parishes are able to act with little-to-no oversight, and our Black community members are disproportionately targeted by police aggression.
As you work on the state budget, I ask that you please take note of the demands of protesters all over the state, country and world, and make efforts to reallocate funding away from the police and prison systems. I ask that you direct funding towards our communities, to education, early childcare, public health, parks and recreation, family services and restoring our wetlands and other critical community needs. Please help to end the terror on our communities inflicted by the police.
Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by milesalex** [comment]
We appreciate your request, but we need emails to be city specific.

Please read more about our email style guidelines [here](https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide).
