### ISSUE TITLE
New Orleans - Letter to City Council 

### ISSUE THREAD

**Issue by lunaluna1** [defund12/defund12.org#528]
Hello,
My name is [YOUR NAME], and I am a resident of [CITY/STATE]. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-Blackness, and immediate reform in how Black people are treated in America. Our city has a shameful history of police abuses and excessively high levels of incarceration. Louisiana has the highest incarceration rate in the entire country, and one of the highest in the world, and more than half of the incarcerated people in Louisiana are Black, and Black community members are disproportionately targeted by police aggression.
As you work on the city budget, I ask that you please take note of the demands of protesters all over the state, country and world, and make efforts to reallocate funding away from the police and prison systems. I ask that you direct funding towards our communities, to education, early childcare, public health, parks and recreation, family services, restoring our wetlands and other critical community needs. Please help to end the terror on our communities inflicted by the police.
Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
@lunaluna1 I think it might be good to get some more New Orleans specific information. How much is currently spent on policing? How much are spent on other programs? Those types of questions are good to know and write in the letter.

Also, we will need the city council and mayor's email information.

**Comment by milesalex** [comment]
Closing for now. Will reopen once comments are addressed

Please read more about our email style guidelines [here](https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide).
