### ISSUE TITLE
Please add Fullerton, CA

### ISSUE THREAD

**Issue by DefundPoliceFullerton** [defund12/defund12.org#539]
Emails: jenniferf@cityoffullerton.com; jflory@cityoffullerton.com; jesuss@cityoffullerton.com; bwwhitaker@live.com;ahmadz@cityoffullerton.com; evaa@cityoffullerton.com 

Subject line: Fullerton demands a People's Budget

Message:
Dear Fullerton City Council Members,

My Name is [YOUR NAME] and I am a resident of [YOUR CITY, YOUR DISTRICT *if you know it*, YOUR STATE]. I am writing to demand that the Fullerton City Council adopts a People’s Budget that prioritizes community well-being and redirects funding away from the police.

According to www.cityoffullerton.com, the proposed budget for the 2020-2021 fiscal year allocates 47% of the general budget ($49,860,929) to the Fullerton Police Force. The budget will also allocate 31% of all funds and expenditures to Public Safety. Meanwhile, Community Development only comprises 5% of the general fund and 3.5% of all funds and expenses. While we’ve been spending extraordinary amounts on policing, but we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Fullerton does not have a crime problem, Fullerton has a social problem. I am demanding you to completely revise the budget for the 2020-2021 fiscal year to **fund care not cops**. 

I insist that the City Council begin meaningfully defunding the Fullerton Police Department and re-allocate those to Community and Economic Development. Specifically, we are looking to bolster our existing child and family, housing and neighborhood, food, health, homeless, training, employment and financial services. I demand a budget that reflects the actual needs of Fullerton residents.

History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city.

Thank you for your time,

[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by DefundPoliceFullerton** [comment]
Subject line of email: Fullerton demands a People's Budget

Emails: jenniferf@cityoffullerton.com; jflory@cityoffullerton.com; jesuss@cityoffullerton.com; bwwhitaker@live.com;ahmadz@cityoffullerton.com; evaa@cityoffullerton.com

**Comment by averymcguirt** [comment]
Thank you for your submission! Minor copy-editing below (please let us know if any concerns). Ready for PR now.

To: 
jenniferf@cityoffullerton.com
jflory@cityoffullerton.com
jesuss@cityoffullerton.com
bwwhitaker@live.com
ahmadz@cityoffullerton.com
evaa@cityoffullerton.com

Subject line: Fullerton demands a budget for the people

Message:
Dear Fullerton City Council Members,

My Name is [YOUR NAME] and I am a resident of [YOUR DISTRICT/NEIGHBORHOOD]. I am writing to demand that the Fullerton City Council adopts a budget that prioritizes community well-being and redirects funding away from the police.

According to www.cityoffullerton.com, the proposed budget for the 2020-2021 fiscal year allocates 47% of the general fund ($49,860,929) to the Fullerton Police Force. Meanwhile, Community Development only comprises 5% of the general fund and 3.5% of all funds and expenses. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city. Fullerton does not have a crime problem, Fullerton has a social problem. I am demanding you completely revise the budget for the 2020-2021 fiscal year to fund care, not cops.

I insist that the City Council begin meaningfully defunding the Fullerton Police Department and re-allocate funds to social programs long proven to be more effective than policing at promoting community safety and equity. Specifically, we are looking to bolster our existing child and family, housing and neighborhood, food, health, homeless, training, employment and financial services. I demand a budget that reflects the actual needs of Fullerton residents.

History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by Ceshion** [comment]
getting started on this now
