### ISSUE TITLE
Letter to officials in Cranston, RI 

### ISSUE THREAD

**Issue by m00ncak3** [defund12/defund12.org#542]
Below are the email addresses for Governor Raimondo, Mayor Fung, and the Cranston City Council members (who must approve the city budget). Source: RI Secretary of State

**TO:** _(Copy/paste emails in individually to ensure they send!)_
governor@governor.ri.gov, afung@cranstonri.org, dukefarina@cs.com, khopkins7878@gmail.com, sstycos26@gmail.com, lammis.vargas@gmail.com, p.jmcauley@yahoo.com, johndoneganforcranston@gmail.com, brady4cranston@gmail.com, chrispaplauskas@gmail.com, mike@favilaw.com

**SUBJECT:** 
Defund Cranston Police

**MESSAGE:** _(Please remember to fill in the [x's] with your info!)_
Hello,

My name is [name] and I am a resident of Cranston. I am writing to urge Governor Raimondo, Mayor Fung, and the members of the Cranston City Council to adopt a budget redirecting all funding from the Cranston Police Department to initiatives that better serve the wellbeing of the community. It has become clear that police do not meet the needs of the community and are in fact a detriment to community safety, furthering the oppression of residents of color, undocumented residents, disabled residents, mentally ill residents, and LGBTQ residents.

The mayor’s office has proposed a police budget of $25,578,656 for FY21. This includes $100,000 to keep police in Cranston public schools, contributing to the criminalization of youth and the school-to-prison pipeline that disproportionately targets Black students and students of color within the Cranston Public School system. 

Imagine what over $25 million could do for this community if it was invested in education, community mental health services, resources for formerly incarcerated, housing, and other services that have been proven to reduce crime and contribute to the safety and well-being of communities.

Cranston may be a small city in a tiny state, but we have shown that we can make a huge impact on America at large. We desperately need to change our financial priorities and let our tax dollars go to our community, not cops. 

Thank you,
[name]
[address]
[number]

**Comment by averymcguirt** [comment]
Minor copy-edits made below. Please let us know if any concerns. Ready for PR now.

TO: 
governor@governor.ri.gov
afung@cranstonri.org
dukefarina@cs.com
khopkins7878@gmail.com
sstycos26@gmail.com
lammis.vargas@gmail.com
p.jmcauley@yahoo.com
johndoneganforcranston@gmail.com
brady4cranston@gmail.com
chrispaplauskas@gmail.com
mike@favilaw.com

SUBJECT:
Defund Cranston Police

Dear Mayor Fung and Cranston City Council,

My name is [YOUR NAME] and I am a resident of [YOUR DISTRICT/NEIGHBORHOOD]. I am writing to urge Governor Raimondo, Mayor Fung, and the members of the Cranston City Council to adopt a budget redirecting funding from the Cranston Police Department to initiatives that better serve the wellbeing of the community. It has become clear that police do not meet the needs of the community and are in fact a detriment to community safety, furthering the oppression of residents of color, undocumented residents, disabled residents, mentally ill residents, and LGBTQ residents.

The mayor’s office has proposed a police budget of $25,578,656 for FY21. This includes $100,000 to keep police in Cranston public schools, contributing to the criminalization of youth and the school-to-prison pipeline that disproportionately targets Black students and students of color within the Cranston Public School system.

Imagine what over $25 million could do for this community if it was invested in education, community mental health services, resources for formerly incarcerated, housing, and other services that have been proven to reduce crime and contribute to the safety and well-being of communities.

Cranston may be a small city in a tiny state, but we have shown that we can make a huge impact on America at large. We desperately need to change our financial priorities and let our tax dollars go to our community, not cops.

Thank you,
[YOUR NAME]
[ADDRESS]
[PHONE NUMBER]
[EMAIL ADDRESS]

**Comment by dionlarson** [comment]
On it!
