### ISSUE TITLE
Sacramento email list problem

### ISSUE THREAD

**Issue by blackaddy** [defund12/defund12.org#545]
# Bug report

Found a problem with the site? Please provide the following information (if possible):

- How to reproduce to the issue
Try to send email to Sacramento City leaders
- Browser/mail client/OS (if relevant)
iOS mail, Gmail app for iOS
- [Optiona] Proposed solution/idea
Remove the ; after hcoy@cityofsacramento.org it's a typo and breaks the entire email from sending

**Comment by skullface** [comment]
Thank you for filing @blackaddy! Digging back into this email list also showed another address had invisible spaces (https://github.com/defund12/defund12.org/pull/547/files#diff-a5bfc8ff4d8be03048318eb5e7c42893L46).
