### ISSUE TITLE
Please add Glendale, CA

### ISSUE THREAD

**Issue by emilyhamily** [defund12/defund12.org#55]
https://www.glendaleca.gov/government/city-council

Mayor: vagajanian@glendaleca.gov

City council members: 
pdevine@glendaleca.gov
anajarian@glendaleca.gov
AKassakhian@Glendaleca.gov
dbrotman@glendaleca.gov

Thank you so much! 🙏🏼🖤

**Comment by averymcguirt** [comment]
Thanks for your submission!
For timely addition of Glendale please submit a detailed (but concise) message to send to officials. see defund12.org for examples.

**Comment by emilyhamily** [comment]
i think this is what you mean:

I am a resident of Glendale, CA. I am writing to demand that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

Not only are we experiencing the trauma of an international pandemic, we are also in the midst of widespread upheaval over the systemic violence embodied by American police departments’ well-documented history of murdering Black people. We will no longer accept empty gestures and suggestions of “reform.” We demand that the City Council of Glendale stand with the People. We demand that you root out systemic and institutional racism by defunding the police and prioritizing and reallocating much-needed funds to education, housing, and community and social services.

We also entreat you to stand in solidarity with the movement by demanding change from the LAPD. As neighbors, we are duty-bound to hold each other accountable. We join the calls of those across the country to #DefundThePolice. We demand budgets that support community wellbeing, rather than empower the police forces that tear them apart.

You need to adopt a People’s Budget. You need to steadfastly pressure your peers on the City Council of Los Angeles to do the same. Public opinion is with me.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by averymcguirt** [comment]
PR created for glendale #607
