### ISSUE TITLE
Eau Claire, Wisconsin

### ISSUE THREAD

**Issue by bergenphelps** [defund12/defund12.org#551]
TO:

terry.weld@EC-CityCouncil.com, Emily.Berge@EC-CityCouncil.com, Emily.Anderson@EC-CityCouncil.com, Jeremy.Gragert@EC-CityCouncil.com, Jill.Christopherson@EC-CityCouncil.com, Andrew.Werthmann@EC-CityCouncil.com, Kate.Beaton@EC-CityCouncil.com, Catherine.Emmanuelle@EC-CityCouncil.com, David.Klinkhammer@EC-CityCouncil.com, John.Lor@EC-CityCouncil.com, Mai.Xiong@EC-CityCouncil.com

MESSAGE: 
Dear Eau Claire City Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY].

I am asking that the Eau Claire City Council make a more overt and visible commitment to racial justice. The City of Eau Claire's inordinate investment in the Eau Claire Police Department (ECPD) comes at the expense of critical youth, education, and health services. 

The Eau Claire City Council must find ways to redirect money away from the Eau Claire Police Department’s overinflated budget and toward sectors that facilitate the dismantling of racial and class inequality.

Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at guaranteeing safety than police or prisons. As such, I demand more aggressive financial support be directed to those areas.

Eau Claire has a unique opportunity to become a leader in racial justice, if we reallocate police funds to public education, homeless services, strong anti-poverty programs and city-wide anti-racist initiatives. I implore you to be a courageous leader at this time.

I am urging you and the Eau Claire City Council to adopt a budget that defunds the police and funds non-violent, community-led health and safety strategies. Can I count on you to be a leader and put forth an anti-racist budget?

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now
