### ISSUE TITLE
Hartford City

### ISSUE THREAD

**Issue by h96sanborn** [defund12/defund12.org#553]
To:  Maly.Rosado@hartford.gov, TJ.Clarke@hartford.gov, James.Sanchez@hartford.gov, Nick.Lebron@hartford.gov, Marilyn.Rossetti@hartford.gov , Shirley.Surgeon@hartford.gov, John.Gale@hartford.gov, wildaliz.bermudez@hartford.gov, Joshua.Michtom@hartford.gov, 

Subject: Reduce the Hartford Police Department’s Budget

Dear City Councilors, 

My name is [YOUR NAME] and I am a resident of Hartford. I am writing to demand that the Hartford City reduce the Hartford Police Department budget. Hartford’s needs must be addressed by the provision of care, and not the threat of violence. We must invest in public services that build towards “a free and fair society” rather than an armed force that endangers us.
Our city faces racial inequalities, borne from historical injustice and brought into sharp relief by the COVID-19 epidemic, that can’t be solved by policing. Hartford is intensely segregated, and deals with the issues of extreme income inequality between Hartford City, and suburbs like West Hartford. Members of our community live in tight quarters and on lean budgets–this before a pandemic stole three months of wages, and counting. Thousands of us are becoming food-insecure and are at risk of eviction as soon as the ban is lifted. Essential educators are living on starvation pay while repeated and overwhelming community demands to right this glaring injustice are ignored.
Hartford City spends over half of its Public Safety budget on Police, when that money could be better reallocated toward improving addiction and mental health services, providing permanent housing for our unhoused neighbors, and improving city infrastructure. 
Now especially, the City Council can take a stand for racial justice by significantly defunding policing and investing in Black and Brown communities–starting with cutting the least transparent and most harmful parts of the Hartford Police Department budget.
Racist police violence doesn’t just happen in other cities–it happens here in Hartford too. We see it in the disproportionate imprisonment of black people, and in the racialized inequality that is prevalent in Hartford. The City Council must stop investing in targeted criminalization and surveillance, and fund what Black and Brown communities need to be safe and healthy: COVID19 relief, housing, healthcare, treatment, healing, cooperative businesses, community centers, community-led organizations and projects.
Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now
