### ISSUE TITLE
No preview when sending link like defund12.org/city

### ISSUE THREAD

**Issue by swallan** [defund12/defund12.org#564]
For specific cities when you share it looks like this: 
<img width="169" alt="Screen Shot 2020-06-06 at 6 52 46 PM" src="https://user-images.githubusercontent.com/44255917/83958463-eb696d00-a826-11ea-9d2b-1df4228fda7b.png">
We should configure it to show like this
<img width="324" alt="Screen Shot 2020-06-06 at 6 53 37 PM" src="https://user-images.githubusercontent.com/44255917/83958468-089e3b80-a827-11ea-8dea-94d45f89a03f.png">

**Comment by swallan** [comment]
I believe the issue is that when you it loads any /city,` <meta itemprop="image" content="{{ page.url | prepend: site.baseurl | prepend: site.url }}images/defund12.org.png">` adds the page URL in there when it should just be the site.

**Comment by milesalex** [comment]
@skullface Do you want to fix?
