### ISSUE TITLE
Defunct Email

### ISSUE THREAD

**Issue by erinliao** [defund12/defund12.org#572]
hi sorry for bothering you! i believe one of the emails i listed above (nelsonfialho@cityofpleasantonca.gov) is now defunct—a bunch of people have been contacting me about emails not going through to him. i'd really appreciate it if you could remove his email from the template so that we can successfully spread the word and contact our town's government. thank you so much for your work!!

_Originally posted by @erinliao in https://github.com/defund12/defund12.org/issues/484#issuecomment-640148180_

**Comment by emilyhuntsman** [comment]
removing now!
