### ISSUE TITLE
Wrapped emails aren't indented on site

### ISSUE THREAD

**Issue by swallan** [defund12/defund12.org#574]
![Screen Shot 2020-06-06 at 8 09 35 PM](https://user-images.githubusercontent.com/44255917/83959444-be6e8780-a831-11ea-897c-585d06019dad.png)
Some of the email titles are long enough that they wrap around on computers and phones, but on the second line it isn't indented fully.

**Comment by bingbongle** [comment]
Thanks for reporting this! Has always bugged me.
