### ISSUE TITLE
Please add phoenix Justice for Dion!

### ISSUE THREAD

**Issue by jforjustice** [defund12/defund12.org#577]
SUBJECT: JUSTICE FOR DION

EMAILS:   pio_unit@azdps.gov, mayor.gallego@phoenix.gov, engage@az.gov

TEXT: 
Hi, my name is Jenny Aranda and I'm from [CITY, ZIPCODE]. I am emailing on behalf of Dion Johnson, who died after he was shot by a DPS trooper, then kicked in the back by an officer as he rolled around on the ground dying, then ignored by EMTs for over six minutes. 

We are outraged. We demand that the police report be released. We demand that the officers' name be released and that the officers involved are fired and held accountable. We demand that Dion Johnson's belongings be released to his family. It is beyond cruel and disgustingly inhumane to shoot an unarmed civilian, kick him while he's down, and refuse to administer life-saving measures for over six minutes. 

Thank you. 

Sincerely, [NAME]. 

COPIED FROM EXTERNAL SOURCE: Black Phx Org Collective https://www.instagram.com/p/CBDz5DOnJVy/

**Comment by swallan** [comment]
Hi @jforjustice,

Thanks for this submission. Unfortunately, it does not comply with the email guidelines of defunding the police forces, the core mission of the site.
