### ISSUE TITLE
Add Monroe County to the Email List

### ISSUE THREAD

**Issue by ditto888** [defund12/defund12.org#580]
Hello, 

I am writing to have Monroe County in New York added to the list of counties on defund12. After conducting some personal research, I have learned that a total of almost $99 million dollars was spent in the 2019-2020 fiscal year to fund the police department and its operations in Monroe County. As of May 15, 2020, the proposed budget is 3.7% less but it is still not enough. One of the “Strategic Goals & Objectives” is to “...reduce crime through crime prevention activities, early identification and intervention of disputes, and apprehension of offenders. (Section 9-13, 2020).” While the budget document does not go into detail about the crime prevention activities, I hardly believe that they will be as effective as a reallocation of funds to services including homeless shelters, education centers, mental health services, etc. My source for this information is the City of Rochester 2019-2020 and 2020-2021 Budget. 

The list below is some of the major elected officials in Monroe County that I think should be emailed of these changes. 

countyexecutive@monroecounty.gov
mcclerk@monroecounty.gov
michaelradler@monroecounty.gov
districtattorney@monroecounty.gov
Monroe16@monroecounty.gov
monroe7@monroecounty.gov
cindy@kaltechsupport.com
info@cityofrochester.gov 
hazelwashington@cityofrochester.gov
 
Let me know if more information is needed. It is imperative that we begin to hold our elected officials accountable for the continued oversight of systemic racism that exists in our community.

**Comment by milesalex** [comment]
Hey! Thanks for the submission. Please write the email as if someone from the govt was going to receive it so a developer can copy paste it into our codebase. Check out our style guide for more clarity:

https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide

**Comment by serifluous** [comment]
Closing this since Rochester is live https://defund12.org/rochester?browse

Please reopen if you have a Monroe County-specific email template!
