### ISSUE TITLE
Greensboro, North Carolina Uprising Demands

### ISSUE THREAD

**Issue by wehaveadvancedpastpolice** [defund12/defund12.org#583]
<!--
Hi, thanks for your interest in adding your city to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Subject: Support the People's Demands for Change
-Emails: nancy.vaughan@greensboro-nc.gov , yvonne.johnson@greensboro-nc.gov , sharon.hightower@greensboro-nc.gov , marikay.abuzuaiter@greensboro-nc.gov , michelle.kennedy@greensboro-nc.gov , goldie.wells@greensboro-nc.gov , justin.outling@greensboro-nc.gov , nancy.hoffmann@greensboro-nc.gov , tammi.thurm@greensboro-nc.gov , David.parrish@greensboro-nc.gov.

-Dear Greensboro City Council,
I am standing with the demands set forth by Greensboro Rising to ensure a safer Greensboro against the harm of over-policing.

The police are killing Black people. They choke us to death like George Floyd in Minneapolis and Marcus Deon Smith in Greensboro. They invade our privacy and search us with no reason, like a 15 year old boy who was stopped while running on the Greenway a week after Ahmaud Arbery was shot for running while Black. They arrest us for things that are legal for white people. We smoke weed at the same rates as white people and are 80% of the people who are arrested for marijuana. We are only 44% of the City.

We need to stop spending money on policing and harm. We need to start spending money on schools, teachers, guidance counselors, affordable housing, healthcare, childcare, livable wages, resources for domestic and sexual violence survivors, and everything that will help our communities thrive. Everything cannot be fixed overnight, and we need change at every level of government. But there are things the Greensboro City Council has the power to do right now. And if they fail to act, we will need a new City Council. The City Council must use their power to pass ordinances instead of relying on the police to make temporary administrative changes. We demand that the Greensboro City Council immediately:

1. Make amends to the family of Marcus Smith, an unarmed man experiencing homelessness who Greensboro police hogtied and killed in the street.
2. End the curfew and stop physically harming and arresting people who are not physically harming others.
3. Defund the police, so they cannot buy militarized weapons to harm us. Fund Crisis Intervention and Recreation Centers.
4. Stop the police from being violent with us.
5. Treat trans and gender non-conforming, intersex and other LGBTQ people with dignity
6. Treat people experiencing homelessness with dignity and stop criminalizing them.
7. End arrests for marijuana.
8. Publicly share data so we can understand how the police are treating us.
9. Make the police get our signed permission before searching us without a warrant.
10. Allow the Police Community Review Board to hold the police accountable.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]

**Comment by teddywilson** [comment]
Hi, thanks for your interest in adding your city to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Subject line for the email
- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!
