### ISSUE TITLE
Add Lexington, KY email template for City Council

### ISSUE THREAD

**Issue by haleybkane** [defund12/defund12.org#588]
- Subject line: URGENT: Reallocate Funding for the LPD

- Addresses: skay@lexingtonky.gov, cellinger@lexingtonky.gov, rmoloney@lexingtonky.gov, jbrown2@lexingtonky.gov, jmccurn@lexingtonky.gov, mswanson@lexingtonky.gov, susanl@lexingtonky.gov, bfarmer@lexingtonky.gov, aevans@lexingtonky.gov, pworley@lexingtonky.gov, fbrown@lexingtonky.gov, jmossotti@lexingtonky.gov, abledsoe@lexingtonky.gov, jreynolds@lexingtonky.gov, kplomin@lexingtonky.gov, CouncilCoreStaff@lexingtonky.gov, mayor@lexingtonky.gov, karmstrong@lexingtonky.gov

- Message:
Hello,

My name is [NAME] and I am a resident of [NEIGHBORHOOD/CITY/STATE]. 

I am extremely concerned with the Lexington Fayette Urban County Government's inordinate investment in the Lexington Police Department (LPD), particularly in light of the death of Breonna Taylor, a 26-year old Black woman who was killed by three Louisville Metro Police Department officers earlier this year on March 13th. The case--along with its mishandling and lack of appropriate corrective actions regarding the officers involved--has made national headlines and instigated protests from hundreds of thousands of people across the city, commonwealth, nation, and globe.

I am therefore writing to demand that the LFUCG consider reapportioning general funds away from the LPD and towards social programs and other critical community needs effective at the beginning of FY20-21, July 1, 2020. 

It is morally reprehensible to dedicate approximately $84 million dollars of the city’s available funds to the LPD while cutting almost all funding to social service agencies, slashing the Affordable Housing Fund by 90%, and reducing funding for Homelessness initiatives by almost 50%. 

Through a reallocation of funds, we can promote the well-being of citizens and reduce crime by sourcing community-based solutions, allowing residents to become invested in providing recommendations for improvements in criminal justice system operations and to engage in creating solutions that best serve their communities and their needs. 

I also urge the LFUCG to enact legislation that holds police members accountable and to overturn policies that allow police members to engage in unlawful behavior with impunity, and that an elected Civilian Oversight Committee be established with real reform powers. Ending an unfair and secretive internal LPD review process is a good first step in achieving this goal.

I ask that all council members lobby the same amount of attention and effort towards fostering sustainable, long-term change, to prevent further tragedies at the hands of the police, and to take immediate action for the well-being of all Lexington citizens.

Thank you,
[YOUR NAME], in solidarity with the protestors and residents of Lexington, KY.
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

Sources used when crafting this message:
https://defund12.org/louisville
https://static1.squarespace.com/static/57fd68af414fb5e705a42fe9/t/5ec2ac38362e25141c5ca936/1589816382990/2020+Budget+Guide+-+Proposed+%28Final%29.pdf
https://docs.google.com/document/d/14HfByWiJj1T6N8cdmqp-ajgmc14rlovYZGvaPkpUxyc/edit?fbclid=IwAR0Ns-sgCLli1HDVjIevNcksbHqA6jSvb-bk2iE8gCdaXSdbUrJztFbk6f0#

**Comment by swallan** [comment]
Checked

**Comment by ctneal91** [comment]
on it now
