### ISSUE TITLE
Add Kansas City, MO

### ISSUE THREAD

**Issue by dtrzn** [defund12/defund12.org#603]
Subject: I Demand Divestment from Police and an Investment in Black Communities

Emails: quinton.lucas@kcmo.org; earnest_rouse@kcmo.org; heather.hall@kcmo.org; 
kevin.oneill@kcmo.org; teresa.loar@kcmo.org; dan.fowler@kcmo.org; brandon.ellington@kcmo.org; Melissa.robinson@kcmo.org; katheryn.shields@kcmo.org; eric.bunch@kcmo.org; lee.barnes@kcmo.org; ryana.parks-shaw@kcmo.org; andrea.bough@kcmo.org

I am a resident of Kansas City. I am writing to demand that the City Council adopts a People’s Budget that divests from the Police Department, and invests into Black communities. I commend Mayor Lucas for de-escalating the protests in our city by removing the unnecessary and militarized police presence. Let that serve as a picture of how our city ought to operate as a whole.

KCPD makes up over 23% of the city’s total budget at $262m. These funds must be divested into community well-being programs such as meal programs, mental health programs, social work outside of KCPD, and housing programs.

Policing as an American institution has proven to be racially imbalanced, violent, and unwilling to correct itself or be held accountable. Kansas City is no exception. Less than 3 months ago, an unarmed Black man, Donnie Sanders, was shot and killed by KCPD. His tragedy has not seen justice.

I do not believe violent crime is a justification for a larger police force. This creates a negative feedback loop where the Police Department is in fact rewarded for doing a worse job and even for contributing to the violence in our city.

According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections . In 2017, they spent $194 billion. A 220 percent increase. Despite continued profiling, harassment, terror and killing of Black communities, local and federal decision-makers continue to invest in the police, which leaves Black people vulnerable and our communities no safer.

Adopt a People’s Budget. Public opinion is with me.

Thank you for your time

[NAME]
[ADDRESS]
[EMAIL]
[PHONE NUMBER]

**Comment by serifluous** [comment]
Hey @dtrzn ! There's another Kansas City email proposed in issue #529. Can you comment there if there's anything you'd like to add?
