### ISSUE TITLE
Defund Ypsilanti Police Department 

### ISSUE THREAD

**Issue by ofbhill** [defund12/defund12.org#606]

**Comment by cjappl** [comment]
Please include the following information with your request:

    A subject message for the email
    A list of emails (at least one) for the government officials you’d like to receive the message
    A detailed message concerning the budgeting decisions that are at stake in your community

**Comment by milesalex** [comment]
Please read more about our email style guidelines [here](https://github.com/teddywilson/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md#email-template-style-guide).
