### ISSUE TITLE
Add Des Moines, Iowa

### ISSUE THREAD

**Issue by t-quartararo** [defund12/defund12.org#608]
To: LindaW@dmgov.org, carlvoss@dmgov.org, fcownie@dmgov.org, pkcmelik@dmgov.org, billgray@dmgov.org, joegatto@dmgov.org, joshmandelbaum@dmgov.org, connieboesen@dmgov.org

Subject: Des Moines City Resident for Defunding the Police

Dear Des Moines City Officials,

My name is [YOUR NAME], and I am a resident of [YOUR DISTRICT]. I am writing to insist that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

I am asking that the Des Moines City Council make a more overt and visible commitment to racial justice. I urge you to pressure the City Manager’s Office towards an ethical and equal reallocation of the city’s expenditures, away from DMPD, and towards sectors that facilitate the dismantling of racial and class inequality.

Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy). As such, I demand more aggressive financial support to be directed to those areas.

Furthermore, I am outraged at the excessive use of force that DMPD used against protesters. Officers with the Iowa State Patrol and Iowa City Police Department used chemical munitions against protesters which is unethical and prohibited for use in warfare by many international treaties. I am calling on you to seriously reduce city funding to DMPD and to implement immediate reform. 

Thank you for your time,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by serifluous** [comment]
**Suggested edit in bold** (also removed mention of reform in the last sentence):

Dear Des Moines City Officials,

My name is [YOUR NAME], and I am a resident of [YOUR DISTRICT]. I am writing to insist that the City Council adopt a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

I am asking that the Des Moines City Council make a more overt and visible commitment to racial justice. I urge you to pressure the City Manager’s Office towards an ethical and equal reallocation of the city’s expenditures, away from DMPD, and towards sectors that facilitate the dismantling of racial and class inequality.

Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at **promoting community safety** than police or prisons (Source: Popular Democracy). As such, I demand more aggressive financial support to be directed to those areas.

Furthermore, I am outraged at the excessive use of force that DMPD used against protesters. Officers with the Iowa State Patrol and Iowa City Police Department used chemical munitions against protesters which is unethical and prohibited for use in warfare by many international treaties. I am calling on you to seriously reduce city funding to DMPD.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by emilyhuntsman** [comment]
got it!
