### ISSUE TITLE
Frederick County- Commit to reallocate for social equity

### ISSUE THREAD

**Issue by athachrisi** [defund12/defund12.org#609]
jgardner@frederickcountymd.gov
MCKeegan-Ayer@frederickcountymd.gov
mblue@frederickcountymd.gov
pdacey@frederickcountymd.gov
JDonald@frederickcountymd.gov
khagen@frederickcountymd.gov
jfitzwater@frederickcountymd.gov
smckay@frederickcountymd.gov

Commit to reallocate for social equity

Frederick County Elected Officials
County Executive and County Council

"To whom it may concern, My name is [YOUR NAME], and I am a Frederick County resident. In the midst of this pandemic and public outcry against police brutality, it feels especially inappropriate to propose an increase to the Frederick Police Department budget of $33,480,852 for fiscal 2020, a $1.07 million — or 3 percent — increase over the budget proposed in March 2018. 
  This proposed appropriation is what continues to fund and sustain systemic violence in our county against the Black and Brown community through policing and mass incarceration. As seen with George Floyd, Breonna Taylor and many others before them, funding the police will not be the solution for a change.
  As such, I urge you to join the calls of those across the country to defund the police. Frederick County cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund the police and support community wellbeing.
  I urge you to ethically reallocate this increase, as well as a meaningful portion of the remaining FPD budget, towards social services and education. Investment in programs such as the Frederick Community Action Agency, Child Advocacy Center, Human Relations Commission, and The Frederick Center for LGBTQ advocacy shows our commitment to communities and the vision that all Frederick residents deserve to thrive. Historically, the city government has spent far more on police than on public health, homeless services, youth services, and other vital agencies. This while Frederick residents face a housing crisis and opioid epidemic. It’s time to staunch the expansion of the FPD's mandate into homeless services, schools, youth services, mental health, and other social services where an armed police force simply doesn't belong. It’s time to protect investments in human services, the social safety net, and racial and economic justice. 
  It is your duty to represent your constituents. Thus, I am urging you to completely revise the Frederick County budget for FY2020-2021. Public opinion is with me.I am asking that city officials give intense care, attention and effort towards sustainable, long-term change. Thank you, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]"

**Comment by mahrer** [comment]
Some minor edits:

jgardner@frederickcountymd.gov
MCKeegan-Ayer@frederickcountymd.gov
mblue@frederickcountymd.gov
pdacey@frederickcountymd.gov
JDonald@frederickcountymd.gov
khagen@frederickcountymd.gov
jfitzwater@frederickcountymd.gov
smckay@frederickcountymd.gov

SUBJECT: Commit to reallocate for social equity

Frederick County Elected Officials
County Executive and County Council

To whom it may concern, 

My name is [YOUR NAME], and I am a resident of [CITY]. In the midst of this pandemic and public outcry against police brutality, it feels especially inappropriate to propose an increase to the Frederick Police Department budget of $33,480,852 for fiscal 2020, a $1.07 million — or 3 percent — increase over the budget proposed in March 2018.
 
This proposed appropriation is what continues to fund and sustain systemic violence in our county against Black and Brown communities through policing and mass incarceration. As seen with George Floyd, Breonna Taylor and many others before them, funding the police will not be the solution for a change.
 
As such, I urge you to join the calls of those across the country to defund the police. Frederick County cannot wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to defund the police and support community wellbeing.

I urge you to ethically reallocate this increase, as well as a meaningful portion of the remaining FPD budget, towards social services and education. Investment in programs such as the Frederick Community Action Agency, Child Advocacy Center, Human Relations Commission, and The Frederick Center for LGBTQ advocacy shows our commitment to communities and the vision that all Frederick residents deserve to thrive. 

Historically, the city government has spent far more on police than on public health, homeless services, youth services, schools, and other vital agencies, all while Frederick residents face a housing crisis and opioid epidemic. It’s time to staunch the expansion of the FPD's mandate into homeless services, schools, youth services, mental health, and other social services where an armed police force simply doesn't belong. It’s time to protect investments in human services, the social safety net, and racial and economic justice.

It is your duty to represent your constituents. Thus, I am urging you to completely revise the Frederick County budget for FY2020-2021. Public opinion is with me. I am asking that city officials give intense care, attention and effort towards sustainable, long-term change. 

Thank you, 
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]"

**Comment by dionlarson** [comment]
On it!

**Comment by averymcguirt** [comment]
@mahrer 
Was looking this one over post-merge and seems the numbers are from 2019. Also conflicting language between county vs. city police/gov't, specific allocation to orgs/programs.

Decided to just delete because it seemed like too much research for the moment.
Will leave it to you/submitter whether to try to fix.
