### ISSUE TITLE
Filename convention

### ISSUE THREAD

**Issue by gamwe6** [defund12/defund12.org#610]
It would be good to have a filename convention, something like `[state]-[city].md`.

**Comment by milesalex** [comment]
Agreed. I'll add this to the teams guidelines

**Comment by milesalex** [comment]
Added in #611

**Comment by Ceshion** [comment]
quick proposal on this, what about restructuring the _emails directory with a subfolder per state? that way as the list grows, it's still clear what emails are in which location at a glance

**Comment by milesalex** [comment]
I also like that

**Comment by gamwe6** [comment]
@Ceshion If we go this route, should we let the `[state]` in the filename? `[state]/[state]-[city].md` or `[state]/[city].md`?

**Comment by Ceshion** [comment]
I think `state/city.md`- there's no need for redundancy there, right?

**Comment by gamwe6** [comment]
If there is no benefit to this redundancy then ok.
Also, I didn't notice, there is a third "object" (eg. "mayor", "senator", etc.), let's call it the `target` for now.
`state` and `city` are separated by a `/`, but how should we separate the `city` and the `target` (`-` or `_`) ?
And spaces inside an "object" are replaced by `-` or `_`?

Let's take *Sioux Falls, South Dakota* as an example.
- `south-dakota/sioux-falls_mayor.md`
- `south_dakota/sioux_falls-mayor.md`
- `sd/sioux_falls-mayor.md`
- `sd/sioux-falls_mayor.md`

**Comment by bingbongle** [comment]
Gonna close this out as we restructured to

_emails/$state/$city.md

Hard to align on `*.md` vs `*.markdown`, because our CMS will add new files as markdown. Not a huge deal to clean them up later.
