### ISSUE TITLE
Add Royal Oak, MI City Commission and City Manager before Vote on June 22nd

### ISSUE THREAD

**Issue by elenaaz** [defund12/defund12.org#612]
To: ccfournier@romi.gov, ccdubuc@romi.gov, ccgibbs@romi.gov, cclevasseur@romi.gov, ccparuch@romi.gov, ccmacey@romi.gov, ccdouglas@romi.gov, citymanager@romi.gov
 
Subject: A budget for the community well-being of Royal Oak
 
Message: 
 
To the City of Royal Oak's 50th Commission and City Manager:
 
My name is [YOUR NAME], and I am a resident of Royal Oak. This past week, our nation has been gripped by protests calling for a rapid and meaningful reconsideration of the role of policing in communities as well as an end to racism and anti-Blackness in America. As the Commission prepares the budget for the 2021 fiscal year beginning July 1, 2020, I demand that you reconsider the budget of the Royal Oak Police Department (ROPD).
 
The fourth goal of the ROPD listed on the 2020-2021 Recommended Budget is "to provide exceptional public safety for major events, such as Woodward Dream Cruise and Arts, Beats and Eats." Given that both of those events have been canceled it is reasonable to ask that the $131,040 that has been budgeted for these events be reallocated to sectors that could more effectively benefit Royal Oak, such as community development, health and welfare, affordable housing, the commissions' sustainability initiative, public works, and education. 
 
The 2020-2021 Recommended Budget has proposed to increase to the ROPD budget by $391,090 with $15,000 specifically dedicated to weapons and ammunition. I emphatically condemn this proposal. ROPD is slated to receive $19,818,220, which is 31% of the proposed Personnel Services budget for the 2020-2021 fiscal year. The ROPD proposed budget is particularly startling compared to the $342,990 that community development is presently set to receive. As a resident of Royal Oak, I demand a budget that reflects a commitment to community well-being, rather than one that entitles the police forces that tear it apart.
 
I call on you, The City of Royal Oak's 50th Commission and City Manager, to decrease the ROPD budget AND, in its place, meaningfully reallocate funds toward investing in social workers who are better equipped to handle cases that are often delegated to police -- such as substance abuse, mental illness, domestic violence, and homelessness, as well as infrastructure for affordable housing, health care, child care, and other critical community needs. 
 
Hundreds marched in the very streets of Royal Oak on June 6th because this community recognizes demands actions that will result in a healthier, more equitable society. I implore you to listen to the needs of your constituents and take immediate action to address their concerns. We can be a beacon for other cities in both the Metro-Detroit Area and nationwide to follow, only if **we as a community** have the courage to catalyze change.
 
Sincerely,
 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by elenaaz** [comment]
https://www.google.com/url?q=https://www.romi.gov/DocumentCenter/View/26724/2020-2021-RECOMMENDED-BUDGET-PDF&sa=D&ust=1591597108425000&usg=AFQjCNFy2n99lSM-l_2Y3g13c6qOrNUrkA

budget source!

**Comment by elenaaz** [comment]
Need this approved ASAP! There's only two meetings before they approve the budget, Today (!) June 8th & 22th

**Comment by ctneal91** [comment]
on it now

**Comment by elenaaz** [comment]
Amazing! I’m eagerly waiting it share it with my network 

Enviado desde mi iPhone

**Comment by elenaaz** [comment]
Update please: the subject line was removed in the final code. It should read: A budget for the well-being of Royal Oak

Enviado desde mi iPhone

**Comment by itf43313** [comment]
Response for anyone interested: 

Thank you for reaching out to me on this important issue. Like you and the millions lifting up their voices across the country, I am outraged and anguished by the daily onslaught of injustice resulting from the systemic racism we continue to fail to address as a community and as a nation. I’ve been a part of social justice movements my entire adult life. I’ve been proud to march with demonstrators in Royal Oak over the last couple weeks and I agree that we must act now to bring about real change.

The resolution I introduced last Monday night, which was passed unanimously by the commission, is a commitment from our city to become much more proactive by formally recognizing the plague of systemic racism and the city's obligation to be a part of the solution.

The first step I proposed was also unanimously approved on our most recent agenda--item 18-- where I recommended that we form a Royal Oak Commission on Human Rights which would help inform city policies, practices, and like you’re suggesting, investments, to ensure we are doing the work to break down institutional bias and systemic racism by creating a formal space for our community to raise and address these issues. The change needed isn't just about policing, but about taking a real hard look at any potential bias in all city policies and practices. In my vision, this body would not just field complaints and hear concerns but would make substantive recommendations on meaningful policy change the city could adopt.

We have much to do for sure, and while I’m happy to engage in conversation around any ideas that could help us be the best community we can be, I’m not clear how arbitrary cuts to our police department will yield the results we want. While I certainly agree with calls to demilitarize, right-size, reform and restructure departments across the country, I think it’s important to have those conversations in the context of each community. For example, the Royal Oak Police Department, which has 1.3 officers to every 1000 residents, is a world of difference from LAPD which has 2.26, Detroit at 3.5, or Chicago at 4.4.

Looking at any budget or line-item as just a number absent any context and making random cuts without a detailed understanding of the nuts and bolts of it—like the fact that a huge portion of our police budget goes to pay obligatory retirement and healthcare legacy costs—doesn’t, in my opinion, help get us where we need to be as a community and is entirely likely to do more harm than good. While I share the passion and the sentiment in the letter you signed, it contains some seriously inaccurate statements about both our public safety budget and the city budget as a whole.

That aside, I wholeheartedly agree with increasing public investment in social services and community supports. But again, this is a wildly different discussion depending on what city you’re talking  about and what programs it has authority over. The city of Royal Oak doesn’t manage education, social services or health service delivery in any official way. Those are managed by completely different government entities including Oakland Schools, Royal Oak School District, Oakland County, and the State of Michigan. But there are things we can do. I have been steadfast in my support for increasing investment in quality of life issues in our city such as parks and recreation, environmental sustainability, senior services, development of affordable housing, and improved service delivery across departments. I will continue to advocate for these things and for a budget that reflects our needs and values. But again, I fail to see how arbitrary cuts to any of our departments, including the police department, without any clear strategy would result in better outcomes for the community.

There is a clear need for serious reform across the criminal justice system and how we approach policing as a society in particular. That is undeniable. But I also think we have a very good department in Royal Oak. We are far from perfect, have made mistakes, and there’s certainly more work to do, but here’s some highlights of where we are right now:

Royal Oak incorporated body cameras last year at the recommendation of our police chief
Ours was one of the first departments in Michigan to conduct implicit bias training.
Royal Oak officers receive de-escalation training when they are hired, and it is required twice a year throughout their careers. 
Our department has adopted and enforces internal policies consistent with the 8 Can't Wait campaign.

While I understand there are issues to address, I honestly believe that our city is working every day to instill a culture of service and compassion into our department. Our chief of police has spoken at several demonstrations that have taken place in our city over the last couple weeks while officers distributed water to protesters. It’s a small gesture but it provides a pretty dramatic contrast with how protesters were received by departments in many other cities. 

I know that like every other community we've got work to do and I am committed to advancing change. I assure you that as long as I'm at the commission table, I'll do everything within my power to ensure Royal Oak is striving to live up to our principles, represent our values, and be the best community it can be. One that lets the world know that we know that Black Lives Matter. And like I said, if there's a case to be made as to how a specific cut to the department's funding would yield a better, safer, healthier, or more just community, I'm happy to listen and have that conversation.

Thanks again for reaching out, for your passion, and for driving us to be a better city. Please don't hesitate to contact me with any other questions.

Sincerely,
-Kyle
Kyle DuBuc
Royal Oak City Commissioner
