### ISSUE TITLE
Add Fort Worth

### ISSUE THREAD

**Issue by caplexxo** [defund12/defund12.org#627]
betsy.price@fortworthtexas.gov, carlos.flores@fortworthtexas.gov, 
brian.byrd@fortworthtexas.gov, cary.moon@fortworthtexas.gov, gyna.bivens@fortworthtexas.gov, jungus.jordan@fortworthtexas.gov, dennis.shingleton@fortworthtexas.gov, kelly.allengray@fortworthtexas.gov, ann.zadeh@fortworthtexas.gov

Subject: We Demand Divestment from Police and an Investment in Black Communities

Hello,

My name is [NAME]. I am a resident of Fort Worth, Texas and I am emailing today to demand a complete overhaul on our Fort Worth Police Department in light of the Black Lives Matter protests being demonstrated across the US, but specifically our city.

WE ARE JOINING TOGETHER TO DEMAND THAT YOU, MY LOCAL OFFICIALS, WILL:

Vote no on all increases to police budgets

Vote yes to decrease police spending and budgets

Vote yes to increase spending on Health care, education and community programs that keep us safe.

The militarized tactics that our Police Department have used against its citizens in response to peaceful protesting is unacceptable and unwarranted. To ensure your dedication to our city and citizens, I demand that you defund the Fort Worth Police Department and start providing more support and funding towards our community efforts and organizations that serve our predominantly Latinx and Black communities, as these are the communities that are being targeted the most. By doing so, I believe this will prevent further police brutality and violence in the future.

The Fort Worth Police Department ride in cars that say "dedicated to protect”. If this true, we demand you listen to our concerns and implement change immediately.

Black communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors. According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections . In 2017, they spent $194 billion. A 220 percent increase. Despite continued profiling, harassment, terror and killing of Black communities, local and federal decision-makers continue to invest in the police, which leaves Black people vulnerable and our communities no safer.

Where could that money go? It could go towards building healthy communities, to the health of our elders and children,to neighborhood infrastructure, to education, to childcare, to support a vibrant Black future. The possibilities are endless.

We join in solidarity with the freedom fighters in Minneapolis, Louisville, and across the United States. And we call for the end to police terror.

Sincerely, [NAME] [PHONE_NUMBER] [EMAIL] [ADDRESS]

**Comment by skullface** [comment]
Hi @caplexxo! @austinzhuang filed a request for Fort Worth today as well. I am copying their content below so you can consolidate messaging.

---

### Email addresses
```
- betsy.price@fortworthtexas.gov
- carlos.flores@fortworthtexas.gov
- brian.byrd@fortworthtexas.gov
- cary.moon@fortworthtexas.gov
- gyna.bivens@fortworthtexas.gov
- jungus.jordan@fortworthtexas.gov
- dennis.shingleton@fortworthtexas.gov
- kelly.allengray@fortworthtexas.gov
- ann.zadeh@fortworthtexas.gov
```

### Message
> Hello all,
> My name is [NAME]. I am a resident of Fort Worth, Texas and I am emailing you today to demand a complete override on our Fort Worth Police Department in light of the Black Lives Matter protests being demonstrated across the US, but specifically our own community.
WE ARE JOINING TOGETHER TO DEMAND THAT YOU, MY LOCAL OFFICIALS, WILL vote NO on all police budget increase for the City of Fort Worth, vote YES to decrease police spending and budgets, and vote YES to increase spending on health care, education towards Fort Worth ISD as a whole, and community programs throughout the city of Fort Worth and Tarrant County.
>
> The militarized tactics that our police have used against its citizens in response to peaceful protesting is not tolerated and unwarranted. To ensure your dedication to our city and citizens, I demand that you defund the Fort Worth Police Department by 75%, and start providing more support and funding towards our community efforts and organizations that serve our predominantly Latinx and Black communities, as these are the communities that are being targeted the most. By doing so, I believe this will prevent further police brutality and violence in the future. Our fellow Latinx and Black brothers and sisters living in these communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes, who are emboldened by state actors. According to some research I've done the Urban Institute mentions that in 1977 alone, state and local governments spent $60 billion on police and corrections. Despite continued profiling, harassment, terror and killing of Black communities, local and federal decision-makers continue to invest in the police, which leaves Black people vulnerable and our communities no more secure than it is at this moment.
>
> Instead, that money could go towards building healthy communities, to the health of our elders and children, to neighborhood infrastructure, to education, to childcare, to support a vibrant Black future. The possibilities are endless.
We join in solidarity with the freedom fighters in Minneapolis, Louisville, and across the United States. And we call for the end to police terror.

---

Also copying @kvrxn who was the original Fort Worth requester. Thank you!

**Comment by swallan** [comment]
betsy.price@fortworthtexas.gov, carlos.flores@fortworthtexas.gov,
brian.byrd@fortworthtexas.gov, cary.moon@fortworthtexas.gov, gyna.bivens@fortworthtexas.gov, jungus.jordan@fortworthtexas.gov, dennis.shingleton@fortworthtexas.gov, kelly.allengray@fortworthtexas.gov, ann.zadeh@fortworthtexas.gov

Subject: We Demand Divestment from Police and an Investment in Black Communities

Hello,

My name is [NAME]. I am a resident of Fort Worth, Texas and I am emailing today to demand a complete overhaul on our Fort Worth Police Department in light of the Black Lives Matter protests being demonstrated across the US, but specifically our city.

I demand that you, as my local official:

- Vote no on all increases to police budgets

- Vote yes to decrease police spending and budgets

Vote yes to increase spending on Health care, education and community programs that keep us safe.

The militarized tactics that our Police Department have used against its citizens in response to peaceful protesting is unacceptable and unwarranted. To ensure your dedication to our city and citizens, I demand that you defund the Fort Worth Police Department and start providing more support and funding towards our community efforts and organizations that serve our predominantly Latinx and Black communities, as these are the communities that are being targeted the most. By doing so, I believe this will prevent further police brutality and violence in the future.

The Fort Worth Police Department ride in cars that say "dedicated to protect”. If this true, we demand you listen to our concerns and implement change immediately.

Black communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors. According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections . In 2017, they spent $194 billion, a 220 percent increase. Despite continued profiling, harassment, terror and killing of Black communities, local and federal decision-makers continue to invest in the police, which leaves Black people vulnerable and our communities no safer.

Where could that money go? It could go towards building healthy communities, to the health of our elders and children,to neighborhood infrastructure, to education, to childcare, to support a vibrant Black future. The possibilities are endless.

We join in solidarity with the freedom fighters in Minneapolis, Louisville, and across the United States. And we call for the end to police terror.

Sincerely, [NAME] [PHONE_NUMBER] [EMAIL] [ADDRESS]

**Comment by ctneal91** [comment]
on it now

**Comment by ctneal91** [comment]
@swallan Should I also put "Vote yes to increase spending on Health care, education and community programs that keep us safe." as a bullet point?
