### ISSUE TITLE
Request: Boise & Meridian Idaho 

### ISSUE THREAD

**Issue by devxdawg** [defund12/defund12.org#630]
Please include these when you get a chance :)

**Comment by serifluous** [comment]
Hey @devxdawg ! There's an email for Boise proposed in issue #708 . Can you comment there if there's anything you'd like to add?

To add Meridian, you **must** provide:

- Subject line for the email
- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!
