### ISSUE TITLE
Defund Arlington, MA Police Department

### ISSUE THREAD

**Issue by polygon134** [defund12/defund12.org#634]
To: JCurro@town.arlington.ma.us, DMahon@town.arlington.ma.us, JLeone@town.arlington.ma.us, achapdelaine@town.arlington.ma.us, SDeCourcey@town.arlington.ma.us, DDunn@town.arlington.ma.us, JHurd@town.arlington.ma.us

Subject: Arlington Resident for Defunding the APD

Message (Don't forget to replace the [x]'s with your information!)

Dear Town Meeting Manager Chapdelaine, Select Board Members Mahon, Curro, Dunn, Hurd, DeCourcey, and Town Moderator Leone,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY], and I am writing to demand that the Arlington Police Department be defunded. 

Over the past week, our nation has been gripped by protests in every single state, calling for the end to police brutality. 

Police "reform," has failed over and over again. NYPD banned chokeholds in 1993. In 1994, the NYPD murdered Anthony Baez by chokehold. In 2014, the NYPD murdered Eric Garner by chokehold. Oklahoma currently requires "de-escalation training," yet is #3 out of the 50 states for police involved killings. In 2014, Tamir Rice was killed by Cleveland PD who had a "warn before shooting" and a requirement to de-escalate already in place.

We know that "reform" does not work. APD is a particularly guilty part of the system that is being protested and dismantled nationally. APD Lieutenant Rick Pedrini wrote a heinous, racist, violent and murderous letter for 2018 issue of The Senteniel. For all we know, the cop who kneeled on George Floyd's neck for 9 minutes read Pedrini's letter and was emboldened by it. But still, Pedrini is an employee of the APD, being paid by the tax dollars of the people he advocated to "put down". 

Defunding the police is not a "radical" idea. Minneapolis city council has already detailed a plan for completely abolishing police in their city, and using that budget to go towards community services that actually help reduce crime. In 2019, Arlington spent $8,214,876 on police. It spent $425,891 on Health and Human Services. What would Arlington look like if that 8 million dollars was invested in the community?

Police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our town. We MUST defund the APD, and we must do it now. 

Thank you for your time, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by root2point0** [comment]
on it!
