### ISSUE TITLE
San Antonio,Texas

### ISSUE THREAD

**Issue by IsabellaDeleon** [defund12/defund12.org#635]
To: info@voteron.com district1@sanantonio.gov jada.rodgers@sanantonio.gov councildistrict.4@sanantonio.gov info@anasandoval.org couragefor9@gmail.com district10@sanantonio.gov info@gregabbott.com

Subject:  We Demand Divestment from Police and an Investment in Black Communities

Hello,

My name is [NAME]. I am a resident of San Antonio, Texas and I am emailing today to demand a complete overhaul on our San Antonio Police Department in light of the Black Lives Matter protests being demonstrated across the US, but specifically our city.

WE ARE JOINING TOGETHER TO DEMAND THAT YOU, MY LOCAL OFFICIALS, WILL: 

1. Vote no on all increases to police budgets 
2. Vote yes to decrease police spending and budgets 
3. Vote yes to increase spending on Health care, education and community programs that keep us safe.

The militarized tactics that our Police Department have used against its citizens in response to peaceful protesting is unacceptable and unwarranted. To ensure your dedication to our city and citizens, I demand that you defund the San Antonio Police Department and start providing more support and funding towards our community efforts and organizations that serve our predominantly Latinx and Black communities, as these are the communities that are being targeted the most. By doing so, I believe this will prevent further police brutality and violence in the future.

The San Antonio Police Department said that “(they) are dedicated to serving the people of San Antonio and strives to reduce crime and provide a safe city.” If this true, we demand you listen to our concerns and implement change immediately.

Black communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes who are emboldened by state actors. According to the Urban Institute, in 1977, state and local governments spent $60 billion on police and corrections . In 2017, they spent $194 billion. A 220 percent increase. Despite continued profiling, harassment, terror and killing of Black communities, local and federal decision-makers continue to invest in the police, which leaves Black people vulnerable and our communities no safer.

Where could that money go? It could go towards building healthy communities, to the health of our elders and children,to neighborhood infrastructure, to education, to childcare, to support a vibrant Black future. The possibilities are endless. 

We join in solidarity with the freedom fighters in Minneapolis, Louisville, and across the United States. And we call for the end to police terror.

Sincerely,
[NAME]
[PHONE_NUMBER]
[EMAIL]
[ADDRESS]

**Comment by serifluous** [comment]
Hey @IsabellaDeleon ! There’s already a San Antonio email being added in issue #226. Can you take a look at that one, and comment with what  you’d like to add?

We’re happy to take edits!
