### ISSUE TITLE
Winston-Salem Letter to Mayor, City Manager, and City Council

### ISSUE THREAD

**Issue by BaileyMP** [defund12/defund12.org#636]
Subject Line: Winston-Salem Resident for Defunding WSPD

Email Addresses: mayorsoffice@cityofws.org; info@cityofws.org; john.larson@cityofws.org; robertc@cityofws.org; jeffm@cityofws.org; danb@cityofws.org; annettes@cityofws.org; denisea@cityofws.org; jamestjr@cityofws.org; morticiap@cityofws.org

Message:

Dear Major Joines and City Council,

My name is [INSERT NAME] and I am writing from zip code [INSERT ZIP CODE] regarding the proposed City of Winston-Salem budget that allocates 52.5% of the General Fund to Public Safety, totally $112.5 million, with $78,711,550 of that for the Police Department. I urge you to advocate for a meaningful reallocation of the city's expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.

In the public Budget Workshop on June 4, 2020, City Council and the Mayor suggested giving WSPD raises due to their work during the peaceful protests in Winston-Salem, calling these protests "crisis situations." The reason given for _not_ including WSPD raises was for the current public optics when the city needs to be focussing on supporting small businesses. In this Budget Workshop, the question of supporting affordable housing was delayed until after the Budget Adoption meeting on June 15th. It is indefensible to allocate this quantity of funds, and to suggest raises to WSPD, when city workers are experiencing layoffs, denials of wage increases, and thousands of community members face unemployment and housing/food insecurity in the midst of the COVID-19 pandemic.  

I call on you to slash the WSPD budget and instead reallocate meaningful funds towards social programs and resources that support affordable housing, jobs, education, health care, child care, and other critical community needs. I demand a budget that supports community wellbeing, rather than empowers the police force that tears them apart. 

Can I count on you to consider an alternative budget that puts focus on social service programs?

Sincerely,
[YOUR NAME], [YOUR ADDRESS], [YOUR EMAIL], [YOUR PHONE NUMBER]

**Comment by root2point0** [comment]
on it
