### ISSUE TITLE
Add Daly City, CA

### ISSUE THREAD

**Issue by manoaboi** [defund12/defund12.org#644]
Emails: citycouncil@dalycity.org, citymanager@dalycity.org

Subject Line: Daly City Resident for Defunding the DCPD

Message Body:

To our Daly City elected and appointed officials,

My name is [NAME], and I am a Daly City resident. Within the past week, we have seen a nationwide movement take to our streets in protest and outrage at the brutalization of Black people in our country at the hands of the police. The discussion has branched to whether the violent enforcement strategies of police actually keep us safe and are helpful to our community, and I believe we need to address that here in Daly City. We must acknowledge and dismantle the waste and harm of our police budget.

Looking at the Daly City budgets from past years to now, DCPD has constantly been awarded a collosal share of our city's expenditures, far more than the rest of our services provided. This year, the allocation for DCPD was $36,691,658, which is 40% of our total city budget. Forty Percent! The next closest item in the budget is our Fire Department at 23%. And to what end? DCPD are not showing in budget reports that their massive resources have kept us safer. We are seeing that police around the country are violent, racist, and wasteful, and that's what we're financially empowering in our community above all other services. What we are also seeing is more and more evidence that community safety is much more likely to occur when people's needs are being met. 

We must consider how far that $36 million would go with other non-violent, prevention-oriented services that address our livelihoods and humanity such as health services, social services, infrastructure, childcare assistance, homelessness services, libraries, and our parks and recreation services. We need to reimagine public safety to address root causes rather than defaulting to violence - which is disproportionately used against our Black neighbors (and others who've been targeted by police historically). Additionally with Covid-19 affecting our community's economy for the forseeable future, budget cuts will likely be made; we must start with DCPD before anything else.

I call on you to slash the DCPD budget and instead apply those massive resources towards these stated alternatives. Help us keep Daly City truly safe, healthy, and prosperous. and join me, your fellow residents, and the rest of the country in moving away from violent policing and toward a just society.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it
