### ISSUE TITLE
Add Hayward,CA

### ISSUE THREAD

**Issue by ceug** [defund12/defund12.org#646]
Subject: Hayward Resident for Defunding the Hayward PD

Emails: 
Barbara.Halliday@hayward-ca.cov
Sara.Lamnin@hayward-ca.cov
Aisha.Wahab@hayward-ca.cov
Dustin.Claussen@hayward-ca.cov
Maria.Hurtado@hayward-ca.cov
Elisa.Marquez@hayward-ca.cov
Mark.Salinas@hayward-ca.cov
Toney.Chaplin@hayward-ca.cov

Template:
To Mayor Halliday, the Hayward City Council, Hayward City Manager, and HaywardPolice Chief:

My name is [YOUR NAME], and I am a resident of Hayward. I am writing to demand that the City Council adopts a People’s Budget that prioritizes community wellbeing and redirects funding away from the police.

This past week, our nation has been gripped by protests calling for a rapid and meaningful reconsideration of the role of policing in communities as well as an end to racism and anti-Blackness in America. The Bay Area has been at the forefront of much of this action. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue.

Hayward PD has been a waste of our resources. Last year, the Hayward PD budget was $78,648,436, almost all of which comes from the Fremont general fund. Hayward’s projected 2020-21 budget appears to be heading in an extraordinarily similar direction.

While we've been spending astonishing amounts of money on policing, we have not seen improvements to safety, homelessness,  education, mental health, or affordability in our city. Instead, I see the wasteful and harmful actions of our police.

I join the calls of those across the country to defund the police. I demand a budget that adequately and effectively meets the needs of at-risk Hayward residents during this trying and uncertain time, when livelihoods are on the line. I call on you to slash the Hayward PD budget and instead meaningfully reallocate funds towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year.

We can be a beacon for other cities to follow if only we have the courage to change.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by serifluous** [comment]
Hey @ceug ! There’s an existing Hayward email proposed in issue #410. Can you comment there and include anything you’d like to add?

**Comment by ceug** [comment]
Hello!

I’ve added a few contacts that the message should also be directed to. When will Hayward,CA be added to the list of template links?
