### ISSUE TITLE
EDIT for Grand Rapids Michigan

### ISSUE THREAD

**Issue by galenhood** [defund12/defund12.org#658]
My name is [NAME] and I am a concerned resident of Grand Rapids. I am asking you to call an emergency council meeting and challenge the proposed budget in favor of The People’s Budget before it is adopted on July 1st.  I know that public services are set to be cut by $22M by FY2021 besides in business redevelopment and a proposed cut to a community engagement effort within the Grand Rapids Police Department. I think that this is unacceptable, and ask that funds be redirected away from the Grand Rapids Police Department and into public services such as affordable housing, quality public education, and improved healthcare access, and to consider direct financial relief to citizens, not just businesses, impacted by COVID-19. This funding must be allocated in a way that provides the most relief to communities of color that have historically been over-policed and disinvested due to the structural racism and inequity that Grand Rapids is built upon, and that the Grand Rapids Police Department and your City Commission is complicit in enforcing. Public tensions are rising and public opinion is dwindling in regard to the City’s inappropriate response to the murder of George Floyd and militarized, over-policed response to subsequent protests of police brutality and racism.

**Comment by todd-m** [comment]
Hi @galenhood, thanks for opening this issue. Is there a specific change you'd like to call out in this issue? From my reading, the content/core demands look the same other than some added phrasing.

**Comment by galenhood** [comment]
Yes it should be just the phrasing- our group caught some shade from our
city commissioners over some word choice so we wanted to address it. Thank
you for checking!

**Comment by todd-m** [comment]
Sorry, but can you be really specific about what needs to make the final cut? This needs a few  edits and I want to make sure I don't take out some key phrasing.

**Comment by galenhood** [comment]
Thank you for being patient while i checked with my group for edits.

Please keep the subject line and contacts the same, and here is the
autofill script we would like to use.
"Dear [x],

My name is [NAME] and I am a concerned resident of Grand Rapids. I am
asking you to call an emergency council meeting and challenge the proposed
budget in favor of The People’s Budget before it is adopted on July 1st.
The GRPD’s budget is currently 39% of the general fund, and I ask that it
is reduced to the charter’s minimum allowance of 32%, freeing up around $9M
for public services. I know that public services are set to be cut by $22M
by FY2021 besides in business redevelopment and law enforcement. I think
that this is unacceptable, and ask that funds be redirected away from the
Grand Rapids Police Department and into public services such as affordable
housing, quality public education, and improved healthcare access, and to
consider direct financial relief to citizens, not just businesses, impacted
by COVID-19. This funding must be redistributed based on the input of
community groups and leaders so that it provides the most relief to
communities of color that have historically been over-policed and
disinvested in due to the structural racism and inequity that Grand Rapids
is built upon, and that the Grand Rapids Police Department and City are
complicit in enforcing. Public tensions are rising and public opinion is
dwindling in regard to the City’s inappropriate response to the murder of
George Floyd and militarized, over-policed response to subsequent protests
of police brutality and racism. Reform is not enough - listen to the people
and improve public services. Cut the budget now. "


Thank you so much for your work managing this amazing tool!!
