### ISSUE TITLE
Revision needed on Los Banos, CA and Ripon, CA

### ISSUE THREAD

**Issue by mahrer** [defund12/defund12.org#659]
The email templates for Los Banos, CA and Ripon, CA both use the same "fight crime" policing language around the 3rd/4th paragraph:

"Crime is not random. Crime usually happens when someone has been unable to meet their basic needs through other means. So, to really “fight crime,” we don’t need more police officers - we need..."

This should be revised per the style guide.

**Comment by emilyhuntsman** [comment]
about to edit! @mahrer

**Comment by mahrer** [comment]
"Crime is not random. Crime usually happens when someone has been unable to meet their basic needs through other means. So, to really “fight crime,” we don’t need more police officers - we need more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!"

can be changed to something like

"Transitioning funding away from [POLICE DEPT] and into community programming such as educational opportunities, arts programs, community centers, healthcare, and mental health resources will strengthen our communities and make them safer for everyone. When every person has the resources they need to be healthy and safe, our community can thrive. This is a long transition process but change starts with reallocating this funding!"
