### ISSUE TITLE
Add new haven, ct

### ISSUE THREAD

**Issue by wlynn53545354** [defund12/defund12.org#681]
# Feature request

Want to add a new feature to the site? Please describe the requested feature and provide any relevant information:

**Comment by ahansrisuk** [comment]
Hi @wlynn53545354  , we can work on adding New Haven to our list but we will need your help composing the message and getting the right recipients. Please provide:

- Subject line
- Recipients
- CC addresses
- Body text

You can refer to this issue #699  for an example template. Thanks!

**Comment by serifluous** [comment]
Please reopen this issue when there's an email template!
