### ISSUE TITLE
Revision needed on Newark - Letter to Mayor Baraka and City Councilors

### ISSUE THREAD

**Issue by circedelusion** [defund12/defund12.org#684]
The first paragraph of this email makes reference to some of the demands from 8cantwait.org. Most activists do not support these reforms, which are considered weak, and they are actually at odds with the more critical demand to defund the police. I recommend removing the last sentence of the first paragraph and replacing it with "Police reforms have not solved police violence: the Minneapolis Police Department had already implemented many reforms, and George Floyd was still murdered. I urge that you take radical steps to defund the police and move towards the goal of reimagining public safety without a police department, per 8 to Abolition (8toabolition.com)."

**Comment by ctneal91** [comment]
on it now
