### ISSUE TITLE
Westchester County - some email addresses bounce back

### ISSUE THREAD

**Issue by saferwestchester** [defund12/defund12.org#686]
Hi! Just a heads up that the following email address in the Westchester County link aren't working: 

Delivery has failed to these recipients or groups:

mkk8@westchestergov.com
Your message can't be delivered because you do not have permissions to send to this email address. Ask the recipient’s e-mail administrator to grant you permissions and then try again. For more information about this issue see DSN code 5.7.1 in Exchange Online.

vxp1@westchestergov.com

gab6@westchestergov.com

jxt2@westchestergov.com

**Comment by ctneal91** [comment]
on it now

**Comment by ctneal91** [comment]
Actually none of these emails are listed in the recipients on the email anymore...

**Comment by serifluous** [comment]
Trying to look into this, and it could be that some of the listed emails may be forwarding to these ones that are bouncing back? Basing off this list: https://sape2016.org/contact-your-elected-officials/westchester-county/county-elected-officials/

- mkk8: kaplowitz@westchesterlegislators.com
- vxp1: perez@westchesterlegislators.com
- gab6: burrows@westchesterlegislators.com
- jxt2: testa@westchesterlegislators.com

**Comment by dionlarson** [comment]
Highlighting the fact that Westchester County Department of Public Safety "does not perform local policing, except for Mount Kisco which is performed under contract"(https://github.com/defund12/defund12.org/issues/760). It may be better to remove this template completely? 🤔
