### ISSUE TITLE
Please add Chowchilla CA

### ISSUE THREAD

**Issue by grilledcheesegood** [defund12/defund12.org#688]
To: WAhmed@CityOfChowchilla.org  ; DPalmer@CityOfChowchilla.org ; RBarragan@CityOfChowchilla.org ; JChavez@CityOfChowchilla.org ; DHaworth@CityOfChowchilla.org ; CityClerk@CityOfChowchilla.org ; DRiviere@CityofChowchilla.org ; RPruett@CityofChowchilla.org ; JMcClendon@CityOfChowchilla.org ; JRogers@CityOfChowchilla.org ; HTurner@CityOfChowchilla.org ; JPalmer@CityOfChowchilla.org ; 
Subject: [***INSERT UNIQUE SUBJECT LINE***]
Message (don't forget to replace [x]'s with your information!):

Dear Mayor Waseem Ahmed, Council members, and City Officials,

My name is [NAME] and I am a resident of [CITY/STATE] emailing you today to demand that the City Council adopt a People’s Budget that prioritizes community well being and redirects funding away from the police. Furthermore, I urge you to pressure the office of the mayor towards an ethical and equal reallocation of the Chowchilla expense budget, away from the local PD and towards social services and education programs.

The grand total department appropriations for the City of Chowchilla Police Department is 4,142,644 for the 2019-2020 year. This makes up a whooping 46% of the general fund expenditures. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city.

Crime is not random. Crime usually happens when someone has been unable to meet their basic needs through other means. So, to really “fight crime,” we don’t need more police officers - we need more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

We don’t need a militarized police force. We need to create a space in which more mental health service providers, social workers, victim/survivor advocates, religious leaders, neighbors, and friends - all of the people who really make up our community - can look out for one another. Mayor Ahmed, will you look out for me, and will you look out for us?

Thank you for your time and consideration,

[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by swallan** [comment]
To: WAhmed@CityOfChowchilla.org ; DPalmer@CityOfChowchilla.org ; RBarragan@CityOfChowchilla.org ; JChavez@CityOfChowchilla.org ; DHaworth@CityOfChowchilla.org ; CityClerk@CityOfChowchilla.org ; DRiviere@CityofChowchilla.org ; RPruett@CityofChowchilla.org ; JMcClendon@CityOfChowchilla.org ; JRogers@CityOfChowchilla.org ; HTurner@CityOfChowchilla.org ; JPalmer@CityOfChowchilla.org ;
Subject: [INSERT UNIQUE SUBJECT LINE]
Message (don't forget to replace [x]'s with your information!):

Dear Mayor Waseem Ahmed, Council members, and City Officials,

My name is [NAME] and I am a resident of [CITY/STATE] emailing you today to demand that the City Council adopt a People’s Budget that prioritizes community well being and redirects funding away from the police. Furthermore, I urge you to pressure the office of the mayor towards an ethical and equal reallocation of the Chowchilla expense budget, away from the local PD and towards social services and education programs.

The grand total department appropriations for the City of Chowchilla Police Department is $4,142,644 for the 2019-2020 year. This makes up a whooping 46% of the general fund expenditures. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in our city.

To promote our community's safety, we don’t need more police officers - we need more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our own communities function. This is a long transition process but change starts with reallocating this funding!

We don’t need a militarized police force. We need to create a space in which more mental health service providers, social workers, victim/survivor advocates, religious leaders, neighbors, and friends - all of the people who really make up our community - can look out for one another. Mayor Ahmed, will you look out for me, and will you look out for us?

Thank you for your time and consideration,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by root2point0** [comment]
on it!
