### ISSUE TITLE
Add Sunnyvale, CA

### ISSUE THREAD

**Issue by daswickerman** [defund12/defund12.org#691]
To: mike.wasserman@bos.sccgov.org, Cindy.Chavez@bos.sccgov.org, dave.cortese@bos.sccgov.org, supervisor.ellenberg@bos.sccgov.org, supervisor.simitian@bos.sccgov.org, 
Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!) 
Hello,

My name is [YOUR NAME] and I am a resident of Santa Clara County. I am writing to demand that funding is reallocated from the Santa Clara Sheriff's Department to social and public programming that takes place in our communities. It is an outrage that 22% of non medical county funding goes towards the Sheriff's Department. The Santa Clara Sheriff's Department has had a track record of poor conditions in jails and officer involved shootings. Additionally the money spent on the annual "Best in the West" SWAT competition would be better spent elsewhere in the community.

We demand that the County Board of Supervisors defund the Santa Clara County Sheriff's Office. We join the calls of those across the country to defund the police. We demand a budget that adequately and effectively meets the needs of at-risk San Jose residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers police.

It is your duty to represent your constituents. I am urging you to completely revise the Santa Clara County budget for 2020-2021 fiscal year. Public opinion is with me.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by root2point0** [comment]
on it
