### ISSUE TITLE
Request for Newport, Rhode Island

### ISSUE THREAD

**Issue by asavino9** [defund12/defund12.org#697]
Below are the email addresses for Governor Raimondo, Mayor Bova, and the Newport City Council members (who must approve the city budget):

Gina Raimondo - Governor: governor@governor.ri.gov 
Jamie Bova - Mayor: jbova@cityofnewport.com 
Susan D. Taylor - Council at Large: staylor@cityofnewport.com 
Jeanne-Marie Napolitano - Council at Large: jnapolitano@cityofnewport.com
Justin S. McLaughlin - Council at Large: justin-at-large@cox.net 
Angella McAlla - First Ward Councilor:  amccalla@cityofnewport.com
Lynn Underwood Cegile - Second Ward Councilor: lceglie@cityofnewport.com 
Kathryn E. Leonard - Third Ward Councilor: KateLeonar@aol.com 

COPY/PASTE EMAILS:
governor@governor.ri.gov, jbova@cityofnewport.com, staylor@cityofnewport.com, jnapolitano@cityofnewport.com, justin-at-large@cox.net, amccalla@cityofnewport.com, lceglie@cityofnewport.com, KateLeonar@aol.com 

Subject: Defund Newport Police

Script: 
My name is [NAME] and I am a resident of Newport. I am writing to demand that Governor Raimondo, Mayor Bova and the members of the City Council do everything in their power to adopt a budget that redirects all funds from the Police Department and towards community wellbeing, mental health and the needs of its residents. It has become clear that police forces are ineffective at keeping local communities safe and that they perpetuate the oppression of residents of color, undocumented residents, disabled residents, mentally ill residents, and LGBTQ residents.

According to the proposed budget for fiscal year 2021 the city of Newport expects to lose $3.5 million as a result of the COVID-19 pandemic, however the city is projecting that General Fund revenue will total approximately $96.4 million for the upcoming fiscal year, with $79.8 million of that money coming directly from this city’s residents through local property and motor vehicle taxes.

There are plans to make donations to various local organizations, including Visiting Nurses, Newport County Mental Health, and Clean Ocean Access.

It’s wonderful that our city would use a portion of the budget to make donations to programs that promote well-being and provide life enriching activities and public spaces for its residents, as well as outreach and civic service to some of the most at risk among us. However, those donations total $127,200. Compare that to the proposed $19 million the city plans to use to police those residents and you might see why it is that thousands of them were marching in the streets on June 6.  

Imagine what over $4 Million could do if it were invested in low-income and public housing, education, resources for formerly incarcerated individuals, public transportation, and other city initiatives that have been proven to strengthen communities and reduce crime.

Newport may be a small city, but our responsibility to our residents, state, and country is large. We desperately need to change our financial priorities and let our tax dollars go to communities, not cops.

Thank you for your time,
[NAME]
[ADDRESS] [NUMBER]

**Comment by skullface** [comment]
Edited for [style guide adherence](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md):

```
- governor@governor.ri.gov
- jbova@cityofnewport.com
- staylor@cityofnewport.com
- jnapolitano@cityofnewport.com
- justin-at-large@cox.net
- amccalla@cityofnewport.com
- lceglie@cityofnewport.com
- KateLeonar@aol.com
```

My name is [NAME] and I am a resident of Newport. I am writing to demand that Governor Raimondo, Mayor Bova and the members of the City Council do everything in their power to adopt a budget that redirects all funds from the Police Department and towards community wellbeing, mental health and the needs of its residents. It has become clear that police forces are ineffective at keeping local communities safe and that they perpetuate the oppression of residents of color, undocumented residents, disabled residents, mentally ill residents, and LGBTQ residents.

According to the proposed budget for fiscal year 2021, the city of Newport expects to lose $3.5 million as a result of the COVID-19 pandemic. However, the city is projecting that General Fund revenue will total approximately $96.4 million for the upcoming fiscal year, with $79.8 million of that money coming directly from this city’s residents through local property and motor vehicle taxes.

There are plans to make donations to various local organizations, including Visiting Nurses, Newport County Mental Health, and Clean Ocean Access. It’s wonderful that our city would use a portion of the budget to make donations to programs that promote well-being and provide life enriching activities and public spaces for its residents, as well as outreach and civic service to some of the most at risk among us. However, those donations total $127,200. Compare that to the proposed $19 million the city plans to use to police those residents and you might see why it is that thousands of them were marching in the streets on June 6.

Imagine what over $4 million could do if it were invested in low-income and public housing, education, resources for formerly incarcerated individuals, public transportation, and other city initiatives that have been proven to strengthen communities.

Newport may be a small city, but our responsibility to our residents, state, and country is large. We desperately need to change our financial priorities and let our tax dollars go to communities, not cops.

Thank you for your time,
[NAME]
[ADDRESS] [NUMBER]

**Comment by root2point0** [comment]
got it
