### ISSUE TITLE
Jersey City, NJ

### ISSUE THREAD

**Issue by RegsMc4** [defund12/defund12.org#7]
We are the 2nd largest city in NJ and rapidly gentrifying which I fear can cause issues.

**Comment by teddywilson** [comment]
Hey, can you provide more information about this? Would love to help.

We're accepting emails with subject, recipients, and body text. If you can that our way, we can take a look and get Jersey City up and running!

**Comment by averymcguirt** [comment]
Closing this for now. Reopen if you'd like to add template language and email addresses @RegsMc4

**Comment by RegsMc4** [comment]
@averymcguirt Please see attached and reopen the case. Thanks!
 
[Defund12 Jersey City.docx](https://github.com/defund12/defund12.org/files/4747341/Defund12.Jersey.City.docx)

**Comment by averymcguirt** [comment]
From the attached document:

Mayor
info@stevenfulop.com
Fulops@jcnj.org

City Council Members
jwatterman@jcnj.org
RLavarro@jcnj.org
DRivera@jcnj.org
DRidley@jcnj.org
MPrinz-Arey@jcnj.org
RBoggiano@jcnj.org
YSaleh@jcnj.org
JSolomon@jcnj.org
JDRobinson@jcnj.org

Email

Hello,

My name is [YOUR NAME] and I am a resident of Jersey City. While I applaud Mayor Fulop’s commitment to the Obama Foundation pledge to review and reform police use of force policies, I don’t believe this is enough. Police reforms do not necessarily eliminate police violence: the Minneapolis Police Department had already implemented many reforms, and George Floyd was still murdered. I urge that you take radical steps to defund the police and move towards the goal of reimagining public safety without a police department.

Jersey City’s proposed 2020 Municipal Budget has $111,390,803 allocated to the Division of Police. This is by far the largest fraction of the city’s budget, and is nearly 50% higher than the second largest allocation of funds (Division of Fire’s $76,744,661). It’s an egregious statistic compared to $41,306,177 proposed for the entire Department of Public Works; $8,569,377 for the Department of Housing, Economic Development & Commerce; and $5,282,056 for the Department of Health & Human Services. The allocation for the police alone takes up nearly 20% of the entire $612 million budget.

I am writing to demand that the 2020-2021 Jersey City municipal budget be revised to reallocate funds away from police and towards things like education, healthcare infrastructure (including non-coercive mental healthcare), youth programming, and non-coercive drug and alcohol treatment programming.

Mayor Fulop and city councilors, please consider making these changes that are in the best interest of our community now and for the future.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE]

**Comment by RegsMc4** [comment]
approved

**Comment by caldric** [comment]
On it.
