### ISSUE TITLE
ADD Antioch, CA 

### ISSUE THREAD

**Issue by defundthenabolish** [defund12/defund12.org#700]
to: swright@ci.antioch.ca.us, jmotts@ci.antioch.ca.us, lthorpe@ci.antioch.ca.us, logorchock@ci.antioch.ca.us, mwilson@ci.antioch.ca.us

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Dear Antioch City Council,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the Antioch City Council adopt a budget that redirects funding away from the police and prioritizes community wellbeing.

In 2019, the City of Antioch allocated 44 million dollars to our police system, in comparison to 4 million dollars directed towards community development. This disparity is unacceptable. I join the calls of those across the country and demand that the City Council defund the Antioch Police Department and re-allocate those funds towards programs that promote a safer and more equitable community, such as mental health services, affordable housing, and education.

As members of the City Council, it is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year, in favor of a budget that reflects the actual needs of Antioch residents. As history has shown us, "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city.

Thank you for your time, 
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by root2point0** [comment]
adding now
