### ISSUE TITLE
Prince George’s County, Maryland

### ISSUE THREAD

**Issue by rehanawc** [defund12/defund12.org#705]
# Feature request

Want to add a new feature to the site? Please describe the requested feature and provide any relevant information:

Prince George’s County Maryland is the wealthiest black county in America. However police brutality runs rampant here. Our schools are underserved and over policed. The time for change is now.

**Comment by ahansrisuk** [comment]
Hi @rehanawc , we can definitely work on adding Prince George's County to our list but we will need your help composing the message and getting the right recicpients. Please provide: 

- Subject line
- Recipients
- CC addresses
- Body text

You can refer to this issue #699 for an example template. Thanks!

**Comment by rehanawc** [comment]
@ahansrisuk Thank you. I have completed the requested information.
