### ISSUE TITLE
Knoxville, TN (based partially on Nashville, TN example)

### ISSUE THREAD

**Issue by ji33** [defund12/defund12.org#709]
To: mayor@knoxvilletn.gov, bhevans@knoxvilletn.gov, gmckenzie@knoxvilletn.gov, tsmith@knoxvilletn.gov, aroberto@knoxvilletn.gov, ssingh@knoxvilletn.gov, lrider@knoxvilletn.gov, cathomas@knoxvilletn.gov, lfugate@knoxvilletn.gov, jtesterman@knoxvilletn.gov, amparker@knoxvilletn.gov, wjohnson@knoxvilletn.gov, dbrace@knoxvilletn.gov, egill@knoxvilletn.gov, swelch@knoxvilletn.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Hello,

My name is [YOUR NAME], and my address is [YOUR ADDRESS]. I am writing to say that I am strongly against the provisions found in the FY2020-2021 budget.

The mayor’s budget would spend $60.7 million ($58 million of which comes directly from the Knoxville City General Fund of $164.5 million, or 35%) on a “public safety” system that does not keep us safe. The vast majority of that money would be spent on police, jails, and courts. That means the mayor wants to spend more on cops and cages than on almost all public goods combined. Fully 1/3 of the full-time government positions in this city are police officers. This isn’t how we create public safety. True public safety requires fully-funded and community-controlled resources, not more police and jails.

In the midst of a budget crisis, the mayor is proposing we increase spending on police and jails, and decrease spending on social services, transit, and other critical public goods. This is unacceptable and will not keep us safe. The mayor has stressed the necessity of fiscal austerity during these trying times, but these cuts come at the expense of necessary community services instead of a massively overfunded police force.

Overpoliced communities are not safe communities. Thriving communities are safe communities, and communities thrive when they are well-resourced. We deserve a budget that divests from policing and jails and uses that money to invest in our community.

Sincerely, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by ji33** [comment]
Edited to correct budget information; data is provided for the city of Knoxville specifically, not Knox County generally.

**Comment by ctneal91** [comment]
on it
