### ISSUE TITLE
Letter to Modesto Mayor and City Council 

### ISSUE THREAD

**Issue by ingatpo** [defund12/defund12.org#713]
To: mayor@modestogov.com, mgrewal@modestogov.com, tmadrigal@modestogov.com, kahyou@modestogov.com, bzoslocki@modestogov.com, jkenoyer@modestogov.com, dridenour@modestogov.com

Subject: Divest from Police and Invest in Community

Message: (Don’t forget to replace the [x]’s with your information)

Mayor Brandvold and City Council members, 

My name is [YOUR NAME], and I am a resident of Modesto, California. This past week, our nation has been gripped by protests calling for rapid and meaningful reevaluation of the role of policing in our communities and an end to racism and anti-Blackness. Based on the population of Modesto, a Black person was [3.1 times as likely](https://policescorecard.org/?city=modesto&fbclid=IwAR0_YqaaVsx3OwQcmyKu5LOVoJI7tK2qLPPefbamlDWup1QAeF0R1Fybou0) to have deadly force used on them than a White person from 2016 - 2018.

At a time when people are calling for an end to racially motivated murders by armed police, in order to reduce police brutality with weapons, there should be a defunding and demilitarization of police. In order for police to be less likely to use deadly force, their access to guns, tear gas, pepper spray and tanks should be limited or completely cut off. After looking at the city’s budget, I am appalled to learn that 50% of Modesto’s general fund expenses is dedicated to funding the police department with only up to 28% of the budget explicitly dedicated to projects, departments, and programs that invest in community well-being. 

With the COVID-19 pandemic, the rise of homelessness in our city and the ongoing problems of access to much needed resources around mental health, healthcare, housing and violence prevention, support for communities in need is necessary-- now more than ever. We demand that the City Council defund the Modesto Police Department, which receives at least $69.5 Million, and redirect that money to much needed services and resources for our community. We demand a budget that adequately and effectively meets the needs of vulnerable Modesto locals during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community well-being rather than empower the police. 

As the City Council, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year. 

Thank you for your time, 

[YOUR NAME]

[ADDRESS]

[EMAIL]

[PHONE NUMBER]

**Comment by ingatpo** [comment]
this is for Modesto, CA

**Comment by root2point0** [comment]
on it!
