### ISSUE TITLE
Prince George’s County, Maryland

### ISSUE THREAD

**Issue by rehanawc** [defund12/defund12.org#719]
Prince George’s County Maryland is the wealthiest black county in America. However police brutality runs rampant here. Our schools are underserved and over policed. The time for change is now.

Subject Line: Fund Schools, Not Police

Angela Alsobrooks: countyexecutive@co.pg.md.us
Todd Turner: CouncilDistrict4@co.pg.md.us
Rodney Streeter: CouncilDistrict7@co.pg.md.us
Mel Franklin: At-LargeMemberFranklin@co.pg.md.us
Calvin Hawkins: At-LargeMemberHawkins@co.pg.md.us
Thomas Dernoga: CouncilDistrict1@co.pg.md.us
Deni Taveras: CouncilDistrict2@co.pg.md.us
Dannielle Glaros: CouncilDistrict3@co.pg.md.us
Jolene Ivey: CouncilDistrict5@co.pg.md.us
Derrick Davis: CouncilDistrict6@co.pg.md.us
Monique Anderson-Walker: CouncilDistrict8@co.pg.md.us
Sydney Harrison: CouncilDistrict9@co.pg.md.us

Body Text:

Prince George's County is the wealthiest black county in the country. For decades we have pursued education and economic status with the hopes that we could improve our conditions.
We were wrong. Even as we obtain degrees and own homes, Prince George's County Police continue to brutalize us as if we were subhuman.

Maryland has the highest number of black men incarcerated per capita, and Prince George's County Police plays a role in this statistic.

We have seen numerous videos of police brutality within our county. Why should the police be funded given their history of violence within our community?

In our schools, school resource officers contribute to the school to prison pipeline and continue to make our children feel unsafe.

Your job as elected officials is to take action when your constituents request. Today, your constituents are demanding that you defund the Prince George's County Police and spend those dollars in other areas that matter.

Remember we are watching your decisions, and should you choose to not take action, your consequence will come at the ballot box.

Thank You,

**Comment by averymcguirt** [comment]
Thank you for your submission! I would recommend a few edits, specifically based on the following point in our style guide:
11. Avoid referring to the email sender as a "citizen" or "voter". Not all senders may be citizens or voters.
And the notion that the templates should be able to come from any resident of the city/town being represented--regardless of class, race, citizenship status, etc.

Could you edit these two sentences to be more inclusive?
"Even as we obtain degrees and own homes, Prince George's County Police continue to brutalize us as if we were subhuman."
"...and should you choose to not take action, your consequence will come at the ballot box."
