### ISSUE TITLE
poor UX using a screenreader

### ISSUE THREAD

**Issue by Ceshion** [defund12/defund12.org#724]
# Bug report

Found a problem with the site? Please provide the following information (if possible):

Repro steps: use a screenreader to read the page while using keyboard controls, see that:
- the filter text items are not read back
- the state headers are not always read as abbreviations (e.g. "de" instead of "D-E" or better yet "Delaware")
- the site title is read as "defund 1-2 .org"
- there is a floating empty paragraph in the reader tree after the filter select
Proposal: Implement ARIA on the filter control, add more friendly labels for the headers and title

**Comment by bingbongle** [comment]
Closed via your awesome PR!
