### ISSUE TITLE
Defund Little Rock Police 

### ISSUE THREAD

**Issue by shelbykait** [defund12/defund12.org#737]
Email: board@littlerock.gov

Dear Little Rock Board of Directors, 

My name is [x] and I’m a resident of Little Rock. I am writing about Little Rock Mayor Frank Scott Jr.’s fiscal year 2021 budget proposal. 

I am writing to demand that the budget vote be delayed so that Board may find ways to redirect money away from Little Rock Police Department’s overinflated budget. I urge you to pressure the City Manager’s Office towards an ethical and equal reallocation of the city’s expenditures, away from LRPD, and towards sectors that facilitate the dismantling of racial and class inequality. 

Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at promoting community safety than police or prisons (Source: Popular Democracy). As such, I demand more aggressive financial support be directed to those areas. 

Do not forget our poor communities and communities of color who are disproportionate targets of police violence. Justice will only be served when the police are defunded and their budget is reallocated to social services that aim to improve the wellbeing of our community members.

Can I count on you to lead our nation by example in this fight against police brutality and racial discrimination?

Thank you, 

[x]

**Comment by swallan** [comment]
Hi @shelbykait,

Please consider revising your email to comply with the guidelines: 
- Avoid using police framing of community problems, i.e. “crime.” Instead of summarizing social programs as being more effective than policing at “reducing crime,” say that they are more effective at “promoting community safety.”
- We are amplifying calls to defund the police, not reform them:

>  Justice will only be served when the police are reformed

**Comment by shelbykait** [comment]
Ok! It should be good to go now. Thanks!!

**Comment by shelbykait** [comment]
@swallan it should all be good now! Thank you for your input!
