### ISSUE TITLE
DEFUND POLICE IN BURLINGTON VERMONT

### ISSUE THREAD

**Issue by btv265** [defund12/defund12.org#745]
Emails: mayor@burlingtonvt.gov ; jredell@burlingtonvt.gov, mtracy@burlingtonvt.gov ; zhightower@burlingtonvt.gov ; bpine@burlingtonvt.gov ; scarpenter@burlingtonvt.gov ; cmason@burlingtonvt.gov ; kpaul@burlingtonvt.gov ; adieng@burlingtonvt.gov ; jstromberg@burlingtonvt.gov ; pfreeman@burlingtonvt.gov ; jhanson@burlingtonvt.gov ; fpaulino@burlingtonvt.gov ; jshannon@burlingtonvt.gov

Subject Line: Defund Police in Burlington, VT
Dear Mayor Weinberger and City Council members,

My name is  [NAME] and I write today to urge you to amend the recommended budget for FY 2020-21. In light of the continued devaluation of Black life in this country, there needs to be change to the ways towns and cities spend their money. The BPD is no longer the best use of city funds. Particularly after the BPD refuses to fire the 3 officers who have been known to abuse Black people.  Black people make up approximately 1.4% of the population of Vermont, yet almost 8% of the state's prisoners are Black. This is one of the highest disparities in the country, at a rate of almost 10 to 1 (https://www.sentencingproject.org/publications/color-of-justice-racial-and-ethnic-disparity-in-state-prisons/)

We have reached a turning point, here in Burlington and around the country. We may choose to divert funds from an increasingly militarized police force and invest in community education, health, and employment. Or we may increase already sizable budgets and escalate the terror Black Americans face on our streets. I hope you all will choose the former.

Please _Defund_ the Burlington Police.

Thank you,

[name]
[town, state]
[email]

**Comment by ctneal91** [comment]
on it now
