### ISSUE TITLE
Please add Santa Monica, CA to defund12

### ISSUE THREAD

**Issue by austenariniello** [defund12/defund12.org#752]
To be sent to council@smgov.net and manager@smgov.net

Dear Councilmembers/City Managers,

My name is [YOUR NAME] from [YOUR CITY/STATE/ZIP CODE]. When the city of Santa Monica’s 2020-21 budget was proposed, the Santa Monica City Council prioritized six outcomes of the city’s budget: 
* Affordability 
* Climate Change
* Engaged and Thriving Community 
* Keeping Neighborhoods Safe
* Mobility and Access
* Reduce Homelessness

Of these priorities set forth by the Council, only the goal of “Keeping Neighborhoods Safe” reasonably applies to Santa Monica’s Police Department. In this context, a 5.9% budget increase has been proposed for SMPD, despite the fact that the proposed budget for Housing and Economic Development — a department whose expansion would help achieve several of the Council’s prioritized outcomes — would be decreased by 19.3%.

We are also in the midst of widespread upheaval over the systemic violence — embodied by LAPD and SMPD — which murders Black people. In 2018, Black people made up 28% of the SMPD’s total arrests yet Black people only make up 4.4% of the city’s population. SMPD embodies a force that “Keeps Neighborhoods Safe” for White people by targeting the Black population. We will no longer accept empty gestures and suggestions of “reform.” 

We need to defund the SMPD. We need to defund the police. We need a budget that adequately and effectively meets the needs of Santa Monicans during this trying and uncertain time; and we need a budget that supports communities and supports their wellbeing, not which empowers the force(s) that tear them apart. 

I am urging you, as representatives of our community, to completely revise the Santa Monica budget for 2020-2021 and fund #CareNotCops. You need to adopt a budget that reflects the same priorities as the ones that the Council identified.

Thank you for your time,
[YOUR NAME]

**Comment by serifluous** [comment]
Hey @austenariniello ! There's a Santa Monica email proposed in issue #587 . Can you comment there if there's anything you'd like to add to that one? Thanks!
