### ISSUE TITLE
Edit Portland, ME

### ISSUE THREAD

**Issue by indoormargo** [defund12/defund12.org#756]
- Change intro to "My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY].”

I want to advise against using the phrases "citizen" and "voter." There may be members of immigrant communities who do not have voting power but want to use these templates. 

- Let's also get rid of the outro that says "A concerned citizen," and just say "Thank you,"

**Comment by root2point0** [comment]
I absolutely agree @indoormargo how do you feel about intense capitalization? keep it as is?

**Comment by indoormargo** [comment]
@root2point0 great question -- i'm gonna bring that up in the style meeting later! i'll leave it up to you whether or not you want to leave this issue open for now or if you want to fix and close this one and i'll open a new one for the capitalization change (if there is one)
