### ISSUE TITLE
Add Iowa City, IA

### ISSUE THREAD

**Issue by ermilde** [defund12/defund12.org#764]
To whom it may concern:

I am NAME, and I am a concerned citizen of Iowa City, Iowa. Police brutality cannot stand, and it is clear that our city is no exception.
I demand:
ICPD must fire Travis Graves, who has been known to brutalize Black Iowans.
A 25% cut in funding for ICPD to be redirected to social services and intervention programs such as: Mental health services; drug treatment and addiction prevention; affordable and low barrier housing; before- and after-school programs; and public transit.
A citizens' police review board with real power, including subpoena power and the ability to enact and enforce measurable consequences when board recommendations are not followed or implemented.
Divestment from and removal of military-grade equipment and contracts from the federal government.
Drop all charges against protesters.
Strong statement from the city in favor of protests including the prioritization of police accountability for racism and addressing issues of systemic racism and inequality, and the deprioritization of law, order, and property.
Decriminalize the use and possession of marijuana <40 grams.
Reduction of probation length and no drug testing for marijuana.
Funding for the SPI program (Parks and Rec).

I also demand from the school board:
An alternative school review board process for students.
A representative school board.
The complete removal of SROs from city schools.

Finally, I demand that ICPD/Johnson County Sheriff may not enforce evictions, and the curfew in Coralville be lifted.

Sincerely,
NAME

Subject: Iowa City Police Reform Demands
TO: council@iowa-city.org, bruce-teague@iowa-city.org, bill-campbell@iowa-city.org, denise-brotherton@iowa-city.org

**Comment by 47780** [comment]
Edited to fit format.

```
To:
council@iowa-city.org, bruce-teague@iowa-city.org, bill-campbell@iowa-city.org, denise-brotherton@iowa-city.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message (Don't forget to replace the [x]'s with your information!

Dear Iowa City Officials,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/BOROUGH/CITY]. Police brutality cannot stand, and it is clear that our city is no exception.
I demand:
ICPD must fire Travis Graves, who has been known to brutalize Black Iowans.
A 25% cut in funding for ICPD to be redirected to social services and intervention programs such as: Mental health services; drug treatment and addiction prevention; affordable and low barrier housing; before- and after-school programs; and public transit.
A citizens' police review board with real power, including subpoena power and the ability to enact and enforce measurable consequences when board recommendations are not followed or implemented.
Divestment from and removal of military-grade equipment and contracts from the federal government.
Drop all charges against protesters.
Strong statement from the city in favor of protests including the prioritization of police accountability for racism and addressing issues of systemic racism and inequality, and the deprioritization of law, order, and property.
Decriminalize the use and possession of marijuana <40 grams.
Reduction of probation length and no drug testing for marijuana.
Funding for the SPI program (Parks and Rec).

I also demand from the school board:
An alternative school review board process for students.
A representative school board.
The complete removal of SROs from city schools.

Finally, I demand that ICPD/Johnson County Sheriff may not enforce evictions, and the curfew in Coralville be lifted.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
```

**Comment by averymcguirt** [comment]
Hi there,
Thanks for your submission. 
I'll direct you to our style guide because this language diverges significantly from our stated goals of defunding, rather than reforming police departments.
https://github.com/defund12/defund12.org/blob/master/EMAIL_TEMPLATE_STYLE_GUIDE.md

I'm going to close this issue, but feel free to reopen if you'd like to rewrite a submission for Iowa City.
