### ISSUE TITLE
Colorado Springs, CO

### ISSUE THREAD

**Issue by swallan** [defund12/defund12.org#768]
jsuthers@springsgov.com, allCouncil@springsgov.com
 Don.Knight@Coloradosprings.gov, David.Geislinger@Coloradosprings.gov, Richard.Skorman@coloradosprings.gov, Yolanda.Avila@coloradosprings.gov, Jill.Gaebler@coloradosprings.gov,  Andy.Pico@Coloradosprings.gov, Bill.murray@coloradosprings.gov, Tom.strand@coloradosprings.gov, Wayne.williams@coloradosprings.gov

Dear Mayor Suthers and Colorado Springs City Council Members,

My name is [YOUR NAME] and I am a resident of Colorado Springs. I write to demand that we defund Colorado Springs Police Department significantly and reallocate funds to be reinvested in communities through more mental health services, social workers, jobs, educational opportunities, community centers, or other beneficial programs.

The CSPD takes up 34.2% of the city’s general fund budget, with only 8.5% of the general fund going to planning and community development, economic development, recreation and administration, and parks, recreation, and cultural services combined. Even with the addition of grants and other funds going to these programs, CSPD is still given 20.6% of funds, while the aforementioned programs are only given 11.3%.

CSPD was also given a $7.2 million increase that came out of the city’s general fund budget to hire 20 new officers. There are many other areas with much smaller budgets where this funding would have stronger benefit, such as homelessness prevention, improving parks and infrastructure, or other types of community support.

The Colorado Department of Labor and Development announced in a news conference June 4th that 517,414 unemployment claims have been filed in Colorado in the past 11 weeks. We need a budget that prioritizes the well-being of Colorado Springs residents and reinvests in communities over the police, an institution that perpetuates systemic racism. 

Across the country, it is becoming more and more clear that now is the time to divest from the police and reinvest in our communities. This is especially necessary at a time of economic depression. 

I urge you to act today.
Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by swallan** [comment]
A friend of mine wrote this, I already checked it over and think it is ready for PR.

**Comment by ocassim** [comment]
This is excellent. Thank you!
