### ISSUE TITLE
Letter to Rancho Cucamonga Mayor and City Council

### ISSUE THREAD

**Issue by amxrib** [defund12/defund12.org#775]
Letter to Rancho Cucamonga Mayor and City Council

To:
council@cityofrc.us, city.clerk@cityofrc.us, james.frost@cityofrc.us 

Subject:
[*** INSERT YOUR OWN SUBJECT LINE***]

Message:
Dear Rancho Cucamonga City Council,

My name is [YOUR NAME], and I am a resident of Rancho Cucamonga. I am writing to you because I am concerned with the city's growing police funding and budget cuts to other services.

The preliminary budget for 2020/21 increases the amount allocated to the police from $42,327,060 to $44,869,070. And while I applaud the substantial increase in the amount allocated to Community Services, there have been budget cuts to Economic and Community Development, Building and Safety Services, Engineering Services, and Planning. Less than $7,000,000 is budgeted for these community development services, while the police get over $44,000,000.

The police in America have never been meant to protect those who are low income and people of color. Unfortunately, Rancho Cucamonga is no exception. Police violence can not be ended by reform. And more policing is not the solution to crime. Instead, we must look to the root causes of crime and address those issues. We must make increased efforts to ensure financial and housing security, improve mental health services, and develop substance abuse treatment services--not increase deployment and militarization of the police.

Following the murder of George Floyd, Minneapolis City Council has announced their plan to "disband the Minneapolis Police Department and invest in community-led public safety."

Rancho Cucamonga must follow this precedent. Rancho Cucamonga must take the initiative to defund the police.

It is no secret that the COVID-19 pandemic has unexpectedly affected city finances. However, a time like this creates even greater necessity to invest in the community. I am urging you to revisit the 2020/21 preliminary budget and reallocate funds from the police back to the community. 

Thank you,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by ctneal91** [comment]
on it now
