### ISSUE TITLE
Add Providence, RI

### ISSUE THREAD

**Issue by nschonz** [defund12/defund12.org#777]
# Feature request

Want to add a new feature to the site? Please describe the requested feature and provide any relevant information:

**Comment by swallan** [comment]
Hi @nschonz,

To add your city, please provide email addressed and an email for us to use! Check out the guidelines here and submit an new request: https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md

Thanks for contributing!
