### ISSUE TITLE
Letter to SBUSD Board Members

### ISSUE THREAD

**Issue by wphoward3** [defund12/defund12.org#780]
SBUSD Board Member Emails:
lcapps@sbunified.org
jreid@sbunified.org
rmunoz@sbunified.org
kford@sbunified.org
wsims-moten@sbunified.org

Dear SBUSD Board Members, 

My name is [YOUR NAME] and I'm writing to you as a Santa Barbara resident to demand you take the following actions: 

-Allocate funds to rehabilitation and mental health services for at-risk youth as an alternative to probation and/or juvenile hall. 
-Adopt a resolution declaring racism as a public health emergency and allocate resources to implement restorative justice practices to deal with hate crimes. 
-Implement equitable hiring practices and recruit culturally competent teachers of color to teach ethnic studies courses. 
-Publicly condemn the school-to-prison pipeline. 
-Offer ethnic studies classes with culturally relevant curricula. 
-Defund any contracts with the SB County Sherrif's Department and Santa Barbara Police Department.

Thank you. 

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

Link to Insta post from a Santa Barbara youth who posted these demands: https://www.instagram.com/p/CBJhuOqnrex/?utm_source=ig_web_copy_link

**Comment by swallan** [comment]
Hi @seylea and @sarahallee ,

It looks like we already have an email for Santa Barbara, and emails are to focus on defunding and not on what the funding should be going towards.

While it may be relevant to request that the school district stop using the police, it should be the primary focus of the email.

**Comment by wphoward3** [comment]
Should I re-submit my request with a different email that emphasizes
cutting ties with SBPD?

Will
