### ISSUE TITLE
Please add Rochester NY

### ISSUE THREAD

**Issue by sarahallee** [defund12/defund12.org#784]

**Comment by seylea** [comment]
!!!

**Comment by swallan** [comment]
Hi @seylea and @sarahallee ,

To add your city, please provide email addressed and an email for us to use! Check out the guidelines here and submit an new request: https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md

Thanks for contributing!
