### ISSUE TITLE
Add Colorado Springs, Colorado

### ISSUE THREAD

**Issue by ocassim** [defund12/defund12.org#785]
To:  Governorpolis@state.co.us, Don.Knight@Coloradosprings.gov, David.Geislinger@Coloradosprings.gov, Richard.Skorman@coloradosprings.gov, Yolanda.Avila@coloradosprings.gov, Jill.Gaebler@coloradosprings.gov, Andy.Pico@Coloradosprings.gov, bill.murray@coloradosprings.gov, tom.strand@coloradosprings.gov,  Wayne.williams@coloradosprings.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE*** Example: Defund the Police, Fund the Community]

Dear Colorado Springs City Council,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY].

I am writing to demand a reallocation of funding from the Colorado Springs  Police Department to social and public programming for our communities. With record unemployment and a seemingly intractable pattern of abuse and unequal treatment by police, our city needs a budget that adequately and effectively meets the needs of at-risk Colorado Springs residents.

For FY2020, $4.4 million dollars were used to hire new police officers while a minimal amount of the budget was used for public transportation ($300,000), People who are experiencing homelesness ($500,000), . This is unacceptable, and I demand that the city council remedy this gross display of priorities. You must support a budget that supports social equity in our community, rather than empowering and growing the police forces that tear us apart.

It is your duty to represent your constituents. I am urging you to advocate for revision of the Colorado Springs city budget for the upcoming fiscal year to reflect the decades of research showing that education and social programs better promote the safety of a city than policing.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by swallan** [comment]
#768

**Comment by samriggio** [comment]
Thanks for adding COS, ocassim! My wife and I were just looking through the city's budget, and it looks like the figures you quote are for _increases_ in FY2020, and the actual total expenditures are much, much higher. I'm digging them up and updating your template.

**Comment by swallan** [comment]
Hi @samriggio and @ocassim, it looks like we already have an issue for this, #768. Please comment there if you would like to enhance that message!

**Comment by ocassim** [comment]
Thank you so much. I admittedly tried to throw this together quickly to get
it out there.

**Comment by bingbongle** [comment]
Closing this one out.
