### ISSUE TITLE
Add Glendale, CA

### ISSUE THREAD

**Issue by madelinelazer** [defund12/defund12.org#786]
# Feature request

Want to add a new feature to the site? Please describe the requested feature and provide any relevant information:

**Comment by madelinelazer** [comment]
Thank you for doing this!!

**Comment by swallan** [comment]
Hi @madelinelazer ,

To add your city, please provide email addressed and an email so we can add it! Check out the guidelines here and submit an new request: https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md

Thanks!
