### ISSUE TITLE
Add Prince William County, VA

### ISSUE THREAD

**Issue by saraavalentine** [defund12/defund12.org#788]
EMAIL PRINCE WILLIAM COUNTY BOARD OF SUPERVISORS TO RECONSIDER 2021 POLICE BUDGET
To: awheeler@pwcgov.org, vsangry@pwcgov.org, jlawson@pwcgov.org, yvega@pwcgov.org, gainesville@pwcgov.org, kboddye@pwcgov.org, abailey@pwcgov.org, mfranklin@pwcgov.org 

Subject: **[Write Your Own Unique Subject Line]** 

To Chairman Ann B. Wheeler and the Prince William County Board of Supervisors, 
My name is **[your name]** and I am a proud resident of Prince William County. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-blackness, and immediate reform in how black people are treated in America. Our county has been at the forefront of much of this action. Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue. 
The PWC Police Department has been a waste of our resources. The proposed budget for the Police Department for 2021 is $118,237,179. Compare this to the Housing & Community Development budget of $43,362,792 or the Public Health budget of just $3,428,388. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in Prince William County. Instead, we see wasteful and harmful action of our police.
I call on you to slash the PWC Police Department budget and instead use those extraordinary resources towards funding what Black and Brown communities need to be safe and healthy: COVID-19 relief, housing, healthcare, treatment, healing, cooperative businesses, community centers, community-led organizations and projects.
We can be a beacon for other cities and counties to follow if only we have the courage to change.
Sincerely,
**[Your name]
[Your address]
[Your phone number]
[Your e-mail]**

**Comment by mahrer** [comment]
reviewing now

**Comment by mahrer** [comment]
Some minor edits:

EMAIL PRINCE WILLIAM COUNTY BOARD OF SUPERVISORS TO RECONSIDER 2021 POLICE BUDGET

To: awheeler@pwcgov.org, vsangry@pwcgov.org, jlawson@pwcgov.org, yvega@pwcgov.org, gainesville@pwcgov.org, kboddye@pwcgov.org, abailey@pwcgov.org, mfranklin@pwcgov.org

Subject: [WRITE YOUR OWN UNIQUE SUBJECT LINE]

To Chairman Ann B. Wheeler and the Prince William County Board of Supervisors,

My name is [YOUR NAME] and I am a resident of [CITY/COUNTY]. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police behavior, an end to racism and anti-Blackness, and immediate reform in how Black people are treated in America. Our county has been at the forefront of much of this action. 

Accordingly, it has come to my attention that the budget for 2021 is being decided as these protests continue. The PWC Police Department has been a waste of our resources. The proposed budget for the Police Department for 2021 is $118,237,179. Compare this to the Housing & Community Development budget of $43,362,792 or the Public Health budget of just $3,428,388. While we’ve been spending extraordinary amounts on policing, we have not seen improvements to safety, homelessness, mental health, or affordability in Prince William County. Instead, we see wasteful and harmful action of our police.

I call on you to slash the PWC Police Department budget and instead use those extraordinary resources towards funding what Black and Brown communities need to be safe and healthy: COVID-19 relief, housing, healthcare, treatment, healing, cooperative businesses, community centers, community-led organizations and projects.

We can be a beacon for other cities and counties to follow if only we have the courage to change.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE NUMBER]
[YOUR E-MAIL]

**Comment by ctneal91** [comment]
on it now
