### ISSUE TITLE
Charleston, SC - letter to Mayor and City Council Members

### ISSUE THREAD

**Issue by noodleghoul** [defund12/defund12.org#792]
To: tecklenburgj@charleston-sc.gov, delcioppom@charleston-sc.gov, shealyk@charleston-sc.gov, jasonsakrandistrict3@gmail.com, mitchellro@charleston-sc.gov, bradyk@charleston-sc.gov, gregoriewd@charleston-sc.gov, waringp@charleston-sc.gov, mike@seekingslaw.com, peter@charlestoncitycouncil9.org, griffinh@charleston-sc.gov, appelr@charleston-sc.gov, jacksonc@charleston-sc.gov

Subject: Defunding the Charleston Police Department

Message:

Dear Mayor Tecklenburg and Charleston City Council Members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY].

I am demanding you reallocate funds from the Charleston City Police department and invest them into social services that would directly improve the well-being of Charleston citizens. 

The budget for 2019 was $51,764,862, and the budget for 2020 is $53,445,152. This is a 3% increase from 2019 to 2020 and an almost 10% increase from 2018 to 2020. That money could be better spent on supporting affordable housing, educational opportunities, healthcare, and community outreach programs that are more successful at promoting safe and stable communities than law enforcement. I demand more aggressive financial support be directed to those areas.

I am demanding long term and sustainable change. I am demanding that the city of Charleston’s budget be better spent on quality of life for all. In particular for those in our Black and Brown communities, who are more than likely to be directly affected by police brutality and violence. I also urge the Charleston City Council to enact legislation that holds police accountable and to overturn policies that allow police to engage in unlawful behavior with impunity.

People are marching in the streets because they know that these actions will result in a healthier, more just society. I implore you to please listen to the needs of your constituents and take immediate action to address their concerns. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by daliadalili** [comment]
update seekingsm@charleston-sc.gov email address to mike@seekingslaw.com

**Comment by noodleghoul** [comment]
updated

**Comment by ctneal91** [comment]
on it now
