### ISSUE TITLE
Request for Norman, Oklahoma

### ISSUE THREAD

**Issue by ajang2000** [defund12/defund12.org#793]

**Comment by swallan** [comment]
Hi @ajang2000  ,

To add your city, please provide email addressed and an email so we can add it! Check out the guidelines here and submit an new request: https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md

Thanks!

**Comment by ajang2000** [comment]
Hello,

Could you clarify that?


Thank you so much!

Ashley

**Comment by swallan** [comment]
@ajang2000,

We are unable to research and determine proper recipients for individual requests, but we may add an email with your elected officials if you write one.

Thanks!
