### ISSUE TITLE
Please add these Police Forces 

### ISSUE THREAD

**Issue by aleachedekel** [defund12/defund12.org#794]
# Feature request

Want to add a new feature to the site? Please describe the requested feature and provide any relevant information:

Would it be possible for you to add the Fairfax CA (a zip code: 94930) police department and the Central Marin Police Authority? I’m trying to start organizing in my vastly white and $$$ county. Thank you so much for you help & for this project.

**Comment by swallan** [comment]
Hi @aleachedekel,

To add your city, please provide email addressed and an email for us to use! Check out the guidelines here and submit an new issue request: https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md

Thanks for contributing!
