### ISSUE TITLE
Bounced Emails for Westchester County

### ISSUE THREAD

**Issue by sneakmeg** [defund12/defund12.org#798]
![0AC6BD98-68CC-4DBA-97A1-7B403FE69869](https://user-images.githubusercontent.com/66575425/83988828-75dacb00-a912-11ea-8e54-5f85a69cce75.png)

**Comment by serifluous** [comment]
@sneakmeg hey! We’re trying to resolve the issue in issue #686. Can you chime in there if there’s more to add?
