### ISSUE TITLE
add Rochester, NY

### ISSUE THREAD

**Issue by animalcrossingmom** [defund12/defund12.org#814]
To: Loretta.Scott@cityofrochester.gov, Malik.Evans@cityofrochester.gov, Mitch.Gruber@cityofrochester.gov, Willie.Lightfoot@cityofrochester.gov, Jacklyn.Ortiz@cityofrochester.gov, LaShay.Harris@cityofrochester.gov, Mary.Lupien@cityofrochester.gov, Michael.Patterson@cityofrochester.gov, Jose.Peo@cityofrochester.gov, info@cityofrochester.gov, Lovely@MayorLovelyWarren.com

Subject: [***INSERT UNIQUE SUBJECT LINE***]

Message: (Don't forget to replace the [x]'s with your information!)
To the Rochester City Council and Mayor Lovely Warren,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD]. I am imploring you to meaningfully restrict the Rochester Police Department’s $95.87 million dollar budget immediately. These funds would be better allocated towards services proven to more effectively promote a safe and equitable community, such as community mental health services, substance abuse treatment services, education, affordable housing programs, and more.

In the proposed 2020-2021 budget, it was mentioned that many residents are dissatisfied with the Rochester City School District and prioritize the cultivation of healthy schools and recreational services for Rochester children. Recreational and youth services are budgeted at just over $12.4 million. The child poverty level in Rochester is one of the highest in the nation, with a rate of 52 percent between 2013 and 2017. The police are allocated over 672% more funds than youth services in the proposed 2020-2021 budget. Additionally, while the city spends $119.1 million in aid to the Rochester City School District, this accounts for only 12.8% of the RCSD budget. If even part of the police budget were allocated to the RCSD, imagine the kind of change that the city could see in its education system.

Much scholarship shows that a living wage, access to health services and treatment, educational opportunity, and stable housing are far more successful at promoting community safety than policing and prisons. Police “reform” is not enough. As such, I demand a meaningful reallocation of police department funds towards education, healthcare, and social programs.

Sincerely, [YOUR NAME]

**Comment by skullface** [comment]
Thanks for your request @animalcrossingmom! This message is in the queue for review from the defund12.org content review team. 

A request was filed for Monroe County yesterday by @ditto888 at https://github.com/defund12/defund12.org/issues/580. We prefer messages to be as specific to as possible in terms of locale, but there might be messaging you can consolidate from @ditto888’s request as well.

cc original Rochester requesters + supporters: @seylea @sarahallee @lanerendell @eastsideboy585 @dunham-mike @dieseltravis

Thank you!

**Comment by averymcguirt** [comment]
@skullface marking this ready for PR since it is more developed than the county submission (#580) 
Also don't see a problem with separate messages to county and city with distinct recipients if #580 is eventually completed.
