### ISSUE TITLE
Hollister, CA - Letter to Revise City Budget 

### ISSUE THREAD

**Issue by shelbyrose30** [defund12/defund12.org#815]
To: mayor@hollister.ca.gov, coh.dist1@hollister.ca.gov, coh.dist2@hollister.ca.gov, coh.dist3@hollister.ca.gov, coh.dist4@hollister.ca.gov, coh.treasurer@hollister.ca.gov 

[*****INSERT UNIQUE SUBJECT LINE*****]

Dear Mayor Velazquez and Hollister City Council,

My name is [YOUR NAME] and I am a resident of Hollister. I am writing to demand that the Hollister City Council adopt a city budget that prioritizes community well-being, and redirects funding away from the police.

In the 2018-2019 fiscal year, the City of Hollister allocated an increase of 2.4 million dollars to our police system. In the 2019-2020 fiscal year, Hollister administered another increase of 1.6 million dollars to our police system, equating to an inordinate 44% of our total budget at 26.4 million dollars. This is compared to just 14% of the budget, $8.3 million, allocated towards community services and supplies - an 18% decrease from the 2018-2019 budget. It has been estimated that there will be a 54 billion dollar deficit in the California state budget as a result of the pandemic. Our local San Benito High School is preparing for significantly less funding following this crisis. The city may recoup some of these funds by decreasing the police budget.

I demand that the City Council begin meaningfully defunding the Hollister Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community. We need funding for community-based mental health services, substance abuse treatment services, and affordable housing programs, not police. I love this community and I want to see it flourish into an even better one. I demand a budget that reflects the actual needs of Hollister residents and works to improve the well being of everyone who lives in and visits this city.

History has shown that police "reform" is not enough. No more money, and more importantly, no more lives must be lost to police. We must take a hard look at the way the current system in place fails to serve - and in fact actively harms - our community, and come together to reimagine the role of police in our city.

I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to invest in the people, not the police. We trust that you will do the right thing for us, because we put our trust in you when we elected you to serve us. This is a moment for you to step up and show us that you care for our community as much as we care for each other and this city.

Thank you for your time,

[YOUR NAME]
[ADDRESS]
[EMAIL]
[PHONE #]

**Comment by swallan** [comment]
This one is really nice!

**Comment by rpalakkal** [comment]
on it
