### ISSUE TITLE
Request to defund the Fort Worth Police Department!

### ISSUE THREAD

**Issue by austinzhuang** [defund12/defund12.org#816]
Template for Defund12, Fort Worth 

To: betsy.price@fortworthtexas.gov, carlos.flores@fortworthtexas.gov, brian.byrd@fortworthtexas.gov, cary.moon@fortworthtexas.gov, gyna.bivens@fortworthtexas.gov, jungus.jordan@fortworthtexas.gov, dennis.shingleton@fortworthtexas.gov, kelly.allengray@fortworthtexas.gov, ann.zadeh@fortworthtexas.gov 

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!) 

Hello all,
My name is [NAME]. I am a resident of Fort Worth, Texas and I am emailing you today to demand a complete override on our Fort Worth Police Department in light of the Black Lives Matter protests being demonstrated across the US, but specifically our own community. 
WE ARE JOINING TOGETHER TO DEMAND THAT YOU, MY LOCAL OFFICIALS, WILL vote NO on all police budget increase for the City of Fort Worth, vote YES to decrease police spending and budgets, and vote YES to increase spending on health care, education towards Fort Worth ISD as a whole, and community programs throughout the city of Fort Worth and Tarrant County.

The militarized tactics that our police have used against its citizens in response to peaceful protesting is not tolerated and unwarranted. To ensure your dedication to our city and citizens, I demand that you defund the Fort Worth Police Department by 75%, and start providing more support and funding towards our community efforts and organizations that serve our predominantly Latinx and Black communities, as these are the communities that are being targeted the most. By doing so, I believe this will prevent further police brutality and violence in the future. Our fellow Latinx and Black brothers and sisters living in these communities are living in persistent fear of being killed by state authorities like police, immigration agents or even white vigilantes, who are emboldened by state actors. According to some research I've done the Urban Institute mentions that in 1977 alone, state and local governments spent $60 billion on police and corrections. Despite continued profiling, harassment, terror and killing of Black communities, local and federal decision-makers continue to invest in the police, which leaves Black people vulnerable and our communities no more secure than it is at this moment. 

Instead, that money could go towards building healthy communities, to the health of our elders and children, to neighborhood infrastructure, to education, to childcare, to support a vibrant Black future. The possibilities are endless.
We join in solidarity with the freedom fighters in Minneapolis, Louisville, and across the United States. And we call for the end to police terror.

Sincerely, 
[NAME] [PHONE_NUMBER] [EMAIL] [ADDRESS]

**Comment by skullface** [comment]
Hi @austinzhuang, thank you for your submission! There is already an open request for Fort Worth, TX. 

I am closing this issue in favor of the existing request just because it was filed earlier, not for merit or quality! 

Please see #627 (https://github.com/defund12/defund12.org/issues/627) for more.
