### ISSUE TITLE
Ask Riverside City Council to reconsider emergency budget before June 16th

### ISSUE THREAD

**Issue by asc823** [defund12/defund12.org#842]
1. [Unique subject line addressing importance of swift action before June 16]
2. Email addresses: EEdwards@riversideca.gov; asmelendrez@riversideca.gov; RFierro@riversideca.gov; cconder@riversideca.gov; GPlascencia@riversideca.gov; jperry@riversideca.gov; SHemenway@riversideca.gov; 2mayor@riversideca.gov
3. Detailed message: 

Dear Mayor Bailey and Riverside City Council Members,
My name is [YOUR NAME] and I am a Riverside resident. I am writing to demand that the Riverside City Council adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police. 
In 2019, the City of Riverside directed $123,598,355 of General Fund money to the police, representing 44% of the total budget alongside additional Measure Z funds. On June 16, the City Council will adopt an Emergency Budget to respond to shortfalls related to the COVID-19 crisis. The proposed budget increases the police budget both numerically and as a percentage of the general fund. Given the circumstances of the public health crisis, it is more urgent than ever that the City Council go back to the drawing board and redirect a significant portion of the police budget toward programs that support a healthy and secure Riverside. I demand a budget that reflects the real needs of Riverside residents including affordable housing programs, community-based mental health services, and more.
Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by asc823** [comment]
https://www.riversideca.gov/finance/PDF/budget-2020/Proposed%20Emergency%20Budget.pdf

Budget information found here^^

**Comment by swallan** [comment]
[Unique subject line addressing importance of swift action before June 16]
Email addresses: EEdwards@riversideca.gov; asmelendrez@riversideca.gov; RFierro@riversideca.gov; cconder@riversideca.gov; GPlascencia@riversideca.gov; jperry@riversideca.gov; SHemenway@riversideca.gov; 2mayor@riversideca.gov
Detailed message:
Dear Mayor Bailey and Riverside City Council Members,

My name is [YOUR NAME] and I am a Riverside resident. I am writing to demand that the Riverside City Council adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police.

In 2019, the City of Riverside directed $123,598,355 of General Fund money to the police, representing 44% of the total budget alongside additional Measure Z funds. On June 16, the City Council will adopt an Emergency Budget to respond to shortfalls related to the COVID-19 crisis. 
The proposed budget increases the police budget both numerically and as a percentage of the general fund. Given the circumstances of the public health crisis, it is more urgent than ever that the City Council go back to the drawing board and redirect a significant portion of the police budget toward programs that support a healthy and secure Riverside. I demand a budget that reflects the real needs of Riverside residents including affordable housing programs, community-based mental health services, and more.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by dionlarson** [comment]
On it!
