### ISSUE TITLE
Edit Miami, FL

### ISSUE THREAD

**Issue by d4nc3r5ky** [defund12/defund12.org#843]
I just noticed that I miscalculated the percentage of the police as part of the total operating budget for the city. It should be **32.8%** instead of 35.8

265621000/808633000=.328

Source, page 17:
http://archive.miamigov.com/Budget/docs/FY20/Adopted%20Budget%20Book%20with%20TOC%20Hyperlinks.pdf

**Comment by todd-m** [comment]
thanks for checking and adding the source! -- looks good and making the change now
