### ISSUE TITLE
Tampa, FL - Letter to Mayor

### ISSUE THREAD

**Issue by anniesidd** [defund12/defund12.org#844]
To: mayor@tampagov.net, tampacitycouncil@tampagov.net

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!) 🔗

Dear Mayor Castor and Tampa City Council Members,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the Tampa City Council adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police.

In 2019, the City of Tampa allocated 163 million dollars to our police system, an inordinate 40% of our total budget. The $2.6 million budgeted for Body Worn Cameras Program will further increase the budget for the police system. This single project has a larger budget than the enitre department for Economic and Urban Development, which is allocated $2.3 million. In addition, the police budget vastly exceeds the only $600k spent on Minority and Small Business Development.

I demand that the City Council begin meaningfully defunding the Tampa Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Tampa residents.

History has shown that police "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve--and in fact actively harms--our community, and come together to reimagine the role of police in our city.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by anniesidd** [comment]
Sorry just saw that I missed issue #652 for Tampa

**Comment by dionlarson** [comment]
@anniesidd feel free to suggest additions on the other issue! 🙂
