### ISSUE TITLE
Add Dutchess County, New York to list

### ISSUE THREAD

**Issue by lilypiya** [defund12/defund12.org#847]

**Comment by mahrer** [comment]
Hi, thanks for your interest in adding your city to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Subject line for the email
- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!

**Comment by lilypiya** [comment]
To:  
tnelson@cityofbeacon.orgarhodes@cityofbeacon.orgjmccredo@cityofbeacon.orgdaymarblair@cityofbeacon.orggmansfield@cityofbeacon.orgagrant@cityofbeacon.orgmayor@cityofbeacon.org

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!) 

Dear Beacon City Council and Mayor,

My name is [YOUR NAME] and I am a Beacon resident and writing to urge you to defund the Beacon Police Department.

The Beacon Police department currently has a budget of $5.5 Million. That has increased $700,000 in the past 6 years while other services have been cut or kept the same. That's about 25% of our total budget for a town of roughly 15K people, taking away desperately needed resources from essential city programs and services.

I demand that the Mayor and City Council begin meaningfully defunding the Beacon Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: our public schools and after-school programs, a recreation center, emergency health center, community-based mental health services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Beacon residents.

History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city.

Thank you for your time, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by lilypiya** [comment]
Also instead of Dutchess County,  the link should say: Beacon (New York) - Letter to Mayor and City Council

**Comment by mahrer** [comment]
reviewing now

**Comment by mahrer** [comment]
Some very minor edits:

To:  
tnelson@cityofbeacon.org, arhodes@cityofbeacon.org, jmccredo@cityofbeacon.org, daymarblair@cityofbeacon.org, gmansfield@cityofbeacon.org, agrant@cityofbeacon.org, mayor@cityofbeacon.org

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!) 

Dear Beacon City Council and Mayor,

My name is [YOUR NAME] and I am a resident of [CITY]. I am writing to urge you to defund the Beacon Police Department. The Beacon Police department currently has a budget of $5.5 Million. That has increased $700,000 in the past 6 years while other services have been cut or kept the same. That's about 25% of our total budget for a town of roughly 15K people, taking away desperately needed resources from essential city programs and services.

I demand that the Mayor and City Council begin meaningfully defunding the Beacon Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: our public schools and after-school programs, a recreation center, emergency health center, community-based mental health services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Beacon residents.

History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city.

Thank you for your time, 
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by rpalakkal** [comment]
on it now
