### ISSUE TITLE
Add Somerville, MA

### ISSUE THREAD

**Issue by julia-zachary** [defund12/defund12.org#848]
To: citycouncil@somervillema.gov, cityclerk@somervillema.gov, mayor@somervillema.gov

Subject:[*** INSERT UNIQUE SUBJECT LINE***]

Dear Somerville City Council,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the Somerville City Council adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police.

For the FY2020 budget, the City of Somerville allocated $18.2 million dollars to our police system, comprising 7% of our total budget (and nearly half of the total Public Safety budget). This is compared to just $4.5 million allocated towards Culture & Recreation (1.8% of the budget). Additionally, within the $21 million of grants received in 2018, $749,867 was allocated to the police system, while only $120,610 was allocated to the Arts Council. Furthermore, the Office of Sustainability & Environment only receives a mere $503,187.

I demand that the City Council begin meaningfully defunding the Somerville Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, sustainable energy options and more. I demand a budget that reflects the actual needs of Somerville residents.

History has shown that police "reform" is not enough. We must take a hard look at the ways that the current system in place fails to serve--and in fact actively harms--our community, and come together to reimagine the role of police in our city.

Thank you for your time,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by dionlarson** [comment]
Hey @julia-zachary! There's an email currently proposed for Somerville in issue #618 which is in the process of getting added. Can you comment there with anything you'd like to add or edit?
