### ISSUE TITLE
Palm Beach County, Florida - Board of County Commissioners

### ISSUE THREAD

**Issue by egheather** [defund12/defund12.org#849]
To: DKerner@pbcgov.org, RWeinroth@pbcgov.org, HValeche@pbcgov.org, gweiss@pbcgov.org, MBerger@pbcgov.org, MMcKinlay@pbcgov.org, MBernard@pbcgov.org, OFMB@pbcgov.org, public@co.palm-beach.fl.us 

**Subject: Reallocate the budget. Defund the police.**  

To the Board of Palm Beach County Commissioners, OFMB Director Brown, and County Administrator Baker,

My name is [YOUR NAME] and I am a resident of [YOUR CITY], Florida. Last May, Palm Beach County Sheriff Ric Bradshaw requested a 6% hike in funding for his department, proposing an annual budget of $703 million for 2020 with $75 million set aside for replacing vehicles in the next five years. According to the Palm Beach County Fiscal Year 2020 Budget, the Sheriff’s Office was appropriated more than $725.8 million—an 8% increase from 2019. 

Combined with federal and municipal-level funding, the full financial cost of policing in our area dramatically dwarfs support for resources that would enrich and protect Florida communities: youth programs, food security, mental health and wellness, free public transport, affordable housing, universal childcare, substance abuse prevention and treatment, and more. 

For example, the 2020 budget awarded $813,582 to the Office of Equal Opportunity, which has a staff of 12 working on disability access, equal employment, and fair housing. The Criminal Justice Commission received just $750,417 from the county to support 11 staff members working to reduce pretrial detentions, incarceration rates, and racial disparities. Speaking of disparities, the Sheriff’s Office averaged more than twice the amount of funding for each of its 4,289 positions. 

I urge you to reimagine the way the justice system works in Palm Beach County. This means investing in our community’s long-term health and prosperity and, in doing so, decreasing the demand for such an expensive police force in the first place. Until Palm Beach County does this, we are failing to serve communities of color and actively upholding a system of white supremacy. 

Your mission statement is “to drive a continuous improvement culture of excellence that achieves a measurably high level of public satisfaction” in Palm Beach County. For such satisfaction to be achieved, you should adopt a budget that prioritizes community wellbeing through education, health care, and social services while redirecting funding away from police and incarceration.

As one of your constituents, I’m asking you to take immediate, concrete action on this issue. I will be sure to tell my friends, family, and neighbors about your response. 

Sincerely,
[YOUR NAME]

**Comment by sagea123** [comment]
I'd been working on adding PBC to this site but I'm glad you guys did it already! Just a suggestion to add their mission statement after "I urge you to..." This is what I had in the letter I was working on:

Your mission statement states “To drive a continuous improvement culture of excellence that achieves a measurably high level of public satisfaction.” For such satisfaction to be achieved, we are demanding that Palm Beach County adopt a budget that prioritizes community wellbeing and redirects funding away from the police. 

I also suggest adding Sherry Brown's email: OFMB@pbcgov.org and the County Administrator: public@co.palm-beach.fl.us

**Comment by egheather** [comment]
cool, i just added those emails and a note about their mission statement!

**Comment by todd-m** [comment]
on it
