### ISSUE TITLE
Please add Rhode Island

### ISSUE THREAD

**Issue by lividol** [defund12/defund12.org#850]
# Feature request

Want to add a new feature to the site? Please describe the requested feature and provide any relevant information:

Please add rhode island so we can add our city form letters! Thank you.

**Comment by mahrer** [comment]
Hi there, it looks like there is an open issue for Newport, Rhode Island #697. Feel free to look that over and comment any input you have. 

If there's another city you'd like to add, you **must** provide:

- Subject line for the email
- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!
