### ISSUE TITLE
Edit Ann Arbor, MI

### ISSUE THREAD

**Issue by michael-gapuz** [defund12/defund12.org#857]
I reviewed Ann Arbor's 2020 budget and am proposing the following clarifications to the Ann Arbor message that is currently posted:

Mayor Taylor and City Council members,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/BOROUGH/CITY]. Given the history of policing and the most recent murders of Black people, I am asking you to redirect money away from the Ann Arbor PD in the 2021 budget and instead to prioritize services that help strengthen our communities.

I want a budget that reflects our community's priorities and needs. In 2020, the City of Ann Arbor's FY Budget showed ~~the majority of funding allocated~~ that 27% of the general fund was allocated to policing while only 16% was allocated to community services and only 6% to public services. We want ~~that~~ Ann Arbor PD's funding redistributed to services that actually help the people of Ann Arbor, including affordable housing, more mental health services, and rent suspension and forgiveness for those who are currently unemployed. Beyond policing our community, these services are proven to be more effective in improving community safety and wellness. I demand a budget that supports community wellbeing, rather than gives power to police forces that tear them apart.

Please consider your role in enriching and empowering our communities, especially during a time of racial injustice, wide-spread illness, and economic vulnerability.

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by averymcguirt** [comment]
Thank you for your suggestions. I agree, and will change the text now.
