### ISSUE TITLE
Annapolis, MD

### ISSUE THREAD

**Issue by leachnotabug** [defund12/defund12.org#860]
SEND TO:

mayorbuckley@annapolis.gov , aldtierney@annapolis.gov , aldpaone@annapolis.gov , aldpindellcharles@annapolis.gov , aldfinlayson@annapolis.gov , aldrodriguez@annapolis.gov , aldgay@annapolis.gov , aldsavidge@annapolis.gov , aldarnett@annapolis.gov

[UNIQUE SUBJECT LINE]

Dear City Council Members and Mayor Buckley,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD]. I write this letter to urge you to defund not only the Annapolis Police Department, but the Office of Emergency Management as well. The UASI (Urban Area Security Initiative) falls under the Office of Emergency Management Department, and is a crucial aspect to be addressed in policy reform for the safety, justice & quality of life of our community.
The Annapolis Police Department takes up 23% of the city's general fund leaving parks and recreation services, community enrichment, and environmental conservation/policy at 1.5%, 3.1% and 2.8% respectively. Beyond the general funding, the grants allocated to the Police Department and Office of Emergency Management take up 96% of the federal grant funds, 73% of state grant funds, and 100% of county grant funds. APD & OEM are taking away needed resources from essential city programs and services that can better the lives of our people! (Source: Annapolis Fiscal Year 2020 Adopted Annual Operating Budget) .

As Annapolis residents, we therefore demand that you take immediate action to ensure the health, safety & wellness of our people.
Defund the Police Department.
Defund the UASI in the Office of Emergency Management
Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.
Invest in community development initiatives and programs.
Invest in environmental restoration & policy.
Annapolis is the capital of Maryland. We demand change!

Thank you,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
reviewing now

**Comment by mahrer** [comment]
Thanks for including your source! Some minor edits:

SEND TO:
mayorbuckley@annapolis.gov , aldtierney@annapolis.gov , aldpaone@annapolis.gov , aldpindellcharles@annapolis.gov , aldfinlayson@annapolis.gov , aldrodriguez@annapolis.gov , aldgay@annapolis.gov , aldsavidge@annapolis.gov , aldarnett@annapolis.gov

[UNIQUE SUBJECT LINE]

Dear City Council Members and Mayor Buckley,

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY]. I write this letter to urge you to defund not only the Annapolis Police Department, but the Office of Emergency Management as well. The UASI (Urban Area Security Initiative) falls under the Office of Emergency Management Department, and is a crucial aspect to be addressed in policy reform for the safety, justice and quality of life of our community.

The Annapolis Police Department takes up 23% of the city's general fund, leaving parks and recreation services, community enrichment, and environmental conservation/policy at 1.5%, 3.1% and 2.8% respectively. Beyond the general funding, the grants allocated to the Police Department and Office of Emergency Management take up 96% of the federal grant funds, 73% of state grant funds, and 100% of county grant funds. APD & OEM are taking away needed resources from essential city programs and services that can better the lives of our people! (Source: Annapolis Fiscal Year 2020 Adopted Annual Operating Budget) .

I demand that you take immediate action to ensure the health, safety & wellness of our people.
Defund the Police Department.
Defund the UASI in the Office of Emergency Management.
Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.
Invest in community development initiatives and programs.
Invest in environmental restoration & policy.
Annapolis is the capital of Maryland. I demand change!

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by leachnotabug** [comment]
awesome. thank you for editing!

molly

**Comment by ctneal91** [comment]
on it now
