### ISSUE TITLE
Letter for City of Westminster, CO

### ISSUE THREAD

**Issue by annacyoung** [defund12/defund12.org#867]
hatchison@cityofwestminster.us
aseitz@cityofwestminster.us
ddemott@cityofwestminster.us
rseymour@cityofwestminster.us
kskulley@cityofwestminster.us
llsmith@cityofwestminster.us
jvoelz@cityofwestminster.us

Dear Westminster City Council,

My name is [YOUR NAME] and I am a resident of Westminster, Colorado.

I am writing to demand a reallocation of funding from the Westminster Police Department to social and public programming for our communities. With record unemployment and a seemingly intractable pattern of abuse and unequal treatment by police, our city needs a budget that adequately and effectively meets the needs of at-risk Westminster residents.

For FY2020, nearly $27 million was allocated for policing (20% of the budget) while only $6.5m was allocated for community development programs. This is unacceptable, and I demand that the city council remedy this gross display of priorities. You must support a budget that supports social equity in our community, rather than empowering the police forces that tear us apart.

It is your duty to represent your constituents. I am urging you to advocate for revision of the Westminster city budget for the upcoming fiscal year to reflect the decades of research showing that education and social programs better promote the safety of a city than policing.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by DiplodocusDad** [comment]
Please add Donald M. Tripp, City Manager, dtripp@cityofwestminster.us to the list of recipients. 

"Dear Westminster City Council" could be updated to: 

"Dear City Council and Executive Leadership"

The above verbiage matches that used in the 2019-2020 CITY OF WESTMINSTER ADOPTED BUDGET: https://www.cityofwestminster.us/Portals/1/Documents/Government%20-%20Documents/Budget/2019%202020%20Adopted%20Budget%20for%20Web.pdf?ver=2018-12-20-150314-543
 

It may not hurt to add some or all of the following recipients as well:
• Barbara Opie, Deputy City Manager, BOpie@cityofwestminster.us
• Jody Andrews, Deputy City Manager, JAndrews@cityofwestminster.us
• Larry Dorr, Deputy City Manager, LDorr@cityofwestminster.us
• Chris Lindsey, Assistant City Manager, CLindsey@cityofwestminster.us
• John Hall, Economic Development Director, JLHall@cityofwestminster.us

**Comment by annacyoung** [comment]
hatchison@cityofwestminster.us
aseitz@cityofwestminster.us
ddemott@cityofwestminster.us
rseymour@cityofwestminster.us
kskulley@cityofwestminster.us
llsmith@cityofwestminster.us
jvoelz@cityofwestminster.us
BOpie@cityofwestminster.us
JAndrews@cityofwestminster.us
LDorr@cityofwestminster.us
CLindsey@cityofwestminster.us
JLHall@cityofwestminster.us

Dear Westminster City Council and Executive Leadership,

My name is [YOUR NAME] and I am a resident of Westminster, Colorado.

I am writing to demand a reallocation of funding from the Westminster Police Department to social and public programming for our communities. With record unemployment and a seemingly intractable pattern of abuse and unequal treatment by police, our city needs a budget that adequately and effectively meets the needs of at-risk Westminster residents.

For FY2020, nearly $27 million was allocated for policing (20% of the budget) while only $6.5m was allocated for community development programs. This is unacceptable, and I demand that the city council remedy this gross display of priorities. You must support a budget that supports social equity in our community, rather than empowering the police forces that tear us apart.

It is your duty to represent your constituents. I am urging you to advocate for revision of the Westminster city budget for the upcoming fiscal year to reflect the decades of research showing that education and social programs better promote the safety of a city than policing.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by annacyoung** [comment]
i don't really know how this works. i edited per your suggestions, now what?

**Comment by DiplodocusDad** [comment]
Hi Anna, 
Thank you for updating your original posting with my suggestions. I'm not entirely sure how this works either; I am just another resident in Westminster who saw you'd beaten me to creating the original request and thought it would be best to involve the City Manager, as they're part of the budget creation process. I presume that the defund12.org team will complete their review and commit the request to the project if everything checks out. 
Thanks again!

**Comment by annacyoung** [comment]
thanks! feel free to add/change some of the language if you want. our city
actually does a little better than most with what they allocate to the
police budget, so i wasn't sure what to call them out on.

**Comment by rpalakkal** [comment]
Working on this one
