### ISSUE TITLE
Please add Tompkins County (New York)

### ISSUE THREAD

**Issue by hcres** [defund12/defund12.org#869]
To: lmcbean@tompkins-co.org; akelles@tompkins-co.org; hgranison@tompkins-co.org; rjohn@tompkins-co.org; akoreman@tompkins-co.org; msigler@tompkins-co.org; dklein@tompkins-co.org; dmckenna@tompkins-co.org;  gmorey@tompkins-co.org; ddawson@tompkins-co.org; sblack@tompkins-co.org; achampion@tompkins-co.org; mrobertson@tompkins-co.org; mlane@tompkins-co.org
Subject: [*** INSERT UNIQUE SUBJECT LINE***]
Message:

Dear Tompkins County Legislature,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am asking the County Legislature to begin meaningfully defunding the Tompkins County Sheriff's Office and other police departments within the county and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Tompkins County residents. Much scholarship shows that a living wage, access to health services and treatment, educational opportunity, and stable housing are far more successful at promoting community safety than policing and prisons. As such, I demand a meaningful reallocation of police department funds towards healthcare and social programs.

Sincerely, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Hi @hcres ! Thanks for your interest in adding Tompkins County to the site. Can you provide more detail about the city budget (as well as your source) to make a more compelling argument, showing the disparities in numbers?

Please see our [email style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for some suggestions.

Thank you!
