### ISSUE TITLE
Letter for Duluth, MN City Council 

### ISSUE THREAD

**Issue by gunnaraas** [defund12/defund12.org#880]
To: 
ganderson@DuluthMN.gov
jsipress@duluthmn.gov
rrandorf@duluthmn.gov
rvannett@DuluthMN.gov
jkennedy@duluthmn.gov
zfilipovich@duluthmn.gov
aforsman@duluthmn.gov
dmedved@DuluthMN.gov
bruss@duluthmn.gov

Dear Duluth City Council, 

My name is [YOUR NAME] and I am a resident of Duluth, MN. 

I am writing to you today to demand the council defund the Duluth Police Department. I stand in solidarity with protesters across the country who are out in the streets in response to the horrific murders of George Floyd, a Black man, by the Minneapolis police, and are appalled by the recent murders of Breonna Taylor, Ahmaud Arbery, Tony McDade and countless others. 

People have been left without the resources they need. Jobs and livelihoods will take a long time to recover. And most of all, Black citizens of Duluth continue to live in a city that is currently upholding White Supremacy, enforced by guns of the DPD. I stand with the anti-racist movement in our city in saying that we will no longer accept empty gestures and suggestions of reform.

I call on the Duluth City Council to take the following actions:

-  Redirect funds divested from policing to provide educational opportunities for communities impacted by police violence.

- Commit resources to support community-led alternatives to policing.

- Propose plans for ensuring the safety of Black and other marginalized people in our community from racial profiling by police and other security forces with input from members of the marginalized communities themselves.

- Issue statements condemning these recent murders.

Although the murder of George Floyd was the catalyst for these recent protests, it was not the sole cause. Black people have been subjected to centuries of state terror, and economic and social exclusion. The current protests reflect concerned members of society taking direct, collective action to demand an end to the abuse and violence directed against Black people. I am urging you, and the rest of the Duluth City Council, to adopt a budget that defunds the police and funds non-violent, community-led, health and safety strategies.

Your neighbor, 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE NUMBER]

**Comment by NickCrews** [comment]
On this one

**Comment by mahrer** [comment]
Hi @gunnaraas ! Thanks for your interest in adding Duluth to the site. Can you provide more detail about the city budget (and your source) to make a more compelling argument, showing the disparities in numbers?

Please see our [email style guide](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for some suggestions.

Thank you!

**Comment by OwlCat-Fox** [comment]
Hi,

I attached a letter that I wrote. Feel free to borrow language from it and add it to your own letter or not. You wrote a good letter. I will add the link to the Duluth 2020 Budget and post the numbers of the DPD budget and the city budget below too, so you don't have to go and find the numbers to add to the current letter.
https://duluthmn.gov/media/9899/2020-budget-book-online-version.pdf
The DPD Approved expenditure was around 24 million dollars, most of it is for salaries (I believe that to be about 14 Million Dollars). Another 7 million dollars is for benefits The last big expense is a little over a million dollars in "other expenses". It is about 26% of the general fund (ie approved expenditures), which totals $92,912,600 dollars. the main thing to harp on, in my opinion, is the lack of transparency in the budget. The budget doesn't illuminate the military style equipment they have, I believe most of it has been gifted to the DPD through a small christian non-profit funded by Twin Metals. Slate did an article on it 2 years ago (I believe).

[Letter to Duluth MN City Council and Mayor.docx](https://github.com/defund12/defund12.org/files/4765775/Letter.to.Duluth.MN.City.Council.and.Mayor.docx)

**Comment by mahrer** [comment]
@gunnaraas @OwlCat-Fox I attempted to edit the original message, adding in data provided by @OwlCat-Fox. If you'd like to add another bit about the military style equipment, feel free to write it up and comment below. Let me know what you think:

---

To:
ganderson@DuluthMN.gov
jsipress@duluthmn.gov
rrandorf@duluthmn.gov
rvannett@DuluthMN.gov
jkennedy@duluthmn.gov
zfilipovich@duluthmn.gov
aforsman@duluthmn.gov
dmedved@DuluthMN.gov
bruss@duluthmn.gov

Dear Duluth City Council,

My name is [YOUR NAME] and I am a resident of Duluth, MN.

I am writing to you today to demand the council defund the Duluth Police Department. I stand in solidarity with protesters across the country who are out in the streets in response to the horrific murders of George Floyd, a Black man, by the Minneapolis police, and are appalled by the recent murders of Breonna Taylor, Ahmaud Arbery, Tony McDade and countless others.

People have been left without the resources they need. Jobs and livelihoods will take a long time to recover. And most of all, Black citizens of Duluth continue to live in a city that is currently upholding White Supremacy, enforced by guns of the DPD. I stand with the anti-racist movement in our city in saying that we will no longer accept empty gestures and suggestions of reform.

We must be aware that our low-income communities and communities of color are disproportionate targets of police violence. An audit conducted by BerryDunn in a 2019 report lays out the injustice in the Duluth Police Department. Yet little is revealed to the public about the progress of reformation. Justice will only be served when our vision of safety is based on community, equality, and justice. This will not be possible until we defund DPD.

According to the 2020 Budget Book, the DPD approved expenditure was around $24 million, paying for salaries, benefits, and "other expenses." This is about 26% of the $92.9 million general fund, more than Property, Parks, Libraries, and Public Works combined. 

I call on the Duluth City Council to take the following actions:

- Redirect funds divested from policing towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.
- Commit resources to support community-led alternatives to policing.
- Propose plans for ensuring the safety of Black and other marginalized people in our community from racial profiling by police and other security forces, with input from members of the marginalized communities themselves.
- Issue statements condemning these recent murders.

Although the murder of George Floyd was the catalyst for these recent protests, it was not the sole cause. Black people have been subjected to centuries of state terror, and economic and social exclusion. The current protests reflect concerned members of society taking direct, collective action to demand an end to the abuse and violence directed against Black people. I am urging you, and the rest of the Duluth City Council, to adopt a budget that defunds the police and funds non-violent, community-led, health and safety strategies.

Your neighbor,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE NUMBER]

Sources:
https://duluthmn.gov/media/9899/2020-budget-book-online-version.pdf 
https://duluthmn.gov/media/9310/duluth-report-full-v21.pdf

**Comment by OwlCat-Fox** [comment]
@mahrer @gunnaraas Those edits look good to me. I would only change the WE in the first sentence of the third paragraph ("we must be aware that our low-income communities and communities of color are disproportionate targets of police violence") to a "You".
So, it would read "You must be aware that our low-income communities and communities of color are disproportionate targets of police violence."

**Comment by mahrer** [comment]
Got it. Final version below:

---

To:
ganderson@DuluthMN.gov
jsipress@duluthmn.gov
rrandorf@duluthmn.gov
rvannett@DuluthMN.gov
jkennedy@duluthmn.gov
zfilipovich@duluthmn.gov
aforsman@duluthmn.gov
dmedved@DuluthMN.gov
bruss@duluthmn.gov

Dear Duluth City Council,

My name is [YOUR NAME] and I am a resident of Duluth, MN.

I am writing to you today to demand the council defund the Duluth Police Department. I stand in solidarity with protesters across the country who are out in the streets in response to the horrific murders of George Floyd, a Black man, by the Minneapolis police, and are appalled by the recent murders of Breonna Taylor, Ahmaud Arbery, Tony McDade and countless others.

People have been left without the resources they need. Jobs and livelihoods will take a long time to recover. And most of all, Black citizens of Duluth continue to live in a city that is currently upholding White Supremacy, enforced by guns of the DPD. I stand with the anti-racist movement in our city in saying that we will no longer accept empty gestures and suggestions of reform.

You must be aware that our low-income communities and communities of color are disproportionate targets of police violence. An audit conducted by BerryDunn in a 2019 report lays out the injustice in the Duluth Police Department. Yet little is revealed to the public about the progress of reformation. Justice will only be served when our vision of safety is based on community, equality, and justice. This will not be possible until we defund DPD.

According to the 2020 Budget Book, the DPD approved expenditure was around $24 million, paying for salaries, benefits, and "other expenses." This is about 26% of the $92.9 million general fund, more than Property, Parks, Libraries, and Public Works combined.

I call on the Duluth City Council to take the following actions:

- Redirect funds divested from policing towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.
- Commit resources to support community-led alternatives to policing.
- Propose plans for ensuring the safety of Black, Indigenous, and other marginalized people in our community from racial profiling by police and other security forces, with input from members of the marginalized communities themselves.
- Issue statements condemning these recent murders.

Although the murder of George Floyd was the catalyst for these recent protests, it was not the sole cause. Black people have been subjected to centuries of state terror, and economic and social exclusion. The current protests reflect concerned members of society taking direct, collective action to demand an end to the abuse and violence directed against Black people. I am urging you, and the rest of the Duluth City Council, to adopt a budget that defunds the police and funds non-violent, community-led health and safety strategies.

Your neighbor,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR PHONE NUMBER]

Sources:
https://duluthmn.gov/media/9899/2020-budget-book-online-version.pdf
https://duluthmn.gov/media/9310/duluth-report-full-v21.pdf
