### ISSUE TITLE
Please add fresno ca, modesto ca, stockton ca. Thank you! 

### ISSUE THREAD

**Issue by lar333** [defund12/defund12.org#899]
# Feature request

Want to add a new feature to the site? Please describe the requested feature and provide any relevant information:

**Comment by skullface** [comment]
Hi @lar333, thanks for your interest in adding these cities to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Subject line for the email
- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** now. When you have that content, please open a new issue for each city. Thank you!
