### ISSUE TITLE
Request to add South San Francisco to the list

### ISSUE THREAD

**Issue by ssf4change** [defund12/defund12.org#905]
We'd like to add South San Francisco, CA to the site, please.

**City:** South San Francisco, CA
**Subject line:** [Insert unique subject line]
**Email addresses of gov't officials:** buenaflor.nicolas@ssf.net, mark.nagales@ssf.net, rich.garbarino@ssf.net, mark.addiego@ssf.net, karyl.matsumoto@ssf.net
**Message:**
Dear South San Francisco Mayor and City Council Members,

My name is [NAME] and I am a [resident/community member/student/alumni/city employee/company employee] of South San Francisco. 

How are the nation’s uprisings against police brutality and systematic oppression that impacts Black and brown communities going to be addressed by the city of South San Francisco? 

I am emailing to demand Mayor Garbarino and the city council divest from the South San Francisco Police Department. Currently, the proposed budget for the next fiscal year would allocate $31,935,228, 28% of the proposed $112,416,313 general fund to the police department. 

As a community member I recognize the hardships that have been brought on by the COVID-19 pandemic and the need to allocate funds for those issues. However, the police department is still receiving a $50,000 increase from 2019, while millions are being removed from Parks and Recreation, Fire, Library, and the Econ. and Community Development Departments. Our community will not benefit from increased policing during these hard times, but instead we need the funds moved into programs that directly benefit our youth, elders and all community members. What part of supporting our community through a pandemic requires increased policing combined with a 50% decrease in training within the SSFPD?

I demand that Mayor Garbarino restructure the FY 2019-2021 budget. By investing in policing, you are investing in a system that was created for and continues to serve the purpose of controlling and threatening Black and brown people. It is unacceptable that Black lives continue to be lost at the hands of police, and it is clear that policing reforms are not enough. We see this same violence inflicted upon our non-Black Latino community as well. I am calling on our city council to commit to reducing the police budget and reinvesting in programs that will actually serve our community such as COVID relief, housing, educational enrichment, transportation, and community programs.

I ask that you take a deeper and reflective look at alternatives to policing that yield better results for public safety as well as how the current resources dedicated to the SSF police department have been harmful to our communities. Specifically, I would rather see funds go towards mental health professionals, crisis de-escalators, and the Community Development Block Grant fund which serves to assist low income persons by: providing decent and affordable housing, providing a suitable living environment, and expanding economic opportunities.

Thank you for your attention to my concerns. I hope to hear back from you soon

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Some minor edits:

City: South San Francisco, CA
Subject line: [Insert unique subject line]
Email addresses of gov't officials: buenaflor.nicolas@ssf.net, mark.nagales@ssf.net, rich.garbarino@ssf.net, mark.addiego@ssf.net, karyl.matsumoto@ssf.net
Message:

Dear South San Francisco Mayor and City Council Members,

My name is [NAME] and I am a resident of [NEIGHBORHOOD/CITY].

How are the nation’s uprisings against police brutality and systematic oppression of Black and Brown communities going to be addressed by the city of South San Francisco?

I am emailing to demand Mayor Garbarino and the City Council divest from the South San Francisco Police Department. Currently, the proposed budget for the next fiscal year would allocate $31,935,228 to the police department -- 28% of the proposed $112,416,313 general fund.

As a community member I recognize the hardships that have been brought on by the COVID-19 pandemic and the need to allocate funds for those issues. However, the police department is still receiving a $50,000 increase from 2019, while millions are being removed from Parks and Recreation, Fire, Library, and the Econ. and Community Development Departments. Our community will not benefit from increased policing during these hard times, but instead we need the funds moved into programs that directly benefit our youth, elders and all community members. What part of supporting our community through a pandemic requires increased policing combined with a 50% decrease in training within the SSFPD?

I demand that Mayor Garbarino restructure the FY 2019-2021 budget. By investing in policing, you are investing in a system that was created for and continues to serve the purpose of controlling and threatening Black and Brown people. It is unacceptable that Black lives continue to be lost at the hands of police, and it is clear that policing reforms are not enough. We see this same violence inflicted upon our non-Black Latino community as well. I am calling on our City Council to commit to reducing the police budget and reinvesting in programs that will actually serve our community such as COVID relief, housing, educational enrichment, transportation, and community programs.

I ask that you take a deeper and reflective look at alternatives to policing that yield better results for public safety as well as how the current resources dedicated to the SSF police department have been harmful to our communities. Specifically, I would rather see funds go towards mental health professionals, crisis de-escalators, and the Community Development Block Grant fund which serves to assist low income persons by: providing decent and affordable housing, providing a suitable living environment, and expanding economic opportunities.

Thank you for your attention to my concerns. I hope to hear back from you soon

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
@ssf4change I'm wondering where you got the data for the $50,000 increase from 2019? According to this document I'm seeing much larger numbers:
https://www.ssf.net/home/showdocument?id=16797

**Comment by ssf4change** [comment]
@mahrer how about the following? SSF city council is planning on discussing budget updates tomorrow. We'd originally gotten the $50,000 figure from the proposed budget changes being discussed tomorrow, but have taken out the specific numbers in light of possible upcoming changes. 

City: South San Francisco, CA
Subject line: [Insert unique subject line]
Email addresses of gov't officials: buenaflor.nicolas@ssf.net, mark.nagales@ssf.net, rich.garbarino@ssf.net, mark.addiego@ssf.net, karyl.matsumoto@ssf.net
Message:
Dear [representative],


My name is [insert name] and I am a [resident/community member/student/alumni/city employee/company employee] of South San Francisco. 

The demonstrations across the nation have made it clear that there is a need for change. How will our city address the police brutality and systematic oppression we see occurring across the nation and in our own city?

I am emailing to demand Mayor Garbarino and the city council divest from the South San Francisco Police Department. Currently, the proposed budget for the next fiscal year would allocate $31,935,228—28% of the proposed $112,416,313 general fund—to the police department. 

As introduced earlier, I urge Mayor Garbarino to restructure the FY 2019-2021 budget. The investment in policing perpetuates a system that was created for and continues to serve the purpose of controlling and threatening Black and brown people. It is unacceptable that Black lives continue to be lost at the hands of police, and it is clear that policing reforms are not enough. I am calling on our city council to commit to reducing the police budget and reinvesting in programs that will directly serve our community such as COVID relief, housing, educational enrichment, transportation, and community programs.

The current funds dedicated to the SSFPD have been harmful to our community and we ask that our leadership and community take a deeper look at alternatives to policing that yield better results. Specifically, I would rather see funds go towards mental health professionals, crisis de-escalators, and the Community Development Block Grant fund, which serves to assist low income persons by: providing decent and affordable housing, providing a suitable living environment, and expanding economic opportunities.


Thank you for your attention to my concerns. We hope to see action from our leadership soon.
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Looks good. Some minor edits:

City: South San Francisco, CA
Subject line: [INSERT UNIQUE SUBJECT LINE]
Email addresses of gov't officials: buenaflor.nicolas@ssf.net, mark.nagales@ssf.net, rich.garbarino@ssf.net, mark.addiego@ssf.net, karyl.matsumoto@ssf.net

Message:

Dear Mayor Garbarino South San Francisco City Council,

My name is [YOUR NAME] and I am a [RESIDENT/COMMUNITY MEMBER/CITY EMPLOYEE/COMPANY EMPLOYEE/ETC] of South San Francisco.

How are the nation’s uprisings against police brutality and systematic oppression of Black and Brown communities going to be addressed by the city of South San Francisco?

I am emailing to demand Mayor Garbarino and the city council divest from the South San Francisco Police Department. Currently, the proposed budget for the next fiscal year would allocate $31,935,228—28% of the proposed $112,416,313 general fund—to the police department.

I urge Mayor Garbarino to restructure the FY 2019-2021 budget. The investment in policing perpetuates a system that was created for and continues to serve the purpose of controlling and threatening Black and Brown people. It is unacceptable that Black lives continue to be lost at the hands of police, and it is clear that policing reforms are not enough. I am calling on our City Council to commit to reducing the police budget and reinvesting in programs that will directly serve our community such as COVID relief, housing, educational enrichment, transportation, and community programs.

The current funds dedicated to the SSFPD have been harmful to our community, and we ask that our leadership and community take a deeper look at alternatives to policing that yield better results. Specifically, I would rather see funds go towards mental health professionals, crisis de-escalators, and the Community Development Block Grant fund, which serves to assist low income persons by: providing decent and affordable housing, providing a suitable living environment, and expanding economic opportunities.

Thank you for your attention to my concerns. We hope to see action from our leadership soon.
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ssf4change** [comment]
Great, thank you!

**Comment by ssf4change** [comment]
I'm sorry can we actually send this updated one:

Dear [representative],

My name is [insert name] and I am a [resident/community
member/student/alumni/city employee/company employee] of South San
Francisco.

I am emailing to demand Mayor Garbarino and the city council divest from
the South San Francisco Police Department. The demonstrations across the
nation have made it clear that there is a need for change. How will our
city address the police brutality and systematic oppression we see
occurring across the nation and in our own city?

Currently, the proposed budget for the next fiscal year would allocate
$31,935,228—28% of the proposed $112,416,313 general fund—to the police
department. I urge Mayor Garbarino and the city council to restructure the
fiscal year 2020-2021 budget. The current investment in policing
perpetuates a system that serves the purpose of controlling and threatening
Black and Brown people. It is unacceptable that Black lives continue to be
lost at the hands of police, and it is clear that policing reforms are not
enough. I am calling on our city council to commit to reducing the police
budget and reinvesting in other essential programs such as COVID relief,
affordable housing, educational enrichment, transportation, and community
programs.

Specifically, I would rather see funds go towards mental health programs,
crisis de-escalators, and the Community Development Block Grant fund which
serves to assist low income persons by: providing decent and affordable
housing, providing a suitable living environment, and expanding economic
opportunities.

The current funds dedicated to the SSFPD have been harmful to our community
and I ask that our leadership take a look at alternatives to policing and
in the meantime allocate money to programs and services that will benefit
our community.

Thank you for your attention to my concerns. We hope to see action from our
leadership soon.

[YOUR NAME]

[YOUR ADDRESS]

[YOUR EMAIL]

[YOUR PHONE NUMBER]

**Comment by mahrer** [comment]
Edited to make "we" statements into "I" statements and insertable lines all caps so that they aren't missed (per our style guide):

Subject line: [INSERT UNIQUE SUBJECT LINE]
Email addresses of gov't officials: buenaflor.nicolas@ssf.net, mark.nagales@ssf.net, rich.garbarino@ssf.net, mark.addiego@ssf.net, karyl.matsumoto@ssf.net

Dear Mayor Garbarino and South San Francisco City Council,

My name is [YOUR NAME] and I am a [RESIDENT/COMMUNITY MEMBER/CITY EMPLOYEE/COMPANY EMPLOYEE/ETC] of South San Francisco.

I am emailing to demand Mayor Garbarino and the City Council divest from the South San Francisco Police Department. The demonstrations across the nation have made it clear that there is a need for change. How will our city address the police brutality and systematic oppression we see occurring across the nation and in our own city?

Currently, the proposed budget for the next fiscal year would allocate $31,935,228—28% of the proposed $112,416,313 general fund—to the police department. I urge Mayor Garbarino and the city council to restructure the fiscal year 2020-2021 budget. The current investment in policing
perpetuates a system that serves the purpose of controlling and threatening Black and Brown people. It is unacceptable that Black lives continue to be lost at the hands of police, and it is clear that policing reforms are not enough. I am calling on our city council to commit to reducing the police budget and reinvesting in other essential programs such as COVID relief, affordable housing, educational enrichment, transportation, and community programs.

Specifically, I would rather see funds go towards mental health programs, crisis de-escalators, and the Community Development Block Grant fund which serves to assist low income persons by: providing decent and affordable housing, providing a suitable living environment, and expanding economic opportunities.

The current funds dedicated to the SSFPD have been harmful to our community and I ask that our leadership take a look at alternatives to policing and in the meantime allocate money to programs and services that will benefit our community.

Thank you for your attention to my concerns. I hope to see action from our leadership soon.

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by ssf4change** [comment]
@mahrer Sounds good, thank you! And can we make the title "DEFUND SSFPD!"?
