### ISSUE TITLE
Add Chico, CA

### ISSUE THREAD

**Issue by swiss528** [defund12/defund12.org#907]
ann.schwab@chicoca.gov Alex.brown@chicoca.gov Scott.huber@chicoca.gov sean.morgan@chicoca.gov karl.ory@chicoca.gov Kasey.reynolds@chicoca.gov randall.stone@chicoca.gov

[Insert Unique Subject Line] 

Dear Chico City Council,
My name is [your name], and I am a concerned resident of Chico, CA. I am emailing in support of the nation wide initiative to defund police departments in favor of supporting community based public safety measures. This includes an increased budget for social services to fight homelessness, addiction, mental illness, domestic violence, and sexual assault.
This past week, our nation and community have been gripped by protests calling for an end to racism and anti-blackness and a complete overhaul in our approach to criminal justice in America. I am writing to demand real change to the Chico criminal justice system.
The police budget for the city of Chico, CA makes up 48.8% of the city budget, per your city budget proposal online.  There is nothing allocated in the budget to support mental health services. As you all well know, there is a large population of homeless residents. Many of these homeless residents are mentally ill, faced with addiction or have experienced domestic violence that has caused this homelessness. Homelessness is a public health and safety issue, and a reallocation of funds to mental health and addiction services instead of police organizations would greatly reduce the risk of homelessness in Chico. This is just one example of a marginalized group in Chico that would benefit from defunding Chico Police Department.
Research shows that a living wage, access to health services and treatment including mental health services, educational opportunity, and stable housing are far more successful at promoting safe and equitable communities than punitive systems like police or prisons. 
In the journal of Sociology of Race and Ethnicity, Phillip McHarris (PhD candidate at Yale focusing on race) argues that we must work towards a reality in which healthcare workers and emergency response teams handle substance abuse, domestic violence, homelessness, or mental health cases. Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing (Sources: The Nation, The Atlantic). We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence.
I demand immediate reduction of the police force budget, cancellation of cadet classes, demilitarization of our forces, and reallocation of funds from police to community-led health and safety strategies. We should redirect police funding to efforts that are actually proven to reduce crime, such as affordable housing, shelters, and mental health services.
It is your duty to represent your constituents. I am urging you to revise the Chico, CA recommended operating budget for FY 2020-21, and to increase funds to non-punitive community efforts.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by averymcguirt** [comment]
Another submission for Chico has been approved for creation of PR. 
@swiss528 would you add any language in particular from here to #1013 ? Happy to facilitate synthesis of messages if so.

**Comment by swiss528** [comment]
I'll get on that now. I'll edit them both together (leaving their language and voice in also) and post in the comments here and in that post.

**Comment by swiss528** [comment]
Dear City Councilmembers of Chico,

My name is [YOUR NAME] and I am a resident of Chico, California. I am emailing in support of the nationwide initiative to defund police departments in favor of supporting community based public safety measures. This includes an increased budget for social services to fight homelessness, addiction, mental illness, domestic violence, and sexual assault.

As you know, George Floyd, Ahmaud Arbery, Breonna Taylor, Tony McDade, Atatiana Jefferson, Tamir Rice, Philando Castile, Anthony Hill, Oscar Grant, Eric Garner, Yvette Smith, Desmond Phillips, and so many unnamed others have been killed as a result of deeply-rooted systemic racism and police brutality.
As a result of these events, I ask that the city council review their 2020-2021 budget. Instead of allocating 48.8% ($27 million dollars) of funds towards the Police Force, and only 2% (1.1 million dollars) towards developing our community, I ask you to reallocate funds from the police department to other areas that desperately need it. These areas include community development, mental health treatment, affordable housing, funding for domestic violence shelters, and investing in the Black and Indigenous communities. Homelessness is a public health and safety issue, and a reallocation of funds to mental health and addiction services instead of police organizations would greatly reduce the risk of homelessness in Chico. This is just one example of a marginalized group in Chico that would benefit from defunding Chico Police Department.

Unfortunately, there are no racial demographics in regard to arrest rates or homelessness that are easily accessible to the public. These statistics would make it much easier for the public and for community leaders, including Chico City Council, to see whether there are a disproportionate amount of arrests of Black, Indigenous, Latino, and other marginalized racial groups. It would also help the city of Chico to see whether the proportion of Black people and people of color face homelessness at higher rates. I demand that these numbers be made available to the public or otherwise counted in order to better serve BIPOC communities in Chico. Representation of these groups in Chico’s statistics for any public survey are of utmost importance. If there is no representation, there is no visibility, and if there is no visibility, then individuals belonging to the most marginalized groups will be underserved.

Research shows that a living wage, access to health services and treatment including mental health services, educational opportunity, and stable housing are far more successful at promoting safe and equitable communities than punitive systems like police or prisons.
In the journal of Sociology of Race and Ethnicity, Phillip McHarris (PhD candidate at Yale focusing on race) argues that we must work towards a reality in which healthcare workers and emergency response teams handle substance abuse, domestic violence, homelessness, or mental health cases. Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing (Sources: The Nation, The Atlantic). We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence.

I demand immediate reduction of the police force budget, cancellation of cadet classes, demilitarization of our forces, and reallocation of funds from police to community-led health and safety strategies. We should redirect police funding to efforts that are actually proven to reduce crime, such as affordable housing, shelters, and mental health services.

It is your duty to represent your constituents. I am urging you to revise the Chico, CA recommended operating budget for FY 2020-21, and to increase funds to non-punitive community efforts.

This is a small step in light of a national discussion including defunding, disarming, and disbanding police forces. Major cities nationwide are having these discussions and just because Chico isn’t a metropolitan area, does not mean that local Black Lives Matter any less. We should be having these discussions alongside the national narrative. We need to reimagine the systems that keep our community safe.

Thank you for all you do for the City of Chico, and for your consideration.

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by serifluous** [comment]
Added Chico here: https://defund12.org/chico
