### ISSUE TITLE
Add Olympia WA Please

### ISSUE THREAD

**Issue by monknoiz** [defund12/defund12.org#909]
City Council Contacts:
Mayor Cheryl Selby cselby@ci.olympia.wa.us
Mayor Pro Tem Jessica Bateman jbateman@ci.olympia.wa.us
Councilwoman Dani Madrone dmadrone@ci.olympia.wa.us
Councilman Clark Gilman cgilman@ci.olympia.wa.us
Councilwoman Lisa Parshley lparshle@ci.olympia.wa.us
Councilwoman Renata Rollins rrollins@ci.olympia.wa.us
Councilman Jim Cooper jcooper@ci.olympia.wa.us
Interim City Manager Jay Burney cityhall@ci.olympia.wa.us

**Comment by skullface** [comment]
Hi @monknoiz, thanks for your interest in adding Olympia to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Email addresses (at least one) of the government officials you’d like to receive the message ✅
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!
