### ISSUE TITLE
Add Roanoke County, pleas!

### ISSUE THREAD

**Issue by ninacummings** [defund12/defund12.org#914]
# Feature request

Want to add a new feature to the site? Please describe the requested feature and provide any relevant information:
 
Request to add "Letter to Board of Supervisors and Departments of Finance and Budget Division" for Roanoke County, Virginia

To: bos@roanokecountyva.gov, PMAHONEY@roanokecountyva.gov, administration@roanokecountyva.gov, llgearheart@roanokecountyva.gov, MTHOMPSON@roanokecountyva.gov, MTHOMPSON@roanokecountyva.gov, cwhite@roanokecountyva.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!)
Dear Members of the City Council and Budget Department,

My name is [YOUR NAME], and I am a resident of Roanoke County. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police brutality, racism and anti-Blackness sentiments, and immediate improvements in how Black people are treated in America. Many citizens, myself included, believe that these changes will begin by defunding police departments and investing in community structures and alternatives to police force.

The Roanoke County Police Department has been a waste of our resources. For FY 2020-2021, nearly $13M has been allocated to RCPD. While we’ve been spending extraordinary amounts on policing, we have not seen sufficient improvements to safety, homelessness, mental health, or affordability in our city. Instead, we see wasteful and harmful actions of our police.

I call on you to further meaningfully restrict the RCPD budget and instead use those resources towards funding what Black and other marginalized communities need to be safe and healthy: COVID-19 relief, affordable housing, education, healthcare (especially mental healthcare and resources), community centers, treatment, and community-led organizations. Currently the Public Assistance branch of Social Services only receives only $4.7M and sees no increase in funding over the previous year, and Public Health receives only $0.5M. These numbers are especially shocking in light of the heroin epidemic impacting this area of the state. 

Roanoke County's public would be better served by dedicating resources to programs that are more effective at promoting safety and social equity than policing and incarceration. Social programs and education generally have been shown to be much more effective at achieving these goals than policing and incarceration.

We can be a beacon for other cities to follow if only we have the courage to change. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Sincerely,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by wendywx** [comment]
edits in bold:

-----------------------------------------------------

To: bos@roanokecountyva.gov, PMAHONEY@roanokecountyva.gov, administration@roanokecountyva.gov, llgearheart@roanokecountyva.gov, MTHOMPSON@roanokecountyva.gov, MTHOMPSON@roanokecountyva.gov, cwhite@roanokecountyva.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!)

Dear Members of the City Council and Budget Department,

My name is [YOUR NAME], and I am a resident of Roanoke County. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police brutality, racism and anti-Blackness sentiments, and immediate improvements in how Black people are treated in America. **I** believe that these changes will begin by defunding police departments and investing in community structures and alternatives to police force.

The Roanoke County Police Department has been a waste of our resources. For FY 2020-2021, **$12.3**M has been allocated to RCPD. While **Roanoke County** has been spending extraordinary amounts on policing, **the community has** not seen sufficient improvements to safety, homelessness, mental health, or affordability in our city. Instead, **I** see wasteful and harmful actions of our police.

I call on you to further meaningfully restrict the RCPD budget and instead use those resources towards funding what Black and other marginalized communities need to be safe and healthy: COVID-19 relief, affordable housing, education, healthcare (especially mental healthcare and resources), community centers, treatment, and community-led organizations. Currently the Public Assistance branch of Social Services only receives only $4.7M and sees no increase in funding over the previous year, and Public Health receives only $0.5M. These numbers are especially shocking in light of the heroin epidemic impacting this area of the state.

Roanoke County's public would be better served by dedicating resources to programs that are more effective at promoting safety and social equity than policing and incarceration. Social programs and education generally have been shown to be much more effective at achieving these goals than policing and incarceration.

We can be a beacon for other cities to follow if only we have the courage to change. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Sincerely,

[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

-----------------------------------------------

Confirmed (and updated some) statistics from:
https://www.roanokecountyva.gov/DocumentCenter/View/18245/REVISED-FY-2020---FY-2021-Proposed-Budget?bidId=

@skullface please update this issue to ready for PR

**Comment by rpalakkal** [comment]
got this one
