### ISSUE TITLE
Defund Bozeman PD

### ISSUE THREAD

**Issue by mab2000** [defund12/defund12.org#915]

**Comment by skullface** [comment]
Hi @mab2000, thanks for your interest in adding Bozeman to the website. Emails on defund12.org are all written by community members. To add your city, you **must** provide:

- Subject line for the email
- Email addresses (at least one) of the government officials you’d like to receive the message
- Detailed message concerning the budgeting decisions at stake in your community

**_Until you provide this content, we cannot post your city._**

Follow our [email style guidelines](https://github.com/defund12/defund12.org/blob/gh-pages/EMAIL_TEMPLATE_STYLE_GUIDE.md) for quicker acceptance. Remember that messages must be city-specific and focused on defunding the police. If your message is copied from an external source, please provide a link to the original source.

Your request will be **closed** until you reply with the necessary content. Thank you!

**Comment by mab2000** [comment]
To: agenda@bozeman.net

Subject: Defund Bozeman PD

Message:

To the Bozeman City Commission,

My name is [YOUR NAME] and I am a resident of [CITY, STATE]. I am writing to demand that the City Commission adopts a budget that prioritizes community well-being and redirects funding away from the police.

Many Montanans may be tempted to think the unique nature of such a vast, yet sparsely-populated state minimizes the likelihood of police brutality in our small city communities. However, as reported by the Billings Gazette last year, Montana ranked ninth in killings by police per capita. In 2017, the Great Falls Tribune reported Montana police killings reached a total higher than the previous six years. These figures are alarming, but don’t tell the full story. Under Montana Code § 2-6-102 and Article II, Section 10 of the Montana Constitution, police disciplinary records are exempt from disclosure if there is an “individual privacy interest that clearly exceeds the merits of public disclosure.” Montana police forces operate within a culture of impunity, and as the members of the communities they are supposed to be protecting, we can’t even begin to grasp the scope of their violence.

We are in the midst of widespread upheaval over the systemic violence of policing. Empty gestures and suggestions of “reform” are inadequate and unacceptable. I am demanding that real change be made to the way this city allocates its resources.

Support for communities in need is necessary now, more than ever. I am demanding that the City Commission meaningfully defund the Bozeman Police Department. I join the calls of those across the country to defund the police. I am demanding a budget that adequately and effectively meets the needs of at-risk Bozeman residents during this trying and uncertain time. I am demanding a budget that supports community wellbeing, rather than empowering the police forces that tear them apart.

As the City Commission, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to fund the social programs proven to be more effective than policing at promoting community safety and equity. Have the courage to be a leader of the change this city, state, and country desperately needs.

Thank you for your time, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]
