### ISSUE TITLE
Defund Bozeman PD

### ISSUE THREAD

**Issue by mab2000** [defund12/defund12.org#921]
To: agenda@bozeman.net

Subject: Defund Bozeman PD

Message:

To the Bozeman City Commission,

My name is [YOUR NAME] and I am a resident of [CITY, STATE]. I am writing to demand that the City Commission adopts a budget that prioritizes community well-being and redirects funding away from the police.

Many Montanans may be tempted to think the unique nature of such a vast, yet sparsely-populated state minimizes the likelihood of police brutality in our small city communities. However, as reported by the Billings Gazette last year, Montana ranked ninth in killings by police per capita. In 2017, the Great Falls Tribune reported Montana police killings reached a total higher than the previous six years. These figures are alarming, but don’t tell the full story. Under Montana Code § 2-6-102 and Article II, Section 10 of the Montana Constitution, police disciplinary records are exempt from disclosure if there is an “individual privacy interest that clearly exceeds the merits of public disclosure.” Montana police forces operate within a culture of impunity, and as the members of the communities they are supposed to be protecting, we can’t even begin to grasp the scope of their violence.

We are in the midst of widespread upheaval over the systemic violence of policing. Empty gestures and suggestions of “reform” are inadequate and unacceptable. I am demanding that real change be made to the way this city allocates its resources.

Support for communities in need is necessary now, more than ever. I am demanding that the City Commission meaningfully defund the Bozeman Police Department. I join the calls of those across the country to defund the police. I am demanding a budget that adequately and effectively meets the needs of at-risk Bozeman residents during this trying and uncertain time. I am demanding a budget that supports community wellbeing, rather than empowering the police forces that tear them apart.

As the City Commission, the budget proposal is in your hands. It is your duty to represent your constituents. I am urging you to completely revise the budget for the 2020-2021 fiscal year, and to fund the social programs proven to be more effective than policing at promoting community safety and equity. Have the courage to be a leader of the change this city, state, and country desperately needs.

Thank you for your time, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by skullface** [comment]
Thanks so much for following up @mab2000! This is now in the review pipeline.

**Comment by NickCrews** [comment]
On this one.

**Comment by NickCrews** [comment]
Made a PR at #988

**Comment by NickCrews** [comment]
@skullface can you change label? I don't have the permission yet...

**Comment by swallan** [comment]
@NickCrews Were you able to review the content when you made the PR?

**Comment by NickCrews** [comment]
@swallan I did mess up and accidentally skipped the review step, but it's the same letter as for Billings, and some other MT cities (minus a few trivial changes like Billings->Bozeman), so I think it's good.

**Comment by NickCrews** [comment]
See https://github.com/defund12/defund12.org/commit/7e6ee6d05b9167a4547d4badbc59f13d29137ff0#commitcomment-39764445 for some more context

**Comment by swallan** [comment]
@NickCrews Ok, as long as it has been somewhat fact checked / looked over.
