### ISSUE TITLE
Please add Jackson, Wyoming. 0 emails for WY so far!

### ISSUE THREAD

**Issue by tisad819** [defund12/defund12.org#933]
[JacksonWY_Defund12_Email.docx](https://github.com/defund12/defund12.org/files/4748107/JacksonWY_Defund12_Email.docx)

To: commissioners@tetoncountywy.gov, pmuldoon@jacksonwy.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message:

[Don't forget to replace the [x]'s with your information!]
Dear County Commissioners and Mayor Muldoon,

My name is [YOUR NAME] and I am writing to you as a concerned resident of [JACKSON/WILSON/RAFTER J/ TETON COUNTY etc]. Now and in the year to come, our community will need to rely on social service organizations like WIC, One22, Public Health, Hole Food Rescue, and others at an increasing rate. Our prospective 2021 budget gives the Sheriff’s Department an extreme priority, while these other essential organizations are left with meager funds to conduct their operations.

It is unacceptable that most organizations will see large cuts while the Sheriff’s Department will see none. In light of this reality:

1)	I urge you to significantly cut the Sheriff’s Department’s $8 million budget 
2)	I urge you to advocate for a meaningful reallocation of Teton County’s expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, childcare, and other critical community needs

The police are not going to feed us when we’re hungry. They are not going to house us when we can no longer pay our rent. They are not going to protect us from domestic violence, and in fact frequently perpetrate it themselves. The residents of Teton County are tired of our tax dollars being used to fund a bloated, overstaffed police department while organizations that prioritize public good are fighting for budgetary scraps.

I know this is not easy, and I am hopeful you will do the right thing. While not a new concept, this topic is currently at the center of conversations across the country. Multiple cities (Los Angeles, Minneapolis, New York) have already taken steps to restructure and reallocate financial resources of their police departments, and more cities are likely to follow suit in the weeks, months, and years to come. A different future is possible. Do not let our county be held hostage by a police department that has too long held sway over everything else.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by wendywx** [comment]
Hi @tisad819 ! I was validating the statistics and wanted to confirm the 8 million sheriff department budget -- the 2021 recommended budget for police is $4,168,117 according to https://www.jacksonwy.gov/DocumentCenter/View/3249/Volume-II---FY2021-Recommended-Line-Item-Budget , if I am mistaken then please ignore.

Could you also add percentages of how much of the budget goes to the police, in comparison to other community programs, initiatives, or infrastructure to make a more compelling argument, showing the disparities in numbers?

**Comment by serifluous** [comment]
It seems like the email's referring to the Teton County Sheriff's Department (the "Total Public Safety" budget here: http://www.tetonwyo.org/DocumentCenter/View/10809/FY-2019-2020-Adopted-Budget)

Email could be reworded to the following (edits in bold). @tisad819 let us know if this is ok:

To: commissioners@tetoncountywy.gov, pmuldoon@jacksonwy.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message:

[Don't forget to replace the [x]'s with your information!]
Dear County Commissioners and Mayor Muldoon,

My name is [YOUR NAME] and I am writing to you as a concerned resident of [JACKSON/WILSON/RAFTER J/ TETON COUNTY etc]. Now and in the year to come, our community will need to rely on social service organizations like WIC, One22, Public Health, Hole Food Rescue, and others at an increasing rate. Our prospective 2021 budget gives the Sheriff’s Department an extreme priority, while these other essential organizations are left with meager funds to conduct their operations.

It is unacceptable that most organizations will see large cuts while the Sheriff’s Department will see none. In light of this reality:

I urge you to significantly cut the **$6.1 million budget of the Sheriff’s Department and communications**.

I urge you to advocate for a meaningful reallocation of Teton County’s expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, childcare, and other critical community needs

The police are not going to feed us when we’re hungry. They are not going to house us when we can no longer pay our rent. They are not going to protect us from domestic violence, and in fact frequently perpetrate it themselves. The residents of Teton County are tired of our tax dollars being used to fund a bloated, overstaffed police department while organizations that prioritize public good are fighting for budgetary scraps.

I know this is not easy, and I am hopeful you will do the right thing. While not a new concept, this topic is currently at the center of conversations across the country. Multiple cities (Los Angeles, Minneapolis, New York) have already taken steps to restructure and reallocate financial resources of their police departments, and more cities are likely to follow suit in the weeks, months, and years to come. A different future is possible. Do not let our county be held hostage by a police department that has too long held sway over everything else.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by tisad819** [comment]
Hi thank you for your fact checking and edits! We have been working to gather more info and talk to local representatives to see what will work best for our demands.[ This is the budget](https://www.tetoncountywy.gov/DocumentCenter/View/14454/FY2021-DRAFT-Budget?bidId=) we have been looking at, so the number we are asking to cut from is $7,893,707. We have tweaked the message to read:




To: commissioners@tetoncountywy.gov 

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message:

[Don't forget to replace the [x]'s with your information!]

Dear County Commissioners,

I am writing to you as a concerned resident of Teton County.

Now, and in the year to come, our community will need to rely on social service organizations such as, but not limited to, One22, Public Health, and Hole Food Rescue at an increasing rate.

Our budget has always given the Sheriff's Department extreme financial priority at the expense of community service organizations, and the 2021 budget is no different. The Commissioners have decided not to decrease Human Services funding in the 2021 budget, but this is not enough. As more families begin to rely on these services, they should receive funding commensurate with the growing need.

I urge you to advocate for a meaningful reallocation of Teton County’s expenditures: away from policing, and towards social programs and resources that support housing, jobs, education, health care, childcare, and other critical community needs
I urge you to:
1) significantly cut the Sheriff Department's projected 7.9 million dollar budget
2) commit to enacting both a community needs survey to find out what we can do to provide for our most vulnerable community members, and a survey of local human services organizations to find out what help they need to best meet these needs, and 
3) use the results of these surveys to advocate for a meaningful reallocation of Teton County's expenditures away from policing, and towards social programs and resources.

I want to see these funds allocated towards resources that support housing, jobs, education, healthcare, childcare and other needs in our community.

The police are not going to feed us when we're hungry. They are not going to house us when we can no longer pay our rent. They are not going to protect us from domestic violence - and statistically, are likely to perpetuate it themselves.

As a resident of Teton County, I want the use of my tax dollars to prioritize funding organizations that contribute to the well being of our community over funding policing.

I am hopeful that you will prioritize the wishes of your community in this matter.

This topic is currently at the center of conversations across the country. Los Angeles, New York City and Minneapolis have already taken steps to reallocate the financial resources of their police departments. More cities are likely to follow suit in the weeks, months and years to come.

A different future is possible. Please do not let our county continue to prioritize a fear-based "need" for policing over genuine community needs.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
