### ISSUE TITLE
Williamsburg, VA Police

### ISSUE THREAD

**Issue by kittycave** [defund12/defund12.org#935]
To:  pfreiling@williamsburgva.gov, bramsey@williamsburgva.gov, dentw@tncc.edu, caleb1424@gmail.com 

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!)

Dear Mayor Freiling and City Council Members, 

My name is [YOUR NAME] and I am a resident of [NEIGHBORHOOD/CITY/COLLEGE]. 

I am writing today in solidarity with the current global call to dismantle and restructure the racist history of police in the United States. The Williamsburg police department is a part of this system and, as your constituent, I am calling on you to meaningfully defund the police.

As elected city representatives, you must address the disproportionate policing of Black people happening in Williamsburg. Based on data from the Vera Institute of Justice, Black Americans make up 12% of the U.S population but account for an estimated 28% of all arrests nationally; according to the official 2019 police report for the city of Williamsburg, 47% of people the Williamsburg Police arrested were Black, despite the fact that only 14% of Williamsburg’s population is Black. This is an astronomical increase of an already biased and discriminatory national trend. 

Recently, the police department’s spokesperson argued that the department maintains a bias-free police force through their training efforts. Heilman also claimed that the police exercise their duties, responsibilities, and obligations “in manner that does not discriminate based on race, sex, gender, national origin, ethnicity, age, or religion.” However, the disproportionate number of arrests of Black people in the community clearly shows that all this training is not working.

According to the 2018 Census, 19.4% of Williamsburg’s White population lived below the nationally-established poverty line while 30% of Williamsburg’s Black population lived in poverty. This matters when it comes to policing because, as reported by the Massachusetts Poverty Law Advocates group, two-thirds of people detained in US jails live in poverty. Overall, police-related death rates are highest in neighborhoods with the greatest concentrations of low-income residents and residents of color, as demonstrated in a 2019 study by the American Public Health Association.

In the proposed $57 million city budget for fiscal year 2021, the police department is allotted almost $12 million ($11,974,256), or approximately 20% of the total budget, while less than $3 million is allotted for public assistance and human services, including homeless intervention and Food Stamp applications ($2,936,270) -- 5% of the total budget. This misdirection of funds creates a city that is better equipped to harm its residents than help them. The average time spent on a waitlist to get into an HUD housing program is 11 months, and that time frame jumps to 18 months for Williamsburg public housing programs. In addition, 21% of police calls that resulted in the use of force in 2019 were for mental illness. The Williamsburg community deserves a balanced budget that takes the basic rights and needs of its citizens into its forefront consideration.

Your decision to fund the police instead of contributing to human services and public outreach programming actively puts Williamsburg’s Black population at risk. Both the past and the present prove that police “reform” is not enough. Williamsburg must defund the police department in order to meet the needs of its residents and actually protect the community.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by averymcguirt** [comment]
closed by #1143

**Comment by averymcguirt** [comment]
closed by #1143

**Comment by averymcguirt** [comment]
closed by #1143

**Comment by averymcguirt** [comment]
closed by #1143

**Comment by averymcguirt** [comment]
closed by #1143
