### ISSUE TITLE
Give NickCrews permissions

### ISSUE THREAD

**Issue by NickCrews** [defund12/defund12.org#948]
# Triage access

👋 I am a defund12.org collaborator requesting triage permissions so I can assist in moderating issues, and doing simple/obvious tweaks. IDK exactly what the permission levels are, sorry I can't be more precise, just give me the lowest one and I can start there.

**Comment by bingbongle** [comment]
Starting you off with triage access to apply labels. Please thoroughly review the teams page on the workflow and how to get started.

**Comment by bingbongle** [comment]
Done!
