### ISSUE TITLE
Add Santa Maria, California

### ISSUE THREAD

**Issue by santamariagal** [defund12/defund12.org#950]
To:  CityCouncil@cityofsantamaria.org, apatino@cityofsantamaria.org , gsoto@cityofsantamaria.org, ewaterfield@cityofsantamaria.org, mmoats@cityofsantamaria.org, mcordero@cityofsantamaria.org

Subject: [*** INSERT UNIQUE SUBJECT LINE***]
Message (Don't forget to replace the [x]'s with your information!) 🔗
Dear Santa Maria City Council,

My name is [YOUR NAME] and I am a resident of [YOUR NEIGHBORHOOD/DISTRICT]. I am writing to demand that the Santa Maria City Council adopt a city budget that prioritizes community wellbeing, and redirects funding away from the police.

In 2019, the City of Santa Maria allocated 34 million dollars to our police system, an inordinate 42.5% of our total budget. This is compared to just $4 million allocated towards community development (5.0% of the budget). Within the community development budget, $1.2 million was projected to be spent on CDBG & HOME Programs (3.5% of the city’s budget).

This is a direct quote from the City of Santa Maria Budget 18'-20', "The City Council-appointed Block Grants Advisory Committee received a total of 32 applications requesting well over $1.4 million in CDBG funds for 2018-19. However, the City is only expecting to receive $1.3 million in
CDBG funding. It is anticipated that this process will continue to be very competitive, particularly with the loss of funding from the State and private foundations to many non-profit agencies." Let it be noted that 100,000 dollars accounts for 0.125% of the budget.

I demand that the City Council begin defunding the Santa Maria Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Santa Maria residents.

History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our city.

Thank you for your time, [YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by devthered** [comment]
reviewing this now!

**Comment by devthered** [comment]
Honestly, this looks great! I'd say ready to be moved to PR.
