### ISSUE TITLE
Benton County, AR Please! 

### ISSUE THREAD

**Issue by storkos** [defund12/defund12.org#952]
Request to add "Letter to Finance Committee Members" for Benton County, Arkansas

To: Treasurer@BentonCountyAR.gov, Comptroller@BentonCountyAR.gov, tallen@sagepartners.com, Susan.Anglin@bentoncountyar.gov, Debra.Hobbs@bentoncountyar.gov, carrie@soarhigher.com, Pat.Adams@bentoncountyar.gov, Jerry.Snow@BentonCountyAR.gov, Shirley.Sandlin@bentoncountyar.gov, James.Furgason@BentonCountyAR.Gov, Joshua.Bryant@bentoncountyar.gov, dtodd409@yahoo.com, Michelle.Chiocco@bentoncountyar.gov, Joel.Edwards@bentoncountyar.gov, mike.mckenzie77@gmail.com, kmoore16342@gmail.com

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!)
Dear Members of the Finance Committee,

My name is [YOUR NAME], and I am a resident of Benton County. This past week, our nation has been gripped by protests calling for rapid and meaningful change with regard to police brutality, racism and anti-Blackness sentiments, and immediate improvements in how Black people are treated in America. Many citizens, myself included, believe that these changes will begin by defunding police departments and investing in community structures and alternatives to police force.

Millions of dollars every year have been funneled toward law enforcement and mass incarceration systems that are harming our communities more than helping them. The funds should be redirected into public education systems and youth programs in these marginalized communities that are traditionally over-surveilled and over-policed. I call on you to further meaningfully restrict the policing budget throughout the county, and instead use those resources towards funding what Black and other marginalized communities need to be safe and healthy: COVID-19 relief, affordable housing, education, healthcare (especially mental healthcare and resources), community centers, treatment, and community-led organizations. Also, the infrastructure of public spaces such as community gardens and parks has always been part of what makes Northwest Arkansas such a beautiful community, and that should not be restricted only to the wealthy areas of town. While we’ve been spending extraordinary amounts on policing, we have not seen sufficient improvements to safety, homelessness, mental health, or affordability in our towns. 

Benton County's public would be better served by dedicating resources to programs that are more effective at promoting safety and social equity than policing and incarceration. Social programs and education generally have been shown to be much more effective at achieving these goals than policing and incarceration.

We can be a beacon for other cities to follow if only we have the courage to change. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Sincerely,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by brickaney** [comment]
I’m reviewing.
