### ISSUE TITLE
Add Baltimore County, MD

### ISSUE THREAD

**Issue by cmartinez727** [defund12/defund12.org#962]
To: council1@baltimorecountymd.gov; council2@baltimorecountymd.gov; council3@baltimorecountymd.gov; council4@baltimorecountymd.gov; council5@baltimorecountymd.gov; council6@baltimorecountymd.gov; council7@baltimorecountymd.gov; johnnyo@baltimorecountymd.gov
Subject: [*** INSERT UNIQUE SUBJECT LINE***]
Message (Don't forget to replace the [x]'s with your information!) 🔗

Dear Baltimore County Executive Johnny Olszewski Jr. and Baltimore County Council Members ,

My name is [YOUR NAME] and I am a Baltimore County resident writing to urge you to defund BCPD. I demand that the Baltimore County Council begin meaningfully defunding the Baltimore County Police Department and re-allocate those funds to programs proven to more effectively promote a safe and equitable community: community-based mental health services, substance abuse treatment services, affordable housing programs, and more. I demand a budget that reflects the actual needs of Baltimore County residents.

BCPD takes an enormous share of the county's budgetary funds, and that percentage has risen over the years. Looking at the most recent budget proposal, it can be shown that the budget allocation for BCPD has increased by over 8% from FY19-FY20 and is proposed to rise by almost 12% from FY20 to FY 21, taking away desperately needed resources from essential county programs and services. **In fact, the total allocation is proposed to rise by 41% from what was allocated in 2009.** Spending on police budgets in Baltimore County was $189,551,210 in 2009 and is proposed to be $268,160,542 for FY21.  Given all that is happening in Baltimore County, couldn't these dollars be spent somewhere else? Education? Building or renovating schools in areas that desperately need it? Focusing on community programs? Investing in small businesses in Black and Brown communities within the county? The list could go on and on. 

As a Baltimore County residents, I therefore demand that you take immediate action to ensure the following:

Reduce BCPD’s allocation from by 50% (roughly $130 Million)for FY21
Disallow unauthorized overtime by BCPD
Discontinue use of general fund dollars to pay for settlements due to police murder, misconduct, and negligence
Invest in  community-based mental health services, substance abuse treatment services, affordable housing programs, youth programs, restorative justice, and more to keep the community safe and thriving.

Baltimore County can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to Defund BCPD.
History has shown that police “reform” is not enough. We must take a hard look at the ways that the current system in place fails to serve–and in fact actively harms–our community, and come together to reimagine the role of police in our county.

Thank you for your time, 
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Comment by brickaney** [comment]
I’m reviewing

**Comment by cmartinez727** [comment]
Black is a proper noun and should be capitalized as should Latinx. In addition, by not having Americans with Latinx once pull imply they are not Americans. Finally, the reference links are not pulling through when you open the email.
