### ISSUE TITLE
DEFUND LITTLE ROCK POLICE

### ISSUE THREAD

**Issue by shelbykait** [defund12/defund12.org#967]
Email: board@littlerock.gov

Dear Little Rock Board of Directors,

My name is [x] and I’m a resident of Little Rock. I am writing about Little Rock Mayor Frank Scott Jr.’s fiscal year 2021 budget proposal.

I am writing to demand that the budget vote be delayed so that Board may find ways to redirect money away from Little Rock Police Department’s overinflated budget. I urge you to pressure the City Manager’s Office towards an ethical and equal reallocation of the city’s expenditures, away from LRPD, and towards sectors that facilitate the dismantling of racial and class inequality.

Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at promoting community safety than police or prisons (Source: Popular Democracy). As such, I demand more aggressive financial support be directed to those areas.

Do not forget our poor communities and communities of color who are disproportionate targets of police violence. Justice will only be served when the police are defunded and their budget is reallocated to social services that aim to improve the wellbeing of our community members.

Can I count on you to lead our nation by example in this fight against police brutality and racial discrimination?

Thank you,

[x]

**Comment by shelbykait** [comment]
@mahrer how do I get this added to your dashboard so Arkansas is listed?

**Comment by mahrer** [comment]
@shelbykait Once our content review team has a chance to read it and approve, our dev team will add it :) Should take less than 24 hours, but we have been pretty busy. Thanks for your patience.

**Comment by mahrer** [comment]
Hi @shelbykait - I didn't catch this before, but it looks like Little Rock has already been added to the site from a previous submission.
https://defund12.org/littlerock 
If you would like to make specific changes to the existing content, please open a new issue so we can follow-up.
Thank you!
