### ISSUE TITLE
EDIT to existing Las Vegas message

### ISSUE THREAD

**Issue by bernardsanders** [defund12/defund12.org#968]
Hello, can you please remove the information fields at the bottom of the email to Las Vegas city Council so that you are only asked to enter your name? I feel that address, email, and phone number is more information than some may be willing to provide and I do not want to deter anyone from sending the email. Thank you so much!

**Comment by bernardsanders** [comment]
Residents are also asking, if possible, that the word “education” be added to this section so that it reads as follows .. “I ask that you redirect the majority of the $174M allotted for crime prevention towards community programs that provide citizens with basic human needs like affordable healthcare, housing, and education” 

THANK YOU you guys are SO cool

**Comment by ctneal91** [comment]
on it now. I am not removing the address, email, and phone number section because doing so would not be in accordance with the email style guide we use.
