### ISSUE TITLE
Please add Alexandria, VA

### ISSUE THREAD

**Issue by kelseykw** [defund12/defund12.org#971]
# Feature request

Want to add a new feature to the site? Please describe the requested feature and provide any relevant information:

Request to add "Letter to City Council and Office of Management and Budget" for Alexandria, Virginia

To: justin.wilson@alexandriava.gov, elizabeth.bennettparker@alexandriava.gov, Mark.Jinks@alexandriava.gov, Morgan.Routt@alexandriava.gov, CityCouncil@alexandriava.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!): 

Dear Members of the City Council and the Office of Management and Budget, 

My name is [YOUR NAME], and I am a resident of Alexandria, VA. This past week, our nation has been gripped by protests calling for a rapid and meaningful reevaluation of the role of policing in our communities and an end to racism and anti-Blackness. 

In the proposed FY 2021 Budget, the city is dedicating $68,306,285 to the Alexandria Police Department and $35,074,056 to the Alexandria Sheriff’s Office, while only dedicating $7,342,873 to the Health Department, $11,583,249 to the Office of Housing and $994,701 to the Office of Human Rights.

Alexandria's public would be better served by dedicating resources to addressing homelessness, strengthening mental health resources, increasing affordable housing, improving education and other community services. I call on you to meaningfully restrict the Alexandria Police Department budget and instead use those extraordinary resources for programs that are much more effective at promoting safety and social equity than policing and incarceration.

We can be a beacon for other counties to follow if only we have the courage to change. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by todd-m** [comment]
Minor edit below. Looks really good -- thanks @kelseykw!

To: justin.wilson@alexandriava.gov, elizabeth.bennettparker@alexandriava.gov, Mark.Jinks@alexandriava.gov, Morgan.Routt@alexandriava.gov, CityCouncil@alexandriava.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!):

Dear Members of the City Council and the Office of Management and Budget,

My name is [YOUR NAME], and I am a resident of Alexandria, VA. This past week, our nation has been gripped by protests calling for a rapid and meaningful reevaluation of the role of policing in our communities, and an end to racism and anti-Blackness.

In the proposed FY 2021 Budget, the city is dedicating $68,306,285 to the Alexandria Police Department and $35,074,056 to the Alexandria Sheriff’s Office, while only dedicating $7,342,873 to the Health Department, $11,583,249 to the Office of Housing and $994,701 to the Office of Human Rights.

Alexandria's public would be better served by dedicating resources to addressing homelessness, strengthening mental health resources, increasing affordable housing, improving education and other community services. I call on you to meaningfully restrict the Alexandria Police Department budget and instead use those extraordinary resources for programs that are much more effective at promoting safety and social equity than policing and incarceration.

We can be a beacon for other counties to follow if only we have the courage to change. Can I count on you to consider an alternative budget that puts a focus on social service programs?

Sincerely,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by dionlarson** [comment]
On it!
