### ISSUE TITLE
Defund Palo Alto Police (California) 

### ISSUE THREAD

**Issue by sparklyasaprettyunicorn** [defund12/defund12.org#972]
To: city.council@cityofpaloalto.org, Adrian.Fine@cityofpaloalto.org, Alison.Cormack@cityofpaloalto.org, Tom.Dubois@cityofpaloalto.org, eric.filseth@cityofpaloalto.org,  liz.kniss@cityofpaloalto.org,   Lydia.Kou@cityofpaloalto.org,  greg.tanaka@cityofpaloalto.org
Subject: [*** INSERT UNIQUE SUBJECT LINE***]
Message (Don't forget to replace the [x]'s with your information!) 🔗
To Mayor Adrian Fine, Palo Alto City Council Members,
My name is [YOUR NAME], and I am a resident of Palo Alto. This past week, our nation and community have been gripped by protests calling for an end to racism and anti-Blackness and a complete overhaul in our approach to criminal justice in America. We are demanding that our voices be heard, and that real change be made to the way this city allocates its resources.
The fact that the PAPD encompasses over 44 million dollars of the city’s general operating fund is shameful and unproductive. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy).
There is not just a need for police reform, but police defunding and abolition, because the entire structure of the police force is inherently corrupt and ineffective. The average police recruit spends 58 hours learning how to shoot and only 8 hours learning how to de-escalate(Source: Campaign Zero). They are not trained or equipped to react to the vast majority of crises. Phillip McHarris (doctoral candidate focusing on race), argues that we must work towards a reality in which healthcare workers and emergency response teams handle substance abuse, domestic violence, homelessness, or mental health cases. Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing (The Nation). We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence.
We demand the immediate freezing of budget increases to the police force, cancelling of cadet classes, refusal to fill the vacancies on the police department, demilitarization of our forces, and reallocation of funds from police to community-led health and safety strategies.
Please do not vote to increase police funding. Do not be complicit in the disproportionate targeting and continuous oppression of people of color. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.
It is your duty to represent your constituents. I am urging you to revise the Palo Alto city budget for the next fiscal year, and to fund #CareNotCops. We can be a beacon for other cities to follow if only we have the courage to change.
Thank you for your time,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by skullface** [comment]
Hi @sparklyasaprettyunicorn! Thanks so much for your submission.

[Palo Alto’s letter is already live](https://defund12.org/paloalto) from a previous submission. If you would like to make specific changes to the existing content, please open a new issue so we can follow-up. 

Thank you!
