### ISSUE TITLE
Salinas, CA

### ISSUE THREAD

**Issue by sinistrum** [defund12/defund12.org#974]
-Emails: 
cityclerkwebmail@ci.salinas.ca.us, <salinasmayor@ci.salinas.ca.us>, <district1@ci.salinas.ca.us>, <district2@ci.salinas.ca.us>,    <district4@ci.salinas.ca.us>,  <district5@ci.salinas.ca.us>,  <district6@ci.salinas.ca.us>,  district3@ci.salinas.ca.us

-Text: 
Dear Mayor Gunter and Salinas City Councilmembers, I am writing to you as a voting resident of Salinas, asking that you budget for our community. As the nation mourns the loss of not only George Floyd, but the deaths of countless people of color at the hands of local law enforcement, now more than ever, we need to support our children and families.   

Our local police department is set to receive an increase of $711,946 in their budget which is already nearly half of our entire general fund (45%). At the same time, our Library and Community Services Department is projected to lose $326,000 of their funding having only received 8% of our budget as it were. 

This is unacceptable. The youngest members of our community deserve access to clean parks, online learning spaces and library resources, and to continue to have access to the quality sports, arts, and cultural programming taking place in our recreation centers. Furthermore, we need to fund mental health professionals, crisis de-escalators, and other resources for those suffering from domestic abuse and addiction, who are too often subjected to unjust policing. 

Please take action to make the necessary investments for the future of our community. Sincerely, [Resident Name, District (optional)]

**Comment by swallan** [comment]
Dear Mayor Gunter and Salinas City Councilmembers, 

I am writing to you as a resident of Salinas, asking that you budget for our community. As the nation mourns the loss of not only George Floyd, but the deaths of countless people of color at the hands of local law enforcement, now more than ever, we need to support our children and families.

Our local police department is set to receive an increase of $447,026 for 2020-2021 in their budget which is already nearly half of our entire general fund (45%). At the same time, our Library and Community Services Department is projected to lose $326,000 of their funding having only received 8% of our budget as it were.

This is unacceptable. The youngest members of our community deserve access to clean parks, online learning spaces and library resources, and to continue to have access to the quality sports, arts, and cultural programming taking place in our recreation centers. Furthermore, we need to fund mental health professionals, crisis de-escalators, and other resources for those suffering from domestic abuse and addiction, who are too often subjected to unjust policing.

Please take action to make the necessary investments for the future of our community. Sincerely, 

[Resident Name, District (optional)]

**Comment by rpalakkal** [comment]
on it now
