### ISSUE TITLE
Triage access for basic review/editing and creating email templates

### ISSUE THREAD

**Issue by dionlarson** [defund12/defund12.org#978]
# Triage access

👋 I am a defund12.org collaborator requesting triage permissions so I can assist in basic review/editing and creating email templates.

https://github.com/defund12/defund12.org/pulls?q=is%3Apr+author%3Adionlarson+
https://github.com/defund12/defund12.org/commits?author=dionlarson
https://github.com/defund12/defund12.org/issues/639
https://github.com/defund12/defund12.org/issues/652

**Comment by bingbongle** [comment]
Done!
