### ISSUE TITLE
Add San Gabriel, CA

### ISSUE THREAD

**Issue by rachaelk1** [defund12/defund12.org#987]
To: dmenchaca@sgch.org, cliao@sgch.org, tonydingforsangabriel@gmail.com, jharrington@sgch.org, jpu@sgch.org

Subject: [Revise San Gabriel City Budget FY2020-2021] 

Dear San Gabriel Mayor and City Council,

My name is [YOUR NAME] and I am a resident of [YOUR DISTRICT/NEIGHBORHOOD]. I am writing to demand that the San Gabriel City Council adopt a budget that prioritizes community wellbeing and redirects funding away from the police.

Not only are we experiencing the trauma of global pandemic, but we are also in the midst of widespread upheaval over the systemic violence embodied by American police departments’ well-documented history of murdering Black people. Empty gestures and suggestions of “reform” are unacceptable. I am demanding that the San Gabriel City Council stand with the People. I am demanding that you root out systemic and institutional racism by defunding the police and prioritizing and reallocating much-needed funds (especially due to the effects of COVID-19) towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.

According to the City of San Gabriel website, the adopted budget for the 2019-2020 fiscal year allocated 36% of the general fund ($41,636,305) to the SGPD. Meanwhile, Community Development only comprised 8% of the general fund. While last year's budget allocated extraordinary and increasing amounts to policing, I am demanding you to completely revise the budget for the 2020-2021 fiscal year to fund care, not cops.

I also entreat you to stand in solidarity with the movement by demanding change from the LAPD. As neighbors, we are duty-bound to hold each other accountable. I join the calls of those across the country to meaningfully defund the police. The people are demanding a budget that supports community wellbeing, rather than empowering the police forces that tear them apart.

You need to adopt a budget that prioritizes the social programs proven to promote safety and equity much more effectively than policing. You need to steadfastly pressure your peers on the City Council of Los Angeles to do the same. Public opinion is with me.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by rachaelk1** [comment]
Revise 3rd paragraph:

According to the proposed budget for the fiscal year 2020-2021, 38% of the General Fund ($41,196,514) is allocated to the SGPD. Meanwhile, Community Development and Community Services only compromise 7% and 3% of the General Fund respectively. It concerns me that funds towards the SGPD are disproportionate to the funds towards Comunity Development and Community Services. I am demanding you to completely revise the budget for the 2020-2021 fiscal year to fund care, not cops.

**Comment by devthered** [comment]
With revised 3rd paragraph, this looks good to me and according with the styleguide. Admin, please tag with ready-for-pr!
