### ISSUE TITLE
Clean up email templates

### ISSUE THREAD

**Issue by NickCrews** [defund12/defund12.org#990]
I'm adding this as a place for general cleanup of email templates. Things are a bit messy as is, and we should stay on top of it. For ex:
- newlines working correctly
- removing bogus escape characters
- ensuring .md files are in the correct directory

**Comment by NickCrews** [comment]
I made PR #989 to remove bogus escaping of brackets in the body of emails. @minicreative it looks like you are managing a lot of the templates?

**Comment by caldric** [comment]
Hey, @NickCrews. I'm a contributor and I can help out with this if you could narrow these down to specific instances. That way, I'd generally know what to look out for across all templates. I think I know what you mean with the escape characters, but not with the newline issue and maybe others that you haven't listed here. It may also be helpful to divide this into separate PRs.

**Comment by NickCrews** [comment]
Hey @caldric, thanks for the help! I don't have a grand or specific vision, I was just intending to try to keep all the email templates consistent. That way
1. People are more confident they are doing the right thing when they copy paste to start a new one.
2. It makes refactors and other programmatic changes better.

So for instance, you could go through all the .md files and ensure that all of the fields are quoted:
```
title: Manchester, New Hampshire
permalink: "/manchesternh"
name: Letter to the Mayor
state: NH
city: Manchester
layout: email
recipients:
- mayor@manchesternh.gov
- kcavanaugh@manchesternh.gov
- wstewart@manchesternh.gov
- long55@comcast.net
- jroy2@manchesternh.gov
- asapienza@manchesternh.gov
- elizabethannmoreau@gmail.com
- rterrio@manchesternh.gov
- mporter@manchesternh.gov
- bshaw@manchesternh.gov
- bbarry@manchesternh.gov
- ngamache@manchesternh.gov
- khirschmann@manchesternh.gov
- jrwaa2@aol.com
- doneil@manchesternh.gov
subject: Reduce the Manchester Police Department Budget
```
to 
```
title: "Manchester, New Hampshire"
permalink: "/manchesternh"
name: "Letter to the Mayor"
state: "NH"
city: "Manchester"
layout: "email"
recipients:
- "mayor@manchesternh.gov"
- "kcavanaugh@manchesternh.gov"
- "wstewart@manchesternh.gov"
- "long55@comcast.net"
- "jroy2@manchesternh.gov"
- "asapienza@manchesternh.gov"
- "elizabethannmoreau@gmail.com"
- "rterrio@manchesternh.gov"
- "mporter@manchesternh.gov"
- "bshaw@manchesternh.gov"
- "bbarry@manchesternh.gov"
- "ngamache@manchesternh.gov"
- "khirschmann@manchesternh.gov"
- "jrwaa2@aol.com"
- "doneil@manchesternh.gov"
subject: "Reduce the Manchester Police Department Budget"
```
because if there are certain characters in those fields, such as `:`, then it breaks things.

**Comment by NickCrews** [comment]
This is a silly issue, it's not very actionable.
