### ISSUE TITLE
Add paragraph to New Orleans email 

### ISSUE THREAD

**Issue by hp1872** [defund12/defund12.org#993]
add this as a third paragraph, it somehow got removed:

The NOPD takes an enormous share of the city’s budget, and that percentage has risen exponentially over the last two decades, taking away desperately needed resources from essential community programs and services. As a member of the community, I am an opposer to the high incarceration rates we have here in New Orleans. The investment in policing has not made us in the Black and Brown communities any safer and the system in which it operates is inarguably anti black, brown, and lgbtq+ – NOPD remains an embarrassment to this city and a lethal threat to what makes us New Orleans. Meanwhile you increase police spending. With New Orleans’s current precarious finances in jeopardy, it is clear that we must defund the police.

It should read:
Dear Mayor Cantrell and City Council Members,

My name is [YOUR NAME]. I am a New Orleans resident writing to urge you to defund the New Orleans Police Department.

I am contacting you to demand a significant reduction to the $194 million that is currently allocated to public safety in the upcoming fiscal budget of 2021 and for a formal review of the New Orleans Police Department Union Contract from an independent party that has no affiliation with NOPD. The police funds make up roughly 20% of the budget, while other important public services do not receive even half as much funding. By reducing police funding and reducing incarceration rates, those funds can be reallocated to housing, education or sanitation, among other needs. That way we can focus on building our community efforts and local organizations, while preventing future police brutality and violence.

The NOPD takes an enormous share of the city’s budget, and that percentage has risen exponentially over the last two decades, taking away desperately needed resources from essential community programs and services. As a member of the community, I am an opposer to the high incarceration rates we have here in New Orleans. The investment in policing has not made us in the Black and Brown communities any safer and the system in which it operates is inarguably anti black, brown, and lgbtq+ – NOPD remains an embarrassment to this city and a lethal threat to what makes us New Orleans. Meanwhile you increase police spending. With New Orleans’s current precarious finances in jeopardy, it is clear that we must defund the police.

As New Orleans residents, we therefore demand that you take immediate action towards the following ends:
* Reduce NOPD’s allocation from the General Fund
* Discontinue use of General Fund dollars to pay for settlements due to police murder, misconduct, and negligence
* Invest in housing, jobs, youth programs, restorative justice, and mental health workers to keep the community safe.
* New Orleans can not wait any longer for a budget that meets the needs of its residents. The only way to achieve this is to take immediate steps to Defund NOPD.

Thank you for your time,
[YOUR NAME]
[YOUR EMAIL]
[YOUR ADDRESS]
[YOUR PHONE NUMBER]

**Comment by hp1872** [comment]
Sorry add as the 3rd paragraph

**Comment by ctneal91** [comment]
on it now.

**Comment by ctneal91** [comment]
Actually, upon further review, it looks like this paragraph was intentionally removed and replaced because of issue #823

**Comment by hp1872** [comment]
@ctneal91 hi! I had requested an edit just to add info to an existing request to add New Orleans... but in doing so I think the person who programmed it may have gotten confused and an important paragraph was removed from the email! So I was thinking it could be added back in... unless you think it doesn’t add to the letter! Thanks so much for your work on this!!!

**Comment by hp1872** [comment]
@ctneal91 actually I see what you mean it is a bit repetitive. I think it doesn’t need that paragraph thanks for your input!

**Comment by ctneal91** [comment]
Great @hp1872. Can you close this issue then? Or do we need someone with other permissions, like @todd-m to close it
