### ISSUE TITLE
Edit Kansas City, MO

### ISSUE THREAD

**Issue by dtrzn** [defund12/defund12.org#994]
The latest revision of content that was agreed upon in #490 was accidentally ignored and an earlier version was published.

The change is only to the first paragraph of the message. 

It currently reads: 

>My name is [NAME] and I am a resident of Kansas City’s [YOUR DISTRICT]. I am writing to ask you to reallocate funds away from the KCPD and toward public resources such as healthcare services, housing, and education.

It should read:

>My name is [NAME] and I am a resident of Kansas City. I am writing to ask you to reallocate funds away from the KCPD and toward public resources such as healthcare services, housing, and education. I commend Mayor Lucas for de-escalating the protests in our city by removing the unnecessary and militarized police presence. Let that serve as a picture of how our city ought to operate as a whole.

Thank you so much!

**Comment by skullface** [comment]
Thanks for following up @dtrzn!

**Comment by todd-m** [comment]
on it
